/**
 * Config.js
 * ===========================================================================
 * WHAT THIS FILE DOES:
 * Single source of truth for ALL static app-level values: version, data file
 * paths, DOM selectors, and UI strings. Nothing is hard-coded at point of use.
 *
 * WHY SEPARATE FILE:
 * Per the Te Kura coding standards (§6), every project has exactly one Config
 * static class. If a path, selector, or label changes, you edit it HERE once
 * instead of hunting for it across the codebase.
 *
 * WHEN TO WORK HERE:
 * - The data/ folder moves, or a runtime data file is renamed.
 * - A DOM id/class in index.html changes.
 * - UI wording needs a tweak.
 *
 * IMPORTANT BOUNDARY:
 * Config holds APP plumbing only. Everything about MODULES — the tag
 * vocabulary, styles, output HTML shapes, acknowledgement formats — lives in
 * the ../data/*.json files, never here. That separation is the whole point of
 * the design: the engine reads its domain knowledge from data files, and
 * Config is just the address book that says where those files are.
 * ===========================================================================
 */

class Config {

	// ---------------------------------------------------------------------
	// APP VERSION
	// ---------------------------------------------------------------------
	// Format: YYMMDD.iteration — a date stamp plus that day's build number.
	//   e.g. 260617.79  ->  2026-06-17, build 79.
	// This is shown in the UI so a developer can tell which build produced a
	// page. It is NOT written into the converted HTML, so changing it never
	// changes any output — bump it whenever you ship a change.
	// ROUND 213 (260617.86): DOMAIN LINK-TEXT DISPLAY (Chris, the BLL241
	// supervisor-note screenshot) — a link on a configured domain whose visible
	// text is itself a URL now renders that text as the domain's canonical
	// display form ("https://speldsa.org.au") while the href keeps the writer's
	// full deep URL. Measured: the human golds do exactly this in the page BODY
	// (67/68 speldsa sites) and keep the full URL text in the acknowledgements —
	// so the rewrite runs as a full-page post-pass (ListsAndRuns.LinkTextDisplay,
	// wired in PageAssembler) that stops at the acks block and skips
	// cv2-interactive placeholder dumps (developer hand-off content stays raw).
	// 92 body links canonicalised across 71 BLL modules. Data
	// elements.link_text_display (domains map — add a domain by adding a key);
	// env LINKTEXT_OFF. This round also ran the FULL ship.sh backstop
	// (392-dir regen, cadence reset).
	// ROUND 212 (260617.85): THE MTK "TE AKA TAUMATUA" DROP-DOWN-MENU BILINGUAL
	// TEMPLATE (Chris, the PNR101 empty-overview screenshot) — the NEW PNR
	// family template opens with a [Content for DROP DOWN MENU] section (ONE
	// English|Māori table = the whole module menu) + a [MODULE CONTENT: PAGE 1]
	// introduction; NONE of those markers was a recognised content start, so
	// the WHOLE overview was silently trimmed as front matter and the module
	// shipped an EMPTY first page (no title, no menu, no body). Fixed with six
	// coupled pieces behind ONE toggle: content-start rescue (TrimFrontMatter),
	// [MODULE CONTENT] stays-on-overview (PageSplitter), scanner suppression
	// of the opener, #partitionItems menu routing, MenuBuilder.#reoDropdownTabs
	// (the bilingual tabs menu compose) + the reo_tabs shell, and the
	// front-matter "Module Name" table row as the bilingual title source
	// (TRR301/TRR304 also gain their gold titles from it). Data
	// elements.dual_language.dropdown_menu + Input_Doc_Rules
	// content_start_fragments_dropdown / front_matter_metadata.table_row_fields;
	// env REODROPMENU_OFF. Blast: PNR101/102/104 + TRR301/304 (TRR203 proven
	// byte-identical).
	// ROUND 211 (260617.84): INFORMATION-PANE NATIVE TWO-COLUMN (Chris, the
	// AGH1002 screenshot) — a tabs-overview Information/Learning pane splits
	// into its group's registered two-column form when it holds the moved LI/SC
	// block plus anything else (the measured within-group discriminator; MXEO's
	// li-carrying Learning panes stay ONE column, so the rule is registry-gated,
	// never global). Two mined split kinds: "li_sc" (LI left | rest right) and
	// "balance" (first ceil(G/2) section groups left). Data menu.tab2_cols
	// (registry GENERATED by outputs/_measure_tab2_cols.py --gen); env
	// INFOCOLS_OFF. Blast: exactly 17 -00 pages.
	// ROUND 209 (260617.83): THE "LEARNING" SECOND TAB (Chris, r206 follow-up
	// ticket 3) — the MXEO/ENGS102 family's second menu tab is labelled
	// "Learning" and homes the LI/SC content (tab 1 keeps only U/K/D), via the
	// shells' new {tab2Label} slot + a registry (menu.learning_tab; env
	// LEARNTAB_OFF). Ticket 2 (BLL Knowledge/Practices tabs) was DECLINED with
	// measurement in round 208 (no build change).
	// ROUND 207 (260617.82): GENERAL BILINGUAL MENU-HEADING REDUCE (Chris, the
	// r206 follow-up ticket 1) — a piped "reo | English" menu subsection heading
	// (tab_map h4/h5, the simplified <h5>, the two_col_li right column) reduces
	// to its English half where the subject|phase group's human golds solidly do
	// (registry menu.bilingual_heading_reduce, 51 rows; env MENUH5REO_OFF); the
	// OSAH/OSOH/OSSC/OSSM keep-family and reo modules stay fully bilingual.
	// ROUND 214 (260617.87): BASIC INTERACTIVES — accordion NUMBERED-SERIES
	// CONTAINMENT (content between [Accordion N] and [Accordion N+1] stays in panel
	// N; nested widgets absorb as sub-bundles and build in place; env ACCNEST_OFF),
	// the rich-accordion member extensions (sub-headings / instruction-skip /
	// list-marker-skip / nested built row-wrap; ACCRICH2_OFF), the carousel
	// trailing-section-heading break for image carousels (CARTRAIL_OFF) + the
	// bold-<p> caption title form (CARCAP_OFF), and the ROW-per-tab table tabs
	// build (OSOH501 READYSAFE; TABROWS_OFF). Chris, OSOH501-01 screenshots.
	// ROUND 206 (260617.81): EXTRA MODULE-MENU TABS (Chris, AGH1001-0.0
	// [Module menu tab rules] screenshot) — a tab2-routed overview-menu section
	// (Connections / Assessment for Learning) whose subject group's human golds
	// promote it now opens its OWN nav tab + pane instead of an <h5> dump in the
	// Information pane (registry menu.extra_tabs; env EXTRATABS_OFF).
	// ROUND 205 (260617.80): the "HTML Generator V2" UI-polish round — six
	// browser-only UI changes (title rename, scroll-to-output, hide-convert,
	// collapsible summary, reset button) + the RAW-VERBATIM {CODE}_interactives.txt
	// hand-off (env MANIFESTRAW_OFF). The HTML pages are byte-identical to r204.
	// ROUND 215 (260617.88): r214-b CEDT501 — the COLUMN-form TITLE-ROW tabs build.
	// A CEDT [tabs] table with a leading single-cell [H*] title above the [tab N][H3]
	// label row now builds real tabs (the gold's form) instead of the placeholder dump;
	// two [tabs] tables in one bundle each build; label "/"-sub-descriptions lead the pane.
	// env TABTITLEROW_OFF. TEDC (r197 registry path) byte-identical.
	// ROUND 217 (260617.90): the ACTIVITY/INTERACTIVE BOUNDARY AUDIT (Chris) — the
	// corpus-wide per-block containment audit found the human INVENTS an activity box
	// around a standalone TASK interactive (6,863 gold boxes vs 5,663 writer [Activity]
	// tags). Shipped: (1) ACTWRAP — a standalone bundle of a measured task type
	// (dragAndDrop 0.97 / unclassified 0.88 / multiChoiceQuiz 0.89 / radioQuiz 0.88 /
	// selfCheck 0.83 / the new bare-invocation 'interactive') wraps in the human's
	// `activity interactive` box with the NEXT positional lesson letter, on
	// numbered-lesson pages (env ACTWRAP_OFF; data activity_wrapper.standalone_widget_box);
	// (2) INTALIAS — the bare standalone "[Interactive]" span (previously demoted to an
	// instruction note, leaking its data table as a kept <table>) re-tags as a generic
	// INTERACTIVE opener so instruction + table are captured and boxed (env INTALIAS_OFF;
	// data Tag_Lexicon qualifier_alias_demote.standalone_becomes + boundary-bank
	// 'interactive' entry + bare_invocation_dissolve_empty for too-thin bundles).
	// Blast 400 pages / 155 modules; skeleton mean +0.141pp IMPROVED.
	// ROUND 218 (260617.91): DOC-14 v2026-07-09 REFRESH + THE GOLD-OVERRIDE MARKING (Chris).
	// Subject_Global_Parameters.json recaptured to the 9-July doc-14 (10 families — adds
	// 14.9 BLLR + 14.10 MiW/WJ; expands Languages/Pathways/Taonga/LS/HPE; + the §14.11
	// _cross_cutting block). Every family is MARKED overrides_gold:true + a dated
	// _meta.gold_override_policy: doc-14 rules are FORWARD-LOOKING and outrank the module's
	// own human gold within scope (the ONE Level-0 exception) — a stocktake divergence
	// matching a marked rule is an INTENTIONAL 'DOC-14 OVERRIDE', never a regression.
	// New scope.exclude_prefixes (BLLR is NOT BLL; PHEFUN/HPFUN are NOT §14.8) honoured in
	// subject_parameters.scope_match + vet_issue.doc14_scope + PrecedenceResolver.#scopeMatch
	// (parity 1504/1504 EXACT). INERT: master_enabled:false unchanged — corpus byte-identical
	// (30/30-page in-place regen proof, BLL110/CEDT501/XDLS501/AGH1001). env SUBJECTPARAMS_OFF.
	// ROUND 219 (260617.92): the online HTML Convertor project's Change Ledger folded into
	// PageForge V2. LIVE: the CL-0010/CL-0013 source-specific red-note prefix scheme —
	// "Writers Note:" (writer note) / "Red Flag:" (converter issue) / "Note from {author}:"
	// (reviewer Word comment) / "Designer/Developer To Do:" (deferred asset; kind "todo"),
	// all red + bold; env NOTESCHEME_OFF reverts to the r57/r72 "CS:"/"RED FLAG:"/"{author}:"
	// legacy forms byte-for-byte. CAPTURED with the r218 gold-override (no-regression) marking
	// in Subject_Global_Parameters._universal_conventions: CL-0007 wrapper widths (never
	// col-md-10 — already true of V2 output), CL-0001/0002 alt-text + iStock acks file,
	// CL-0003/0026 video acks (verified already in effect), CL-0004/0023 button labels.
	// Online-project-only rows (Split/Update/Comparison-Mode mechanics) deliberately NOT
	// incorporated — see the round-219 changelog triage table.
	// ROUND 220 (260617.93): PNR104-00 raw-dump fix — PageSplitter flags EVERY table in
	// the [MODULE CONTENT: PAGE n] region as _reoModuleContent (the r212 walk stopped at
	// the FIRST; PNR104's writer split the module intro into TWO tables and the second
	// shipped as a raw cv2 bilingual-unbuilt dump). Measured over ALL 428 WTs: the
	// multi-table region = EXACTLY PNR104. Data dropdown_menu.module_content_all_tables;
	// env REOMODCONTENT_OFF (first-table-only legacy walk).
	static AppVersion = 260617.93;

	// ---------------------------------------------------------------------
	// RUNTIME DATA FILES (paths are relative to app/index.html — served over HTTP)
	// ---------------------------------------------------------------------
	// WHAT: every file the engine reads at runtime, listed by a friendly key.
	// WHY:  DataService loads exactly this list at startup, so adding a new
	//       data file is a one-line change here.
	// USAGE: DataService reads Config.DataFiles.TagLexicon, etc.
	static DataFiles = {
		TagLexicon:        "../data/Tag_Lexicon.json",
		TagExceptions:     "../data/Tag_Exceptions.json",
		InstructionCues:   "../data/Instruction_Cues.json",
		InputDocRules:     "../data/Input_Doc_Rules.json",
		StyleRegistry:     "../data/Style_Anchor_Registry.json",
		MajorityRegistry:  "../data/Style_Anchor_Registry_Majority_And_Deviations.json",
		BoundaryBank:      "../data/Interactive_Boundary_ChildTag_Bank.json",
		// NOTE: Interactive_Wrapper_Catalogue.json is reference-only and is
		// deliberately NOT loaded at runtime — widget RECOGNITION comes from the
		// lexicon + boundary bank, and widget MARKUP from
		// Emit_Templates.interactive_builders. Re-adding it would just load
		// ~1,400 unused lines at every startup.
		EmitTemplates:     "../data/Emit_Templates.json",
		AcksFormats:       "../data/Acks_Formats.json",
		ManifestPatterns:  "../data/Manifest_Patterns.json",
		ConventionRegistry: "../data/Html_Convention_Registry.json",
		// The menu type (tabs / simplified / none) per subject × phase,
		// measured from the human-built corpus.
		MenuScaffold:      "../data/Menu_Scaffold_Registry.json",
		// The whitelist of Creative-Services authors whose native Word comments
		// we surface into the page, plus how to render them.
		CommentAuthors:    "../data/Comment_Authors.json",
		// Whole-page "template mode": the order of the <body> class tokens plus
		// the language / translation attributes.
		TemplateModes:     "../data/Template_Modes.json",
		// The three files behind the module precedence cascade (see
		// PrecedenceResolver.js): the per-module built-structure index (plus
		// module_meta, the data the cascade filters over), the cascade's level
		// order and reliability floors, and the subject-level default parameters.
		// These are loaded but the live engine application ships turned OFF
		// (Precedence_Cascade.engine_inherit.enabled === false), so today they
		// are read-only reference data.
		ModuleStructureIndex: "../data/Module_Structure_Index.json",
		PrecedenceCascade:    "../data/Precedence_Cascade.json",
		SubjectParameters:    "../data/Subject_Global_Parameters.json",
		// A frequency list of overview-menu heading phrases seen across the
		// human corpus. MenuBuilder uses it to decide when a one-line
		// "**Title:** content" heading should be split (env MENUHEADINGLEX_OFF).
		// Rebuilt by reference/tests/build_menu_heading_lexicon.py.
		OverviewMenuHeadingLexicon: "../data/Overview_Menu_Heading_Lexicon.json",
	};

	// ---------------------------------------------------------------------
	// DOM SELECTORS — the element ids used in app/index.html
	// ---------------------------------------------------------------------
	// HOW TO USE: document.getElementById(Config.Selectors.DropZone)
	static Selectors = {
		FileGuard:     "file-guard",       // the "you opened this via file://" warning screen
		AppRoot:       "app-root",
		DropZone:      "drop-zone",
		FileInput:     "file-input",
		FileList:      "file-list",
		ModeP:         "mode-p",
		ModeD:         "mode-d",
		ModeExtract:   "mode-extract",     // the interactive "hand-off" mode switch (off by default)
		ConvertButton: "convert-button",
		// The "clear everything & convert another module" reset control (its
		// wrapper + the button). Shown only after a conversion completes; the
		// reset returns the converter to its fresh state IN PLACE, without a
		// page reload (a reload would drop back to the site's landing view).
		ResetPanel:    "reset-panel",
		ResetButton:   "reset-button",
		ProgressLog:   "progress-log",
		// The Convert-panel progress bar. App.js drives it; the engine reports
		// progress through the guarded run.onProgress hook (see ConversionRun.js).
		ProgressBar:      "progress-bar",
		ProgressBarFill:  "progress-bar-fill",
		ProgressBarLabel: "progress-bar-label",
		SummaryPanel:  "summary-panel",
		DownloadAll:   "download-all",
		OutputList:    "output-list",
	};

	// ---------------------------------------------------------------------
	// UI STRINGS — the words shown to the person using the tool
	// ---------------------------------------------------------------------
	static Strings = {
		ReadyToConvert: "Ready — drop the Writers Template (+ Media List) above, choose the image mode, then Convert.",
		Converting:     "Converting…",
		Done:           "Conversion complete.",
		// Progress-bar stage labels (set by App.#progressSet).
		ProgressExtract: "Reading files",
		ProgressPrep:    "Preparing module",
		ProgressPages:   "Converting pages",
		ProgressAcks:    "Acknowledgements & media",
		ProgressDone:    "Done",
		ProgressFailed:  "Failed — see the log below",
	};

	// ---------------------------------------------------------------------
	// FAIL-SAFE — the last-resort UI when the app cannot recover (standards §6).
	// ---------------------------------------------------------------------
	// Replaces the whole app body with a plain message and a Retry button.
	static FULL_BREAK(message) {
		const root = document.getElementById(Config.Selectors.AppRoot);
		if (!root) return;
		root.innerHTML = `
			<div class="full-break">
				<p>${message || "Something went wrong loading the converter."}</p>
				<button onclick="location.reload()">Retry</button>
			</div>
		`;
	};
}
