/**
 * Config.js
 * ===========================================================================
 * WHAT THIS FILE DOES:
 * Single source of truth for ALL static app-level values: version, data file
 * paths, DOM selectors, and UI strings. Nothing is hard-coded at point of use.
 *
 * WHY SEPARATE FILE:
 * Per the Te Kura coding standards (§6), every project has exactly one Config
 * static class. If a path, selector, or label changes, you edit it HERE once
 * instead of hunting for it across the codebase.
 *
 * WHEN TO WORK HERE:
 * - The data/ folder moves, or a runtime data file is renamed.
 * - A DOM id/class in index.html changes.
 * - UI wording needs a tweak.
 *
 * IMPORTANT BOUNDARY:
 * Config holds APP plumbing only. Everything about MODULES — the tag
 * vocabulary, styles, output HTML shapes, acknowledgement formats — lives in
 * the ../data/*.json files, never here. That separation is the whole point of
 * the design: the engine reads its domain knowledge from data files, and
 * Config is just the address book that says where those files are.
 * ===========================================================================
 */

class Config {

	// ---------------------------------------------------------------------
	// APP VERSION
	// ---------------------------------------------------------------------
	// Format: YYMMDD.iteration — a date stamp plus that day's build number.
	//   e.g. 260617.79  ->  2026-06-17, build 79.
	// This is shown in the UI so a developer can tell which build produced a
	// page. It is NOT written into the converted HTML, so changing it never
	// changes any output — bump it whenever you ship a change.
	// ROUND 213 (260617.86): DOMAIN LINK-TEXT DISPLAY (Chris, the BLL241
	// supervisor-note screenshot) — a link on a configured domain whose visible
	// text is itself a URL now renders that text as the domain's canonical
	// display form ("https://speldsa.org.au") while the href keeps the writer's
	// full deep URL. Measured: the human golds do exactly this in the page BODY
	// (67/68 speldsa sites) and keep the full URL text in the acknowledgements —
	// so the rewrite runs as a full-page post-pass (ListsAndRuns.LinkTextDisplay,
	// wired in PageAssembler) that stops at the acks block and skips
	// cv2-interactive placeholder dumps (developer hand-off content stays raw).
	// 92 body links canonicalised across 71 BLL modules. Data
	// elements.link_text_display (domains map — add a domain by adding a key);
	// env LINKTEXT_OFF. This round also ran the FULL ship.sh backstop
	// (392-dir regen, cadence reset).
	// ROUND 212 (260617.85): THE MTK "TE AKA TAUMATUA" DROP-DOWN-MENU BILINGUAL
	// TEMPLATE (Chris, the PNR101 empty-overview screenshot) — the NEW PNR
	// family template opens with a [Content for DROP DOWN MENU] section (ONE
	// English|Māori table = the whole module menu) + a [MODULE CONTENT: PAGE 1]
	// introduction; NONE of those markers was a recognised content start, so
	// the WHOLE overview was silently trimmed as front matter and the module
	// shipped an EMPTY first page (no title, no menu, no body). Fixed with six
	// coupled pieces behind ONE toggle: content-start rescue (TrimFrontMatter),
	// [MODULE CONTENT] stays-on-overview (PageSplitter), scanner suppression
	// of the opener, #partitionItems menu routing, MenuBuilder.#reoDropdownTabs
	// (the bilingual tabs menu compose) + the reo_tabs shell, and the
	// front-matter "Module Name" table row as the bilingual title source
	// (TRR301/TRR304 also gain their gold titles from it). Data
	// elements.dual_language.dropdown_menu + Input_Doc_Rules
	// content_start_fragments_dropdown / front_matter_metadata.table_row_fields;
	// env REODROPMENU_OFF. Blast: PNR101/102/104 + TRR301/304 (TRR203 proven
	// byte-identical).
	// ROUND 211 (260617.84): INFORMATION-PANE NATIVE TWO-COLUMN (Chris, the
	// AGH1002 screenshot) — a tabs-overview Information/Learning pane splits
	// into its group's registered two-column form when it holds the moved LI/SC
	// block plus anything else (the measured within-group discriminator; MXEO's
	// li-carrying Learning panes stay ONE column, so the rule is registry-gated,
	// never global). Two mined split kinds: "li_sc" (LI left | rest right) and
	// "balance" (first ceil(G/2) section groups left). Data menu.tab2_cols
	// (registry GENERATED by outputs/_measure_tab2_cols.py --gen); env
	// INFOCOLS_OFF. Blast: exactly 17 -00 pages.
	// ROUND 209 (260617.83): THE "LEARNING" SECOND TAB (Chris, r206 follow-up
	// ticket 3) — the MXEO/ENGS102 family's second menu tab is labelled
	// "Learning" and homes the LI/SC content (tab 1 keeps only U/K/D), via the
	// shells' new {tab2Label} slot + a registry (menu.learning_tab; env
	// LEARNTAB_OFF). Ticket 2 (BLL Knowledge/Practices tabs) was DECLINED with
	// measurement in round 208 (no build change).
	// ROUND 207 (260617.82): GENERAL BILINGUAL MENU-HEADING REDUCE (Chris, the
	// r206 follow-up ticket 1) — a piped "reo | English" menu subsection heading
	// (tab_map h4/h5, the simplified <h5>, the two_col_li right column) reduces
	// to its English half where the subject|phase group's human golds solidly do
	// (registry menu.bilingual_heading_reduce, 51 rows; env MENUH5REO_OFF); the
	// OSAH/OSOH/OSSC/OSSM keep-family and reo modules stay fully bilingual.
	// ROUND 214 (260617.87): BASIC INTERACTIVES — accordion NUMBERED-SERIES
	// CONTAINMENT (content between [Accordion N] and [Accordion N+1] stays in panel
	// N; nested widgets absorb as sub-bundles and build in place; env ACCNEST_OFF),
	// the rich-accordion member extensions (sub-headings / instruction-skip /
	// list-marker-skip / nested built row-wrap; ACCRICH2_OFF), the carousel
	// trailing-section-heading break for image carousels (CARTRAIL_OFF) + the
	// bold-<p> caption title form (CARCAP_OFF), and the ROW-per-tab table tabs
	// build (OSOH501 READYSAFE; TABROWS_OFF). Chris, OSOH501-01 screenshots.
	// ROUND 206 (260617.81): EXTRA MODULE-MENU TABS (Chris, AGH1001-0.0
	// [Module menu tab rules] screenshot) — a tab2-routed overview-menu section
	// (Connections / Assessment for Learning) whose subject group's human golds
	// promote it now opens its OWN nav tab + pane instead of an <h5> dump in the
	// Information pane (registry menu.extra_tabs; env EXTRATABS_OFF).
	// ROUND 205 (260617.80): the "HTML Generator V2" UI-polish round — six
	// browser-only UI changes (title rename, scroll-to-output, hide-convert,
	// collapsible summary, reset button) + the RAW-VERBATIM {CODE}_interactives.txt
	// hand-off (env MANIFESTRAW_OFF). The HTML pages are byte-identical to r204.
	// ROUND 215 (260617.88): r214-b CEDT501 — the COLUMN-form TITLE-ROW tabs build.
	// A CEDT [tabs] table with a leading single-cell [H*] title above the [tab N][H3]
	// label row now builds real tabs (the gold's form) instead of the placeholder dump;
	// two [tabs] tables in one bundle each build; label "/"-sub-descriptions lead the pane.
	// env TABTITLEROW_OFF. TEDC (r197 registry path) byte-identical.
	// ROUND 217 (260617.90): the ACTIVITY/INTERACTIVE BOUNDARY AUDIT (Chris) — the
	// corpus-wide per-block containment audit found the human INVENTS an activity box
	// around a standalone TASK interactive (6,863 gold boxes vs 5,663 writer [Activity]
	// tags). Shipped: (1) ACTWRAP — a standalone bundle of a measured task type
	// (dragAndDrop 0.97 / unclassified 0.88 / multiChoiceQuiz 0.89 / radioQuiz 0.88 /
	// selfCheck 0.83 / the new bare-invocation 'interactive') wraps in the human's
	// `activity interactive` box with the NEXT positional lesson letter, on
	// numbered-lesson pages (env ACTWRAP_OFF; data activity_wrapper.standalone_widget_box);
	// (2) INTALIAS — the bare standalone "[Interactive]" span (previously demoted to an
	// instruction note, leaking its data table as a kept <table>) re-tags as a generic
	// INTERACTIVE opener so instruction + table are captured and boxed (env INTALIAS_OFF;
	// data Tag_Lexicon qualifier_alias_demote.standalone_becomes + boundary-bank
	// 'interactive' entry + bare_invocation_dissolve_empty for too-thin bundles).
	// Blast 400 pages / 155 modules; skeleton mean +0.141pp IMPROVED.
	// ROUND 218 (260617.91): DOC-14 v2026-07-09 REFRESH + THE GOLD-OVERRIDE MARKING (Chris).
	// Subject_Global_Parameters.json recaptured to the 9-July doc-14 (10 families — adds
	// 14.9 BLLR + 14.10 MiW/WJ; expands Languages/Pathways/Taonga/LS/HPE; + the §14.11
	// _cross_cutting block). Every family is MARKED overrides_gold:true + a dated
	// _meta.gold_override_policy: doc-14 rules are FORWARD-LOOKING and outrank the module's
	// own human gold within scope (the ONE Level-0 exception) — a stocktake divergence
	// matching a marked rule is an INTENTIONAL 'DOC-14 OVERRIDE', never a regression.
	// New scope.exclude_prefixes (BLLR is NOT BLL; PHEFUN/HPFUN are NOT §14.8) honoured in
	// subject_parameters.scope_match + vet_issue.doc14_scope + PrecedenceResolver.#scopeMatch
	// (parity 1504/1504 EXACT). INERT: master_enabled:false unchanged — corpus byte-identical
	// (30/30-page in-place regen proof, BLL110/CEDT501/XDLS501/AGH1001). env SUBJECTPARAMS_OFF.
	// ROUND 219 (260617.92): the online HTML Convertor project's Change Ledger folded into
	// PageForge V2. LIVE: the CL-0010/CL-0013 source-specific red-note prefix scheme —
	// "Writers Note:" (writer note) / "Red Flag:" (converter issue) / "Note from {author}:"
	// (reviewer Word comment) / "Designer/Developer To Do:" (deferred asset; kind "todo"),
	// all red + bold; env NOTESCHEME_OFF reverts to the r57/r72 "CS:"/"RED FLAG:"/"{author}:"
	// legacy forms byte-for-byte. CAPTURED with the r218 gold-override (no-regression) marking
	// in Subject_Global_Parameters._universal_conventions: CL-0007 wrapper widths (never
	// col-md-10 — already true of V2 output), CL-0001/0002 alt-text + iStock acks file,
	// CL-0003/0026 video acks (verified already in effect), CL-0004/0023 button labels.
	// Online-project-only rows (Split/Update/Comparison-Mode mechanics) deliberately NOT
	// incorporated — see the round-219 changelog triage table.
	// ROUND 228 (260618.01): EMPTY FOOTER NAV HREFS — Change Ledger CL-0044 / constraint 71
	// (the CL-0029..0052 triage kickoff's first shipped ticket). Every footer nav anchor
	// ships href="" — prev-lesson / next-lesson / home-nav alike; D2L wires the real links
	// at publish time. MEASURED (outputs/_measure_footer_hrefs.py): the GOLD library is
	// ALREADY 97% empty (2,188/2,263 pages; the 68 "populated" golds carry D2L quickLink
	// URLs = the publish-time wiring itself) — so the directive and the gold AGREE, and
	// V2's round-8 sibling auto-chaining (1,809 pages / 301 modules) was the divergence.
	// PageAssembler's {prevHref}/{nextHref} fill goes empty; the per-position <li>
	// composition (value_map) + id/class/target unchanged; the r226 choice-page TILE
	// links (a different element) stay populated. Blast EXACTLY the 1,809 predicted
	// pages; skeleton per-page IDENTICAL to r227 (0 moved @ 1836, href not a KEEP_ATTR,
	// token-proven); every other gate EXACT. SAME ROUND: _stalecheck.sh symlink repair —
	// "find ../../data" (final-component symlink, GNU find -P) had contributed NOTHING
	// since the 2026-07-09 consolidation; trailing slashes are now load-bearing there.
	// Data footer.nav_links_empty; env FOOTEREMPTY_OFF reverts to the round-8 chaining.
	// Also this round, NO output change: the CL-0029..0052 record-only triage (see the
	// round-228 changelog) + a cl0044 rule appended to _universal_conventions (byte-
	// proven output-inert, 9/9 pages).
	// ROUND 227 (260618.00): THE DROPPED SOFT LINE BREAK — w:br → "\n" (Chris, the XDLS900
	// triage's corpus-wide lever, measured r225: 5,999 soft breaks / 357 of 429 WTs). A
	// writer's Shift+Enter stores a <w:br/> inside the paragraph; the old w:t-only run
	// extraction silently DELETED it, gluing the flanking text with no separator at all
	// ("…two kinds of data.Measurements and numbers…") — corrupted text corpus-wide.
	// DocxExtractor now contributes "\n" at the break's own position (page/column breaks
	// untouched); renderBlackText's per-line split ships the majority gold form (separate
	// <p>s), table cells render the \n as plain HTML whitespace (gold's space-joined form),
	// Utils.Fold collapses \s+ so tag classification is unchanged, and the r225 proverb
	// split goes dormant (lines arrive pre-split — XDLS905/906 byte-identical). TWO
	// containments caught live: a soft-break-only COLOURLESS run between two red runs
	// merges INTO the red span (it was invisible pre-fix — splitting it changed tag
	// granularity, caught on SSOG103's lesson menu), and a "\n" inside a woven
	// U+E000…U+E001 hover-sentinel pair collapses to a space in renderBlackText so the
	// per-line split can never cut the pair (caught on MXDI202-09, defect class E → 0).
	// Blast 305 pages / 143 modules; FULL ship. Data Input_Doc_Rules.paragraph.
	// soft_break_newline; env SOFTBR_OFF.
	// ROUND 226 (260617.99): XDLS900 CHOICE-PAGE TILE NAVIGATION (Chris, the XDLS900
	// screenshot triage — round 225's recorded lever). The [LESSON Choice page] +
	// [Tab Nav Layout …] one-column category table now builds the human's icon-tile grid
	// (row > col-12.choicePage > div.choice per lesson) on page 00 — tile links = the
	// GENERATED lesson HTML files (Chris's decision 2026-07-15; the gold's online quickLink
	// rcodes are in no WT), labels = the writer's own categories (or lesson titles when no
	// table — XDLS902), iconType EMPTY + one To Do note (icon choice is editorial; gold
	// carries its own "CS: review iconType" comments). The [Sticky Nav Layout …] span is a
	// nav SET-UP instruction, not a page boundary (the word PAGE inside its bracket had
	// mis-split pages); both layout tables surface as Designer/Developer To Do notes (the
	// human drops them — sticky nav is a js/stickyNav.js include); bare [Tab Nav] repeat
	// markers are consumed (they re-leaked an "Orphan sub-tag [tab n]" flag on ~every
	// XDLS90x page); the choice page MERGES into page 00 (every gold ships 00 + one page
	// per lesson). Population = EXACTLY XDLS902-906 + XDLS908 (outputs/_detect_choicetiles
	// .cjs, ALL 431 dirs). Data body_region.choice_page_tiles; env CHOICETILES_OFF /
	// TABNAVDROP_OFF / CHOICEMERGE_OFF.
	// ROUND 225 (260617.98): WHAKATAUKĪ PROVERB NORMALISE (Chris, the XDLS905/906 screenshots)
	// — the writer's proverb (bold reo + SOFT line break w:br + English) arrives GLUED because
	// the extractor drops soft breaks; the human house form is TWO separate PLAIN <p>s
	// (measured 213/215 gold .whakatauki; <b> 2/215, <i> 5/215, edge quotes 9/215).
	// ContentConverter.#proverbSplit re-derives the lost break from its visible boundary
	// (exact **/*-pair group abutting text · leading “quoted” phrase · space-before pipe ·
	// full-tail "(translation)", parens dropped) + #proverbStripSeg strips bold/italic/edge
	// quotes/orphan edge pipe at segment level. Glued boxes 27→9 (the 9 = measured declines:
	// English not in the WT, or no derivable split point), <b>/<i>/edge-quotes → 0.
	// Data callouts.by_tag.whakatauki.proverb_normalise; env PROVERBNORM_OFF. Scoped ship #5;
	// skeleton 49.538%/918/179/12 IMPROVED, cs exact +15, all other gates EXACT.
	// Tool outputs/_measure_whakatauki.py. Corpus-wide w:br→\n extractor fix = recorded lever
	// (5,999 soft breaks / 357 WTs — its own full-ship round).
	// ROUND 224 (260617.97): THE BLL200 PHASE EXCEPTION (Chris, 2026-07-14) — all BLL2xx
	// modules are actually PHASE 1, so the <html template=""> attribute is "1-3", NEVER the
	// "4-6" their series digit or a mis-built sibling would suggest; BLLR2xx ARE phase 2 and
	// keep "4-6" (explicit guard entry — the r218 "BLLR is NOT BLL" fence). Shipped as the
	// GENERAL prefix-override mechanism skeleton.template_phase_presets.prefix_overrides
	// (longest matching code prefix wins; null = explicitly no override; outranks sibling
	// inheritance AND the r221 digit preset), applied in SkeletonBuilder right after the
	// digit preset. OUTPUT-INERT on the current corpus (all 50 BLL2 modules already resolve
	// "1-3"; live-proven byte-identical on 8 modules + 431-dir resolve scan) — the rule is
	// the permanent guarantee. The 5 gold modules carrying the wrong 4-6 (BLL250/261/264/
	// 265/275, all unpaired/untracked) were corrected in 01-Finalized_Modules_ (13 files,
	// incl. BLL265's page-local html[template="4-6"] CSS selectors). Env TPLPREFIX_OFF
	// (independent of TPLPRESET_OFF). Probes outputs/_detect_tplprefix.cjs +
	// _probe_tplprefix.cjs (5-leg detection/toggle/fence proof) + _probe_tplprefix_inert.cjs.
	// ROUND 223 (260617.96): ENGJ403 follow-ups (Chris) — (1) ACTIVITY-ID INTEGER LESSON
	// PREFIX: the {lessonNumber}{letter} renumber uses the INTEGER lesson part of a dotted
	// page number ("1.0"→"1A" not "1.0A"; the map key too, so a lesson split over sub-pages
	// CONTINUES its lettering), and a DOTTED-lettered writer id ("[Activity 5.1A]") also
	// renumbers into the integer sequence (gold ENGJ403/CEDK501/CEDT501/MXDB301/MXEO301/
	// MXFL302 all integer+letter; the letter-less dotted TRR/PNR gold ids never enter this
	// path). Data activity_wrapper.lesson_letter_number.integer_prefix; env ACTLNINT_OFF.
	// (2) THE "hover info ‘X’:" HOVER FORM: (A4) def-in-own-black-tail scanner weave (the
	// unclosed "[hover info ‘pitch’:" span + black def + bare "]" span — ENGJ403's standard
	// idiom, 12 occ) + QUOTED NAMED ANCHOR placement (scanner + hoverStitch cells) + the
	// glued "[hoverinfo" head. ENGJ403 free-body hovers now weave as class=infoTrigger
	// matching gold; the widget-dump-trapped ones (0.0 ×8 / 4.0 tables) = the standing r201
	// cv2-trapped class (widget boundary/build territory, recorded). Data
	// hover_definition_inline.split_bracket.def_black_tail + head_pattern +
	// render_stitch.head_words; env HOVERTAIL_OFF.
	// ROUND 222 (260617.95): ENGJ403 conversion issues — the pagination trio + the lesson-menu
	// label (Chris). (1) [Lesson 0.0] after [MODULE INTRODUCTION] is the OVERVIEW's own number —
	// the introduction stays on the 0.0 page instead of splitting to a spurious empty-overview
	// "0.0.0" file (ZEROLESSON_OFF; population EXACTLY ENGJ403). (2) DOTTED writer lesson numbers
	// ([Lesson 2.1]) become the page label VERBATIM instead of "2.1.0" (DOTLESSON_OFF; ENGJ403 +
	// CEDK/CEDO/CEDR/CEDT/CEDW501 + XMES202 — gold ships the same "2.1"-style). (3) The
	// [end tile lesson navigate back to lesson N] closer is an IN-PAGE tile closer, never a page
	// boundary (TILECLOSER_OFF; ENGJ403 ×2 — lesson 5 no longer splits into 3 files). ENGJ403 now
	// ships gold's exact 10-page set. (4) The LESSON-MENU "Learning intentions" label: the human
	// opens a lesson's simplified menu with a GENERATED label heading (not in the WT); registry
	// rows generated where the group share ≥0.80 over ≥5 gold menus (13 rows; MENULILABEL_OFF;
	// data menu.lesson_li_label). Data page_split.writer_lesson_numbers + menu.lesson_li_label.
	// ROUND 221 (260617.94): ENGJ403 (Chris) — (1) THE TEMPLATE-ATTRIBUTE PRESET RULE:
	// the <html template="…"> attribute follows the preset module-LEVEL rule (level digit
	// 1→1-3, 2→4-6, 3→7-8, 4→9-10, 5→NCEA), SUPERSEDING sibling inheritance for THIS
	// attribute only (ENGJ403 inherited "4-6" from ENGJ402, itself wrong; the human ships
	// "9-10"). SkeletonBuilder attribute-only override; rules.template_phase (conventions,
	// groupKey) keeps the sibling rule untouched. Data skeleton.template_phase_presets;
	// env TPLPRESET_OFF. Also FIXES toward gold: TRR203/301/304, CEDT101/104, TEDC401/402
	// (shipped an EMPTY attr). (2) WRITER-AUTHORED MENU TAB PARTITION: the new WT era
	// authors the overview menu tabs explicitly ([please set up as two tabs…][tab 1]…
	// [close tab][tab 2]…[close tab]) — MenuBuilder honours the writer's partition instead
	// of the tab_map fold routing (banner h3 + LI/SC-left|rest-right cols + h5 leads +
	// piped headings kept). Fire population = EXACTLY ENGJ403 (428 WTs measured). Data
	// menu.writer_tab_partition + menu.shells.writer_tabs; env MENUTABPART_OFF.
	// ENGJ403 joined the tracked corpus (compare_set 199→200 — the r197 join pattern).
	// ROUND 220 (260617.93): PNR104-00 raw-dump fix — PageSplitter flags EVERY table in
	// the [MODULE CONTENT: PAGE n] region as _reoModuleContent (the r212 walk stopped at
	// the FIRST; PNR104's writer split the module intro into TWO tables and the second
	// shipped as a raw cv2 bilingual-unbuilt dump). Measured over ALL 428 WTs: the
	// multi-table region = EXACTLY PNR104. Data dropdown_menu.module_content_all_tables;
	// env REOMODCONTENT_OFF (first-table-only legacy walk).
	// ROUND 229 (260618.02): the Change Ledger CL-0030 + CL-0048 ACTIVITY PAIR (Chris's
	// kickoff). MEASURED FIRST over every activity box on both sides (7,539 gold /
	// 5,850 Claude — outputs/_activity_anatomy_core.py): BOTH ledger rules are
	// forward-looking directives the gold library predates. CL-0030 (one interactive
	// per activity): gold ships >=2 interactive groups in ONE box 510x/226 modules and
	// Claude's own 47 multi boxes are dominated by BOX-EXACT gold matches (BLL phonics
	// 2C carousel+accordion == gold 2C) → live universal flip = MEASURED DECLINE;
	// rule CAPTURED overrides_gold in Subject_Global_Parameters._universal_conventions
	// (cl0030_one_interactive_per_activity — the r219 CL-0007 pattern). CL-0048
	// (prose | interactive in separate inner rows): gold-dominant anatomy is same_col
	// 75.4% (Claude's existing form) → universal flip captured NOT live
	// (cl0048_prose_interactive_rows); LIVE for the gold-solid registry slice only —
	// ENFUN|Fundamentals (gold separated 77/96 = 0.802; widget col 'col-md-12 col-12'
	// 74/77): a prose-carrying activity-owned bundle closes its prose row and emits the
	// widget in its OWN row at the group width (ContentConverter bundle-owned emit,
	// actProse flag; registry GENERATED by _measure_activity_inner_rows.py --gen).
	// ENFUN same_col 76→5 (residue = the inline-path fringe), two_rows 0→71, all
	// gold-form. Blast EXACTLY the 8 ENFUN pages (scoped ship; toggle-OFF byte-identical
	// to the r228 manifest 0/2009). Data activity_wrapper.prose_interactive_rows; env
	// ACTROWS_OFF (no ACTSPLIT_OFF exists — CL-0030 shipped no live behaviour).
	// ROUND 230 (260618.03): THE OSSC PAIR — CL-0042 lesson-h1 GUARANTEE (output-inert,
	// the r224 pattern) + CL-0043 lead-in VERIFIED ALREADY IN EFFECT; both captured
	// overrides_gold. CL-0042: an OSSC lesson page ships ONE title h1 (its own lesson
	// title) at EVERY level — the SkeletonBuilder lesson-branch te-reo/dual-title push
	// is gated by header.lesson_title_h1.subjects (["OSSC"]). Claude ALREADY ships the
	// rule's form (OSSC301 3/3 lessons); the GOLD diverges (repeats "Ngā Tāware" as a
	// 3rd h1 — pre-dates the rule; recorded override, never chase). Hazard real: OSSC3
	// lesson h1_count=2 + the push fires wherever run.teReoTitle exists — OSSC301
	// escapes only because its ✅-glued [TITLE BAR] never splits. Blast ZERO pages
	// (dual emitters today = XMES/CEDT/SSFUN, 0 OSSC); proof _probe_ossch1.cjs 4 legs
	// (inert/detection/toggle/fence) ALL PASS. CL-0043: the [Lesson Overview] lead
	// sentence already renders as a verbatim <p> above the first <h5> (r114/r147
	// machinery; OS-family pairwise gold match; OSSC population 0) — capture only,
	// no new code. Env OSSCH1_OFF.
	// ROUND 231 (260618.04): CL-0033 LANGUAGES COMBO (output-inert, the r224/r230
	// class). Every page of a Languages-cohort module (doc-14 §14.1's 12 code
	// prefixes: CHIFUN…SPAFUN + CHI…SPA) ships template="combo" on <html>; the
	// sub-type stays on the <body> class. SkeletonBuilder applies the cohort
	// override AFTER prefix_overrides — unconditional, outranks sibling
	// inheritance + the digit preset. Census round 231: the corpus holds ZERO
	// Languages dirs (431 codes, 0 hits, 0 short-prefix collisions) → blast ZERO
	// pages; the guarantee closes the gap where a fresh Languages code would ship
	// the TEDC-style EMPTY attribute (nothing else ever resolves combo for it).
	// Proof _probe_langcombo.cjs ALL LEGS PASS (inert byte-identity on
	// ENFUN01/BLL210/OSSC301; synthetic JAPFUN01+JAP101 → combo; toggle → NCEA).
	// Captured cl0033_languages_combo. Data
	// skeleton.template_phase_presets.cohort_overrides; env LANGCOMBO_OFF.
	// ROUND 232 (260618.05): CL-0038 — [MTKquiz] → the "Go to quiz" BUTTON + To Do
	// note (Chris — the CL0038 kickoff, ticket 7 of the CL0029-CL0052 triage; the
	// first output-changing round since r229; SCOPED ship #4). Any [MTKquiz]-family
	// marker (any modifiers — 54 occurrences / 21 modules measured live,
	// _detect_mtkquiz.cjs) now ships <a href="#" target="_blank"><div class=
	// "button">Go to quiz</div></a> (blank href — the dev wires the D2L quicklink;
	// gold's populated quickLinks ARE that wiring, intentional divergence) + ONE
	// red+bold "Designer/Developer To Do:" note (kind todo, cv2-note = gate-
	// excluded) carrying the writer's raw quiz spec. The TagNormaliser span-level
	// RETAG (Tag_Lexicon._meta.mtk_quiz_retag; the r170 tag_promote class, but
	// firing on tag-less instruction spans too) normalises the family's messy live
	// resolutions (mcq bundles that swallowed the quiz content into dumps /
	// instructions / a text-box + a dropdown mis-route) into ONE "mtk quiz"
	// ELEMENT: junk co-tags dropped (dropbox never attaches), primary recomputed
	// SURVIVORS-FIRST + CONTAINER-FIRST ([Activity 2B] [MTK quiz…][H3] keeps its
	// box — the h3-would-win catch), the closer [End of MTK Quiz content] excluded
	// (stays a CONTAINER_CLOSE; ARFUN01 byte-identical, probe-proven). Writer quiz
	// content STAYS rendered (constraint 1 — ELEMENT ⇒ no capturing bundle).
	// ContentConverter: #mtkQuizPrepass absorbs the writer's own adjacent quiz
	// button ([button] "Go to quiz."/"Quiz", or a [Go to quiz] span/bundle in the
	// window) into ONE canonical anchored button; emits at 4 sites — element
	// route, button upgrade, activity-opener co-tag, bundle tail (captured
	// members + the opener item — the ARFUN04-1H catch). 19 tracked modules ship
	// 54 buttons + 54 notes (1:1); HPRE301/SSCI104 untracked = forward guarantee
	// (_probe_mtkquiz_fwd.cjs ALL LEGS PASS); 5 no-gold-button modules = named
	// CHANGE-LEDGER OVERRIDE deltas (captured cl0038_mtkquiz_button). Toggle-OFF
	// byte-identical to r229 (32/32); every gate held-or-improved (skeleton mean
	// +0.008, body 266→265, tags 9557/9557). Data Tag_Lexicon "mtk quiz" entry +
	// _meta.mtk_quiz_retag + Emit_Templates.interactive_builders.mtk_quiz; env
	// MTKQUIZ_OFF.
	// ROUND 233 (260618.06): CL-0037 — CS/Audiovisual videos → Vimeo scaffold =
	// MEASURED DECLINE + SGP capture (Chris — the CL0037 kickoff, ticket 8 of the
	// CL0029-CL0052 triage; ZERO-blast output-inert round, the r229-CL-0030/r230/
	// r231 class — no engine change, no regen). The ledger rule (pending-ID
	// player.vimeo.com iframe + "Designer/Developer To Do: add vimeo embed for
	// [audiovisual item x]" note) needs a CS-VIDEO discriminator that V2's inputs
	// do not carry: the [Audiovisual item N]/[AV item N]/[Audiovisual request
	// item N] marker family (160 occ / 13 modules, live detector
	// _detect_avitem.cjs over ALL 431 WTs — red spans resolve as data-marker
	// SUBTAGs, black/table forms untagged) denotes CS media of ANY kind and is
	// AUDIO-dominant (pronunciation sounds, mp3 voice-overs, an avatar); no WT/ML
	// channel marks the kind (zero cs-video Media List rows; "Te Kura" rows =
	// images/templates/links); ZERO of the 13 golds ship vimeo (gold pairs
	// per-kind: audioButton/audio players inside widget builds; an EMPTY
	// videoSection + red "Animation to come" for the one animation; ENGJ403's
	// new-era gold ships kind-todo notes for its two AUDIO items); the 201 gold
	// vimeo pages are marker-less editorial (zero pending-ID scaffolds corpus-
	// wide). Emitting the video scaffold at the markers would be wrong-kind-
	// dominant → DECLINED on measurement (the ticket pre-authorised it); rule
	// captured overrides_gold as cl0037_cs_video_vimeo (audit protection — never
	// chase gold's vimeo), mechanism pre-named for the live-wiring round
	// (elements.cs_video_vimeo + VIMEOSCAFFOLD_OFF + the comment_policy third
	// exception). Proof: _probe_r233_inert.cjs — ENGJ403 10/10 + BLL210 1/1
	// byte-identical to disk; subject_parameters + vet_issue selftests PASS;
	// every gate holds by construction at the r232 baselines.
	// ROUND 234 (260618.07): CL-0051 — THE NO-EMOJI RULE (Chris — the CL0051
	// kickoff, ticket 9 of the CL0029-CL0052 triage; FULL ship, ledger reset).
	// Emoji are stripped from rendered writer content as a FULL-PAGE POST-PASS
	// (ListsAndRuns.EmojiStrip, the r213 LinkTextDisplay seam wired in
	// PageAssembler — post-pass placement makes every pre-render fence
	// untouchable BY CONSTRUCTION: tag classification, the ✅-glued [TITLE BAR]
	// fences (r230 OSSC, probe ALL LEGS PASS post-ship), the r192 ✅[Tile]
	// delimiters, the 🔴 red-run sentinels). Scope = Extended_Pictographic
	// grapheme CLUSTERS minus the ledger's exempt ticks & crosses ✅✓✔☑✗✘❌❎
	// (kept cluster-whole, VS16 never orphan-stripped) minus the measured
	// maths-operator extension ✖➗➕➖; EP arrows ➡⬅⬆⬇⮕ map to plain →←↑↓
	// (gold's own TEDC402 treatment); keycap digits keep the digit; 2+
	// consecutive emoji-prefixed plain <p>s → ONE <ul> (lone stays <p>);
	// emptied <p>s dropped (ARFUN02's 31 <p><b>🤔</b></p>); spacing healed;
	// ONE red+bold cv2-note disclosure per affected page at the first removal
	// (ledger wording verbatim, via NotesAndComments.redFlag). The checkbox
	// family ☐☒□🗹 + 🖵 + 🡪 are NOT Extended_Pictographic → out of scope
	// (measured: bilingual checklists / printable tick-sheets / phonics
	// boxes). Skips: cv2-interactive dumps, cv2-note/comment quotes, acks
	// (verbatim oEmbed titles + our own ❗ ack-todo markers), attributes,
	// interactives.txt. MEASURED first (outputs/_measure_emoji.py, both
	// rendered corpora): Claude visible strippable ~907 chars+riders / 50
	// modules; gold ALREADY lives the rule (CEDT104 1-of-279 kept) except the
	// named keeps (TEDC402 faces, MXDI201's emoji-as-content — cv2-trapped
	// today, the recorded WATCH class) — captured overrides_gold as
	// cl0051_no_emoji. Blast 54 pages / 40 modules, 0 pagination churn;
	// EMOJISTRIP_OFF byte-identical to the r232 manifest (49-page proof).
	// Gates ALL HELD-or-IMPROVED: skeleton 49.567% (+0.010) / 918 / 179 / 12 /
	// RAW 34.789% @1836 skipped 0; cs exact 9463 (+21) / EXTRA 174 (+2, the
	// ledger's own <ul> containers, r61 class) / missing 456 (+1); body 265;
	// clean 97.7% / leak 290/46; tags 9557/9557; flipCard 33/div 0;
	// speechBubble 0; entry-parity PASS. Data Input_Doc_Rules.emoji_strip;
	// env EMOJISTRIP_OFF.
	// ROUND 235 (260618.08): THE DEFAULT COLLAPSIBLE INTERACTIVE HAND-OFF +
	// the verified _istock-acks.txt input (Chris). The "Interactive hand-off"
	// UI section is GONE — every run now renders each un-built interactive as
	// its loud reference-code box (the search-by-code contract unchanged) with
	// the raw captured content COLLAPSED inside it, expandable/collapsible via
	// the animated ▼/▲ arrow at the right end of the box; the same codes head
	// {CODE}_interactives.txt. The wrapper carries cv2-interactive so every
	// gate exclusion applies to the whole box; the Page Stitcher replaces the
	// balanced wrapper by data-cv2-ref, raw content and all. Upload also
	// accepts a *_istock-acks.txt (API-sourced verified iStock acks; parsed in
	// PrepareRun — entry parity): its titles outrank the URL-slug derivation
	// in AcksBuilder. Env INTCOLLAPSE_OFF reverts the whole hand-off default
	// byte-for-byte to r234 (INTEXTRACT_ON + INTCOLLAPSE_OFF = the legacy bare
	// marker); env ISTOCKACKS_OFF ignores the acks file. Data
	// interactive_placeholder.extract.default_mode/.collapse +
	// Acks_Formats.istock_acks_file.
	// ROUND 236 (260618.09): UNVERIFIED-iSTOCK HONESTY + CONTENT-FIRST ACKS-FILE
	// RECOGNITION (Chris). Without a verified acks file every iStock title is
	// DERIVED from the image URL and read exactly like a checked one — each such
	// acknowledgement now carries a ❗ (inside the existing plain <p>, no class
	// change, so the skeleton sees nothing) and the acks block opens with one
	// red "Designer/Developer To Do:" note explaining why. Partial cover is
	// flagged per-asset. AND the acks .txt is recognised by its CONTENTS, not
	// its filename (per-module names like _istock-acks-OSAI501.txt are coming);
	// AcksBuilder.LooksLikeIstockAcks / PickIstockAcks is the one shared test
	// both entries use. Env ISTOCKUNVERIFIED_OFF / ISTOCKDETECT_OFF. Data
	// Acks_Formats.istock_unverified + istock_acks_file.detect.
	// ROUND 237 (260618.10): UI COPY ONLY — the site's HTML Generator intro drops
	// the "opens in the panel below" sentence, and the generator's upload drop
	// zone is reduced to two plain sentences (what to upload, plus the
	// iStock-acks.txt line). No engine, data or output change; the corpus is
	// byte-identical by construction.
	// ROUND 238 (260618.11): DEV-FEEDBACK R1 FAMILY A — THE "no precedent → n/a"
	// SKELETON FALLBACK (module SCCH302, the first module of a brand-new subject).
	// A first-in-series module used to ship the literal string "n/a" as its body
	// class, level attribute, footer class and even INTO the idoc script URL
	// (https://n/a.desire2learn.com/… → the page loads with no styling at all).
	// Three coupled fixes: (1) the UNIVERSAL-FIELD FALLBACK — mined "n/a" registry
	// values are never overlaid and an EVIDENCE FLOOR resolves a gold-less group
	// wholesale from the defaults tier (Style_Anchor_Registry _meta.universal_fields;
	// env SKELDEFAULT_OFF); (2) the UNKNOWN-SUBJECT DIGIT FALLBACK — a new subject
	// with no resolved template gets the band from its own code digit (SCCH302 →
	// "7-8"; FUN-shaped codes measured MIXED → still empty; env TPLFALLBACK_OFF);
	// (3) the FIRST-IN-SERIES DEFAULT LESSON-MENU LABEL — the modern
	// <h4><span>Learning Intentions</span></h4> row when no measured registry row
	// exists (menu.lesson_li_label.default_row; env MENUDEFAULT_OFF) + tab_map
	// gains "knowledge"/"practices" (corpus-inert, canary-proven). NO REGENERATION
	// (deferred to Dev-Feedback Round 6 per Chris, 2026-07-30); proven by the
	// in-memory matrix outputs/_probe_r238_familya.cjs (ALL PASS).
	// ROUND 239 (260618.12): DEV-FEEDBACK R2 FAMILY B — the five writer-tag
	// VOCABULARY GAPS (B1–B5, module SCCH302). Five independently-toggled data
	// fixes: B1 [right-hand alert] → the side-alert canonical (alertActivity
	// col-md-4 + the r123 backward pair; Tag_Lexicon tag_promote when_match; env
	// RHSALERT_OFF) + the EMPTY SPAN-WRAP KILL (a lead-only [alert]…[end alert]
	// box drops its unused inner row>col-12 — Claude shipped 70 / gold 2;
	// callouts.drop_empty_span_wrap; env EMPTYWRAP_OFF); B2 free-body [caption]
	// → <p class="captionText"> (gold ×545; widget-member captions untouched BY
	// CONSTRUCTION — the fix lives at the orphan-sub-tag branch;
	// elements.caption_text; env CAPTIONTEXT_OFF); B3 the bare [define: DEF] head
	// joins the hover weave + render-stitch ('definition' scanner-side MEASURED
	// DECLINED — 247 widget-member subtags; hover_definition_inline.define_heads;
	// env DEFINEHEAD_OFF); B4 an explicit go-to-journal [button] → the templated
	// <h4 class="goJournal">Go to your journal</h4> INSIDE the activity box
	// (gold ERA-MIXED h4 ×568 vs button ×1,052 — the dev's rule ships as a
	// forward-looking overrides-gold convention, captured in
	// Subject_Global_Parameters r239_go_journal_h4; buttons.go_journal; env
	// GOJOURNAL_OFF); B5 [button to download journal with standard instructions]
	// → the templated docs/{CODE} Journal.docx download scaffold + ONE To Do note
	// (corpus population ZERO — forward guarantee; buttons.download_journal; env
	// DLJOURNAL_OFF). NO REGENERATION (deferred to Dev-Feedback Round 6 per
	// Chris, 2026-07-30); proven by outputs/_probe_r239_fixes.cjs (ALL PASS:
	// SCCH302 fix-ON + toggles-OFF broken-state + canary byte-identity + per-
	// toggle delta decomposition) with tags 9557/9557, entry-parity PASS.
	// ROUND 240 (260618.13): DEV-FEEDBACK R3 of 6, FAMILY D — the three image
	// rules D1–D3 (the SCCH302 developer-feedback chain; NO regeneration —
	// deferred to Round 6 per Chris 2026-07-30). D1 every content image fills
	// alt from the asset title (verified iStock API title from *_istock-acks.txt
	// > URL-slug Title-Case > empty) + gains loading="lazy" — a post-fill
	// (MediaBuilder.FinishImg, the r200 post-replace class) on free-body +
	// table-cell images; gold era-mixed (alt 73% hand-typed / lazy 24%) → the
	// dev's rule ships forward-looking overrides-gold, captured in
	// Subject_Global_Parameters r240_img_alt_lazy (elements.image_attrs; env
	// IMGATTRS_OFF). D2 a title-anchored table-cell [image] (title text in the
	// cell, URL only in the docx hyperlink the extractor stores on the table
	// BLOCK) resolves its URL via the block's links — longest folded-anchor-in-
	// cell match — instead of slugifying the title (SCCH302's Solutions table:
	// clear-yellow-…-beake.jpg → iStock-1321097020.jpg; threaded contentTable →
	// renderCellInline/layoutTableGrid/renderCellParts → cellImage as trailing
	// optional params; body_region.cell_image_link_match; env CELLIMGLINK_OFF).
	// D3 an image's own title-form REFERENCE line (the hyperlink's anchor text /
	// the iStock "– Download Image Now –" form) never renders as a caption <p> —
	// the r80 video-title-drop class extended to images, in MediaBuilder.image
	// (anchor-equality on OWN lines) + the renderBlackText stitch seam (pattern
	// rule, free-body only — cv2 dumps keep their raw lines BY CONSTRUCTION;
	// gold ships 0 such <p>s vs Claude 145; elements.image_reference_title_drop;
	// env IMGREFTITLE_OFF). Proven by outputs/_probe_r240_fixes.cjs (ALL PASS:
	// SCCH302 fix-ON + toggles-OFF broken-state + canary byte-identity +
	// image-free fix-ON identity + per-toggle hash decomposition) with tags
	// 9557/9557, entry-parity PASS, flipCard div 0, speechBubble 0, tabs div 0.
	// ROUND 241 (260618.14): DEV-FEEDBACK R4 of 6, FAMILY C2 + E1–E3 — clickDrop
	// lists + text hygiene (the SCCH302 developer-feedback chain; NO regeneration —
	// deferred to Round 6 per Chris 2026-07-30). C2 clickDrop revealed content routes
	// through the standard black-text renderer so Word bullets become real <ul><li>
	// instead of literal "<p>• …</p>" (gold ships ZERO such bullets / 134 list pages;
	// interactive_builders.clickDrop.list_content; env CDLIST_OFF). E1 the extractor
	// normalises invisible whitespace at the r227 run-walk seam: NBSP U+00A0 → plain
	// space + zero-width U+200B/C/D/FEFF stripped (15,198 NBSPs across 416/429 WTs;
	// 2,108 shipped vs gold ~0; Input_Doc_Rules.text_normalise; env NBSP_OFF; tags
	// gate 9557/9557 proves red-span granularity unchanged). E2 a lesson page with a
	// DISTINCT own title no longer repeats the module's Te Reo title as a second h1
	// (the recorded r199 follow-up, dev-confirmed; 35 dual-h1 pages → 25 suppress /
	// 10 keep, gold-matched; header.lesson_te_reo_suppress; env LESSONTEREO_OFF).
	// E3 the AI-variant acks block ("acks acksTemplate acksAI") omits the three
	// boilerplate paragraphs the site template injects (gold triple-class 24/27 omit;
	// catch-all kept; empty opening group dropped; Acks_Formats.standing_items
	// .template_variant_omit; env ACKSBOILER_OFF). Proven by
	// outputs/_probe_r241_fixes.cjs (ALL PASS: SCCH302 fix-ON 15/15 + toggles-OFF
	// broken-state + whole-chain-revert canary byte-identity + E2 isolation legs +
	// pure-whitespace E1 delta proof + per-toggle hash decomposition) with tags
	// 9557/9557 REAL 0, entry-parity PASS, clickDrop verifier defect 0 + selftest
	// GREEN, flipCard div 0, speechBubble defect 0, index-sync 32/27.
	// ROUND 242 (260618.15): DEV-FEEDBACK R5 of 6, FAMILY C1 — the un-numbered
	// accordion (the SCCH302 developer-feedback chain; NO regeneration — deferred to
	// Round 6 per Chris 2026-07-30). Triangulation found the un-numbered repeated-
	// label [accordion] form was ALREADY accepted (scanner same-type absorb + the
	// rich walk's bare-head panel delimiters; 75 repeat regions / 41 modules measured
	// live over all 429 WTs); the ONE blocker on SCCH302's mixtures accordion was the
	// writer's "[2 images next to each other]" LAYOUT instruction, which parses to a
	// URL-less embedded [image] and bailed BOTH image walks. FIX 1: the arrangement
	// vocabulary ("images" + side by side / next to each other / beside each other)
	// is skipped as build content and surfaced as the standard red Writers Note after
	// a successful build (accordion.image_layout_marker; env ACCIMGMARK_OFF; corpus
	// fire population ZERO — 12/12 vocabulary carriers hash-identical → a pure
	// forward guarantee, the r231 class). FIX 2: the r240 D1 RIDER taken — widget-
	// internal images (#assetImage) route through MediaBuilder.FinishImg (verified-
	// map alt by filename id + lazy; elements.image_attrs.widget_internal; env
	// WIDGETIMG_OFF, decomposing independently of the r240 body-path IMGATTRS_OFF);
	// corpus-visible effect = loading="lazy" completing flipCard's Mode-P template on
	// EXACTLY 13 pages / 10 modules (named r240_img_alt_lazy delta). Proven by
	// outputs/_probe_r242_fixes.cjs (ALL PASS: SCCH302 fix-ON 18/18 builds the
	// 2-panel 4-image accordion with verified alts + the deduped note; toggles-OFF
	// placeholder-state; whole-chain 18-toggle canary byte-identity BLL210/OSAH501/
	// TRR203/BLL225 vs the r236 disk; per-toggle hash decomposition) with tags
	// 9557/9557 REAL 0, entry-parity PASS, accordion verifier 27 panels 0 defects +
	// selftest GREEN, flipCard 33/div 0, speechBubble 0, tabs 39/div 0, carousel 0,
	// index-sync 32/27. Residue recorded: SCCH302 lesson-6 title-anchored-media
	// accordion (the D2-in-widgets follow-up) + lesson-8 activity-owned capture.
	// ROUND 243 (260618.16): DEV-FEEDBACK ROUND 6 of 6 — FAMILY E4 (block-level
	// line breaking: HtmlFormatter splits glued div/table-structural `><` runs onto
	// their own lines per the measured gold convention, empty-element one-liners
	// kept; whitespace-only BY PROOF — strip-all-whitespace + tag-stream + PRIMARY-
	// skeleton-parser identity 24/24; env LINEBREAK_OFF) + THE LIBRARY FILE NAMING
	// (Chris, 2026-07-31 — pages now ship as {code}_{lesson}_{part}.html, e.g.
	// SCCH302_0_0.html, from each page's own lessonLabel via the ONE shared
	// PageAssembler.PageFileNames source of truth, tile hrefs + interactives.txt
	// File: lines included; env PAGENAME_OFF reverts the 12/06/26 dash form)
	// + THE ONE FULL CORPUS REGENERATION closing the SCCH302 chain (r238–r243):
	// 393 dirs 0-stale, all gates held-or-improved net of the chain's named deltas
	// (skeleton 49.566%/921/176/12/RAW 32.659% @1837 skipped 0; cs exact 9699 +236;
	// body 273 +1 pairing-correction; clean 97.7% leak 290/46 EXACT; tags 9557;
	// widget verifiers 0 defects; entry-parity PASS). Chain kickoffs swept.
	// NOTE: quoted from round 237 on — a bare 260618.10 is the NUMBER 260618.1 and
	// the badge would drop the trailing zero. Only ever interpolated into a string.
	// ROUND 244 (260618.17): KB catch-up captures — Change-Ledger CL-0053..0068 triage
	// + the doc-14 §14.8 HPE refresh (CL-0067) into Subject_Global_Parameters.json.
	// Output-inert (probe-proven byte-identity); no engine code changed.
	// ROUND 246 (260618.19): BASIC INTERACTIVE BUILDERS — build the WRITER's tagged widget.
	// (1) speechBubble no-table avatar+bubble (SBNOTBL_OFF) — the scanner recovers the
	//     paragraph-mate [Image] (same source block) and the bubble builds beside it:
	//     29 builds / 2 modules, the gold agrees at 36/36 of the sites the guard fires on.
	// (2) accordion heading-less numbered panels (ACCNOTBL_OFF) — "[accordion 1]" alone on
	//     its line opens a panel that takes its heading from its own first text line:
	//     8 builds / 2 modules; strictly ADDITIVE (retried with the rule off on failure).
	// (3) carousel RICH SLIDE fallback (CARNOTBL_OFF) — slides composed from whatever mix
	//     of heading / image / video / prose the writer supplied: 58 builds / 33 modules.
	// Chris's directive (2026-08-03): where the writer tagged the widget, build it — the
	// human's substitution follows unrecorded verbal feedback (Decision Framework A1), so
	// these ship on the widget VERIFIERS + never-half-build, not on the human-match gates.
	// NO regeneration (not requested): the round-245 baselines still describe the corpus.
	// ROUND 247 (260618.20): ENGS404-00 BASIC INTERACTIVES COMPLETED — the text-only bubble
	// + the media-series carousel (Chris, 2026-08-04: "ALL basic interactives are built").
	// (1) speechBubble TEXT-ONLY build (SBTEXT_OFF) — a bubble with no character image and
	//     no table ("[insert thought bubble] Where do we find stories?") ships the human's
	//     own text-only form (385 gold occurrences; layout="thought" for the thought
	//     wording), one row per invocation; 229 bundles / 52 modules measured.
	// (2) carousel MEDIA-SERIES boundary (CARSERIES_OFF, scanner) — a back-to-back run of
	//     [image]/[video] members after the invocation IS the carousel; the first
	//     following non-media element resumes the section (the whole-page over-capture
	//     that killed every such build).
	// (3) carousel PER-MEDIA SLIDES (CARMEDSLIDE_OFF) — marker-less bundles ship one slide
	//     per media item (2 videos no longer pile into one slide and fail min_slides).
	// (4) carousel VIDEO-TAIL URL (CARVIDTAIL_OFF) + the body-path FOLLOWING-LINE hyperlink
	//     (MEDIAFOLLOWLINK_OFF) — "[insert video]" with its title-anchored link on the NEXT
	//     line resolves and embeds (137 widget members / 38 modules + the free-body class).
	// speechBubble verifier gains the A1 gold-subst lane (inject selftest, the accordion
	// pattern); carousel selftest detection channel ACTIVATED (video slides now build).
	// NO regeneration (not requested): the round-245 baselines still describe the corpus.
	// ROUND 248 (260618.21): LANGUAGES AUDIOVISUAL PACKAGE FINALISED (Chris, 5 Aug 2026 —
	// the final 20260511_Language_HTML + covering note). DATA-ONLY round, no engine JS change:
	// (1) cohort_overrides.prefixes gains CHFUN + JPNFUN — the Languages code forms ACTUALLY
	//     in circulation (CHFUN01-07 live; they had been falling to the r245 last_resort_default
	//     with a loud warn; JPNFUN05 = the designer-named language-05 reference). PROVEN
	//     OUTPUT-INERT: fix-ON == LANGCOMBO_OFF byte-identical, one process per state
	//     (outputs/_probe_r248_langassets.cjs, ALL CHECKS PASS — route-only change).
	// (2) SGP family 14.1 captures the FINALISED per-language asset_registry (the
	//     [Audiovisual package <asset> item N] tag family, the 8 phase-auto-coloured icons,
	//     German/French/Chinese/Japanese/Spanish/Samoan characters + Vimeo/audio ids) and the
	//     CHFUN / JPNFUN05 structural reference points. SGP stays shipped-inert (engine never
	//     reads it at runtime; master_enabled:false). KB-side: htmlconvertor-kb CL-0070.
	// NO regeneration (not requested): the round-245 baselines still describe the corpus.
	// ROUND 249 (260618.22): THE REFERENCE-MODULE PANEL (Chris, 2026-08-05) — the HTML
	// Generator's upload flow gains a "Reference module" section: once the uploaded
	// filenames (or the first docx's front matter) reveal the module code, the panel
	// names the SUGGESTED reference module (PrecedenceResolver.SuggestReference — the
	// nearest already-built relative in the library index, series+template first,
	// widening outward; advisory-only) and offers three choices. "Automatic"
	// (default) changes NOTHING. "Choose a different reference module" (a searchable
	// list of all library codes) re-resolves the structural rules AS that module's
	// registry home. "Upload reference HTML" (for a module with no suitable library
	// relative) mines the Style-Anchor tracked fields out of the uploaded finished
	// pages (ReferenceMiner.Distil — regex-only, browser+node identical), applies
	// them to the run, and ships {REFCODE}_reference-template.json in the outputs to
	// send to Chris so the reference joins PageForge's templated modules. Both
	// overrides ride into ModuleResolver.PrepareRun as plain options (entry parity —
	// the batch harness passes neither, so batch/corpus output is byte-identical BY
	// CONSTRUCTION; proven by _probe_r249_refmod.cjs: onplain == REFMOD_OFF-with-
	// options md5-identical across processes). New engine file ReferenceMiner.js
	// (index-sync 33/28). Data Emit_Templates.reference_module; env REFMOD_OFF.
	// ROUND 250 (260618.23): REFERENCE-MODULE PANEL REFINEMENTS (Gavin, same day) —
	// the "Automatic (recommended)" choice is REMOVED; the pick choice is renamed
	// "Choose a reference module from the library (suggested module selected if one
	// exists)" and is now a DROPDOWN that AUTO-SELECTS the suggestion. The suggestion
	// rule is Gavin's two-tier walk with NO wider fallback: (1) same module series
	// (OSAI502 → OSAI501 first and foremost), (2) same subject at the same phase
	// (no OSAI5xx → an Online Safety 5xx sibling, e.g. OSOH501/OSBY501; the subject
	// is borrowed from any indexed module sharing the prefix when the code is new);
	// neither tier → the dropdown shows "Please select a reference module" and the
	// CONVERT BUTTON STAYS INACTIVE until a module is selected OR reference HTML
	// pages are uploaded (App.#updateConvertGate). "Chris" → "Gavin" in the
	// reference-HTML instructions/labels/notes. Probe re-run ALL GREEN
	// (_probe_r249_refmod.cjs: OSAI502→OSAI501 series · OSSC502→OSAH501
	// subject_phase · ZZQQ101→null · toggle-off identity); entry-parity PASS;
	// index-sync 33/28.
	// ROUND 251 (260618.24): REFERENCE-DROPDOWN TYPE-TO-FILTER (Gavin) — a filter
	// box above the reference dropdown narrows the 390-code list live as a code is
	// typed (case-insensitive substring on the code and its subject · template
	// label); an EXACT single match selects itself, the current selection is never
	// dropped by filtering, clearing the box (or the reset, or a fresh suggestion
	// auto-select) restores the full list. UI-only (App.js/index.html/Config
	// selectors/styles.css); the engine and every conversion byte are untouched;
	// entry-parity PASS; index-sync 33/28.
	// ROUND 252 (260618.25): REFERENCE LIST IN PLAIN SIGHT (Gavin — "the user
	// cannot see the modules being filtered until they click the drop down") —
	// the reference dropdown is now an always-visible scrolling LIST BOX
	// (size=8): the filtering happens in front of the person as they type, the
	// selected row scrolls into view, and a live "Showing N of 390 library
	// modules…" line underneath narrates the filter state (incl. an explicit
	// no-matches message). UI-only; engine untouched; entry-parity PASS.
	// ROUND 253 (260618.26): LIBRARY REGISTRIES REFRESHED WITH THE NEW GOLD MODULES
	// (Gavin — "update the distilled templates from 01-Finalized_Modules_").
	// Module_Structure_Index.json + Granular_Scaffold_Registry.json rebuilt from the
	// grown gold library: 390 → 454 modules (+64: the BLL24x/25x/26x/27x intake,
	// BLLR201, the CED additions, CHFUN01/04-07, ENGJ403, ENGS405, HPFUN/HPRE,
	// OSSC401/501, OSSM401/501, SCCH301, SCPH301, SSCI/SSEA/SSOG, TEDC401/402,
	// TRR110, TWH* siblings, XGF9002, XMES202). The reference dropdown/suggestion now
	// covers all 454 (SCCH302 → SCCH301, CHFUN02 → CHFUN01, OSSC402 → OSSC401 — all
	// previously suggestion-less). Named consequence: a base whose FIRST gold member
	// just landed (e.g. SCCH via SCCH301) no longer trips the r238 evidence floor —
	// real evidence now exists, by design. Rebuild recipe updated for the grown
	// corpus (48-way shards via outputs/_r253_shard_driver.sh — a 12-way slice no
	// longer fits the sandbox wall). Registry selftest PASS; cascade selftest PASS
	// after re-pinning the stale SOLIDIFY-DEFER fixture BLL111→ENFUN03 (the r218
	// stale-pin class — the intake legitimately moved BLL111 to a full escalate);
	// vet + subject-params selftests PASS; JS↔Python parity 1653/1653 EXACT;
	// entry-parity PASS. NO corpus regeneration (not requested).
	// ROUND 254 (260618.27): REFERENCE-LIST SUBJECT + PHASE FILTERS (Gavin) — two
	// new dropdowns beside the type-to-filter box narrow the visible modules by
	// SUBJECT (every distinct subject in the library index, 17 today incl.
	// "Unclassified") and by PHASE LEVEL, each phase option carrying a concise
	// label + a real example code ("Phase 3 · Years 7–8 (e.g. ANZH301)", "NCEA ·
	// senior secondary (e.g. AGH1001)", "Fundamentals (e.g. ARFUN01)", "9xx series
	// · short courses (e.g. EXBP901)"). Phase classification = the engine's own
	// ModuleResolver.PhaseKeyFor (not a UI re-derivation); all three filters
	// COMBINE; the count line names every active filter; the current selection is
	// never dropped by filtering; a suggestion auto-select and the reset clear all
	// filters. UI-only; engine untouched; entry-parity PASS.
	// ROUND 255 (260618.28): FILTER LAYOUT + THE COMPLETE PHASE LIST (Gavin's
	// screenshot). Element order swapped per the markup: subject + phase dropdowns
	// first, the type-to-filter box below them. "Unclassified" removed from the
	// subject list (subject-less modules still show under "All subjects"). The
	// phase list is now COMPLETE, enumerated over all 454 library codes with the
	// filter's OWN classifier #refPhaseKey (the engine's PhaseKeyFor folds a
	// leading 5 into NCEA for registry-lookup purposes, which hid Phase 5 from
	// the filter): 1xx 120 · 2xx 105 · 3xx 42 · 4xx 28 · **5xx 15 (NEW — "Phase 5
	// · Years 11–13", OSAI501/CEDO501-class)** · NCEA 45 · FUN 61 · 9xx 30 ·
	// other 8 (XLP/XWHA specials). UI-only; entry-parity PASS.
	// ROUND 256 (260618.29): THE "RECOMMENDED" ROW NOTE (Gavin) — the suggested
	// reference module's row in the visible list carries a red "— ★ recommended"
	// note (option.ref-recommended, red + bold; native options can't hold real
	// badge elements, so it's styled row text). The note survives every list
	// rebuild (filtering, manual picks — the suggestion is remembered on
	// App.#refSuggestedCode) and clears with the reset. UI-only; entry-parity PASS.
	// ROUND 257 (260618.30): PINNED RECOMMENDED ROW + SUBJECT→PHASE CASCADE (Gavin) —
	// the recommended module is PINNED to the TOP of the visible list no matter what
	// filters are active (rendered first after the placeholder, excluded from its
	// alphabetical spot; the count line includes it and says so when it is the only
	// row a filter left visible); and choosing a SUBJECT rebuilds the phase dropdown
	// to offer ONLY that subject's phases (data-verified: Online Safety → Phases 1–5
	// only; 1-10 Science → Phase 3 + Fundamentals; NCEA1 → NCEA + Fundamentals),
	// with example codes drawn from within the subject and an invalidated phase
	// choice resetting to "All phases" (App.#renderPhaseOptions, also re-run by the
	// filter clear). UI-only; entry-parity PASS.
	// ROUND 258 (260618.31): PLACEHOLDER DROP + THE RED CONVERT-GATE NOTE (Gavin) —
	// with a recommended module pinned (and pre-selected) the "Please select a
	// reference module" placeholder row is REMOVED from the list (a real selection
	// always exists; without a suggestion the placeholder stays as the visible
	// nothing-chosen state the gate keys on); and while the Convert button is
	// deactivated BY THE REFERENCE REQUIREMENT, a red note under it says why
	// ("Please select a reference module, or upload a reference module's HTML
	// pages in Section 2" — wording per Gavin's follow-up;
	// Config.Strings.ConvertGateReference, #convert-gate-note, driven by
	// App.#updateConvertGate). UI-only; entry-parity PASS.
	// ROUND 259 (260618.32): PRE-SELECTED SUBJECT + PHASE FOR THE RECOMMENDATION
	// (Gavin) — when a suggested module exists, its SUBJECT and PHASE are also
	// pre-selected in the filter dropdowns, so the visible list opens on the
	// recommendation's own cohort (the r257 cascade fills the phase list from
	// that subject first; an unclassified suggestion leaves "All subjects").
	// A manual pick still stands untouched; the reset clears everything.
	// UI-only; entry-parity PASS.
	// ROUND 260 (260618.33): THE TEMPLATE FILTER (Gavin) — a fourth filter dropdown
	// narrows the visible modules by TEMPLATE type (the library carries exactly
	// four: Standard 316 · Inquiry 65 · Fundamentals 53 · Bilingual 20). It behaves
	// like the others: narrows with the chosen subject (only that subject's
	// templates offered; invalidated choice resets to "All templates"), combines
	// with the code/subject/phase filters, is named in the count line, is
	// PRE-SELECTED from the recommended module on auto-select, never drops the
	// current selection, and clears with the filter reset. UI-only; entry-parity
	// PASS.
	// ROUND 261 (260618.34): THE PICKER'S TWO-COLUMN LAYOUT + RESET BUTTON (Gavin's
	// annotated screenshot). The reference picker rearranges per his drawing: the
	// LEFT column stacks the three filter dropdowns, each with a label (Subject /
	// Phase / Template), plus a "Reset filters" button (clears the code text + all
	// three dropdowns; the current selection is untouched); the RIGHT column holds
	// the type-to-filter box directly above the always-visible module list with the
	// count line under it. The status text takes his direct wording: two lines —
	// "Module detected: X." / "Suggested reference: Y (SERIES · TYPE Template)" —
	// with the why-phrase dropped. UI-only; entry-parity PASS.
	// ROUND 262 (260618.35): PLAIN-LANGUAGE IMAGE-MODE LABELS (Gavin) — the two
	// image options lose their "Mode P"/"Mode D" jargon: "Placeholder images:
	// pages show a temporary placeholder for each image (real filename commented
	// out in backend)." / "Direct images: pages link
	// straight to the real image files — no placeholders." The Module-details card
	// says "Placeholder images"/"Direct images" instead of the internal "P"/"D"
	// (which remain the run/option values — wording only). UI-only; entry-parity
	// PASS.
	// ROUND 263 (260618.36): SCCH302 missing menus — the SCCH registry rows mined
	// from SCCH301's gold (Style-Anchor base_rules + Menu-Scaffold SCCH|7-8) +
	// the curriculum extra-tabs composition (env XTABCURRIC_OFF) + two
	// ReferenceMiner mining corrections + the "how will i know i have learned it"
	// ld_labels entry. NO regeneration (not requested).
	// ROUND 265 (260618.37): CHFUN01 (Chris) — THE SELF-CLOSED-PARAGRAPH
	// EXTRACTOR REPAIR (a <w:p .../> counted as an open with no close ratcheted
	// #findClose's depth and swallowed the rest of the document into ONE giant
	// block — front matter leaked, every paragraph boundary lost; env
	// SELFCLOSEP_OFF; 20 modules' block streams repair, incl. TRR203's
	// "mega-paragraph") + THE LEVEL-PAGE FUNDAMENTALS DIALECT ([PAGE N Novice]
	// sections grouped by LEVEL into fundamentalsPanels, level-named phases
	// nav/tiles, [Page Overview] LI/SC aggregated into per-level menu tabs; env
	// LEVELPAGE_OFF; registry-gated CHFUN|combo) + the Style-Anchor
	// "1-10 Languages"/CHFUN base row (page_model single-file — CHFUN05 was
	// shipping 52 files against the human's 1). NO regeneration (not requested).
	// ROUND 266 (260618.38): CHFUN01 screenshot follow-through (Chris) — THE
	// MEDIA-TABLE CAROUSEL ("MAKE INTO CAROUSEL!"): a [slideshow] table whose
	// every cell is [image]/[video]+URL(+[caption]) BUILDS one slide per cell
	// (shorts → youtubeShort 1x1) AND terminates the capture right after the
	// table, so the following quiz becomes its OWN bundle (env CARMEDTBL_OFF);
	// the [dropquiz] UNRESOLVED-MARKER RETAG → a dropdown bundle, zero-tag
	// spans only (env DROPQUIZ_OFF); the level-pages ID-LED ACTIVITY BOX
	// ("1A Check your understanding" → activity interactive 1A/1B/1C with the
	// writer's own title h3; rides LEVELPAGE_OFF). FULL corpus regeneration +
	// every protected gate HELD-or-IMPROVED (skeleton 49.862%/983/190/16,
	// blast 22 named modules).
	// ROUND 267 (260618.39): "MAKE YOUR OWN TEMPLATE" (Gavin) — a third reference
	// choice between the library picker and the HTML upload: three REQUIRED
	// horizontal dropdowns (Subject / Phase / Template) that always show ALL
	// available options (no cascade, not narrowed by the destination module);
	// Convert stays inactive until all three are chosen (gate note
	// Config.Strings.ConvertGateCustom). The engine inherits the structure from
	// the MOST TYPICAL library module of the narrowest matching pool via
	// ReferenceMiner.PickBySpec — THE TEMPLATE IS NEVER RELAXED (each template is
	// a separate beast; Fundamentals/Inquiry are one-page formats, so it dictates
	// the content/lesson layout): subject+phase+template → subject+template →
	// phase+template → template only; "most typical" = per-field majority
	// agreement over the Style-Anchor tracked fields (ties → most recent).
	// Rides the standard PrepareRun referenceCode pathway (entry-parity PASS;
	// probe _probe_r267_customtpl.cjs ALL GREEN: OS·3xx·Standard → OSAI301 exact
	// pool n=7; Science·5xx·Fundamentals → SCFUN01 phase-relaxed; OS·1xx·
	// Bilingual → TRR115 template kept; REFMOD_OFF-with-spec == plain
	// md5-identical cross-process). ALSO: "No suitable module" renamed "Upload a
	// reference module"; shared phase classifier moved to
	// ReferenceMiner.PhaseKey (UI + engine can't drift). Data
	// reference_module.custom_template; env REFMOD_OFF.
	// ROUND 268 (260618.40): SECTION ORDER SWAP (Gavin) — "Image output mode" is
	// now section 2 and "Reference module" section 3, so the reference choices sit
	// directly above the Convert button and the person can SEE the button
	// activate/deactivate as they complete (or un-complete) the reference
	// requirement. The two red gate notes now say "Section 3". UI-only; ids,
	// wiring and behaviour unchanged; entry-parity PASS.
	// ROUND 269 (260618.41): THE DOUBLE-❗ ACKNOWLEDGEMENT FIX (Gavin, the SCBI301
	// report). An iStock item that was BOTH title-unverified (r236 — ❗ prefixed)
	// AND of an unknown Media-List type (the r-ackTodo re-wrap, whose visible form
	// prepends its OWN ❗) shipped "❗ ❗ …" — 58 corpus pages carry the class.
	// FIX 1 (general): #todoFromEntry strips the entry's own leading unverified
	// marker before wrapping — ONE ❗ ever, by construction; both machine comments
	// (unknown-type + istock-unverified) now ride the line together, and the top
	// designer note still counts the id. FIX 2 (data): "drawing" joins
	// Acks_Formats.type_prefix_map ("Drawing" — the prefix the fallback already
	// guessed; SCBI301's Drawing-typed items are a legitimate recurring type, so
	// they stop being unknown-type flags entirely). Probe-proven on the exact
	// SCBI301 items (one ❗ each; a still-unknown "Sketch" + unverified case keeps
	// exactly one; no signal lost). The 58 shipped double-marker pages heal at the
	// NEXT regeneration (named delta; none requested this round). Rides the
	// existing ISTOCKUNVERIFIED_OFF / ACKUNKNOWN_OFF toggles. Entry-parity PASS.
	// ROUND 270 (260618.42): CUSTOM-TEMPLATE DROPDOWN TITLES + ONE-LINE LAYOUT
	// (Gavin's annotated screenshot) — the "Make your own template" dropdowns gain
	// a title above each (Subject / Phase / Template) and the three fields share
	// ONE horizontal line (flex nowrap, equal shares, selects width:100% — the
	// template no longer wraps to a second line). UI-only.
	// ROUND 271 (260618.43): THE MEDIA|CAPTION TABLE CAROUSEL + THE FEATURE INDEX.
	// (Chris, OSSC401-1.0 "there are still some carousels not being built"). A
	// carousel authored as one table pairing a media cell with the slide's prose now
	// builds (env CARMEDCAP_OFF), and its table TERMINATES the capture so the next
	// section is no longer swallowed (env CARCAPTBL_OFF). Same round: the per-module
	// FEATURE INDEX (data/Module_Feature_Index.json + reference/tests/regen_scope.cjs)
	// so a fix can be regenerated over only the modules that carry the feature it
	// touches, instead of the whole corpus.
	// ROUND 272 (260618.44): EXACT-MATCH SUGGESTION (Gavin) — when the detected
	// module code itself exists in the library index (a distilled template
	// exactly matching the module — common while testing), THAT module is the
	// suggested/recommended reference, ahead of the two-tier relative walk
	// (PrecedenceResolver.SuggestReference gains the "exact" tier). Same styling,
	// same pinned red ★ row, same subject/phase/template pre-selects — no visible
	// difference between a perfect match and the closest match. At conversion the
	// PrepareRun guard (referenceCode !== moduleCode) correctly skips the
	// override: the module's own registry home IS the exact-match template, so
	// output is identical by construction. Probe leg D updated (an indexed code
	// suggests ITSELF; tier pins refreshed for the 454-module library) — ALL
	// GREEN; entry-parity PASS.
	// ROUND 273 (260618.45): THE DUPLICATE "Go to your journal" BUTTON (Chris —
	// the SCCH302-03 screenshot, "why is this button being added twice"). The
	// r239 absorb pulls a writer's go-to-journal [button] that sits after a
	// bundle-owned activity's widget INSIDE the still-open box and marks the item
	// _consumed — but the main loop has NO general _consumed guard for a TAG
	// item, only the positional "skip the items immediately after me" idiom,
	// which cannot reach this button because the widget's own unconsumed end tag
	// ([end click and drop]) sits in between. So the button rendered AGAIN on its
	// own turn: a SECOND identical h4 in a bare row underneath the closed box.
	// The absorb now also marks the item _goJournalAbsorbed and the main loop
	// skips the ITEM outright (so no empty row/col is left behind either) — the
	// r232 #mtkQuizEmit "emit exactly once, wherever the item is reached"
	// discipline. Contained BY CONSTRUCTION: only an item this absorb itself
	// claimed is ever suppressed. MEASURED affected set (34 candidates × 2
	// states, outputs/_detect_r273_gojournal.cjs): EXACTLY 10 pages / 7 modules
	// (CEDO102, ENGC102, ENGJ102, MXDI103 ×2, MXFL103, SCCH301 ×2, SCPH301 ×2) —
	// every diff a PURE deletion of the duplicate heading. SCOPED REGENERATION of
	// those 7 (Chris asked for it once the fix was proven): scoped ship #1 since
	// r266, blast 12 pages (the 10 + 2 overview pages coming current with the r269
	// acks fix, named), 0-stale, containment 7 ⊆ 7, spot-check 12/12 byte-identical
	// IN MEMORY, every protected gate HELD at the r266 baselines. Proven by
	// outputs/_probe_r273_gojournal.cjs, one process per state, ALL CHECKS PASS
	// both ways. Data buttons.go_journal.absorb_suppresses_own_render; env
	// GOJOURNALDUP_OFF.
	// ROUND 274 (260618.46): CUSTOM-TEMPLATE EXISTING-COMBINATIONS CASCADE (Gavin,
	// superseding the r267 no-cascade rule at his request) — in "Make your own
	// template", choosing a SUBJECT now narrows the phase and template dropdowns
	// to what that subject has ALREADY DEVELOPED, and the two cross-narrow (a
	// chosen template limits the phases and vice versa), so ONLY combinations
	// that exist in the library can be assembled — guaranteeing real templated
	// attributes to inherit (a subject with no Bilingual modules can't offer
	// Bilingual; no suitable combination = the trigger to use "Upload a
	// reference module"). Before a subject is chosen the full lists show; an
	// invalidated choice resets to its placeholder and re-gates Convert; the
	// reset restores the full lists. Data-verified: Online Safety → phases 1–5 ·
	// Standard only; Science → {3xx, FUN} × {Standard, Fundamentals} with the
	// cross-narrow blocking Science+3xx+Fundamentals; TMoA → Bilingual only.
	// The engine's PickBySpec relaxation chain is unchanged (now a belt-and-
	// braces safety net — the UI guarantees the exact pool is non-empty).
	// App.#renderCustomOptions; UI-only; entry-parity PASS.
	// ROUND 275 (260618.47): THE THREE BUILDER BLOCKERS (Chris — carousel/video,
	// accordion/TABLE, clickDrop/image; FULL regeneration + gates, ledger reset).
	// ACCTABLE_OFF — a captured data table inside an accordion PANEL renders through
	// the converter's own kept-table emitter (the seam rich TABS has used since r195;
	// gold ships 325 such accContent blocks across 99 modules), plus the
	// #accordionWithImages CONTENT-LOSS repair (a table item has no .text, so it fell
	// through the blank-line guard and vanished) and a leak guard on the widget table
	// seam (the r167 rule: a table still showing a resolved [tag] declines, so building
	// one can never ADD a counted leak). CARVIDEO_OFF — the widened tail-URL lookahead
	// (the writer's URL line is often a RED span, not the plain black line r247 looked
	// for, so the video resolved no id and the whole carousel bailed), Shorts/other
	// hosts embedding as MediaBuilder already does, and the bare-URL slide line dropped
	// as the reference it is (gold: 1,618 carousel captions, 0 bare-URL). CDIMAGE_OFF —
	// an [image] no longer bails a clickDrop: each item keeps an ordered part list and
	// the image renders in the writer's own position (gold: 939 of 2,877
	// clickDropContent blocks carry an <img>), an empty media-list marker is skipped,
	// a leading label-less [click drop] is the opener, and text riding along with the
	// URL is body continuation. Coverage 21.4% -> 23.4%; NEW BUILDS accordion +54 /
	// carousel +48 / clickDrop +1, LOST 0 across every type.
	// ROUND 276 (260618.48): SPEECHBUBBLE — BUILD EVERY VARIATION (Chris, the
	// interactive-coverage chain, round 1 of 8). A decline-reason probe that rewrites
	// every `return null` in the speechBubble region to a recorder made the SHIPPED
	// builder report its own verdict: 100% of the 258 declines were decided in the
	// narrow 1x2-table branch, on guards about the writer's LAYOUT rather than the
	// widget — 72 "not exactly one table", 67 "any modifier at all", 50 "more than one
	// row", 38 "not exactly two cells". SBRICH_OFF — the RICH GENERAL COMPOSER, tried
	// LAST so all four existing branches stay byte-identical: members and every table
	// cell flatten into an ordered stream of parts (bubble / image / head / text /
	// note) and one `row speechBubble` is emitted per bubble, avatar form or text-only
	// form, reusing the round-246/247 templates because the gold measurement (1218
	// rows / 143 modules) says those ARE the plurality. Table cells group by the axis
	// that yields one bubble per group; a plain-cell table under a bubble invocation
	// becomes one bubble per cell; a non-iStock image takes the round-126 slug name;
	// asset requests and writer instructions ride along as red Writers Notes.
	// speechBubble coverage 55.9% -> 86.3% (327 -> 505 of 585); overall interactive
	// coverage 23.4% -> 26.9%; NEW BUILDS 178, LOST 0 across every type.
	// ROUND 277 (260618.49): hint + hintSlider — build every variation (Chris — the
	// interactive-coverage chain, round 2 of 8). THE HEADLINE: `hint` and `hintSlider`
	// are two DIFFERENT elements, and `hint` had no template in Emit_Templates at all,
	// so Build returned null at its missing-template guard and not one of its 64 tagged
	// bundles ever reached a builder. Adds the measured p.hintLink + span.hint +
	// hintDropContent element (HINTELEM_OFF), a general LABELLED-PAIR slider composer
	// that runs last so every pre-277 build is byte-identical (HINTPAIR_OFF), and the
	// scanner rule that stops a writer's own [Title] paragraph — a `title bar`
	// SECTION_MARKER, an absolute terminator — from ending the capture before anything
	// was collected (HINTTITLE_OFF). hint 0 -> 48 of 64; hintSlider 22 -> 32 of 44;
	// overall interactive coverage 26.9% -> 28.1%; NEW BUILDS 58, LOST 0 in every type.
	// ROUND 278 (260618.50): ACCORDION — BUILD EVERY VARIATION (Chris, the
	// interactive-coverage chain, round 3 of 8). The decline recorder accounted for
	// 100% of the accordion's 454 declines and the biggest class — 239 / 105 modules —
	// was ONE mechanism: content arrived before any panel opened, because only an
	// [accordion N] tag could open a panel while writers delimit panels with a table,
	// a repeating heading or a bold lead just as often. #accordionPanels resolves all
	// four (ACCPANELS_OFF), and a trailing [button] now ends the capture so it renders
	// as a real button instead of being swallowed (ACCBTNTAIL_OFF).
	// accordion 253 -> 371 of 707 (35.8% -> 52.5%); overall coverage 28.1% -> 30.5%;
	// NEW BUILDS 126, LOST 0 in every type.
	// ROUND 279 (260618.51): CAROUSEL — BUILD EVERY VARIATION (Chris, the
	// interactive-coverage chain, round 4 of 8). The decline recorder accounted for
	// 100% of the carousel's 561 declines: 277 carry a captured TABLE, and 143 of
	// those died at a DEAD-END where the one narrow image|caption branch RETURNED its
	// null so no fallback was ever tried. #carouselTableSlides reads any of them by
	// the gold's own rule — one data ROW is one slide (CARTABLE_OFF); a captured table
	// with another carousel ahead now ENDS the walk, so XTAS101's three slideshows are
	// three carousels as the gold has them (CARSPLIT_OFF); the member vocabulary names
	// a non-iStock image, an unembeddable video, a [Caption] and an [audio]
	// (CARMEMBER_OFF); and "carousel + carousel" is only the placeholder label
	// (CARSAMETYPE_OFF).
	// carousel 308 -> 639 of 896 (35.4% -> 71.3%); overall coverage 30.5% -> 36.8%;
	// NEW BUILDS 331, LOST 0 in every type.
	// ROUND 280 (260618.52): MODAL — BUILD EVERY VARIATION (Chris, the
	// interactive-coverage chain, round 5 of 8). The decline recorder accounted for
	// 100% of the modal's 292 declines and they collapsed onto TWO guards of the
	// round-73 BUTTON path. The cause underneath: there was a builder for the
	// IMAGE-triggered modal (r216) and one for a modal that is really a link to a PDF
	// (r73), and NOTHING for the ordinary TEXT-triggered modal — which the gold says
	// is DOMINANT (div.button.TKmodalButton 213 of 283 = 75.3%, 52 modules).
	// #modalSets is tried LAST and emits the corpus convention (trigger + its sibling
	// div.TKmodal) from four delimiters: numbered [Modal N …] sub-tags, the
	// same-block label line, a table row, and the tag's own text (MODALSETS_OFF);
	// the scanner recovers the first set's label from the line above (MODALLEAD_OFF).
	// modal 88 -> 161 of 380 (23.2% -> 42.4%); overall coverage 36.8% -> 38.2%;
	// NEW BUILDS 73, LOST 0 in every type.
	// ROUND 281 (260618.53): TABS — BUILD EVERY VARIATION (Chris, the
	// interactive-coverage chain, round 6 of 8). Tabs already had FIVE builders, four
	// of them gated by a mined gold-choice REGISTRY row, so the round opened by
	// testing the obvious hypothesis: neutralising EVERY registry gate moved tabs
	// from 17 built to 18 — a gain of exactly ONE. The registry was never the
	// blocker, only the first door. The real blocker is that the writer's pane
	// DELIMITER is usually a TABLE (or a plain heading run) no builder reads, and one
	// unplaceable member bails the whole widget. #tabsPanes is a general composer
	// tried LAST (so all 17 pre-round builds are byte-identical by construction),
	// resolving panes from an ordered delimiter vocabulary — [Tab N] tags, a table
	// read column-major (incl. a role-labelled first column), a table read row-major
	// or cell-per-pane, and a repeating heading run — over the shared round-278
	// member vocabulary (TABPANES_OFF). Two guards the tabs VERIFIER caught before
	// they shipped: a wholly-red label row (a flipCard [front]/[drop] table was
	// becoming four tabs all labelled "front") and duplicate labels.
	// tabs 17 -> 34 of 113 (15.0% -> 30.1%); overall coverage 38.2% -> 38.5%;
	// NEW BUILDS 17, LOST 0 in every type.
	// ROUND 282 (260618.54): FLIPCARD — BUILD EVERY VARIATION (Chris, the
	// interactive-coverage chain, round 7 of 8). flipCard was the WORST-COVERED
	// widget in the library (49 of 484 = 10.1%) and the second-largest class by
	// modules (191). The decline recorder accounted for 100% of the 435 declines and
	// they collapsed onto two mechanisms: 289 carry a captured TABLE the four dialect
	// builders cannot read (220 of them died on the single line `if (width !== 2)` —
	// the dialects know three table layouts, the writers use at least six), and
	// #flipCardMembers DEMANDS an image on every card, which the gold contradicts
	// outright (measured over 643 gold groups / 3122 cards, a front is a HEADING
	// alone 22.3% and a PARAGRAPH alone 20.7% — text-only cards are 43% of the
	// library). #flipCardCards is a general composer tried LAST (so all 49 pre-round
	// builds are byte-identical by construction), resolving cards from an ordered
	// delimiter vocabulary — face-marker rows, a face-marker label COLUMN, per-cell
	// face markers, a two-row column table, an N x 2 row table, [Flip Card N] tags,
	// [front]/[back] markers, face LABEL WORDS, and a bare media series
	// (FLIPCARDS_OFF). THREE bugs the flipCard VERIFIER caught before they shipped:
	// the writer's PHOTO BRIEF rendering as visible card text, a bare URL rendering
	// as a paragraph, and — in the verifier itself — the gold's `class="front
	// flipImage"` faces (1065 of them) never being harvested at all.
	// flipCard 49 -> 228 of 484 (10.1% -> 47.1%); overall coverage 38.5% -> 42.0%;
	// NEW BUILDS 179, LOST 0 in every type.
	// ROUND 283 (260618.55): CLICKDROP — BUILD EVERY VARIATION (Chris, the
	// interactive-coverage chain, round 8 of 8 — THE LAST). clickDrop was the
	// worst-covered widget left (61 of 690 = 8.8%) and the third-largest class by
	// modules (143). The decline recorder accounted for 100% of the 629 declines and
	// CORRECTED the coverage dashboard: the [image] blocker it named was fixed at
	// round 275 and decides only 23 declines now. The real ones: 240 an item with a
	// LABEL and NO CONTENT, 125 NO item resolved at all (85 of them a TABLE the walk
	// never looked at), 94 content arriving BEFORE the first button, 85 a member it
	// cannot place. #clickDropItems is a general composer tried LAST (so all 61
	// pre-round builds are byte-identical by construction) resolving items from an
	// ordered delimiter vocabulary — labelled [click drop N] tags, a captured table
	// read five ways, and a repeating heading run — over the round-278 member
	// vocabulary shared verbatim (CLICKDROPS_OFF). Gold-backed guards from 1199 gold
	// groups / 211 modules: a ONE-item clickDrop is the gold's own plurality at
	// 43.5%, and of 3036 gold labels <=8 words is 99.2%. THREE bugs the clickDrop
	// VERIFIER caught before they shipped: the writer's PHOTO BRIEF becoming a button
	// label, a bare URL becoming a label over an empty panel, and — in the verifier
	// itself — a non-greedy regex that could not read a panel containing a nested
	// <div> (674 of the gold's own panels do).
	// clickDrop 61 -> 163 of 690 (8.8% -> 23.6%); overall coverage 41.9% -> 43.9%;
	// NEW BUILDS 102, LOST 0 in every type; 67 modules.
	//
	// ROUND 285 (260618.57): CLOSING THE ROUND-284 DATA-RECOVERY RESIDUAL — DATA ONLY,
	// no engine change, no new toggle. Four wrong values and one missing block, each
	// recovered as a real convention and proven against outputs/_r284_CORRECT_corpus.md5:
	//   * flipCard face_label_pattern / face_label_back_pattern — a face marker is a BARE
	//     bracketed word (measured [front] 358 / [back] 354 / [reverse] 104 / [facing] 22 /
	//     [on flip] 5; ZERO separator forms corpus-wide). The gate must carry BOTH faces:
	//     'facing' is a lexicon alias of 'back', and EXPFUN06's [on flip] has no tag at all.
	//   * flipCard asset_reference_pattern — an asset request is LABELLED at the start, or
	//     carries the writer's own [Image] tag, or is a bare gm-id. image\b never matches
	//     "Images": a brief names ONE asset, the plural is prose.
	//   * clickDrop note_tags += "engagement quiz button" — a widget marker, like [button].
	//   * modal_sets.content_image — the block was MISSING, so an image inside a modal wore
	//     the trigger's TKmodalButton class (gold ships img-fluid 456:1 inside a TKmodal).
	// Oracle 28 -> 13 differing (27 real -> 12, named in the changelog; XMES203_2_0 differs
	// BY DESIGN). Scoped ship: 257 modules regenerated, EXACTLY 15 pages changed / 0 added /
	// 0 removed; every protected criterion EXACT.
	//
	// ROUND 287 (260618.58): THE DROPDOWN — the first builder this widget has ever had.
	// All 390 captured dropDown bundles used to decline at Build's own missing-template
	// guard, before the dispatch: there was no `dropDown` key in Emit_Templates and no
	// case in the switch. Two things had to be settled before any code:
	//   * THE POPULATION IS NOT WHAT THE TYPE NAME SAYS. The lexicon aliases the student
	//     file-upload "dropbox" onto this same widget type. Measured over every Writers
	//     Template: 240 of 393 captured bundles are dropbox (87 modules), 142 are a
	//     genuine dropdown (82). The builder is FENCED on the writer's own opener, so
	//     every dropbox bundle is byte-identical BY CONSTRUCTION (proven on 61 pages).
	//   * THE ANSWER SIGNAL IS NOT ONLY RED. Writers mark the correct option by colouring
	//     it red OR with an explicit [correct] tag before it; both reduce to a MARK at a
	//     character position, so one derivation serves both.
	// Four dialects, each gold-quoted: D1 paragraph-parens (BLL273), D2 question+mark
	// (PHE1007), D3 table+red (SCCH301), D4 bullets+(correct) (ENGC101). A label, an
	// option and an answer are NEVER invented — the largest decline bucket (76 bundles /
	// 52 modules) is a dropdown whose answer the writer never marked.
	// RESULT dropDown 0 -> 14 of 390; NEW BUILDS 14 / LOST 0 in every type; 12 modules.
	// Verifier: 128 units, exact 76, defect 0, selftest GREEN. No regeneration (not
	// requested) — the r284/r285 baselines still describe the corpus. env DROPDOWN_OFF.
	static AppVersion = "260618.58";

	// ---------------------------------------------------------------------
	// RUNTIME DATA FILES (paths are relative to app/index.html — served over HTTP)
	// ---------------------------------------------------------------------
	// WHAT: every file the engine reads at runtime, listed by a friendly key.
	// WHY:  DataService loads exactly this list at startup, so adding a new
	//       data file is a one-line change here.
	// USAGE: DataService reads Config.DataFiles.TagLexicon, etc.
	static DataFiles = {
		TagLexicon:        "../data/Tag_Lexicon.json",
		TagExceptions:     "../data/Tag_Exceptions.json",
		InstructionCues:   "../data/Instruction_Cues.json",
		InputDocRules:     "../data/Input_Doc_Rules.json",
		StyleRegistry:     "../data/Style_Anchor_Registry.json",
		MajorityRegistry:  "../data/Style_Anchor_Registry_Majority_And_Deviations.json",
		BoundaryBank:      "../data/Interactive_Boundary_ChildTag_Bank.json",
		// NOTE: Interactive_Wrapper_Catalogue.json is reference-only and is
		// deliberately NOT loaded at runtime — widget RECOGNITION comes from the
		// lexicon + boundary bank, and widget MARKUP from
		// Emit_Templates.interactive_builders. Re-adding it would just load
		// ~1,400 unused lines at every startup.
		EmitTemplates:     "../data/Emit_Templates.json",
		AcksFormats:       "../data/Acks_Formats.json",
		ManifestPatterns:  "../data/Manifest_Patterns.json",
		ConventionRegistry: "../data/Html_Convention_Registry.json",
		// The menu type (tabs / simplified / none) per subject × phase,
		// measured from the human-built corpus.
		MenuScaffold:      "../data/Menu_Scaffold_Registry.json",
		// The whitelist of Creative-Services authors whose native Word comments
		// we surface into the page, plus how to render them.
		CommentAuthors:    "../data/Comment_Authors.json",
		// Whole-page "template mode": the order of the <body> class tokens plus
		// the language / translation attributes.
		TemplateModes:     "../data/Template_Modes.json",
		// The three files behind the module precedence cascade (see
		// PrecedenceResolver.js): the per-module built-structure index (plus
		// module_meta, the data the cascade filters over), the cascade's level
		// order and reliability floors, and the subject-level default parameters.
		// These are loaded but the live engine application ships turned OFF
		// (Precedence_Cascade.engine_inherit.enabled === false), so today they
		// are read-only reference data.
		ModuleStructureIndex: "../data/Module_Structure_Index.json",
		PrecedenceCascade:    "../data/Precedence_Cascade.json",
		SubjectParameters:    "../data/Subject_Global_Parameters.json",
		// A frequency list of overview-menu heading phrases seen across the
		// human corpus. MenuBuilder uses it to decide when a one-line
		// "**Title:** content" heading should be split (env MENUHEADINGLEX_OFF).
		// Rebuilt by reference/tests/build_menu_heading_lexicon.py.
		OverviewMenuHeadingLexicon: "../data/Overview_Menu_Heading_Lexicon.json",
	};

	// ---------------------------------------------------------------------
	// DOM SELECTORS — the element ids used in app/index.html
	// ---------------------------------------------------------------------
	// HOW TO USE: document.getElementById(Config.Selectors.DropZone)
	static Selectors = {
		FileGuard:     "file-guard",       // the "you opened this via file://" warning screen
		AppRoot:       "app-root",
		DropZone:      "drop-zone",
		FileInput:     "file-input",
		FileList:      "file-list",
		ModeP:         "mode-p",
		ModeD:         "mode-d",
		// (ModeExtract removed — ROUND 235: the interactive hand-off is the
		// default for every run; the UI switch no longer exists.)
		ConvertButton: "convert-button",
		// ROUNDS 249/250 — the Reference-module panel (suggested-module dropdown
		// / reference-HTML upload; round 250 removed the "Automatic" choice and
		// made the dropdown auto-select the suggestion).
		ReferencePanel:  "reference-panel",
		ReferenceStatus: "reference-status",
		RefPick:         "ref-pick",
		RefHtml:         "ref-html",
		RefPickBlock:    "ref-pick-block",
		RefHtmlBlock:    "ref-html-block",
		RefCodeSelect:   "ref-code-select",
		RefCodeFilter:   "ref-code-filter",   // ROUND 251 — the type-to-filter box
		RefCodeCount:    "ref-code-count",    // ROUND 252 — the live "showing N of M" line
		RefSubjectFilter: "ref-subject-filter",   // ROUND 254 — subject filter dropdown
		RefPhaseFilter:   "ref-phase-filter",     // ROUND 254 — phase-level filter dropdown
		ConvertGateNote:  "convert-gate-note",    // ROUND 258 — the red "why Convert is inactive" note
		RefTemplateFilter: "ref-template-filter", // ROUND 260 — template filter dropdown
		RefFilterReset:    "ref-filter-reset",    // ROUND 261 — the "Reset filters" button
		// ROUND 263 — the "Make your own template" choice + its three required dropdowns
		RefCustom:         "ref-custom",
		RefCustomBlock:    "ref-custom-block",
		RefCustomSubject:  "ref-custom-subject",
		RefCustomPhase:    "ref-custom-phase",
		RefCustomTemplate: "ref-custom-template",
		RefHtmlInput:    "ref-html-input",
		RefHtmlList:     "ref-html-list",
		// The "clear everything & convert another module" reset control (its
		// wrapper + the button). Shown only after a conversion completes; the
		// reset returns the converter to its fresh state IN PLACE, without a
		// page reload (a reload would drop back to the site's landing view).
		ResetPanel:    "reset-panel",
		ResetButton:   "reset-button",
		ProgressLog:   "progress-log",
		// The Convert-panel progress bar. App.js drives it; the engine reports
		// progress through the guarded run.onProgress hook (see ConversionRun.js).
		ProgressBar:      "progress-bar",
		ProgressBarFill:  "progress-bar-fill",
		ProgressBarLabel: "progress-bar-label",
		SummaryPanel:  "summary-panel",
		DownloadAll:   "download-all",
		OutputList:    "output-list",
	};

	// ---------------------------------------------------------------------
	// UI STRINGS — the words shown to the person using the tool
	// ---------------------------------------------------------------------
	static Strings = {
		ReadyToConvert: "Ready — drop the Writers Template (+ Media List) above, choose the image mode, then Convert.",
		Converting:     "Converting…",
		Done:           "Conversion complete.",
		// Progress-bar stage labels (set by App.#progressSet).
		ProgressExtract: "Reading files",
		ProgressPrep:    "Preparing module",
		ProgressPages:   "Converting pages",
		ProgressAcks:    "Acknowledgements & media",
		ProgressDone:    "Done",
		ProgressFailed:  "Failed — see the log below",
		// ROUND 258 — shown in red under the deactivated Convert button when the
		// reference requirement is what's blocking it.
		ConvertGateReference: "Please select a reference module, or upload a reference module's HTML pages in Section 3",
		// ROUND 263 — shown when "Make your own template" is active but incomplete.
		ConvertGateCustom: "Please select a subject, phase and template in Section 3 (all three are required)",
	};

	// ---------------------------------------------------------------------
	// FAIL-SAFE — the last-resort UI when the app cannot recover (standards §6).
	// ---------------------------------------------------------------------
	// Replaces the whole app body with a plain message and a Retry button.
	static FULL_BREAK(message) {
		const root = document.getElementById(Config.Selectors.AppRoot);
		if (!root) return;
		root.innerHTML = `
			<div class="full-break">
				<p>${message || "Something went wrong loading the converter."}</p>
				<button onclick="location.reload()">Retry</button>
			</div>
		`;
	};
}
