/**
 * ConventionResolver.js
 * ===========================================================================
 * WHAT THIS FILE DOES:
 * Resolves the module's HTML CONVENTIONS — the scaffolding the human
 * developers apply beyond literal tag conversion (menu archetype + forms,
 * callout lead element, video host) — through the group cascade:
 *
 *      series deviation  →  subject×phase dominant  →  global default
 *
 * This mirrors the style-anchor methodology exactly (and was mandated as
 * such): conventions are measured per subject × template_phase group with
 * overview/lesson as separate page scopes, and a module belonging to an
 * EXISTING series keeps that series' own pattern over the group majority.
 *
 * WHY SEPARATE FILE:
 * One concern only: registry group → HTML conventions. It never reads the
 * docx/DOM (ModuleResolver's job) and never touches tag text (TagNormaliser's
 * job) — it just turns "this module is in group X" into "here is the menu
 * archetype, callout lead, and video host for X."
 *
 * DATA THIS FILE READS:
 * Html_Convention_Registry.json — generated by
 * reference/tests/build_convention_registry.py from the finished corpus.
 * Re-running that script after new modules ship is the maintenance story;
 * no convention lives in code.
 * ===========================================================================
 */

class ConventionResolver {

	/**
	 * Resolves conventions for a run (call after ModuleResolver.Resolve).
	 *
	 * WHAT IT RETURNS (attached to run.conventions):
	 * {
	 *   menu: { overview: {archetype,…}|null, lesson: {archetype,…}|null },
	 *   calloutLead: "h4"|null,
	 *   videoHost: "nocookie"|"youtube"|null,
	 *   source: "series BLL …" | "group …" | "global defaults"
	 * }
	 *
	 * @param {ConversionRun} run - moduleCode + groupKey/seriesCode set by
	 *                              ModuleResolver during registry resolution
	 * @returns {Object} conventions (also stored on run.conventions)
	 */
	static Resolve(run) {
		const REG = DataService.Data.ConventionRegistry;
		const out = {
			menu: { overview: null, lesson: null },
			calloutLead: null, videoHost: null, source: "global defaults",
		};

		const group = run.groupKey ? REG?.groups?.[run.groupKey] : null;
		if (group) {
			out.menu.overview = group.menu?.overview?.dominant ?? null;
			out.menu.lesson = group.menu?.lesson?.dominant ?? null;
			out.calloutLead = group.callout_lead?.element ?? null;
			out.videoHost = group.video_host?.host ?? null;
			out.source = `group ${run.groupKey}`;

			// sibling consistency: the module's own series overrides the
			// group dominant where it deviates (the rule Chris locked)
			const dev = group.series_deviations?.[run.seriesCode];
			if (dev) {
				if (dev.menu_overview) out.menu.overview = dev.menu_overview;
				if (dev.menu_lesson) out.menu.lesson = dev.menu_lesson;
				out.source = `series ${run.seriesCode} (deviation over ${run.groupKey})`;
			}
			run.AddNote("info", "ConventionResolver",
				`HTML conventions from ${out.source}: overview menu ${out.menu.overview?.archetype ?? "default"}, lesson menu ${out.menu.lesson?.archetype ?? "default"}.`);
		} else {
			run.AddNote("info", "ConventionResolver",
				"No convention group found for this module — using the global Emit_Templates defaults.");
		}

		run.conventions = out;
		return out;
	};
}

// Node test-harness hook; browsers ignore it.
if (typeof module !== "undefined") module.exports = { ConventionResolver };
