/**
 * ManifestBuilder.js
 * ===========================================================================
 * WHAT THIS FILE DOES:
 * Produces {MODULE_CODE}_interactives.txt — the reference document that
 * catalogues every captured interactive so the later build phase can
 * construct each one and insert it into the exact file and position
 * WITHOUT re-reading the HTML output.
 *
 * FORMAT HERITAGE:
 * The v1-proven reference document format from
 * 00-PageForge/PageForge Phases/phase4_message.md — format only, no code
 * reuse. The 13 data-pattern names + the tier rule live in
 * Manifest_Patterns.json (Phase 1 keeps the tier field for later phases;
 * ALL interactives are placeholder-only in Phase 1).
 *
 * ANSWER-KEY NOTE:
 * The manifest deliberately CONTAINS the captured data (including answer
 * marks) — it is a developer-only working file that never ships inside a
 * module page. The placeholder HTML carries no answer-bearing comments.
 * ===========================================================================
 */

class ManifestBuilder {

	/**
	 * Builds the complete manifest text for a run.
	 *
	 * @param {ConversionRun} run - interactives + outputs already assembled
	 * @returns {string} plain text document
	 */
	static Build(run) {
		const patterns = DataService.Data.ManifestPatterns;
		const code = run.moduleCode ?? "MODULE";
		const list = run.interactives;

		const tier1 = list.filter((b) => patterns.tiers.tier_1_types.includes(b.type));
		const files = [...new Set(run.outputs.filter((o) => o.kind === "page").map((o) => o.filename))];

		// This txt file is a HAND-OFF WORKLIST for the developer who still has to build the
		// un-built interactives by hand: an interactive the converter already BUILT into the
		// generated HTML is not outstanding work, so by default its entry is OMITTED from the
		// list and the remaining entries are renumbered over the un-built ones only. The
		// summary header still reports BOTH counts (built + un-built) so nothing is hidden,
		// and its NOTE lines are rewritten to describe whichever mode is active; the per-entry
		// "Status:" line is dropped in this mode (every listed entry is un-built by
		// construction, so the line would be redundant). Data flag
		// interactive_placeholder.manifest_unbuilt_only controls this; env MANIFESTALL_OFF
		// switches back to listing every interactive, built and un-built alike, with the
		// Status line restored.
		const unbuiltOnly = (DataService.Data.EmitTemplates.interactive_placeholder?.manifest_unbuilt_only?.enabled !== false)
			&& !(typeof process !== "undefined" && process.env && process.env.MANIFESTALL_OFF);
		const shown = unbuiltOnly ? list.filter((b) => !b.built) : list;

		// RAW-VERBATIM mode (round 205, Chris). When on, an un-built entry keeps
		// only its minimal header (File / Placeholder marker / Activity / Type,
		// plus the extract reference code when in extract mode) and then a single
		// "Content:" block that reproduces the writer's source blocks EXACTLY —
		// sentinels, [tags], ** and all — with any captured table rendered inline
		// as its raw ASCII box. It DROPS the Modifier / Tier / Data Pattern /
		// Position / Activity Heading / Writer Instructions / Associated Media /
		// Red Flags sections for the un-built entry (Chris: type + anchor + raw
		// content only). Data flag interactive_placeholder.manifest_raw_verbatim
		// controls it; env MANIFESTRAW_OFF reverts to the round-176 processed form.
		// Only affects the un-built worklist (built entries are already omitted).
		const rawVerbatim = (DataService.Data.EmitTemplates.interactive_placeholder?.manifest_raw_verbatim?.enabled !== false)
			&& !(typeof process !== "undefined" && process.env && process.env.MANIFESTRAW_OFF);

		const out = [];
		out.push("=====================================");
		out.push(`INTERACTIVE REFERENCE — ${code}`);
		out.push("Generated by HTML Generator V2 (Phase 1)");
		out.push("=====================================");
		out.push("");
		// how many the converter BUILT automatically this run vs left as a
		// placeholder for manual development (b.built is set by ContentConverter
		// when InteractiveBuilder produced the real widget).
		const builtCount = list.filter((b) => b.built).length;
		const unbuiltCount = list.length - builtCount;
		out.push(`TOTAL INTERACTIVES: ${list.length}`);
		out.push(`  Tier 1 (simple static structures): ${tier1.length} — ${patterns.tiers.tier_1_types.join(", ")}`);
		out.push(`  Tier 2 (requires full build): ${list.length - tier1.length}`);
		out.push(`  BUILT AUTOMATICALLY this run: ${builtCount}  (no work needed — shipped live)`);
		out.push(`  STILL UN-BUILT (placeholders to develop): ${unbuiltCount}`);
		if (unbuiltOnly) {
			out.push(`  NOTE: this file is the hand-off WORKLIST — it lists ONLY the ${unbuiltCount} un-built`);
			out.push(`  placeholder(s); the ${builtCount} BUILT interactive(s) are already live in the HTML and are omitted.`);
		} else {
			out.push(`  NOTE: entries marked "Status: BUILT" are already live on the page;`);
			out.push(`  entries marked "Status: un-built placeholder" await manual development.`);
		}
		out.push(`FILES: ${files.join(", ")}`);
		// EXTRACT mode (the Phase-1 hand-off workflow) is a special conversion mode in which
		// the generated HTML page OMITS the un-built interactives entirely and marks each spot
		// with a short reference code instead of a placeholder box. When that mode is active,
		// announce it here so the reader knows the reference codes appearing in the blocks
		// below are the SAME codes actually live in the HTML — a real cross-reference, not
		// decoration. Gated on run.interactiveMode so the default "inline" manifest (the
		// normal placeholder-in-page workflow) is unaffected.
		const ex = DataService.Data.EmitTemplates.interactive_placeholder?.extract;
		const extractMode = run.interactiveMode === "extract" && !!ex;
		if (extractMode) {
			out.push("");
			out.push(ex.manifest_banner);
		}
		out.push("");
		out.push("=====================================");

		shown.forEach((b, idx) => {
			// RAW mode applies to an UN-BUILT entry only: it keeps the minimal
			// header + a single raw Content block. A BUILT entry (only present
			// when MANIFESTALL_OFF lists everything) keeps the full processed form.
			const raw = rawVerbatim && !b.built;

			out.push("");
			out.push(`INTERACTIVE ${idx + 1} of ${shown.length}`);
			out.push("-------------------------------------");
			// In EXTRACT mode, an un-built box carries a unique reference code (b.extractRef,
			// assigned by ContentConverter when it decides the widget can't be built). Head
			// this block with that SAME code so the .txt file and the HTML page cross-reference
			// 1:1 — the developer can search the page for the code and land on the exact spot.
			if (extractMode && b.extractRef) {
				out.push(Utils.FillTemplate(ex.manifest_heading, { label: b.extractLabel }));
				out.push(Utils.FillTemplate(ex.manifest_heading_hint, { file: b.targetFile }));
				out.push("");
			}
			out.push(`File: ${b.targetFile}`);
			out.push(`Placeholder marker: data-cv2-index="${b.index}" (the placeholder div to replace)`);
			out.push(`Activity: ${b.activityId ?? "(none — inline component)"}`);
			out.push(`Type: ${[b.type, ...(b.extraTypes ?? [])].join(" + ")}`);

			// RAW-VERBATIM un-built entry: minimal header above + the raw Content
			// stream below, nothing else. See #rawContent for the renderer.
			if (raw) {
				const rawLines = this.#rawContent(b);
				out.push("");
				out.push("Content:");
				if (rawLines.length) for (const l of rawLines) out.push(l);
				else out.push("  (no captured content)");
				out.push("");
				out.push("-------------------------------------");
				return;
			}

			const pattern = this.#identifyPattern(b, patterns);
			const tier = patterns.tiers.tier_1_types.includes(b.type) ? 1 : patterns.tiers.tier_default;

			out.push(`Modifier: ${b.modifier || "none"}`);
			// BUILT = the converter produced the real widget (no manual work).
			// un-built = an honest placeholder still awaiting development.
			// (unbuilt-only mode drops the line — every listed entry is un-built by construction.)
			if (!unbuiltOnly) out.push(`Status: ${b.built ? "BUILT — live on the page (no manual work needed)" : "un-built placeholder — awaiting development"}`);
			out.push(`Tier: ${tier} — ${tier === 1 ? "simple static structure" : "requires implementation"}`);
			out.push(`Data Pattern: ${pattern.id} — ${pattern.name}`);
			out.push(`Position: ${b.positionContext}`);
			out.push("");
			out.push(`Activity Heading: ${b.headingText || "(none)"}`);

			// ---- captured data ------------------------------------------
			if (b.tables.length) {
				b.tables.forEach((t, ti) => {
					const rows = t.rows ?? [];
					const cols = rows[0]?.length ?? 0;
					out.push("");
					out.push(`Data (Table ${ti + 1} — ${rows.length} rows × ${cols} columns):`);
					rows.forEach((cells, r) => {
						const label = r === 0 ? "Headers" : `Row ${r}`;
						out.push(`  ${label}: ${cells.map((c) => this.#clean(c)).join(" | ")}`);
					});
				});
			}
			// FAITHFUL CONTENT mode. A naive capture that renders each member's blackAfter text
			// (the plain body text that follows a tag, with all markup already stripped) has
			// two problems for a developer reading this hand-off file. (a) It DROPS the
			// writer's red-highlighted words — often the very adjectives an activity is built
			// around ("big, blue" / "stripey" / "cold" / "curious") — because red text is a
			// separate channel from the black body text that blackAfter captures. (b) It STRIPS
			// the bracketed tags themselves (e.g. "[Speech bubble]"), leaving gap-riddled
			// fragments ("There are two" / "fish and lots of" / "fish.") that don't read as
			// real sentences. Instead, render Content from the members' UNIQUE SOURCE BLOCKS —
			// the original WT paragraphs — cleaning ONLY the internal red-text sentinel markers
			// and the "**" bold markers, so the developer sees each line EXACTLY as the writer
			// authored it (brackets, red words, and all), one line per source block, in reading
			// order. This is the maximum-fidelity hand-off: the developer building the widget
			// by hand needs to see everything the writer wrote, not a stripped-down summary.
			// Data flag interactive_placeholder.manifest_faithful_content controls this; env
			// MANIFESTFAITHFUL_OFF reverts to the older blackAfter-only capture described above.
			const faithful = (DataService.Data.EmitTemplates.interactive_placeholder?.manifest_faithful_content?.enabled !== false)
				&& !(typeof process !== "undefined" && process.env && process.env.MANIFESTFAITHFUL_OFF);
			let freeText;
			if (faithful) {
				const seenBlk = new Set();
				freeText = [];
				for (const m of b.memberItems) {
					if (m.type === "table") continue;         // tables render in the Data section above
					const blk = m.block;
					if (blk) {
						if (seenBlk.has(blk)) continue;       // one line per source block, deduped
						seenBlk.add(blk);
						const t = this.#clean(blk.text ?? "");
						if (t) freeText.push(t);
					} else {                                  // synthetic item (no source block) — fall back
						const t = this.#clean(m.type === "black" ? (m.text ?? "") : (m.blackAfter ?? ""));
						if (t) freeText.push(t);
					}
				}
			} else {
				freeText = b.memberItems
					.filter((m) => m.type === "black" || (m.type === "tag" && (m.blackAfter ?? "").trim()))
					.map((m) => this.#clean(m.type === "black" ? m.text : m.blackAfter))
					.filter(Boolean);
			}
			if (freeText.length) {
				out.push("");
				out.push("Content:");
				for (const t of freeText) out.push(`  ${t}`);
			}

			out.push("");
			out.push("Writer Instructions:");
			if (b.instructions.length) for (const i of b.instructions) out.push(`  - ${this.#clean(i)}`);
			else out.push("  (none)");

			out.push("");
			out.push("Associated Media:");
			if (b.media.length) for (const m of b.media) out.push(`  - ${m.target}`);
			else out.push("  (none)");

			out.push("");
			out.push("Red Flags:");
			if (b.redFlags.length) for (const f of b.redFlags) out.push(`  - ${f}`);
			else out.push("  None");

			out.push("");
			out.push("-------------------------------------");
		});

		return out.join("\n");
	};

	/**
	 * Scores the bundle against the data-pattern signatures (data-driven;
	 * Manifest_Patterns.json). Zero confidence → pattern 0 + a red flag on
	 * the entry — surfaced, never guessed.
	 */
	static #identifyPattern(bundle, patterns) {
		const subtags = new Set();
		for (const m of bundle.memberItems) {
			if (m.type !== "tag") continue;
			for (const t of m.parse.tags) {
				if (t.directive === "SUBTAG") subtags.add(t.tag);
			}
		}
		const hasTable = bundle.tables.length > 0;

		let best = null;
		for (const p of patterns.patterns) {
			let score = 0;
			const sig = p.signals ?? {};
			const typeListed = (p.used_by ?? []).includes(bundle.type);
			if (sig.type_required && !typeListed) continue;     // hard gate
			if (typeListed) score += 2;
			if (sig.table === true && hasTable) score += 1;
			if (sig.table === false && !hasTable) score += 1;
			if (sig.table === true && !hasTable) score -= 2;    // wrong shape
			if ((sig.subtags_any ?? []).some((s) => subtags.has(s))) score += 2;
			if (best === null || score > best.score) best = { score, p };
		}

		if (!best || best.score <= 0) {
			bundle.redFlags.push("No data pattern matched confidently — read the captured data manually.");
			return patterns.unclassified;
		}
		return best.p;
	};

	/** Strips markers/markdown for clean manifest text. */
	static #clean(s) {
		return String(s)
			.replace(/\u{1f534}/gu, "").replace(/\[\/?RED TEXT\]/g, "")
			.replace(/\*\*/g, "").replace(/\s+/g, " ").trim();
	};

	/**
	 * RAW-VERBATIM Content renderer (round 205). Walks the bundle's member
	 * items in reading order and returns each member's ORIGINAL source text,
	 * UNPROCESSED — the 🔴[RED TEXT] sentinels, the [tags] and the ** bold
	 * markers are ALL preserved, so the developer sees exactly what the writer
	 * authored. A captured table comes through as its own raw block text, which
	 * is already the ┌─── TABLE ───/│ cell ║ cell/└─── END TABLE ─── ASCII box
	 * (DocxExtractor serialises every table into that form — see
	 * Input_Doc_Rules.table_markers), so it renders INLINE at its position with
	 * no extra work. Multiple red spans authored in ONE paragraph become several
	 * member items that all point at the SAME source block, so blocks are
	 * DEDUPED by identity (one line per source block) exactly like the round-176
	 * faithful path. A synthetic member with no source block (rare) falls back to
	 * its own raw text. Only the trailing whitespace of each line is trimmed —
	 * the content itself is never collapsed or stripped.
	 *
	 * @param {Object} b - the interactive bundle
	 * @returns {string[]} the raw Content lines (each already split on newlines)
	 */
	static #rawContent(b) {
		const lines = [];
		const seen = new Set();
		const push = (text) => {
			const s = String(text ?? "");
			if (!s.trim()) return;
			// a table (or any multi-line block) keeps its own line breaks
			for (const ln of s.split("\n")) lines.push(ln.replace(/\s+$/, ""));
		};
		for (const m of b.memberItems ?? []) {
			const blk = m.block;
			if (blk) {
				if (seen.has(blk)) continue;   // one line per source block, deduped
				seen.add(blk);
				push(blk.text ?? "");
			} else {                            // synthetic member — no source block
				push(m.type === "black" ? (m.text ?? "") : (m.blackAfter ?? ""));
			}
		}
		return lines;
	};
}

// Node test-harness hook; browsers ignore it.
if (typeof module !== "undefined") module.exports = { ManifestBuilder };
