"""ROUND 314 splice — APPLIED 2026-09-14 (session 2). Identical to _r314_splice_UNAPPLIED.py except:
(1) CC_A_OLD/CC_A_NEW dedented ONE tab per line — the owner close site sits at 6 tabs, the draft wrote 7;
(2) the Emit_Templates edit is idempotent (skipped when the block is already present)."""
import sys
ROOT = r"C:/Users/Gavin/TeKura/FINAL_MODULE_DATA/pageforge-site/converter-v2/"
CC = ROOT + "app/js/ContentConverter.js"
IB = ROOT + "app/js/InteractiveBuilder.js"
ET = ROOT + "data/Emit_Templates.json"

def edit(path, pairs):
    b = open(path, "rb").read()
    for old, new in pairs:
        o = old.encode("utf-8"); n = new.encode("utf-8")
        cnt = b.count(o)
        assert cnt == 1, f"{path}: anchor count {cnt} != 1 for anchor starting {old[:60]!r}"
        b = b.replace(o, n)
    open(path, "wb").write(b)
    print("edited", path, len(pairs), "edit(s)")

# ---------------------------------------------------------------- data block
DATA_OLD = 'single-col flow."\n\t\t},\n\t\t"modifier_classes": {'
DATA_NEW = ('single-col flow."\n\t\t},\n'
 '\t\t"owned_activity_keeps_trailing_dropbox": {\n'
 '\t\t\t"enabled": true,\n'
 '\t\t\t"env": "ACTDBXINSIDE_OFF",\n'
 '\t\t\t"max_lookahead": 120,\n'
 '\t\t\t"_round314_note": "ROUND 314 (the autonomous loop\'s Round 1, 2026-09-14 \\u2014 KB constraint 43, the dropbox modifier/placement class; the loop file\'s REGENERATE CORPUS mandate, scoped by the \\u00a70a/\\u00a70b family rules). A bundle-OWNED activity box closes at its widget\'s end (the r232/r239 close site), so a writer\'s dropbox marker placed AFTER the widget but still INSIDE the activity ([Activity 2D] \\u2026 [clickdrop button] \\u2026 [microphone, camera and video dropbox buttons] [End page] \\u2014 XMES101) escaped into its own row UNDER the closed box: round 310 frees the marker into its own dropDown bundle, round 308 builds the Upload-to-dropbox button, and round 305\'s postpass (which marks `dropbox` only when the button sits INSIDE the box\'s own span) never fired \\u2014 its documented 17% recall. MEASURED (outputs/_measure_r314_dbxplace.py, every gold + Claude page, buttons classified inside/trailing/free against the depth-balanced activity span): GOLD keeps the button INSIDE the activity 702/733 non-BLL (96%) and 1024/1024 BLL (100%); CLAUDE shipped 166 non-BLL trailing buttons across 22 modules where the Writers Template places the marker inside the activity span (75 WT-verified true) + 196 BLL trailing. THE RULE: at the owner close site, walk forward from the bundle\'s opening item with the auto-close boundary semantics (scanSupNote\'s walk \\u2014 skip the owner\'s own members, consumed items, blank lines; black text, tables and non-boundary tags are content; a stray non-activity CONTAINER_CLOSE is the widget\'s own end tag and is flagged so it cannot pop the held frame; a heading <= rendered_heading_max, an activity_close_before directive/tag, an activity closer, a page boundary, a section marker, or an item consumed by a DIFFERENT non-dropbox bundle ends the walk with NO hold); when the first foreign bundle reached is a freed upload-box bundle (InteractiveBuilder.UploadBoxCandidate \\u2014 round 308\'s own scan, promoted public so scanner/builder/holder can never drift) with no activity of its own (canonTag/activityOwner/activityId all unset \\u2014 the loop\'s own isNewActivity test), the activity frame is LEFT OPEN: the dropbox bundle then renders through the ordinary non-owner path inside the still-open box, autoClose (or the page-end drain) closes the box at the next boundary, and the round-305 postpass marks it `dropbox`. FENCES: the ENFUN prose|widget row split (prose_interactive_rows, pirKey) is excluded \\u2014 its widget row is already closed at the site (ENFUN carries 0 of the 121 affected modules); the r308 buttonD/BLL plain-box convention is untouched (the postpass\'s \\\\bbutton\\\\b blindness to buttonD stays, per _r308_widening_declined \\u2014 the BLL button moves inside the box, the box stays plain as the gold\'s own 1024 BLL boxes are). max_lookahead mirrors #goJournalTail\'s 120. Env toggle ACTDBXINSIDE_OFF reverts to closing the box at the widget\'s end (the r310 corpus form)."\n'
 '\t\t},\n'
 '\t\t"modifier_classes": {')
if open(ET,"rb").read().count(DATA_NEW.encode("utf-8")) == 1:
    print("data block already present — skipped")
else:
    edit(ET, [(DATA_OLD, DATA_NEW)])

# ------------------------------------------------------- ContentConverter (a) owner close site
CC_A_OLD = ('\t\t\t\t\t\t\temit(...this.#goJournalTail(bodyItems, i, run, bundle));\n'
 '\t\t\t\t\t\t\t// close the activity at the bundle\'s end (the\n'
 '\t\t\t\t\t\t\t// terminator that ended the widget \u2014 e.g. the [H3])\n'
 '\t\t\t\t\t\t\temit(stack.pop().close);\n'
 '\t\t\t\t\t\t\tbreakRow();\n'
 '\t\t\t\t\t\t} else {\n')
CC_A_NEW = ('\t\t\t\t\t\t\temit(...this.#goJournalTail(bodyItems, i, run, bundle));\n'
 '\t\t\t\t\t\t\t// ROUND 314 (loop Round 1 \u2014 KB constraint 43). A writer\'s dropbox marker\n'
 '\t\t\t\t\t\t\t// that sits INSIDE this activity\'s span but AFTER the widget that owns\n'
 '\t\t\t\t\t\t\t// the box (the round-310 freed upload-box bundle) used to land in its\n'
 '\t\t\t\t\t\t\t// own row UNDER the closed box; the human keeps the "Upload to dropbox"\n'
 '\t\t\t\t\t\t\t// button inside the box (gold non-BLL 702/733, BLL 1024/1024) and marks\n'
 '\t\t\t\t\t\t\t// it `activity dropbox`. When the lookahead finds such a bundle before\n'
 '\t\t\t\t\t\t\t// any activity boundary, the frame is LEFT OPEN: the dropbox bundle then\n'
 '\t\t\t\t\t\t\t// renders through the ordinary non-owner path inside the still-open box,\n'
 '\t\t\t\t\t\t\t// autoClose (or the page-end drain) closes it at the next boundary, and\n'
 '\t\t\t\t\t\t\t// the round-305 postpass adds the `dropbox` class. The ENFUN prose|widget\n'
 '\t\t\t\t\t\t\t// row split (pirKey) is excluded \u2014 its widget row is already closed here.\n'
 '\t\t\t\t\t\t\t// Data activity_wrapper.owned_activity_keeps_trailing_dropbox; env ACTDBXINSIDE_OFF.\n'
 '\t\t\t\t\t\t\tif (!pirKey && this.#dropboxTailHold(bodyItems, i, bundles, it.consumedBy, tpl, renderedHeading)) {\n'
 '\t\t\t\t\t\t\t\tmarkContent();\n'
 '\t\t\t\t\t\t\t\trun.AddNote("info", "ContentConverter",\n'
 '\t\t\t\t\t\t\t\t\t`Page ${page.lessonLabel}: activity box kept open for its trailing upload box (round 314).`);\n'
 '\t\t\t\t\t\t\t} else {\n'
 '\t\t\t\t\t\t\t\t// close the activity at the bundle\'s end (the\n'
 '\t\t\t\t\t\t\t\t// terminator that ended the widget \u2014 e.g. the [H3])\n'
 '\t\t\t\t\t\t\t\temit(stack.pop().close);\n'
 '\t\t\t\t\t\t\t\tbreakRow();\n'
 '\t\t\t\t\t\t\t}\n'
 '\t\t\t\t\t\t} else {\n')

# ------------------------------------------------------- ContentConverter (b) the static method
CC_B_OLD = ('\t\t\tbreak;   // the first real item was not a go-to-journal button \u2014 stop\n'
 '\t\t}\n'
 '\t\treturn [];\n'
 '\t}\n'
 '\n'
 '\t/** A pre-pass-claimed BUTTON bundle with no real content members \u2014 its\n')
CC_B_NEW = ('\t\t\tbreak;   // the first real item was not a go-to-journal button \u2014 stop\n'
 '\t\t}\n'
 '\t\treturn [];\n'
 '\t}\n'
 '\n'
 '\t/**\n'
 '\t * ROUND 314 (loop Round 1 \u2014 KB constraint 43, the dropbox placement class;\n'
 '\t * XMES101 2D / XTAS101 1C). A bundle-OWNED activity box closes at its widget\'s\n'
 '\t * end, so a writer\'s dropbox marker placed after the widget but still inside the\n'
 '\t * activity ([Activity 2D] \u2026 [clickdrop button] \u2026 [microphone, camera and video\n'
 '\t * dropbox buttons] [End page]) escaped into its own row under the closed box \u2014\n'
 '\t * round 310 frees the marker into its own bundle, round 308 builds the button,\n'
 '\t * and round 305\'s postpass (which marks `dropbox` only when the button is INSIDE\n'
 '\t * the box) never fired. The gold keeps the button inside 96% (non-BLL) / 100%\n'
 '\t * (BLL) of the time (outputs/_measure_r314_dbxplace.py: 166 non-BLL trailing\n'
 '\t * buttons, 22 modules with the writer\'s marker inside the activity span).\n'
 '\t *\n'
 '\t * Called at the owner close site: walks forward from the bundle\'s opening item\n'
 '\t * with the auto-close boundary semantics (scanSupNote\'s walk), skipping the\n'
 '\t * owner\'s own members, consumed items and blank lines; black text, tables and\n'
 '\t * non-boundary tags are content and continue; a stray non-activity\n'
 '\t * CONTAINER_CLOSE (the widget\'s own unconsumed end tag \u2014 the same item\n'
 '\t * #goJournalTail steps over) is FLAGGED `_dbxStrayCloser` so the main loop\'s\n'
 '\t * CONTAINER_CLOSE case cannot pop the held frame; a heading <= rendered_heading_max,\n'
 '\t * an activity_close_before directive/tag, an activity closer, a page boundary, a\n'
 '\t * section marker, or an item consumed by a DIFFERENT non-dropbox bundle ends the\n'
 '\t * walk with NO hold. Returns true \u2014 hold the frame \u2014 only when the first foreign\n'
 '\t * bundle reached is a freed upload-box bundle (InteractiveBuilder.UploadBoxCandidate,\n'
 '\t * round 308\'s own scan promoted public so scanner/builder/holder cannot drift)\n'
 '\t * with no activity of its own (the loop\'s own isNewActivity test, inverted).\n'
 '\t * Data activity_wrapper.owned_activity_keeps_trailing_dropbox; env ACTDBXINSIDE_OFF.\n'
 '\t */\n'
 '\tstatic #dropboxTailHold(bodyItems, i, bundles, ownerIdx, tpl, renderedHeading) {\n'
 '\t\tconst cfg = tpl.activity_wrapper?.owned_activity_keeps_trailing_dropbox;\n'
 '\t\tif (!cfg || cfg.enabled === false) return false;\n'
 '\t\tif (typeof process !== "undefined" && process.env && process.env[cfg.env ?? "ACTDBXINSIDE_OFF"]) return false;\n'
 '\t\tconst ddTpl = tpl.interactive_builders?.dropDown;\n'
 '\t\tif (!ddTpl) return false;\n'
 '\t\tconst ownerBundle = bundles[ownerIdx];\n'
 '\t\tif (!ownerBundle) return false;\n'
 '\t\tconst ccfg = tpl.container_auto_close?.activity_close_before ?? {};\n'
 '\t\tconst hMax = (typeof process !== "undefined" && process.env && process.env.ACTHEAD_OFF)\n'
 '\t\t\t? (ccfg.rendered_heading_max_legacy ?? 3) : (ccfg.rendered_heading_max ?? 4);\n'
 '\t\tconst max = cfg.max_lookahead ?? 120;\n'
 '\t\tconst strays = [];\n'
 '\t\tfor (let j = i + 1; j < bodyItems.length && j <= i + max; j++) {\n'
 '\t\t\tconst c = bodyItems[j];\n'
 '\t\t\tif (!c || c._consumed) continue;\n'
 '\t\t\tif (c.consumedBy !== undefined && c.consumedBy !== null) {\n'
 '\t\t\t\tif (c.consumedBy === ownerIdx) continue;                 // the owner\'s own members\n'
 '\t\t\t\tif (c.consumedBy === "activity-super-content") continue;  // hoisted into THIS box\'s panel\n'
 '\t\t\t\tconst b = bundles[c.consumedBy];\n'
 '\t\t\t\tif (!b) return false;                                     // a merge sentinel = a new activity\n'
 '\t\t\t\tif (b === ownerBundle) continue;\n'
 '\t\t\t\tif (b.type === "dropDown" && b.canonTag !== "activity"\n'
 '\t\t\t\t\t&& b.activityOwner === undefined && b.activityId === null\n'
 '\t\t\t\t\t&& InteractiveBuilder.UploadBoxCandidate(b, ddTpl)) {\n'
 '\t\t\t\t\tfor (const s of strays) s._dbxStrayCloser = true;\n'
 '\t\t\t\t\treturn true;\n'
 '\t\t\t\t}\n'
 '\t\t\t\treturn false;                                             // a different widget = a boundary\n'
 '\t\t\t}\n'
 '\t\t\tif (c.type !== "tag") continue;                               // prose, a blank line, a table = content\n'
 '\t\t\tconst p = c.parse?.primary;\n'
 '\t\t\tif (!p) continue;                                             // an instruction / noise span\n'
 '\t\t\tif (p.directive === "CONTAINER_CLOSE") {\n'
 '\t\t\t\tif (p.tag === "end activity" || /\\bactivity\\b/i.test(p.tag ?? "")) return false;\n'
 '\t\t\t\tstrays.push(c); continue;                                 // the widget\'s own end tag\n'
 '\t\t\t}\n'
 '\t\t\tif (p.directive === "PAGE_BOUNDARY" || p.directive === "SECTION_MARKER") return false;\n'
 '\t\t\tif ((ccfg.directives ?? []).includes(p.directive) || (ccfg.tags ?? []).includes(p.tag)) return false;\n'
 '\t\t\tconst isTitle = (ccfg.title_heading_tags ?? []).includes(p.tag);\n'
 '\t\t\tconst hh = isTitle ? null : renderedHeading(p);\n'
 '\t\t\tif (hh !== null && hh <= hMax) return false;                  // a section heading closes the box\n'
 '\t\t}\n'
 '\t\treturn false;\n'
 '\t}\n'
 '\n'
 '\t/** A pre-pass-claimed BUTTON bundle with no real content members \u2014 its\n')

# ------------------------------------------------------- ContentConverter (c) the stray closer guard
CC_C_OLD = ('\t\t\t\tcase "CONTAINER_CLOSE": {\n'
 '\t\t\t\t\tif (stack.length) {\n'
 '\t\t\t\t\t\tconst top = stack.pop();\n')
CC_C_NEW = ('\t\t\t\tcase "CONTAINER_CLOSE": {\n'
 '\t\t\t\t\t// ROUND 314 \u2014 a widget\'s own unconsumed end tag that the dropbox-tail\n'
 '\t\t\t\t\t// hold walked over must not pop the activity frame it deliberately left\n'
 '\t\t\t\t\t// open (before the hold this closer met an EMPTY stack and was ignored \u2014\n'
 '\t\t\t\t\t// the same outcome, the same info note). See #dropboxTailHold.\n'
 '\t\t\t\t\tif (stack.length && !it._dbxStrayCloser) {\n'
 '\t\t\t\t\t\tconst top = stack.pop();\n')
def _dedent1(s):
    return "\n".join(l[1:] if l.startswith("\t") else l for l in s.split("\n"))
CC_A_OLD = _dedent1(CC_A_OLD); CC_A_NEW = _dedent1(CC_A_NEW)
edit(CC, [(CC_A_OLD, CC_A_NEW), (CC_B_OLD, CC_B_NEW), (CC_C_OLD, CC_C_NEW)])

# ------------------------------------------------------- InteractiveBuilder: the shared scan
IB_OLD = ('\tstatic #ddUploadBox({ bundle, tpl, run, renderBlock }) {\n'
 '\t\tconst cfg = tpl.upload_box;\n'
 '\t\tif (!cfg || cfg.enabled === false) return null;\n'
 '\t\tif (typeof process !== "undefined" && process.env && process.env.DBXBUTTON_OFF) return null;\n'
 '\t\t// the OPENER \u2014 the same member scan as the family fence, so the two cannot drift\n'
 '\t\tconst delims = tpl.delimiter_tags ?? ["dropdown"];\n'
 '\t\tconst deny = new RegExp(tpl.opener_deny_pattern ?? "drop\\\\s*box", "i");\n'
 '\t\tlet opener = null;\n'
 '\t\tfor (const m of bundle?.memberItems ?? []) {\n'
 '\t\t\tif (m?.type !== "tag") continue;\n'
 '\t\t\tif (!delims.includes(m.parse?.primary?.tag)) continue;\n'
 '\t\t\topener = m; break;\n'
 '\t\t}\n'
 '\t\tif (!opener || !deny.test(String(opener.text ?? ""))) return null;\n'
 '\t\tif (new RegExp(cfg.opener_exclude_pattern ?? "\\\\balert\\\\b", "i").test(String(opener.text ?? ""))) return null;\n'
 '\t\t// a SAME-TYPE merge ("dropDown + dropDown") is only the placeholder LABEL\n'
 '\t\t// (the r242/r279 rule \u2014 two dropbox brackets scanned into one bundle, ONE\n'
 '\t\t// upload area); any MIXED merge is the round-310 gathering class \u2192 decline.\n'
 '\t\tif ((bundle.extraTypes ?? []).some((e) => e !== "dropDown")) return null;\n'
 '\t\tif ((bundle.tables ?? []).length || (bundle.media ?? []).length) return null;\n'
 '\t\tconst allow = new RegExp(tpl.opener_pattern ?? "drop[\\\\s-]*down|dropquiz|drop\\\\s*quiz", "i");\n'
 '\t\tconst textTags = new Set(cfg.text_member_tags ?? ["body"]);\n'
 '\t\tconst spec = [];       // the writer\'s own designer-facing words \u2192 ONE To Do note\n'
 '\t\tconst content = [];    // captured learner text, released in the writer\'s own order\n'
 '\t\tconst rb = renderBlock ?? ((t) => [`<p>${t}</p>`]);\n'
 '\t\tconst push = (t) => { const s = String(t ?? "").trim(); if (s) content.push(rb(s).join("")); };\n'
 '\t\tfor (const m of bundle.memberItems ?? []) {\n'
 '\t\t\tif (!m) continue;\n'
 '\t\t\tif (m.type === "black") { push(m.text); continue; }\n'
 '\t\t\tif (m.type !== "tag") return null;                    // a table or anything else \u2192 decline\n'
 '\t\t\tconst prim = m.parse?.primary?.tag ?? null;\n'
 '\t\t\tif (prim && !delims.includes(prim) && !textTags.has(prim)) return null;   // a foreign widget\'s piece\n'
 '\t\t\tif (prim && delims.includes(prim)) {\n'
 '\t\t\t\tconst own = String(m.text ?? "");\n'
 '\t\t\t\t// a GENUINE dropdown bracket merged in means a QUIZ rode along \u2014 never\n'
 '\t\t\t\t// release quiz material as plain prose; the hand-off box stays honest.\n'
 '\t\t\t\tif (allow.test(own) && !deny.test(own)) return null;\n'
 '\t\t\t\tconst raw = own.replace(/\\s+/g, " ").trim();\n'
 '\t\t\t\tif (raw) spec.push(raw);                          // every bracket\'s words reach the note\n'
 '\t\t\t} else if (!prim) {\n'
 '\t\t\t\tconst raw = String(m.text ?? "").replace(/\\s+/g, " ").trim();\n'
 '\t\t\t\tif (raw) spec.push(raw);\n'
 '\t\t\t}\n'
 '\t\t\tpush(m.blackAfter);\n'
 '\t\t}\n')
IB_NEW = ('\tstatic #ddUploadBox({ bundle, tpl, run, renderBlock }) {\n'
 '\t\t// ROUND 314 \u2014 the whole decline scan lives in #ddUploadBoxScan so the\n'
 '\t\t// public UploadBoxCandidate predicate and this builder can never drift.\n'
 '\t\tconst scan = this.#ddUploadBoxScan(bundle, tpl);\n'
 '\t\tif (!scan) return null;\n'
 '\t\tconst cfg = tpl.upload_box;\n'
 '\t\tconst spec = scan.spec;          // the writer\'s own designer-facing words \u2192 ONE To Do note\n'
 '\t\tconst rb = renderBlock ?? ((t) => [`<p>${t}</p>`]);\n'
 '\t\t// captured learner text, released in the writer\'s own order\n'
 '\t\tconst content = scan.raw.map((s) => rb(s).join(""));\n')
IB_SCAN = ('\t/**\n'
 '\t * ROUND 314 \u2014 the round-308 upload-box decline scan, factored out of #ddUploadBox\n'
 '\t * VERBATIM (every guard in its original order) and PROMOTED PUBLIC through\n'
 '\t * UploadBoxCandidate (the r246 NoTableBubbleParagraphs / r306 SbTableForeign\n'
 '\t * shared-predicate discipline): ContentConverter\'s dropbox-tail hold asks "would\n'
 '\t * this freed bundle build the button?" with the builder\'s OWN answer, so the\n'
 '\t * scanner (r310), the builder (r308) and the holder (r314) cannot drift. Pure \u2014\n'
 '\t * reads only, never mutates the bundle. Returns { opener, spec, raw } (raw = the\n'
 '\t * trimmed learner-text pieces in the writer\'s own order, still unrendered) or\n'
 '\t * null on any decline; the leak guard stays in the builder because it needs the\n'
 '\t * rendered content.\n'
 '\t */\n'
 '\tstatic #ddUploadBoxScan(bundle, tpl) {\n'
 '\t\tconst cfg = tpl?.upload_box;\n'
 '\t\tif (!cfg || cfg.enabled === false) return null;\n'
 '\t\tif (typeof process !== "undefined" && process.env && process.env.DBXBUTTON_OFF) return null;\n'
 '\t\t// the OPENER \u2014 the same member scan as the family fence, so the two cannot drift\n'
 '\t\tconst delims = tpl.delimiter_tags ?? ["dropdown"];\n'
 '\t\tconst deny = new RegExp(tpl.opener_deny_pattern ?? "drop\\\\s*box", "i");\n'
 '\t\tlet opener = null;\n'
 '\t\tfor (const m of bundle?.memberItems ?? []) {\n'
 '\t\t\tif (m?.type !== "tag") continue;\n'
 '\t\t\tif (!delims.includes(m.parse?.primary?.tag)) continue;\n'
 '\t\t\topener = m; break;\n'
 '\t\t}\n'
 '\t\tif (!opener || !deny.test(String(opener.text ?? ""))) return null;\n'
 '\t\tif (new RegExp(cfg.opener_exclude_pattern ?? "\\\\balert\\\\b", "i").test(String(opener.text ?? ""))) return null;\n'
 '\t\t// a SAME-TYPE merge ("dropDown + dropDown") is only the placeholder LABEL\n'
 '\t\t// (the r242/r279 rule \u2014 two dropbox brackets scanned into one bundle, ONE\n'
 '\t\t// upload area); any MIXED merge is the round-310 gathering class \u2192 decline.\n'
 '\t\tif ((bundle.extraTypes ?? []).some((e) => e !== "dropDown")) return null;\n'
 '\t\tif ((bundle.tables ?? []).length || (bundle.media ?? []).length) return null;\n'
 '\t\tconst allow = new RegExp(tpl.opener_pattern ?? "drop[\\\\s-]*down|dropquiz|drop\\\\s*quiz", "i");\n'
 '\t\tconst textTags = new Set(cfg.text_member_tags ?? ["body"]);\n'
 '\t\tconst spec = [];       // the writer\'s own designer-facing words \u2192 ONE To Do note\n'
 '\t\tconst raw = [];        // captured learner text, in the writer\'s own order (unrendered)\n'
 '\t\tconst push = (t) => { const s = String(t ?? "").trim(); if (s) raw.push(s); };\n'
 '\t\tfor (const m of bundle.memberItems ?? []) {\n'
 '\t\t\tif (!m) continue;\n'
 '\t\t\tif (m.type === "black") { push(m.text); continue; }\n'
 '\t\t\tif (m.type !== "tag") return null;                    // a table or anything else \u2192 decline\n'
 '\t\t\tconst prim = m.parse?.primary?.tag ?? null;\n'
 '\t\t\tif (prim && !delims.includes(prim) && !textTags.has(prim)) return null;   // a foreign widget\'s piece\n'
 '\t\t\tif (prim && delims.includes(prim)) {\n'
 '\t\t\t\tconst own = String(m.text ?? "");\n'
 '\t\t\t\t// a GENUINE dropdown bracket merged in means a QUIZ rode along \u2014 never\n'
 '\t\t\t\t// release quiz material as plain prose; the hand-off box stays honest.\n'
 '\t\t\t\tif (allow.test(own) && !deny.test(own)) return null;\n'
 '\t\t\t\tconst w = own.replace(/\\s+/g, " ").trim();\n'
 '\t\t\t\tif (w) spec.push(w);                              // every bracket\'s words reach the note\n'
 '\t\t\t} else if (!prim) {\n'
 '\t\t\t\tconst w = String(m.text ?? "").replace(/\\s+/g, " ").trim();\n'
 '\t\t\t\tif (w) spec.push(w);\n'
 '\t\t\t}\n'
 '\t\t\tpush(m.blackAfter);\n'
 '\t\t}\n'
 '\t\treturn { opener, spec, raw };\n'
 '\t}\n'
 '\n'
 '\t/** ROUND 314 \u2014 would round 308 build this bundle\'s Upload-to-dropbox button?\n'
 '\t *  The builder\'s own scan, promoted public for ContentConverter\'s dropbox-tail\n'
 '\t *  hold (see #ddUploadBoxScan). Pure. */\n'
 '\tstatic UploadBoxCandidate(bundle, ddTpl) {\n'
 '\t\treturn this.#ddUploadBoxScan(bundle, ddTpl) !== null;\n'
 '\t}\n'
 '\n')
IB_ANCHOR_DOC = ('\t/**\n'
 '\t * ROUND 308 \u2014 THE UPLOAD BOX (Chris, 2026-08-11: "Build it"). The student\n')
b = open(IB, "rb").read()
assert b.count(IB_ANCHOR_DOC.encode()) == 1, "IB doc anchor"
edit(IB, [(IB_OLD, IB_NEW), (IB_ANCHOR_DOC, IB_SCAN + IB_ANCHOR_DOC)])
print("done")
