#!/usr/bin/env python3
"""ROUND 342 (loop session 9 Round 2, finished in session 11) — finalise: changelog, AppVersion (260619.12 → 260619.13),
CLAUDE.md §9/§11/§14, gate_baseline.json, KB status D-row, CONVERTER_V2_GUIDE.md A4, LOOP_STATE.md (what shipped + position + round log).
Idempotent; LF kept (io.open newline="")."""
import io, os, json
HERE = os.path.dirname(os.path.abspath(__file__))
PF = os.path.join(HERE, "..", "..", "pageforge-site", "converter-v2")
def rd(p):
    with io.open(p, encoding="utf-8", newline="") as f: return f.read()
def wr(p, s):
    with io.open(p, "w", encoding="utf-8", newline="") as f: f.write(s)

SK_B, SK_A, RAW_B, RAW_A = "51.133", "51.129", "35.323", "35.309"
SK_B4, SK_A4 = "51.1325", "51.1291"
GE50, GE75_B, GE75_A, GE90, PAIRS = 1073, 200, 198, 15, 1962
CS, EX, MI = 11482, 175, 608
BODY_B, BODY_A = 191, 180
DELTA = "−0.003"; PCT = "55.8"
MOVED = ("41 moved — 16 up / 25 down, every mover in the affected set, pp-sum −6.76 scaffold / −1.65 RAW; every dip ≤ 2.21pp and every one the "
         "SAME class: a hyperlinked `[audio]` now ships the standing audio element (`audio.audioPlayer.icon`, in its own section row when it "
         "stands alone) plus its words as the caption `<p>`, where the gold builds the per-word `wordDrag` / `audioButton` / `word` widget "
         "(the r300 non-derivable `audioName` form — decision D10-3's dragAndDrop kickoff territory) and where the OFF page's literal "
         "`<p>[audio] …</p>` line had matched a gold `<p>` by coincidence — BLL151_2_0 −2.21, BLL217_1_0 −2.04 (75.86 → 73.83, the ≥75 "
         "down-crosser: `<p><b>[audio]</b> crane, above, glove…</p>` → `<p>crane, above…</p>` + a `row > col-md-8 > audio` where the gold's "
         "`row.wordDrag` holds 8 `div.word`s), BLL126_1_0 −1.91 (76.39 → 74.48, the other crosser: `<p>[audio]</p>` + a Writers Note → the "
         "audio element + the script as its caption), BLL252 / BLL253 / BLL166 / BLL131 / BLL222 / BLL241 / BLL114 / BLL157 / BLL176 / BLL172 / "
         "BLL242 −1.33 … −0.53; MXEO201_4_0 −0.32, XWHA02_3_0 −0.31, ENGC101_4_0 −0.22, HIS1001_10_0 −0.11, EXPFUN04_0_0 −0.00 = the "
         "session-9 gap-1 rescues (a hand-off box now stands — one collapsed widget marker — where the notes-only render stood; ENGC101's "
         "RAW 35.4 → 34.1 is the box's five `[Source image: …]` faces now dumped); the gains: BLL160_0_0 +2.61, BLL151_1_0 +2.06, BLL137_1_0 "
         "+2.03, BLL162_1_0 +1.75 (the gold ships `audio.audioPlayer.icon` there — exact), BLL251 +1.02, BLL166_1_0 +0.87, HIS1002_13_0 +0.65 "
         "(the hyperlinked `[Link: youtube]` → the r340 embed, the gold's own), BLL220 +0.57, BLL146 +0.53 …")
VER = ("the literal-tag-leak gate's own predicate over the 147 changed modules (`_r342_s11_quality.py`): **15 → 15**, no module worse; "
       "corpus-wide **26 / 23 → 26 / 23 EXACT**; the word-loss check over the 147 (every word incl. notes / dumps / attribute values): the "
       "losses are the reference URLs that became `<img>` placeholders (the r240 D3 class — istock / shutterstock / drive link text), the "
       "literal tag tokens, Writers-Note chrome, the seven `Go to your journal` labels the audio button no longer invents, and the "
       "`Go to video` externalButton HIS1002_13_0 replaced with the gold's own embed; hand-off boxes: **7 pages gain a box** (BLL150_0_0, "
       "BLL166_1_0, ENGC101_4_0, EXPFUN04_0_0, HIS1001_10_0, MXEO201_4_0, XWHA02_3_0 — the gap-1 rescues) and **1 page 'loses' one because it "
       "BUILT**: BLL253_2_0's five `[image]`-hyperlinked clickDrop panels (5 buttons / 5 panels with the prose inside; the affected-set "
       "clickDrop verifier 47 clickDrops / 116 items defect 0)")

# ---------------------------------------------------------------- 1. BUILD_CHANGELOG.md
CL = os.path.join(PF, "BUILD_CHANGELOG.md"); s = rd(CL)
head = "# BUILD CHANGELOG — Stage 2 (engine + UI)" + chr(10) + chr(10)
ENTRY = f"""## 2026-09-16 (round 342, build 260619.13) — A WRITER'S MEDIA TAG TYPED AS A HYPERLINK IS STILL A TAG (`[audio 1]` linked to its sound file — the r341 seam extended to `w:hyperlink` runs whose bracket head is a data-listed media word; plus the three hand-off-box gaps the ON leg exposed, fixed not reverted; the autonomous loop's session-9 Round 2, finished in session 11 — item 0 of Chris's session-10 queue; **FULL regeneration of all 416 gated dirs — the ledger resets to 0**)

### 1. WHAT CHANGED, IN ONE LINE

**The BLL phonics writers type a media tag AS A HYPERLINK — `[audio 1]` in the hyperlink blue (`1155cc` / `3494ba` / `0563c1`) or black, linked to the sound file on Drive / SharePoint — so it was invisible to the tag detector (only red runs are scanned; r341 added the near-red band) and shipped as the literal `<p>[audio 1] Kim had a roast pork bun.</p>`. A run INSIDE a `w:hyperlink` whose bracket opens with a data-listed media head (`audio`, `audios`, `audio button`, `audiovisual`, `av`, `video`, `image`, `link`) now counts as red — behind THREE data fences measured in the corpus: the head list itself (those writers hyperlink EVERY WORD of a phonics list — `[scissors]`, `[wrist]` … ~230 runs of CONTENT), `exclude_words` (`[Audio Animation N: …]` is a CS-animation brief, r233), and `link_target_match` (the target must be a media-file carrier — the drive / sharepoint / istock / youtube hosts that carry 590 of the 600 hyperlinked bracket runs, or a media file extension; BLL262's `[Audio]` links a tahurangi School-Journal PAGE). Three rules ride with it because the ON leg exposed them (§0b — debug, never revert): a hyperlinked media tag's OWN words (`[audio] snail, paint, trail…`) are its caption, exactly as a black run after a red `[audio 1]` already is (`MEDIALEAD_OFF`); a tag member's bracket-line text — and a hyperlinked media tag's link target — is CONTENT for the un-built hand-off box, so the box and its `.txt` entry no longer vanish (`MEMBERTEXT_OFF`, session 9's gap 1 + session 11's linked-tag arm); and a bare `[audio button]` defaults to an EMPTY label, never `Go to your journal` (`BTNLABELDEF_OFF`).** Data `Input_Doc_Rules.red_runs.hyperlinked_tag_runs` · `Emit_Templates.elements.media_hyperlinked_lead` · `interactive_placeholder.embedded_member_text` · `buttons["audio button"].label_default` · env `HYPERTAG_OFF` / `MEDIALEAD_OFF` / `MEMBERTEXT_OFF` / `BTNLABELDEF_OFF`.

### 2. THE EVIDENCE (docx → human → Claude)

- **BLL146 lesson 1** — WT `[audio 1] ` (run colour `1155cc`, hyperlink → a drive.google.com file) + black `Kim had a roast pork bun.` → gold `<audio preload="none" src="audio/….mp3" class="audioPlayer icon">` ×5 (one per line) → Claude before `<p>[audio 1] Kim had a roast pork bun.</p>` inside the alertActivity box; after the `audioPlayer` element + the caption (+0.53 on the skeleton — the gold's own form).
- **BLL140 overview** — WT `[audio] snail, paint, trail, stain, faint, train` (the WHOLE line hyperlinked to the sound folder) → gold `div.word word="snail" audioName="snail"` ×6 (a per-word widget) → Claude before the literal line; after the audio element + `<p>snail, paint, trail, stain, faint, train</p>` — every word on the page (the widget form is the r300 non-derivable `audioName`, decision D10-3's territory).
- **BLL141 lesson 1 (gap 3)** — WT `[drop and drag] Can we make something like this please…` + `**[audio]**` (hyperlinked, no words) + red `free, boat, seed, goal, week, road` → gold `activity interactive 1C` with a `wordDrag` of 6 `div.word`s → Claude before the hand-off box #3 (dragAndDrop 1C) holding `<p><b>[audio]</b></p>`; with the rule ON but no fence the `[audio]` became a text-less element, the r72 empty-box guard read the bundle as notes-only and the BOX AND ITS `.txt` ENTRY VANISHED with the writer's request; after: the box stands, its dump reads `[audio] https://drive.google.com/…` (the link IS the member's content).
- **XDLS905 overview (fence 2)** — WT `[Audio Animation 1: <sharepoint script> Note this will be repeated across five units XDLS 902-6]` (hyperlinked) → gold a Vimeo `videoSection` (the CS animation, r233 / CL-0037) → with the head rule alone Claude shipped a bare `<audio src="audio/.mp3">` and LOST the link + note; `exclude_words: ["animation"]` keeps the literal link line + Writers Note the page already carried (byte-identical).
- **BLL262 / BLL263 lesson 1 (fence 3 + the `embed` omission)** — WT `[Carousel]` + `✅[Audio] [LINK: tahurangi…/staying-afloat/5637163409.p]` + `[Embed] Staying afloat, Junior Journal 54` / `[Embed audio book] [LINK: sharepoint doc]` → gold a hand-sourced carousel of the story's page images + an audio player (the r279 reading-book family, a recorded correct decline) → with `[Audio]` / `[Embed audio book]` recognised the carousel composer half-built THREE identical placeholder "images" of one web page (and a SharePoint Word doc as an iframe slide); `link_target_match` (a resource page is not a media file) and leaving `embed` off the head list (its only hyperlinked runs ARE this family, 3 corpus-wide) keep both honest hand-off boxes byte-identical.
- **The KB:** 05A lists three audio forms (`audioPlayer`, `audioPlayer icon`, `audioButton`) with no rule for which a free-body line takes — the FORM is the developer's (the BLL gold's `audioButton` 164 vs `audioPlayer` 20 across the 20 free-body modules; `audioName` varies per module — r300's non-derivable finding stands); the RECOGNITION is LOOP §1b level 3 / 4 — the gold builds a sound element at every triangulated site. Class B-i. This round = recognition + the words; the element form stays Claude's standing `[audio]` form.

### 3. THE MEASUREMENT (session 9: `outputs/_measure_r342_hyperlinked_brackets.py` → `_r342_hyperlinked_brackets.log`; `_r342_audio_visible.py`; `_measure_r342_embedded_members.cjs` → `_r342_emb_off_*.json`; `_measure_r342_media_embedded.cjs` → `_r342_medemb_*.json` + `_r342_medemb_summary.log` · session 11: `_r342_medlead_gold.py` → `_r342_medlead_gold.log`)

- **600 hyperlinked bracket runs corpus-wide** — heads `audio` 226 · `insert` 43 (already red) · `audiovisual` 27 · `clickdrop` 26 (red) · `av` 12 · `number` 10 (`[Number and Operations]`, MXDI201 — a curriculum-strand link, NOT a tag) · `image` 5 · `video` 4 · `embed` 3 · **~230 phonics WORD links** (`[scissors]`, `[wrist]`, `[hedgehog]` … BLL240/250/260 — content, the gold's `audioTrigger` click-to-hear words); targets drive.google.com 354 / sharepoint 125 / istock 29 / youtube 17 / docs 10. Free-body visible `[audio…]` brackets in the r341 corpus: 71 on 36 pages / 30 modules (+ 423 inside hand-off boxes). Link-BLUE bracket tags 182 / 52 gated modules — 177 INSIDE a `w:hyperlink`, 175 the `audio` family.
- **Gap 2, the media embedded lead, DECIDED BY MEASUREMENT (session 11):** does the human keep the words a writer typed inside the media tag's own span? Gold KEEPS them as visible text on **10 / 40 of the hyperlinked sites (0.25; audio 2/31, audio button 8/8)** and **87 / 359 of the pre-existing RED-span sites (0.24; video 0.29, embed 0.26, audio 0.16)** — for the phonics lists the gold builds per-word `word` / `audioButton` / `flipCard audioTrigger` widgets (`word="snail" audioName="snail"`), an un-derivable developer form. So the fold is SCOPED to the hyperlinked class (where the alternative is losing words the OFF page carried) and the 359 pre-existing red-span leads stay dropped (the gold agrees at 0.76) — option (a) of the session-9 note, narrowed; option (b)'s `[Audio Animation N:` sites are the `exclude_words` fence.
- **Gap 3 (session 11):** across the 248 changed pages the ON state made 5 pages LOSE a hand-off box (BLL141_1_0, BLL171_1_0, BLL253_2_0, BLL262_1_0, BLL263_1_0 — all the phonics `[audio]`-inside-a-widget shape) and 7 GAIN one (the gap-1 rescues). BLL141 / BLL171 = the text-less linked member (fixed by `linked_tag_counts`); BLL262 / BLL263 = the reading-book half-builds (fenced by the target host + the `embed` omission); BLL253 = a real clickDrop BUILD (5 buttons / 5 panels with the prose inside, verifier defect 0). After the fences: 0 lost / 7 gained / 1 built.
- **The audio button's label (session 11):** the gold's `audioButton` is text-less on **1,014 of 1,014** sites (`<div class="audioButton" audioName=…></div>`); Claude's `button audioButton` form carried the journal default on 7 corpus sites and the hyperlinked rule would have added 8 (`[audio button]` BLL140/150/160/170) — a per-key `label_default` (`""` for `audio button`) with its own toggle.

### 4. THE FIX — one extractor seam, one media seam, one hand-off seam, one button seam, all data-fenced

- **`DocxExtractor.#parseParagraph`:** `hyperRed = !listRed && !nearRed && hyperTagOn && !!currentLink && hyperTarget && (nearOpen > 0 || #hyperlinkedTagHead(text, head_words, exclude_words))` — `hyperTarget` = `link_target_match` tested on the hyperlink's target; the r341 `nearOpen` depth keeps a split bracket whole; every piece records `hyper`, and a paragraph with a fired piece is marked `block.hyperTag` (a side-channel — never in the text, so red-span granularity and every downstream byte are identical by construction; the tags gate 9557/9557 is the canary). `static #hyperlinkedTagHead(text, heads, excludes)`: the bracket's first word(s) ∈ `head_words`, none of its words ∈ `exclude_words`.
- **`MediaBuilder.media(it, bodyItems, i, kind, run, norm)`:** a sixth `norm` argument (the `TablesAndGrids.contentTable` precedent; six call sites pass `this.#norm`); on a `block.hyperTag` item the embedded lead (`norm.RenderText(it.text)`) is folded in FRONT of the own / black-after text and the standing rules apply unchanged — a built video has already dropped its own text as the title (r80), audio / un-built keep the caption. Data `elements.media_hyperlinked_lead` · env `MEDIALEAD_OFF`.
- **`ContentConverter.#interactivePlaceholder`:** `embeddedText(it)` — a TAG member with an empty tail whose primary directive is ELEMENT / INLINE and whose class is `tag` (an instruction-class member already surfaces as the note before the box) returns its raw bracket line when it has words; **session 11:** when it has no words but the block is `hyperTag` with a link target, it returns `[audio] <url>` (`linked_tag_counts`). Both guards (`hasText` / `hasRenderedNonInstr`) and the member dump read it. Data `interactive_placeholder.embedded_member_text` · env `MEMBERTEXT_OFF`.
- **`ContentConverter` button seam:** `label = keyDefaultOn ? btn.label_default : journal_label_default` when the writer gave no label. Data `buttons["audio button"].label_default: ""` · env `BTNLABELDEF_OFF`.

### 5. THE PROOF AND THE GATES

- The in-memory probe over ALL 416 modules (`_r342_probe.cjs` / `_r342_s11_probe_run.sh`, 4 shards): **ALL-OFF (`HYPERTAG_OFF` + `MEMBERTEXT_OFF` + `MEDIALEAD_OFF` + `BTNLABELDEF_OFF`) = disk 2110 / 2110** (`_r342_s11_probe_off_0*.log`); **ON = 248 pages changed / 147 modules, 0 added / 0 removed** (`_r342_s11_probe_on_0*.log`, `_r342_s11_affected.txt`; the 147 = the 52 session-9 hyperlinked modules ∪ the 124-module member-text class ∪ the 7 audio-button-label modules). **FULL regeneration** of all 416 gated dirs (the r335 batch list, 36 batches, 4 workers, `_r342_fullship_par.sh`; seven batches returned rc 1 under the parallel run — `BATCH FATAL: SyntaxError … in JSON` in `batch_progress.log`, the r279 parallel-write race on batch_convert's results cache — re-run one at a time, all rc 0; `_r342_fullship_regen.log`); `_stalecheck.sh` **0 stale**; `_content_manifest.py diff` = **248 pages / 147 modules, 0 added / 0 removed — exactly the probe's prediction; the other 269 modules byte-identical** (the r341 full ship's manifest is the OFF state, so this doubles as the whole-family proof §0b asks for: every audio / video / image / link carrier the rule does not fire on is proven byte-identical).
- **Skeleton (PRIMARY): SCAFFOLD mean {SK_B}% → {SK_A}% ({DELTA}pp; {SK_B4} → {SK_A4}) / ≥50% {GE50} EXACT / ≥75% {GE75_B} → {GE75_A} (−2 NAMED) / ≥90% {GE90} EXACT / skipped 0 @ {PAIRS} pairs; RAW {RAW_B}% → {RAW_A}%** (state `outputs/_r342_sk_final.json`, FRESH). {MOVED} (`_r342_sk_movers.log`). The PICK predicted "≈ neutral on the skeleton (`p` → `audio.audioPlayer.icon`, both unlike the gold's `div.audioButton`; exact where the gold ships the player)" — the −0.003pp is that prediction: the pages whose gold ships the player rise, the pages whose gold ships the per-word widget dip, and the OFF literal lines had been matching gold `<p>`s by coincidence. The fast-loop's `--accept-named` for the ≥75 −2 (the r289 / r326 / r338 named-movement override).
- **compare_structure exact {CS} / EXTRA {EX} / missing {MI} — EXACT. body_compare ANY {BODY_B} → {BODY_A} (IMPROVED — EMPTY 135, over-capture 42, runaway 4). Structurally clean 2087 / 2110 = 98.91%, literal-tag leak 26 / 23 — EXACT.** Every other gate EXACT (full suite `_r342_gates.log`): tags **9557 / 9557 REAL 0** · flipCard TOTAL 61 exact 32 / defect 18 / divergence 0 · speechBubble built 62 defect 4 (the standing pre-existing baseline, identical to r341) · modal 13 groups defect 0 · mtkQuiz 17 shells defect 0 · index-sync 33/28 · entry-parity PASS · 13 selftests GREEN (`_r342_selftests.log`). Over the 147 affected modules: clickDrop 47 / 116 items defect 0 (BLL253's new build included), accordion 276 panels / 44 modules every panel matching the human, dropDown 100 groups defect 0, tabs 105 texts defect 2 = the standing PHE1005 / XLP06 editorial-rewrite pair (r196 / r281), carousel 195 built / 18 mismatched slide ids = the r246 / r295 A1 class (the writer's video absent from the gold) — **proven pre-existing: the embedded video ids on BLL116 / BLL120 / BLL133 / BLL144 / BLL150 / BLL155 are identical between the ALL-OFF pages and the ON disk** (`_r342_s11_off6/`).
- **Verifier:** {VER}.
- Fast-loop baseline re-snapshotted from the fresh corpus (`_r342_fastloop_snapshot.log`, values = the gate suite's), manifest snapshot (2110 pages / 413 modules), `_ship_ledger.py record-full --build 260619.13` (counter 0), feature index rebuilt (8 shards + merge, selftest GREEN — `_r342_feature_index.log`).

### 6. NAMED, NOT CHASED

- The audio element's FORM (`audio.audioPlayer.icon` vs the gold's `audioButton` / `wordDrag` per-word widgets — 1,014 text-less `audioButton`s in the gold; the `audioName` is in no WT): the r300 non-derivable finding, and decision D10-3's dragAndDrop / clickDrop build kickoffs are where the phonics word lists become widgets. The 359 pre-existing red-span media leads the gold drops at 0.76 (recorded, not folded). The hyperlinked `[audiovisual]` / `[av]` heads (39 runs; `[Audiovisual request item 1]` in BLL254 now routes to the r300 orphan note rather than the black link line — 1 site, named). The plain-BLACK tag class (≈ 300 brackets, the 26 residual leaks). The `] Read it like you heard it` heading on BLL263_1_0 (a pre-existing split-bracket `[Activity 1A` … `]` leak, identical OFF and ON). BLL126's `[embed book 1] Are we able to embed…` writer question now visible inside its hand-off box's Writers Note (the dump — developer-facing, gate-excluded).

**Ledger:** FULL ship — counter reset to 0 · data `Input_Doc_Rules.red_runs.hyperlinked_tag_runs` {{head_words, exclude_words, link_target_match}} + `Emit_Templates.elements.media_hyperlinked_lead` + `interactive_placeholder.embedded_member_text` {{directives, linked_tag_counts}} + `buttons["audio button"].label_default` · env `HYPERTAG_OFF` / `MEDIALEAD_OFF` / `MEMBERTEXT_OFF` / `BTNLABELDEF_OFF` · tools (session 9) `outputs/_measure_r342_hyperlinked_brackets.py` (+ `.log`), `_r342_audio_visible.py` (+ `.log`), `_r342_audio_forms.log`, `_r342_blackblue_pages.py` (+ `.log`), `_measure_r342_embedded_members.cjs` (+ `_r342_emb_off_*.{{json,log}}`), `_measure_r342_media_embedded.cjs` (+ `_r342_medemb_*.{{json,log}}`, `_r342_medemb_summary.log`), `_r342_scanstate.cjs`, `_r342_notes.cjs`, `_r342_patch_membertext.py`, `_r342_stopstate.py`, `_r342_probe.cjs` + `_r342_probe_run.sh` + `_r342_shard_0*` + `_r342_probe_{{off,on}}_0*.log`, `_r342_flagsoff_identity.log` · (session 11) `_r342_medlead_gold.py` (+ `.log`), `_r342_s11_probe_run.sh` + `_r342_s11_probe_{{off,on}}_0*.log` + `_r342_s11_probe_sample.log`, `_r342_s11_affected.txt` + `_r342_s11_changed_modules.txt`, `_r342_s11_quality.py` (+ `.log`), `_r342_fullship_run.sh` + `_r342_fullship_par.sh` + `_r342_fullship_regen.log`, `_r342_gates.log`, `_r342_sk_final.json` / `_r342_sk_full.log`, `_r342_sk_movers.py` (+ `.log`), `_r342_selftests.log`, `_r342_verify_carousel.log`, `_r342_fastloop_snapshot.log`, `_r342_feature_index.log`, `_r342_finalise.py` · AppVersion 260619.13.

"""
if "round 342, build 260619.13" not in s:
    assert s.startswith(head); s = head + ENTRY + s[len(head):]; wr(CL, s); print("changelog prepended")

# ---------------------------------------------------------------- 2. Config.js
CF = os.path.join(PF, "app", "js", "Config.js"); c = rd(CF)
OLD = '\tstatic AppVersion = "260619.12";' + chr(10)
NEW = ('\t// ROUND 342 (2026-09-16, build 260619.13): a writer\'s MEDIA tag typed as a HYPERLINK is still a tag — a run inside a' + chr(10) +
       '\t// w:hyperlink whose bracket head is a data-listed media word (and whose target is a media-file carrier) counts as red' + chr(10) +
       '\t// (DocxExtractor, Input_Doc_Rules.red_runs.hyperlinked_tag_runs, env HYPERTAG_OFF); its own words are the caption' + chr(10) +
       '\t// (MediaBuilder, env MEDIALEAD_OFF); a tag member\'s bracket-line text / link keeps the hand-off box alive (env' + chr(10) +
       '\t// MEMBERTEXT_OFF); a bare [audio button] never invents a journal label (env BTNLABELDEF_OFF). FULL regeneration.' + chr(10) +
       '\tstatic AppVersion = "260619.13";' + chr(10))
if '"260619.13"' not in c:
    assert c.count(OLD) == 1; c = c.replace(OLD, NEW, 1); wr(CF, c); print("AppVersion bumped")

# ---------------------------------------------------------------- 3. CLAUDE.md §9 / §11 / §14
CM = os.path.join(PF, "CLAUDE.md"); m = rd(CM)
OLD9 = "| **Skeleton (PRIMARY)** | `python3 _skeleton_compare.py` | **ROUND 341 BASELINE (a writer's tag typed in a NON-STANDARD RED is still a tag"
NEW9 = (f"| **Skeleton (PRIMARY)** | `python3 _skeleton_compare.py` | **ROUND 342 BASELINE (a writer's MEDIA tag typed as a HYPERLINK is still a tag — the r341 seam on `w:hyperlink` runs, three data fences; FULL regeneration): SCAFFOLD mean {SK_A}% / >=50% {GE50} / >=75% {GE75_A} / >=90% {GE90} / skipped 0 @ {PAIRS}; RAW {RAW_A}%** (state `outputs/_r342_sk_final.json`, FRESH). r342 {DELTA} ({SK_B4} → {SK_A4}; ≥75 −2 NAMED; {MOVED}); compare_structure exact {CS} / EXTRA {EX} / missing {MI} EXACT; body {BODY_B} → {BODY_A} IMPROVED; clean 98.91% / leak 26/23 EXACT; every other gate EXACT. Older r341 text: **ROUND 341 BASELINE (a writer's tag typed in a NON-STANDARD RED is still a tag")
if "ROUND 342 BASELINE" not in m:
    assert m.count(OLD9) == 1, "§9"; m = m.replace(OLD9, NEW9, 1); print("§9")
ROW = ("| `HYPERTAG_OFF` | 342 | **A WRITER'S MEDIA TAG TYPED AS A HYPERLINK IS STILL A TAG** (the autonomous loop's session-9 Round 2, finished in session 11 — item 0 of Chris's session-10 queue; **FULL regeneration, ledger 0**). Reverts byte-for-byte (ALL-OFF of the four r342 toggles in memory = disk 2110/2110). ON (default), `Input_Doc_Rules.red_runs.hyperlinked_tag_runs` `{ enabled, env, head_words, exclude_words, link_target_match }`: in `DocxExtractor.#parseParagraph` a run INSIDE a `w:hyperlink` whose bracket opens with a listed media head (`audio` / `audios` / `audio button` / `audiovisual` / `av` / `video` / `image` / `link` — the BLL phonics writers hyperlink `[audio 1]` to its sound file in the link blue `1155cc` / `3494ba` / `0563c1` or black, 226 audio runs of 600 hyperlinked bracket runs measured `outputs/_measure_r342_hyperlinked_brackets.py`) counts as red, the r341 `nearOpen` depth keeping a split bracket whole; the paragraph is marked `block.hyperTag` (a side-channel). THREE FENCES, each measured: the head list (the same writers hyperlink every phonics WORD — `[scissors]`, `[wrist]` … ~230 runs of content; `embed` deliberately absent — its 3 runs are the r279 reading-book family), `exclude_words` (`animation` — XDLS903/904/905's `[Audio Animation N: …]` CS briefs), `link_target_match` (the target must be a drive / sharepoint / docs / istock / shutterstock / youtube / vimeo / desire2learn host or a media file extension — 590 of the 600; BLL262's tahurangi School-Journal PAGE is a reference, not a file). OFF: every hyperlinked media tag ships as literal text again. |\n"
       "| `MEDIALEAD_OFF` | 342 | **THE HYPERLINKED LEAD** — on a `block.hyperTag` item `MediaBuilder.media` (now taking the normaliser as a sixth argument, the `contentTable` precedent) folds the element's embedded lead (`RenderText` of its own span — `[audio] snail, paint, trail…` → the words) in FRONT of its own / black-after text; the standing rules then apply unchanged (a built video drops it as its title per r80; audio / un-built keep it as the caption `<p>`). Scoped to the hyperlinked class by measurement (`outputs/_r342_medlead_gold.py`: the gold keeps a lead's words as visible text on 0.25 of the 40 hyperlinked sites and 0.24 of the 359 pre-existing red-span sites — for the phonics lists it builds per-word `word` / `audioButton` widgets, the r300 non-derivable form), so the pre-existing red-span leads stay dropped. Data `elements.media_hyperlinked_lead`. OFF: the words vanish from the page. |\n"
       "| `MEMBERTEXT_OFF` | 342 | **A TAG MEMBER'S BRACKET-LINE TEXT IS HAND-OFF CONTENT** — `ContentConverter.#interactivePlaceholder`'s `embeddedText(it)`: a tag member with an empty tail whose primary directive is ELEMENT / INLINE and whose class is `tag` (an instruction-class member already surfaces as the note before the box; an INTERACTIVE invocation's bracket text is its own spec) counts in both empty-box guards and the member dump renders its raw bracket line (`[audio] while, whale, whirl, whole, whine`; `[Source image: angry person]`); a HYPERLINKED media tag with no words but a link target dumps `[audio] <url>` (`linked_tag_counts` — the link IS the member's content; without it BLL141 / BLL171's dragAndDrop box and its `.txt` entry vanished). Measured (session 9, `_measure_r342_embedded_members.cjs`): 255 un-built bundles / 124 modules carry such a member; 7 boxes were suppressed outright and now stand (BLL150_0_0, BLL166_1_0, ENGC101_4_0, EXPFUN04_0_0, HIS1001_10_0, MXEO201_4_0, XWHA02_3_0). Data `interactive_placeholder.embedded_member_text`. OFF: the guards read blackAfter alone again. |\n"
       "| `BTNLABELDEF_OFF` | 342 | **A BUTTON KEY'S OWN LABEL DEFAULT** — at the generic button seam a writer-less label takes `buttons[<key>].label_default` when the key defines one, else `journal_label_default`; `audio button` defines `\"\"` because the gold's `audioButton` is text-less on 1,014 of 1,014 sites (`<div class=\"audioButton\" audioName=…></div>`) — 7 corpus sites shipped `Go to your journal` on an audio button before this and the hyperlinked rule would have added 8 (BLL140/150/160/170's `[audio button]`). OFF: every key falls back to the journal default. |\n")
if "| `HYPERTAG_OFF` | 342 |" not in m:
    A = "| `NEARRED_OFF` | 341 |"; assert m.count(A) == 1, "§11"; m = m.replace(A, ROW + A, 1); print("§11")
B14 = (f"- **Build:** `260619.13` (round 342 — **a writer's MEDIA tag typed as a HYPERLINK is still a tag** (`[audio 1]` linked to its sound file — the r341 seam on `w:hyperlink` runs behind three measured fences; its own words become the caption; a tag member's bracket line / link keeps the hand-off box alive; a bare `[audio button]` never invents a journal label; the autonomous loop's session-9 Round 2 finished in session 11 — item 0 of Chris's session-10 queue; **FULL regeneration of all 416 dirs — ledger reset to 0**). **ROUND 342 BASELINE: SCAFFOLD mean {SK_A}% / ≥50% {GE50} / ≥75% {GE75_A} / ≥90% {GE90} / skipped 0 @ {PAIRS}; RAW {RAW_A}%** (state `outputs/_r342_sk_final.json`, FRESH) = **{PCT}% of achievable** (ceiling 91.6%). {DELTA}pp ({SK_B4} → {SK_A4}; ≥75 −2 NAMED — BLL217_1_0 / BLL126_1_0, the hyperlinked `[audio]` shipping the standing audio element where the gold builds the per-word `wordDrag` widget, the r300 non-derivable form; 41 moved, every dip the same class — see §9). cs exact **{CS}** / EXTRA **{EX}** / missing **{MI}** EXACT; **body {BODY_B} → {BODY_A} IMPROVED**; clean **2087/2110 = 98.91%** / leak **26/23** EXACT; every other gate EXACT: tags **9557/9557** · flipCard TOTAL 61 divergence 0 · index-sync 33/28 · entry-parity PASS · mtkQuiz shell defect 0 · all THIRTEEN selftests GREEN. Corpus **2110 pages / 413 modules**, 0-stale, **248 pages / 147 modules changed, 0 added/removed, the other 269 byte-identical** (= the in-memory probe's prediction to the page). Env `HYPERTAG_OFF` / `MEDIALEAD_OFF` / `MEMBERTEXT_OFF` / `BTNLABELDEF_OFF`.\n")
if "- **Build:** `260619.13` (round 342" not in m:
    A = "- **Build:** `260619.12` (round 341 —"; assert m.count(A) == 1, "§14"; m = m.replace(A, B14 + A, 1); print("§14")
wr(CM, m)

# ---------------------------------------------------------------- 4. gate_baseline.json
GB = os.path.join(HERE, "..", "reference", "tests", "gate_baseline.json"); raw = rd(GB); d = json.loads(raw)
d["_meta"]["build"] = "260619.13"; d["_meta"]["round"] = 342; d["_meta"]["date"] = "2026-09-16"
d["skeleton"].update({"mean_scaffold_pct": float(SK_A), "raw_mean_pct": float(RAW_A), "pages_ge_50": GE50, "pages_ge_75": GE75_A, "pages_ge_90": GE90})
for sect in ("body", "body_compare"):
    if sect in d and isinstance(d[sect], dict):
        for k in ("any", "pages_any", "any_breakdown", "any_flag"):
            if k in d[sect]: d[sect][k] = BODY_A
d["_meta"]["_round342_note"] = (f"Round 342 (a writer's MEDIA tag typed as a HYPERLINK is still a tag; FULL regeneration). Skeleton {SK_B4}->{SK_A4} ({DELTA}pp; >=50 {GE50}, "
    f">=75 {GE75_B}->{GE75_A} (-2 named: BLL217_1_0, BLL126_1_0 — the r300 non-derivable audio form), >=90 {GE90}; pairs {PAIRS}); cs {CS}/{EX}/{MI} EXACT; "
    f"body {BODY_B}->{BODY_A} IMPROVED; clean 98.91% / leak 26/23 EXACT; every other gate EXACT. Corpus 2110 pages, 248 changed / 147 modules.")
wr(GB, json.dumps(d, ensure_ascii=False) + (chr(10) if raw.endswith(chr(10)) else "")); print("gate_baseline.json refreshed")

# ---------------------------------------------------------------- 5. KB_AMALGAMATION_STATUS.md D-row
KB = os.path.join(HERE, "..", "..", "KB_AMALGAMATION_STATUS.md"); k = rd(KB)
anchor = "| ~~—~~ | (not a KB row — the KB is silent on the SHADE of red;"
drow = (f"| ~~—~~ | (not a KB row — KB 05A lists three audio forms with no rule for which a free-body line takes; the RECOGNITION is level 3 / 4) a writer's MEDIA tag typed as a HYPERLINK is still a tag — `[audio 1]` linked to its sound file counts as red (head-word list, `exclude_words`, `link_target_match` fences); its own words are the caption; a tag member's bracket line / link keeps the hand-off box alive; a bare `[audio button]` never invents a journal label | **SHIPPED round 342** (session 9 built + OFF-proven; session 11 settled gap 2 by measurement — the gold keeps a media lead's words on 0.25 / 0.24 of sites, so the fold is scoped to the hyperlinked class — fenced the two reading-book half-builds and the CS-animation briefs, fixed the vanishing-box gap, FULL regeneration) | 248 pages / 147 modules | {DELTA}pp (≥75 −2 named — the r300 non-derivable audio form) / cs EXACT / body 191 → 180 / clean + leak EXACT | `HYPERTAG_OFF` (+ `MEDIALEAD_OFF` / `MEMBERTEXT_OFF` / `BTNLABELDEF_OFF`) | CAPTURED-LIVE (gold, §1b level 3 — the writer's tag is the writer's tag whatever its colour or link; the element FORM stays the r300 non-derivable) |\n")
if "typed as a HYPERLINK is still a tag" not in k:
    assert k.count(anchor) == 1; k = k.replace(anchor, drow + anchor, 1); print("KB status D-row")
wr(KB, k)

# ---------------------------------------------------------------- 6. CONVERTER_V2_GUIDE.md A4
GD = os.path.join(PF, "..", "CONVERTER_V2_GUIDE.md"); g = rd(GD)
OLDG = "  - `near_red_tag_runs` (round 341) — "
NEWG = ("  - `hyperlinked_tag_runs` (round 342) — `{ \"enabled\": true, \"env\": \"HYPERTAG_OFF\", \"head_words\": [...], \"exclude_words\": [\"animation\"], \"link_target_match\": \"...\" }`. Some writers type a media tag as a hyperlink instead of red text — `[audio 1]` in the link blue, linked to the sound file on Drive or SharePoint — so the tag detector never saw it and the bracket shipped as literal text. A hyperlinked run whose bracket opens with one of the listed media words now counts as red, but only when the link points at a media-file carrier (`link_target_match` — the Drive / SharePoint / iStock / YouTube hosts or a media file extension) and the bracket carries none of the `exclude_words`. The head list is the fence: the same writers hyperlink every WORD of a phonics list (`[scissors]`, `[wrist]` …), which is content, not a tag — never widen the list without measuring (`outputs/_measure_r342_hyperlinked_brackets.py` tallies every hyperlinked bracket by its head word and target host). `embed` is deliberately absent (its only hyperlinked runs are the reading-book family the carousel must not half-build).\n"
        + OLDG)
if "hyperlinked_tag_runs` (round 342)" not in g:
    assert g.count(OLDG) == 1, "guide A4"; g = g.replace(OLDG, NEWG, 1); wr(GD, g); print("guide A4")

# ---------------------------------------------------------------- 7. LOOP_STATE.md
LS = os.path.join(HERE, "..", "..", "LOOP_STATE.md"); s = rd(LS); nl = chr(13) + chr(10) if chr(13) + chr(10) in s[:3000] else chr(10)
def L(t): return t.replace(chr(10), nl)
SEC = L(f"""## Session 9 · Round 2 = Session 11 · Round 0 (engine r342) — what shipped (a writer's MEDIA tag typed as a HYPERLINK is still a tag)
- **Fix:** `Input_Doc_Rules.red_runs.hyperlinked_tag_runs` {{enabled, env HYPERTAG_OFF, head_words, exclude_words ["animation"], link_target_match}}
  + `DocxExtractor.#hyperlinkedTagHead` + the `block.hyperTag` side-channel: a run inside a `w:hyperlink` whose bracket opens with a listed
  media word, carries no excluded word, and whose target is a media-file carrier (the drive / sharepoint / istock / youtube hosts that carry 590
  of the 600 hyperlinked bracket runs, or a media file extension) counts as red; the r341 `nearOpen` depth keeps a split bracket whole.
  `embed` deliberately absent (its 3 hyperlinked runs = BLL262/263's `[Embed audio book]`, the r279 reading-book family — as a recognised
  element the carousel half-built a SharePoint Word doc as an iframe slide). **Riding on it:** `MEDIALEAD_OFF` — `MediaBuilder.media` (now
  taking `norm` as a sixth argument) folds a `hyperTag` item's own words in front of its caption (gap 2, DECIDED by `_r342_medlead_gold.py`:
  the gold keeps a media lead's words on 0.25 of the hyperlinked / 0.24 of the 359 pre-existing red-span sites — per-word widgets, the r300
  non-derivable form — so the fold is scoped to the hyperlinked class and the pre-existing leads stay dropped); `MEMBERTEXT_OFF` — session 9's
  `embedded_member_text` (a tag member's bracket line is hand-off content) + session 11's `linked_tag_counts` (a text-less hyperlinked media tag
  dumps `[audio] <url>` — gap 3: without it BLL141 / BLL171's dragAndDrop box and `.txt` entry vanished with the writer's `[drop and drag]`
  request); `BTNLABELDEF_OFF` — `buttons["audio button"].label_default: ""` (the gold's audioButton is text-less 1,014 / 1,014; 7 corpus sites
  + 8 new ones would have said `Go to your journal`).
- **Regeneration:** FULL (all 416 gated dirs, 36 batches / 4 workers, `_r342_fullship_par.sh`; seven batches rc 1 = the r279 parallel-write
  race on batch_convert's results cache (`BATCH FATAL: SyntaxError … in JSON`, `batch_progress.log`), re-run one at a time rc 0; 0 stale). The
  in-memory probe over ALL 416 first (`_r342_s11_probe_run.sh`): ALL-OFF (4 toggles) = disk 2110/2110; ON = 248 pages / 147 modules
  (`_r342_s11_affected.txt`). Manifest diff = exactly 248 / 147, 0 added / removed, the other 269 byte-identical (= the §0b whole-family
  proof: the r341 full ship's manifest is the OFF state). Quality (`_r342_s11_quality.py`): leaks by the gate's own predicate 15 → 15, no
  module worse; word-loss = reference URLs → `<img>` placeholders (r240 D3), tag tokens, note chrome, the 7 invented journal labels;
  hand-off boxes 7 gained (the gap-1 rescues) / 0 lost / 1 BUILT (BLL253_2_0's five `[image]`-hyperlinked clickDrop panels, verifier defect 0).
  The three-repair rule: gap 2 settled (fold), gap 3 the vanishing box (fence 1: the link counts), the two reading-book half-builds
  (fence 2: the target host + no `embed`), the CS-animation briefs (fence 3: `exclude_words`) — inside the round.
- **Gates:** skeleton {SK_B} → {SK_A} ({DELTA}pp; {SK_B4} → {SK_A4}; pairs {PAIRS}); ≥50 {GE50} EXACT; ≥75 {GE75_B} → {GE75_A} (−2 NAMED: BLL217_1_0 75.86 →
  73.83, BLL126_1_0 76.39 → 74.48 — the hyperlinked `[audio]` ships the standing audio element (in its own section row) + the words as a
  caption where the gold builds the per-word `wordDrag` / `word` widget, the r300 non-derivable form; the OFF literal `<p>[audio] …</p>` had
  matched a gold `<p>` by coincidence); ≥90 {GE90}; RAW {RAW_B} → {RAW_A}; {MOVED}. cs exact {CS} / EXTRA {EX} / missing {MI} EXACT. body
  {BODY_B} → {BODY_A} IMPROVED. clean 2087/2110 = 98.91% / leak 26/23 EXACT; tags 9557/9557; flipCard divergence 0; speechBubble defect 4 =
  r341's standing baseline; modal / mtkQuiz defect 0; over the 147: clickDrop 47 / 116 items defect 0, accordion 276 panels every one matching
  the human, dropDown defect 0, tabs defect 2 = PHE1005 / XLP06 (r196 / r281 editorial rewrites), carousel 18 mismatched ids = the r246 / r295
  A1 class, proven pre-existing (identical video ids OFF vs ON on all six modules, `_r342_s11_off6/`); 13 selftests GREEN. Fast-loop
  baseline re-snapshotted, manifest snapshot (2110 / 413), `_ship_ledger.py record-full --build 260619.13` (counter 0), feature index
  rebuilt (selftest GREEN). **{PCT}% of achievable.** The plateau window: r341 +0.021 · r342 −0.003 (one under-0.02 round).
- **Verifier:** {VER}.
- **Named:** the audio element's FORM (audioPlayer vs the gold's text-less audioButton / per-word wordDrag — D10-3's build kickoffs); the 359
  pre-existing red-span media leads (gold drops 0.76); the hyperlinked `[audiovisual]` / `[av]` heads (39 runs — BLL254's `[Audiovisual
  request item 1]` now an r300 orphan note rather than the black link line, 1 site); the plain-BLACK tag class (≈ 300, the 26 residual leaks);
  BLL263_1_0's pre-existing `] Read it like you heard it` split-bracket heading; BLL126's `[embed book 1] Are we able…` question now visible
  inside its hand-off box's note.

""")
ANCHOR = "## Session 9 · Round 2 (engine r342) — IN PROGRESS at the stop"
if "## Session 9 · Round 2 = Session 11 · Round 0 (engine r342) — what shipped" not in s:
    assert s.count(ANCHOR) == 1; s = s.replace(ANCHOR, SEC + ANCHOR, 1); print("LOOP_STATE section")
OLD_P = "- Session 9 Round 2 (engine r342 — a writer's MEDIA tag typed as a HYPERLINK is still a tag: `[audio 1]` linked to its sound file; the r341 seam"
i = s.find(OLD_P); assert i > 0, "position anchor"
j = s.find(nl + "- Remaining KB queue", i); assert j > i, "position end"
NEW_P = (f"- Session 9 Round 2 = Session 11 Round 0 (engine r342 — a writer's MEDIA tag typed as a HYPERLINK is still a tag: `[audio 1]` linked to its sound file; the r341 seam extended to `w:hyperlink` runs behind three measured fences (head words / `exclude_words` / `link_target_match`); its own words the caption (`MEDIALEAD_OFF`); a tag member's bracket line or link keeps the hand-off box (`MEMBERTEXT_OFF`); a bare `[audio button]` never invents a journal label (`BTNLABELDEF_OFF`)): built + OFF-proven in session 9, **gap 2 decided by measurement, gap 3 + two reading-book half-builds fenced, flipped ON + SHIPPED 2026-09-16 ≈16:50 (session 11)**. AppVersion 260619.13, CLAUDE.md §9/§11/§14, KB status D-row, CONVERTER_V2_GUIDE A4, **FULL regeneration (ledger 0)**. Skeleton {DELTA}pp (≥75 −2 named — the r300 non-derivable audio form), ≥50 / ≥90 EXACT, cs EXACT, body 191 → 180 IMPROVED, clean / leak EXACT; 248 pages / 147 modules.")
if "= Session 11 Round 0 (engine r342" not in s:
    s = s[:i] + NEW_P + s[j:]; print("position")
OLD_R = "- s9-r2 (engine r342 — IN PROGRESS, stopped by Chris ≈11:05)"
i = s.find(OLD_R); assert i > 0, "round log anchor"; j = s.find(nl, i) + len(nl)
NEW_R = (f"- s9-r2 / s11-r0 (engine r342) · a writer's MEDIA tag typed as a HYPERLINK is still a tag (`[audio 1]` in the link blue linked to its Drive / SharePoint sound file — the r341 seam on `w:hyperlink` runs whose bracket head is a data-listed media word, fenced by the head list (the ~230 hyperlinked phonics WORDS stay content), `exclude_words` (the XDLS `[Audio Animation N:` CS briefs) and `link_target_match` (a media-file carrier — BLL262's tahurangi PAGE stays a link); its own words become the caption; a tag member's bracket line or link keeps the hand-off box + `.txt` entry; a bare `[audio button]` never invents `Go to your journal`) · built + OFF-proven s9, gap 2 decided by measurement + 3 fences s11 · SHIPPED 2026-09-16 · FULL regeneration (ledger 0), 248 pages / 147 modules, 0 added/removed · scaffold {SK_B}→{SK_A} ({DELTA}; {SK_B4}→{SK_A4}; 41 moved — 16 up / 25 down, pp-sum −6.76, every mover in the affected set; every dip ≤ 2.21pp = the recognised `[audio]` shipping the standing audio element where the gold builds the per-word wordDrag / audioButton widget (r300 non-derivable) and the OFF literal line's coincidental `<p>` match), ≥50 {GE50} EXACT, ≥75 {GE75_B}→{GE75_A} (−2 NAMED BLL217_1_0 / BLL126_1_0), ≥90 {GE90}, cs {CS}/{EX}/{MI} EXACT, **body {BODY_B}→{BODY_A} IMPROVED**, clean 98.91% / leak 26/23 EXACT, every other gate EXACT · hand-off boxes +7 rescued / 0 lost / 1 built (BLL253 clickDrop, defect 0) · {PCT}% of achievable · commit (see git log) · **plateau window: r341 +0.021 · r342 −0.003**" + nl)
if "- s9-r2 / s11-r0 (engine r342)" not in s:
    s = s[:i] + NEW_R + s[j:]; print("round log")
wr(LS, s); print("LOOP_STATE.md written")
