#!/usr/bin/env python3
"""ROUND 349 (loop session 13 Round 2 — Chris's D10-9: KB constraint 23 / 01B lesson-menu labels everywhere) — finalise:
changelog, AppVersion (260619.19 → 260619.20), CLAUDE.md §9 / §11 / §14, gate_baseline.json (skeleton + the new menulabels
block), KB_AMALGAMATION_STATUS.md (row 23 + a §D row), loop/README.md rows, LOOP_STATE.md (PICK + what shipped + position +
round log). Idempotent; LF kept (the r343 / r348 pattern)."""
import io, os, json
HERE = os.path.dirname(os.path.abspath(__file__))
PF = os.path.normpath(os.path.join(HERE, "..", "..", "pageforge-site", "converter-v2"))
def rd(p):
    with io.open(p, encoding="utf-8", newline="") as f: return f.read()
def wr(p, s):
    with io.open(p, "w", encoding="utf-8", newline="") as f: f.write(s)

SK_B, SK_A, SK_B4, SK_A4 = "51.283", "50.965", "51.2832", "50.9655"
RAW_B, RAW_A = "35.409", "35.049"
GE50_B, GE50_A, GE75_B, GE75_A, GE90_B, GE90_A, PAIRS = 1074, 1072, 198, 159, 15, 14, 1955
CS, EX, MI, POOL = 11464, 175, 607, 13513
PCT_B, PCT_A, CEIL = "55.8", "55.5", "91.9"
UP75 = "ANZH105_0_0 BLL125_0_0 BLL131_0_0 BLL136_0_0 BLL137_0_0 BLL141_0_0 BLL142_0_0 BLL143_0_0 BLL144_0_0 BLL164_0_0 BLL171_0_0 BLL172_0_0 BLL174_0_0 BLL175_0_0 BLL176_0_0 BLL177_0_0 BLL211_0_0 BLL212_0_0 BLL215_0_0 BLL216_0_0 BLL217_0_0 BLL221_0_0 BLL222_0_0 BLL223_0_0 BLL224_0_0 BLL225_0_0 BLL226_0_0 BLL227_0_0 BLL231_0_0 BLL232_0_0 BLL235_0_0 BLL245_0_0 BLL252_0_0 ENGC202_0_0 ENGI203_0_0 ENGI405_0_0 ENGJ101_0_0 ENGS302_0_0 SCPH301_5_0"
DOWN50 = "ENGC401_0_0 ENGI302_4_0 ENGJ301_7_0 ENGR101_0_0 HPFUN902_0_0 SSOG103_0_0 XGF9006_0_0 XLP01_0_0 XLP02_0_0"
UP50 = "AGH1002_2_0 CEDT501_5_0 ENGJ302_9_0 ENGR301_8_0 ENGS401_1_0 ENGS401_6_0 PES1007_1_0"
MOVERS = ("322 moved — 114 up / 208 down, EVERY mover inside the 715 changed pages (0 outside); by page type: the LESSON pages (constraint 23's own scope) are a net GAIN — 158 movers, "
          "+0.063pp (Standard +101.23 pp-sum, 102 up / 47 down; Fundamentals +11.92, 3 / 2; Inquiry +9.09, 3 / 1) — and the OVERVIEW pages (D10-9 (f), 01B 196–197: the r81 / r142 eng- and banner-family `<p>` labels → `<h5>`) are the whole dip — 164 movers, "
          "−0.375pp (Standard −692.70 pp-sum, 3 up / 115 down; Fundamentals −20.34, 0 / 22; Inquiry −20.89, 3 / 21); by series the BLL family alone is −474.68 (1 up / 87 down: its overview two-column menu keeps `<p>` labels in the gold, 154 of 179), then ENGI −52.16, ENGC −38.63, ANZH −33.26, XLP −26.84, SCPH −23.03, XGF −18.88, HPFUN −13.46; "
          "the largest dips are overview pages — ENGI401_0_0 −14.31 (93.48 → 79.17, the one ≥90 crosser), ANZH203_0_0 −13.58, OSBY301_0_0 −13.34, XLP05_0_0 −13.10, ANZH205_0_0 −12.53, ENGC102_0_0 −10.13; the largest gains are lesson pages — ENGR301_7_0 +8.73, ENGS401_6_0 +8.65, ENGI401_10_0 +8.34, XFUN02_6_0 +7.14, ENGJ302_9_0 +6.61, AGH1002_5_0 +6.57")

# ---------------------------------------------------------------- 1. BUILD_CHANGELOG.md
CL = os.path.join(PF, "BUILD_CHANGELOG.md"); s = rd(CL)
head = "# BUILD CHANGELOG — Stage 2 (engine + UI)" + chr(10) + chr(10)
ENTRY = f"""## 2026-09-16 (round 349, build 260619.20) — EVERY LEARNING / SUCCESS LABEL IN THE MODULE MENU IS THE KB'S `<h5>` FORM (Chris's decision D10-9, Option A — KB constraint 23 (Universal) + 01B "Lesson Pages — Simplified Module Menu" and the overview-tab label row: every label `<h5>` in the colon form, the writer's "We are learning to:" family normalised to "We are learning:" with its items in "to …" form (constraint 24), a section title directly above a label dropped on a lesson page, the overview tab's labels `<h5>` too, the constraint-70 OSSC sentence untouched; a NEW protected verifier `_verify_menulabels.cjs`; the autonomous loop's session-13 Round 2; FULL regeneration of all 416 gated dirs; a NAMED KB-over-gold override — the lesson half GAINS +0.063pp, the overview half Chris chose costs −0.375pp (three times the −0.1pp estimate; one data flag reverts that half alone)) + a SECOND batch-runner race closed (`batch_results.json`, found by this regeneration)

### 1. WHAT CHANGED, IN ONE LINE

**Inside `#module-menu-content` on every page, a learning / success LABEL — "We are learning:", "I can:", "You will show your understanding by:", "Ākonga will:", "Learning intentions" … (the data `role_lexicon`), at most eight words, ending in a colon / an ellipsis or followed by a list — ships as `<h5>` ending in a colon, whatever the writer typed it as (`<p>`, `<p><b>`, `<h3>`, `<h4>`, "…", "..."); the writer's "We are learning to:" / "We are learning about/to …" family becomes the KB's `We are learning:` and each item of its list gains "to " with its first letter lowercased (constraint 24's "verb form matching heading context" — exactly the gold's own re-wording on CEDO502 / ENGC401 …); on a LESSON page a section TITLE ("Learning intentions", "How will I know if I've learned it?", "Success criteria") that sits directly above a label is dropped (01B 223 — the `<h5>` IS the label); the OVERVIEW tab's labels are `<h5>` too (01B 196–197 — the r81 / r142 eng- and banner-family `<p>` form retired for the labels only; its `<h4><span>` titles stay); a constraint-70 SENTENCE ("Ākonga will learn the difference between …", "You will be able to …") is never a label and stays `<p>`; the SUCCESS label keeps the writer's wording (colon form only) because 01B's year table needs a year the data does not hold.** Authority: KB level 1 (a numbered constraint — no gold-share test, LOOP §2 amended) over the gold's per-series split; Chris's D10-9 verbatim: "apply constraint 23 everywhere: every lesson-menu label becomes <h5> with the KB's normalised wording, the section titles above them go, and the overview tab's labels become <h5> too".

### 2. THE MEASUREMENT (`outputs/_measure_r349_menuform.py` → `_r349_menuform.{{json,log}}`; 1,056 paired lesson pages + 381 overview pages with a menu on both sides; the session-12 pre-measurement `_r348_menulabels.log` stands)

- **Lesson pages:** 1,318 Claude labels — 1,129 already `<h5>`, **189 residue** (`<p>`: 154 learning / 35 success) on 146 pages / 34 modules (Standard 180, Fundamentals 5, Inquiry 4, Bilingual 0; English 86, Maths 44, ConnectED 25, NCEA1 19); the gold's tag for the residue: `<p>` 72 / `<h5>` 59 / absent 30 / `<h3>` 24 / `<li>` 4 (the gold is split — the KB decides). **Section titles** Claude shipped on lesson pages: 152 on 116 pages / 21 modules (`<h5>Learning intentions</h5>` 77, `<h4>Learning Intentions</h4>` 28, `<h5>Learning Intentions</h5>` 21, `<h5>How will I know if I've learned it?</h5>` 16 …); the gold keeps 124 of them — **117 sit directly above a label (dropped), 20 are the two-column banner (`<h4>Learning Intentions</h4>` → `<h5>Understand</h5>` …, kept), 15 are the label of their own list (followed by `<ul>`, kept)**.
- **Wording:** the gold re-words 181 of 1,156 matched labels — "we are learning to" → "we are learning" 58 (kept 147), "we are learning about" → "we are learning" 40 (kept 36); where it re-words "to" → bare, **it prefixes the items with "to " and lowercases them on 30 of 39 checked pages** (CEDO502 `understand what credit and debt are …` → `to understand …`; ENGC401 `Understand the history …` → `to understand the history …`) — the mechanical rule this round ships; "We are learning about:" is kept (its items would need a verb rewrite — editorial). **Form:** the gold's exact strings — `We are learning:` 389, `I can:` 259, `You will show your understanding by:` 220, `We are learning to:` 160, `We are learning about:` 38, then the ellipsis forms 18 + 10 + 9 + 5 + 4 — the colon is the form at ≥ 0.9 in every family; Claude shipped `You will show your understanding by …` 65 / `…` 27 / bare 18, `We are learning to ...` 39, `We are learning to` 19.
- **Overview pages:** 1,301 labels — Claude `<p>` 552 on 288 pages (the gold keeps `<p>` on 480 of them: Blended Literacy 154, English 59, Online Safety 56, Leaving to Learn 54, Maths 36 …), `<h5>` 575, `<h4>` 172. D10-9 (f) makes the 552 `<h5>` — the named override.
- **The OSSC / "Ākonga will …" split:** LABEL (≤ 7 words, colon: BLL 22, MXFL 20, MXDB 18, ANZH 7, MXDI 7, SSOG 3) vs SENTENCE (XDLS 28, OSAH 14, OSBY 11, OSGM 8, OSOH 8, OSSM 8, OSAI 5, OSSC 3, ART 3, MXFU 3) — the sentences stay `<p>` (constraint 70).
- **The year table (01B 240–244):** not in the data (the session-12 pre-measurement: the code's level digit is not a year; the gold is per-MODULE consistent, 6 of ~130 mix) — `menu.lesson_label_form.year_table {{}}` ships as the hook; the success label keeps the writer's wording. Not re-asked (LOOP §5b; the review's "owed by Chris" item stands).

### 3. THE SEAM (data `Emit_Templates.menu.lesson_label_form` {{enabled, env, level 5, role_lexicon, title_lexicon, label_max_words 8, drop_titles, overview_labels, colon_form, learning_to_normalise, learning_to_pattern, learning_label, item_prefix, year_table}}; env `MENULABEL_OFF`)

- `ContentConverter.#menuLabelForm(html, isOverview)` — a post-pass on EVERY menu pane string (`tab1` / `tab2` / `content` / `left` / `right` / `wtPanes` / `reoPanes`) and on every `{{cls, html}}` column of the array panes (`tab1Cols` / `tab2Cols` / `funLiCols` / `cols`), run right AFTER the r-lesson-repeat copy (so a repeated overview menu gets the lesson treatment on a lesson page) and before the precedence cascade. It tokenises the pane into `<p>` / `<h1–6>` blocks and flat lists; a block is a LABEL when its folded text starts with a role lead-in, is ≤ `label_max_words`, and ends with a colon / ellipsis or is followed by a list; a label is re-emitted as `<h5{{its own attributes}}>` + the text with its trailing `...` / `…` / `.` / `:` stripped and a colon added (the MTK menus' `<h5 eng>` keep their attribute — found by the whole-family probe on PNR101 and fixed before the ship); the "to" family (`learning_to_pattern` on the folded text, where "about/to" reads "about to") takes `learning_label` and marks the next list, whose `<li>`s gain `item_prefix` unless they already start with it, first letter lowercased; on a lesson page a `title_lexicon` block immediately followed by a label is dropped with its whitespace; a sentence, a title followed by its own list, a two-column banner, and everything inside a widget subtree are untouched. The r117 `menu_lead_in_headings` promotion and the r81 / r142 `skip_named_promotion` flags are left in place (they run first; this pass supersedes their result for labels).
- The durable record: `outputs/_r349_splice.py` (idempotent; §6 atomic writes — encode first, temp file, `node --check` / a duplicate-key JSON load, `os.replace`), proven to reproduce BOTH live files from the HEAD blobs; `_r349_patch_attrs.py` (the attribute fix, applied to the engine and to the record).
- **The second race (tooling, `batch_convert.cjs`):** the first full regeneration with the r348 oembed-cache fix in place still lost 4 of 36 batches (12 / 22 / 27 / 33) — to the OTHER shared file: `batch_results.json` (4.5 MB) is read whole at startup and rewritten whole after every module by every worker (`Unterminated string in JSON at position 4320808`). `_r349_patch_results_race.py`: a torn-tolerant read (warn, start empty — it is a diagnostic ledger) and an atomic MERGED write (`readResults()` overlaid with this worker's rows → `.pid.tmp` → `renameSync`). The four batches were re-run IN PARALLEL with the fix — rc 0, all four. The r341–r347 "≈ 3 of 36" were a mix of both files; the next full regeneration is the test of 0.

### 4. THE VERIFIER — `reference/tests/_verify_menulabels.cjs`, a NEW protected gate (in `run_all_gates.sh`; `--selftest` GREEN: LIVENESS 16 labels on ENGC401, DETECTION an injected `<h5>` → `<p>` 0 → 2)

- Per module, in memory: every label is `<h5>` (rule 1), ends with a colon (2), no lesson-page title directly above a label (4), no `<p>` between a label and its list (5); the "bare-verb items under We are learning:" count is REPORTED, not a defect (the writer's own "We are learning:" lists are left as written). Gate set (every authoring shape): AGH1002 (the combined "about/to" label), ENGC401 (the "to" family), MXFL201 (titles + bold Māori labels + the lesson-repeat), OSSC401 (the c70 sentence), ANZH101 (the two-column banner), BLL110 (the banner-family overview), XFUN02 (Fundamentals `funLiCols`), CEDT501 (Inquiry), CEDO502 — **91 labels, defect 0**. It reads `gate_baseline.json.menulabels.per_module` the r348 way (✓ at baseline, ✗ only above).

### 5. THE PROOF

- In-memory probe over ALL 416 (`_r349_probe.cjs` = the r342 probe with `MENULABEL_OFF`, 4 shards): **OFF = disk 2110/2110; ON = 715 pages / 319 modules** (`_r349_probe_on_*.log`, classified line by line in `_r349_probe_classify.log`: overview label `<p>` → `<h5>` 557, lesson label `<p>` → `<h5>` 159, `<h5>` labels re-formed (colon / "We are learning:") 438 lesson + 20 overview, list items "to " + lowercase 452 lesson + 248 overview, lesson-page titles dropped 94 `<h5>` + 8 `<h4>` — **0 other kinds; Bilingual 0 pages**). FULL regeneration of all 416 gated dirs (`_r349_fullship_par.sh`, 36 batches × 4 workers 21:49–21:53; the four race batches re-run in parallel after the fix 21:54–21:55, rc 0); `_stalecheck.sh` 0 stale; `_content_manifest.py diff` = **exactly the 715 predicted pages / 319 modules, 0 added / removed**.
- **Skeleton (PRIMARY): SCAFFOLD mean {SK_B}% → {SK_A}% (−0.318pp; {SK_B4} → {SK_A4}) / ≥50% {GE50_B} → {GE50_A} (9 down-crossers: {DOWN50}; 7 up: {UP50}) / ≥75% {GE75_B} → {GE75_A} (39 down, 0 up — {UP75}) / ≥90% {GE90_B} → {GE90_A} (ENGI401_0_0) / skipped 0 @ {PAIRS}; RAW {RAW_B}% → {RAW_A}%** (state `outputs/_r349_sk_final.json`, FRESH; movers `_r349_sk_movers.log` / `.json`): {MOVERS}. **Every dip is a NAMED KB-over-gold override on a changed page — 38 of the 39 ≥75 crossers and 8 of the 9 ≥50 crossers are OVERVIEW pages whose gold keeps `<p>` labels; net of the overview half the round is +0.063pp.** The estimate in D10-9 was "≈ −0.1pp"; the measured cost of the overview half is 3.75× that — reported to Chris; `menu.lesson_label_form.overview_labels: false` reverts that half alone, the lesson half stands on its own.
- compare_structure exact **{CS}** / EXTRA **{EX}** / missing **{MI}** EXACT (pool {POOL}); body 180; clean 2080/2103 = 98.91%; leak 26/23; tags 9557/9557; flipCard / speechBubble (4, ✓ at baseline) / modal / mtkQuiz / math (322/323, ✓ at baseline) identical — **every RESULT line in the suite green, the first time**; fast-loop baseline re-snapshotted (`_r349_fastloop_snapshot.log`); manifest snapshot 2110 / 413; `_ship_ledger.py record-full --round 349 --build 260619.20` (scoped counter 0, 8 of headroom); feature index `--rehtml` 678 + `--merge`, selftest GREEN; **15 selftests GREEN** (14 + `_verify_menulabels.cjs`). **{PCT_A}% of achievable** (ceiling {CEIL}%; was {PCT_B}%).

### 6. RECORDED

- The overview half's measured cost (−0.375pp, 164 pages, BLL 87) vs the −0.1pp estimate — Chris to confirm or flip `overview_labels`. The success label's wording (the year table — data / KB session). "We are learning about:" kept (a verb rewrite is editorial). The gold's 124 kept section titles and its `<p>` labels on 480 overview / 72 lesson pages — the named override. KB deltas for a KB session: 01B's year table needs a per-module source; constraint 24's item form is now partly mechanical (the "to" prefix) — worth a sentence there.

**Ledger:** FULL ship (round 349; counter reset) · data `Emit_Templates.menu.lesson_label_form` · env `MENULABEL_OFF` · engine `ContentConverter.js` (`#menuLabelForm` + the call site) · gate tools (outside git, mirrored to `loop/`) `_verify_menulabels.cjs` (NEW), `_selftest_core.cjs`, `run_all_gates.sh`, `batch_convert.cjs` (the results-ledger race), `gate_baseline.json` · tools `outputs/_measure_r349_menuform.py`, `_r349_splice.py`, `_r349_patch_attrs.py`, `_r349_patch_results_race.py`, `_r349_probe.cjs` (+ `_r349_probe_run.sh`), `_r349_probe_classify.log`, `_r349_fullship_par.sh` / `_r349_fullship_run.sh`, `_r349_postship.sh`, `_r349_sk_movers.{{log,json}}`, `_r349_finalise.py` · AppVersion 260619.20.

"""
if "round 349, build 260619.20" not in s:
    assert s.startswith(head); s = head + ENTRY + s[len(head):]; wr(CL, s); print("changelog prepended")

# ---------------------------------------------------------------- 2. Config.js
CF = os.path.join(PF, "app", "js", "Config.js"); c = rd(CF)
OLD = '\tstatic AppVersion = "260619.19";' + chr(10)
NEW = ('\t// ROUND 349 (2026-09-16, build 260619.20): every learning / success label in the module menu is the KB\'s <h5> colon' + chr(10) +
       '\t// form (Chris\'s D10-9 — KB constraint 23 / 01B): ContentConverter.#menuLabelForm behind Emit_Templates.menu.lesson_label_form,' + chr(10) +
       '\t// env MENULABEL_OFF; the "We are learning to:" family → "We are learning:" + "to …" items; lesson-page titles above a' + chr(10) +
       '\t// label dropped; the overview tab\'s labels <h5> too; a new protected verifier _verify_menulabels.cjs; FULL regeneration.' + chr(10) +
       '\tstatic AppVersion = "260619.20";' + chr(10))
if '"260619.20"' not in c:
    assert c.count(OLD) == 1; c = c.replace(OLD, NEW, 1); wr(CF, c); print("AppVersion bumped")

# ---------------------------------------------------------------- 3. CLAUDE.md §9 / §11 / §14
CM = os.path.join(PF, "CLAUDE.md"); m = rd(CM)
OLD9 = "| **Skeleton (PRIMARY)** | `python3 _skeleton_compare.py` | **ROUND 347 BASELINE (every content table ships the KB 05D class form"
NEW9 = (f"| **Skeleton (PRIMARY)** | `python3 _skeleton_compare.py` | **ROUND 349 BASELINE (every learning / success label in the module menu is the KB's `<h5>` colon form — Chris's D10-9, KB constraint 23 / 01B; FULL regeneration of all 416 gated dirs, the ledger's full-ship backstop, scoped counter 0; a NAMED KB-over-gold override): SCAFFOLD mean {SK_A}% / >=50% {GE50_A} / >=75% {GE75_A} / >=90% {GE90_A} / skipped 0 @ {PAIRS}; RAW {RAW_A}%** (state `outputs/_r349_sk_final.json`, FRESH) = **{PCT_A}% of achievable** (ceiling {CEIL}%). r349 −0.318pp ({SK_B4} → {SK_A4}): the LESSON half (constraint 23's own scope) +0.063pp, the OVERVIEW half Chris chose in D10-9 (f) −0.375pp — 322 moved, every mover inside the 715 changed pages; ≥75 198 → 159 = 39 named overview pages (BLL 32, ENG 6, ANZH105, SCPH301_5) whose gold keeps `<p>` labels; ≥90 15 → 14 (ENGI401_0_0); cs exact {CS} / EXTRA {EX} / missing {MI} / clean 2080/2103 / leak 26/23 / body 180 EXACT. `menu.lesson_label_form.overview_labels: false` reverts the overview half alone. Older r347 text: **ROUND 347 BASELINE (every content table ships the KB 05D class form")
if "ROUND 349 BASELINE" not in m:
    assert m.count(OLD9) == 1, "§9"; m = m.replace(OLD9, NEW9, 1); print("§9")
OLD11 = "| `TBLBORDER_OFF` | 347 | **EVERY CONTENT TABLE SHIPS `table table-bordered`**"
NEW11 = ("| `MENULABEL_OFF` | 349 | **EVERY LEARNING / SUCCESS LABEL IN THE MODULE MENU IS THE KB'S `<h5>` COLON FORM** (Chris's D10-9, Option A — KB constraint 23 (Universal) + 01B; the autonomous loop's session-13 Round 2; **FULL regeneration of all 416 gated dirs**). Data `Emit_Templates.menu.lesson_label_form` {enabled, env, level, role_lexicon, title_lexicon, label_max_words, drop_titles, overview_labels, colon_form, learning_to_normalise, learning_to_pattern, learning_label, item_prefix, year_table}; engine `ContentConverter.#menuLabelForm` — a post-pass on every menu pane (string panes + the `{cls, html}` column arrays) after the lesson-repeat copy: a label (role lead-in, ≤ 8 words, colon / ellipsis or a list after it) → `<h5>` with its own attributes, colon form; the \"We are learning to:\" family → `We are learning:` + \"to …\" items lowercased (constraint 24 — the gold's own re-wording); a lesson-page title directly above a label dropped (01B 223); the overview tab's labels `<h5>` (01B 196–197 — the r81 / r142 `<p>` form retired for labels); a constraint-70 sentence stays `<p>`; the success label keeps the writer's wording (the year table is an empty hook). Probe OFF = disk 2110/2110, ON = 715 pages / 319 modules = the regenerated set exactly (0 other change kinds, Bilingual 0). Verifier `_verify_menulabels.cjs` (NEW, protected; 91 labels / defect 0; selftest GREEN). Skeleton 51.2832 → 50.9655 (−0.318pp): the lesson half +0.063pp (158 movers), the overview half −0.375pp (164 movers, BLL 87) — a NAMED KB-over-gold override, every mover inside the changed set; ≥75 198 → 159 (39 named overview pages), ≥90 15 → 14 (ENGI401_0_0), ≥50 1074 → 1072; every other gate EXACT. Also r349: `batch_convert.cjs`'s `batch_results.json` save is atomic + merged and its read torn-tolerant (the second parallel-worker race, 4 of 36 batches). | `MENULABEL_OFF=1` restores the r347 menu forms byte-for-byte (2110/2110). `overview_labels: false` in the data keeps the lesson half and reverts the overview half alone. |\n"
         + OLD11)
if "| `MENULABEL_OFF` | 349 |" not in m:
    assert m.count(OLD11) == 1, "§11"; m = m.replace(OLD11, NEW11, 1); print("§11")
B14 = (f"- **Build:** `260619.20` (round 349 — **every learning / success label in the module menu is the KB's `<h5>` colon form** (Chris's D10-9, Option A — KB constraint 23 / 01B: `ContentConverter.#menuLabelForm` behind `Emit_Templates.menu.lesson_label_form`, env `MENULABEL_OFF`; the \"We are learning to:\" family → `We are learning:` + \"to …\" items (constraint 24); lesson-page titles directly above a label dropped (01B 223); the overview tab's labels `<h5>` (01B 196–197); the c70 sentence untouched; the success label's wording kept — the year table is an empty data hook; a NEW protected verifier `_verify_menulabels.cjs` (91 labels / defect 0, selftest GREEN); the autonomous loop's session-13 Round 2; **FULL regeneration of all 416 gated dirs — the ledger's full-ship backstop, scoped counter 0**; the second batch-runner race (`batch_results.json`) closed). **ROUND 349 BASELINE: SCAFFOLD mean {SK_A}% / ≥50% {GE50_A} / ≥75% {GE75_A} / ≥90% {GE90_A} / skipped 0 @ {PAIRS}; RAW {RAW_A}%** (state `outputs/_r349_sk_final.json`, FRESH) = **{PCT_A}% of achievable** (ceiling {CEIL}%; was {PCT_B}%). −0.318pp ({SK_B4} → {SK_A4}): a NAMED KB-over-gold override — the lesson half +0.063pp, the overview half −0.375pp (164 pages, BLL 87; the D10-9 estimate was −0.1pp — reported to Chris; `overview_labels: false` reverts that half alone); 322 moved, every mover inside the 715 changed pages; ≥75 198 → 159 (39 named overview pages), ≥90 15 → 14 (ENGI401_0_0), ≥50 1074 → 1072 (9 down / 7 up, named). cs exact **{CS}** / EXTRA **{EX}** / missing **{MI}**; clean **2080/2103** / leak **26/23**; body **180**; math 322/323; speechBubble 4 — all EXACT; every RESULT line green; 15 selftests GREEN. Corpus 2110 pages / 416 modules, 0 truly stale, **715 pages / 319 modules changed, 0 added/removed**. **Plateau window: r349's PICK predicted a skeleton move and it moved 0.318pp — the window restarts (0 of 3).**\n")
if "- **Build:** `260619.20` (round 349" not in m:
    A = "- **Build:** `260619.19` (round 348 —"; assert m.count(A) == 1, "§14"; m = m.replace(A, B14 + A, 1); print("§14")
wr(CM, m)

# ---------------------------------------------------------------- 4. gate_baseline.json
GB = os.path.join(HERE, "..", "reference", "tests", "gate_baseline.json"); raw = rd(GB); d = json.loads(raw)
if "_round349_note" not in d["_meta"]:
    d["_meta"]["build"] = "260619.20"; d["_meta"]["round"] = 349; d["_meta"]["date"] = "2026-09-16"
    d["skeleton"].update({"mean_scaffold_pct": float(SK_A), "raw_mean_pct": float(RAW_A), "pages_ge_50": GE50_A, "pages_ge_75": GE75_A, "pages_ge_90": GE90_A, "pairs": PAIRS, "pairs_skipped": 0})
    d["menulabels"] = {"labels": 91, "defect": 0, "per_module": {}, "_note": "Round 349 — _verify_menulabels.cjs over AGH1002 ENGC401 MXFL201 OSSC401 ANZH101 BLL110 XFUN02 CEDT501 CEDO502 (every authoring shape): 91 labels, defect 0. per_module is the r348 baseline table (✓ at-or-under, ✗ above); empty = every module at 0."}
    d["_meta"]["_round349_note"] = (f"Round 349 (D10-9: every learning / success label in the module menu is the KB's <h5> colon form — constraint 23 / 01B; FULL regeneration of all 416, ledger counter 0). "
        f"skeleton {SK_B4}->{SK_A4} (-0.318pp = a NAMED KB-over-gold override: the lesson half +0.063pp, the overview half Chris chose -0.375pp (BLL 87 pages); 322 moved, all inside the 715 changed pages); "
        f">=50 {GE50_B}->{GE50_A} / >=75 {GE75_B}->{GE75_A} (39 named overview pages) / >=90 {GE90_B}->{GE90_A} (ENGI401_0_0); RAW {RAW_B}->{RAW_A}; cs {CS}/{EX}/{MI} / clean 2080/2103 / leak 26/23 / body 180 / math 322/323 / speechBubble 4 all EXACT. New gate: menulabels (91 / 0).")
    wr(GB, json.dumps(d, ensure_ascii=False) + (chr(10) if raw.endswith(chr(10)) else "")); print("gate_baseline.json refreshed")

# ---------------------------------------------------------------- 5. KB_AMALGAMATION_STATUS.md — row 23 + a §D row
KB = os.path.join(HERE, "..", "..", "KB_AMALGAMATION_STATUS.md"); k = rd(KB)
OLDROW = "| 23 | Lesson-page menu labels normalised to `<h5>` (We are learning: / I can: / You will show your understanding by:) | pre-ledger | lesson pages with a menu | **AUTHORISED — Chris D10-9 (2026-09-16): apply everywhere, overview tab included, normalised wording by year level, no section title above; queued (FULL regeneration); the `<p>` residue is 206 labels / 176 lesson pages + ~296 overview pages (`_r341_menulabels.log`).** Was:"
NEWROW = "| 23 | Lesson-page menu labels normalised to `<h5>` (We are learning: / I can: / You will show your understanding by:) | pre-ledger | lesson pages with a menu | **SHIPPED round 349 (2026-09-16) — Chris D10-9, Option A: every label `<h5>` in the colon form on every page (the overview tab too), the \"We are learning to:\" family → `We are learning:` + \"to …\" items (c24), a lesson-page title directly above a label dropped, the c70 sentence untouched; the SUCCESS label keeps the writer's wording — 01B's year table is an empty data hook (`menu.lesson_label_form.year_table`) until a per-module year source exists; verifier `_verify_menulabels.cjs` 91 / 0; 715 pages / 319 modules changed; the lesson half +0.063pp, the overview half −0.375pp (named). Was AUTHORISED — Chris D10-9 (2026-09-16); the `<p>` residue was 206 labels / 176 lesson pages + ~296 overview pages (`_r341_menulabels.log`).** Was:"
if "| 23 | Lesson-page menu labels normalised to `<h5>` (We are learning: / I can: / You will show your understanding by:) | pre-ledger | lesson pages with a menu | **SHIPPED round 349" not in k:
    assert k.count(OLDROW) == 1, "KB row 23"; k = k.replace(OLDROW, NEWROW, 1); print("KB row 23")
DANCHOR = "| — | 05D \"Tables\" — `table table-bordered` default;"
DROW = ("| ~~—~~ | c23 + 01B \"Lesson Pages — Simplified Module Menu\" + the overview-tab label row — every learning / success label in `#module-menu-content` is `<h5>` in the colon form; \"We are learning to:\" → `We are learning:` with \"to …\" items (c24); a lesson-page title above a label dropped; the overview tab's labels `<h5>`; the c70 sentence stays `<p>`; the success label's wording kept (no year source) | **SHIPPED round 349 (2026-09-16)** — Chris D10-9, Option A; `Emit_Templates.menu.lesson_label_form` + `ContentConverter.#menuLabelForm`; verifier `_verify_menulabels.cjs` (protected, 91 / 0); FULL regeneration | 715 pages / 319 modules (lesson 410, overview 305; Bilingual 0) | −0.318pp = a NAMED override: lesson half +0.063, overview half −0.375 (BLL 87 pages); ≥75 −39 (named overview pages); every other gate EXACT | `MENULABEL_OFF`; `overview_labels: false` reverts the overview half alone | DECIDED (Chris); the year table + the overview half's measured cost reported |\n")
if "c23 + 01B \"Lesson Pages — Simplified Module Menu\"" not in k:
    assert k.count(DANCHOR) == 1, "KB §D anchor"; k = k.replace(DANCHOR, DROW + DANCHOR, 1); print("KB §D row")
wr(KB, k)

# ---------------------------------------------------------------- 6. loop/README.md rows
RM = os.path.join(PF, "loop", "README.md"); r = rd(RM)
ROW_ANCHOR = "| `_verify_speechbubble.cjs` / `_verify_math.cjs` / `batch_convert.cjs` / `gate_baseline.json` | `CONVERTER_V2/reference/tests/` | Session 13 Round 1"
NEWROWS = ("| `_verify_menulabels.cjs` / `_selftest_core.cjs` / `run_all_gates.sh` / `batch_convert.cjs` / `gate_baseline.json` | `CONVERTER_V2/reference/tests/` | Session 13 Round 2 (engine r349, Chris's D10-9) — the NEW protected verifier (every menu label `<h5>` colon form, no title above a label on a lesson page, no `<p>` between a label and its list; `--selftest` INJECT), the selftest spec + gate runner that carry it, the batch runner with its SECOND race closed (`batch_results.json` atomic + merged), the baseline with the new `menulabels` block; the gate tools are outside git, so these are the durable copies |\n"
           "| `_measure_r349_menuform.py` / `_r349_menuform.{json,log}` / `_r349_splice.py` / `_r349_patch_attrs.py` / `_r349_patch_results_race.py` / `_r349_probe.cjs` / `_r349_probe_run.sh` / `_r349_probe_{off,on}_0*.log` / `_r349_probe_classify.log` / `_r349_on_changed_modules.txt` / `_r349_fullship_par.sh` / `_r349_fullship_run.sh` / `_r349_fullship_regen.log` / `_r349_postship.sh` / `_r349_gates.log` / `_r349_sk_final.json` / `_r349_sk_full.log` / `_r349_sk_movers.{log,json}` / `_r349_selftests.log` / `_r349_verify_menulabels.log` / `_r349_finalise.py` | `CONVERTER_V2/outputs/` | Session 13 Round 2 (r349) — the measurement (residue / wording / titles / overview / the OSSC split), the idempotent splice (proven to reproduce both live files from the HEAD blobs) + its two patches, the 416-module OFF/ON probe and its line-by-line classification, the full-regeneration runner, the gates, the skeleton state + movers decomposition (lesson half vs overview half), the finalise |\n")
if "Session 13 Round 2 (engine r349, Chris's D10-9)" not in r:
    assert r.count(ROW_ANCHOR) == 1, "README anchor"; r = r.replace(ROW_ANCHOR, NEWROWS + ROW_ANCHOR, 1); wr(RM, r); print("README rows")

# ---------------------------------------------------------------- 7. LOOP_STATE.md
LS = os.path.join(HERE, "..", "..", "LOOP_STATE.md"); s = rd(LS); nl = chr(13) + chr(10) if chr(13) + chr(10) in s[:3000] else chr(10)
def L(t): return t.replace(chr(10), nl)
PICK = L("""## Session 13 · Round 2 PICK (engine r349 — D10-9: c23 / 01B lesson-menu labels everywhere) — written before any code, 2026-09-16 21:30 NZST
- **Class:** Chris's D10-9 (Option A, verbatim in "Decisions from Chris (session 10)"); the pre-measurement recorded as "Session 12 · Round 5 PICK-in-progress (engine r348 — D10-9)" carries over unchanged (only the number moved: r348 became the verifier-baseline tooling round). Authority: KB level 1 — constraint 23 (Universal, numbered: "`<h5>` label headings normalised to standard patterns … NOT writer's verbatim text, NOT `<h4>` headings, NOT intermediate `<p>` elements") + 01B 221–246 and the overview-tab row 196–197 — no gold-share test (LOOP §2 amended); the gold's disagreement is a NAMED override.
- **Scope decided by the measurement (`_measure_r349_menuform.py`):** (a) every label `<h5>` in the colon form on lesson AND overview pages; (b) the "We are learning to:" family → `We are learning:` + "to …" items (c24 — the gold's own mechanical re-wording, 30 of 39 checked pages), "We are learning about:" kept; (c) a lesson-page title directly above a label dropped (117 of Claude's 152 titles; the 20 two-column banners and the 15 label-of-list titles kept); (d) the overview tab's labels `<h5>` (D10-9 (f)); (e) the c70 sentence stays `<p>`; (f) the SUCCESS label keeps the writer's wording — the year table is an empty data hook (never re-ask; the review's "owed by Chris" item). Predicted: ≈ −0.1pp named (Chris's estimate); FULL regeneration (the menu is on every page).
- Steps: PICK ✔ · MEASURE ✔ → IMPLEMENT (`menu.lesson_label_form` + env `MENULABEL_OFF`; `ContentConverter.#menuLabelForm`) → the verifier `_verify_menulabels.cjs` → PROBE all 416 → FULL regeneration → gates → movers → finalise → commit.

""")
SEC = L(f"""## Session 13 · Round 2 (engine r349 — D10-9) — what shipped (every learning / success label in the module menu is the KB's `<h5>` colon form)
- **Fix:** `Emit_Templates.menu.lesson_label_form` {{enabled, env MENULABEL_OFF, level 5, role_lexicon, title_lexicon, label_max_words 8, drop_titles, overview_labels,
  colon_form, learning_to_normalise, learning_to_pattern, learning_label, item_prefix, year_table {{}}}}; `ContentConverter.#menuLabelForm(html, isOverview)` — a post-pass
  on every menu pane (the string panes + the `{{cls, html}}` column arrays) after the lesson-repeat copy: a label → `<h5>` with its own attributes (the MTK `<h5 eng>`
  kept — found by the whole-family probe on PNR101), colon form; the "to" family → `We are learning:` + "to …" items lowercased; a lesson-page title directly
  above a label dropped; a sentence / a label-of-list title / a two-column banner untouched. Splice `outputs/_r349_splice.py` (idempotent; reproduces both live
  files from the HEAD blobs) + `_r349_patch_attrs.py`. **A second batch-runner race closed** (`_r349_patch_results_race.py`: `batch_results.json` read torn-tolerant,
  written atomic + merged — 4 of 36 batches had died on it even with the r348 fix; the four re-ran in parallel rc 0).
- **Verifier:** `_verify_menulabels.cjs` (NEW, protected, in `run_all_gates.sh` + the selftest spec): 91 labels / defect 0 over AGH1002 ENGC401 MXFL201 OSSC401
  ANZH101 BLL110 XFUN02 CEDT501 CEDO502; selftest GREEN (16 on ENGC401; injected `<h5>` → `<p>` 0 → 2). It reads `gate_baseline.json.menulabels.per_module` the r348 way.
- **Regeneration:** FULL — probe over ALL 416: OFF = disk 2110/2110, ON = 715 pages / 319 modules (every changed line one of the intended kinds, Bilingual 0);
  36 batches × 4 workers 21:49–21:53 (+ the 4 race batches 21:54–21:55); `_stalecheck.sh` 0 stale; manifest `diff` = exactly the 715 / 319, 0 added / removed.
- **Gates:** skeleton **{SK_B} → {SK_A} (−0.318pp; {SK_B4} → {SK_A4})** = a NAMED KB-over-gold override: 322 moved (114 up / 208 down), EVERY mover inside the
  changed set; **the LESSON half (c23's own scope) +0.063pp** (158 movers; Standard 102 up / 47 down), **the OVERVIEW half Chris chose in D10-9 (f) −0.375pp**
  (164 movers; Standard 3 up / 115 down; BLL alone −474.68 pp-sum, 87 pages — its two-column overview keeps `<p>` labels in the gold); ≥50 {GE50_B} → {GE50_A}
  (9 down / 7 up, named), **≥75 {GE75_B} → {GE75_A}** (39 named overview pages: BLL 32, ENG 6, ANZH105, SCPH301_5), ≥90 {GE90_B} → {GE90_A} (ENGI401_0_0); RAW
  {RAW_B} → {RAW_A}; cs {CS}/{EX}/{MI}, body 180, clean 2080/2103, leak 26/23, tags 9557/9557, every verifier ✓ (the first fully green suite); fast-loop
  re-snapshotted; manifest 2110 / 413; ledger FULL (counter 0, 8 of headroom); feature index rehtml 678 + merge GREEN; 15 selftests GREEN. **{PCT_A}% of achievable**
  (was {PCT_B}%). **The D10-9 estimate was ≈ −0.1pp; the overview half alone measures −0.375pp — reported to Chris in the §5 report; `overview_labels: false` reverts that
  half alone, the lesson half stands on its own.** Not re-asked (§5b) — it is a decided item; the report gives him the one-flag reversal.
- **Recorded:** the success label's wording (the empty year table — a data / KB session); "We are learning about:" kept; the gold's 124 kept titles and its `<p>`
  labels on 480 overview / 72 lesson pages (the override); KB deltas for a KB session (01B's year source; c24's mechanical "to" prefix).
- **Plateau window:** r349's PICK predicted a skeleton move and it moved 0.318pp → the window restarts (0 of 3).

""")
ANCHOR = "## Session 13 · Round 1 (tooling round r348) — what shipped"
if "## Session 13 · Round 2 (engine r349 — D10-9) — what shipped" not in s:
    assert s.count(ANCHOR) == 1; s = s.replace(ANCHOR, SEC + PICK + ANCHOR, 1); print("LOOP_STATE sections")
OLD_P = "- Remaining KB queue (§D):"
NEW_P = (f"- Session 13 Round 2 (engine r349 — Chris's D10-9: every learning / success label in the module menu is the KB's `<h5>` colon form; FULL regeneration of all 416): **SHIPPED 2026-09-16 ≈22:20 (session 13)**. AppVersion 260619.20, CLAUDE.md §9/§11/§14, KB status row 23 + §D, `gate_baseline.json` (skeleton {SK_A} / {GE50_A} / {GE75_A} / {GE90_A} @ {PAIRS}; new `menulabels` block). −0.318pp = a named override (lesson half +0.063, overview half −0.375); {PCT_A}% of achievable; ledger FULL (counter 0)." + nl)
if "- Session 13 Round 2 (engine r349" not in s:
    assert s.count(OLD_P) == 1, "position"; s = s.replace(OLD_P, NEW_P + OLD_P, 1); print("position")
OLD_R = "- s13-r1 (tooling r348)"
i = s.find(OLD_R); assert i > 0, "round log anchor"
NEW_R = (f"- s13-r2 (engine r349, D10-9) · every learning / success label in `#module-menu-content` is the KB's `<h5>` colon form (c23 / 01B) — the \"We are learning to:\" family → `We are learning:` + \"to …\" items, lesson-page titles above a label dropped, the overview tab's labels `<h5>`, the c70 sentence kept; new protected verifier `_verify_menulabels.cjs` (91 / 0); the second batch-runner race closed · SHIPPED 2026-09-16 · FULL regeneration (715 pages / 319 modules changed) · scaffold {SK_B}→{SK_A} (−0.318pp = a NAMED KB-over-gold override: lesson half +0.063, overview half −0.375, BLL 87 pages; ≥75 {GE75_B}→{GE75_A} named; ≥90 {GE90_B}→{GE90_A}; ≥50 {GE50_B}→{GE50_A}) · cs {CS}/{EX}/{MI}, clean 2080/2103, leak 26/23, body 180 EXACT · {PCT_A}% of achievable · commit (see git log) · plateau window restarts (0 of 3)" + nl)
if "- s13-r2 (engine r349" not in s:
    s = s[:i] + NEW_R + s[i:]; print("round log")
wr(LS, s); print("LOOP_STATE.md written")
