#!/usr/bin/env python3
"""ROUND 350 (loop session 14 Round 1 — Chris's D10-3: the dragAndDrop build kickoff, shape (1) the image-pair table → KB 03B
`dragAndDrop images` + the 03B button row) — finalise: changelog, AppVersion (260619.20 → 260619.21), CLAUDE.md §9 / §11 / §14,
gate_baseline.json (raw + the new dragdrop block), KB_AMALGAMATION_STATUS.md (the D10-3 row), loop/README.md rows, LOOP_STATE.md
(what shipped + position + round log). Idempotent; LF kept (the r349 pattern)."""
import io, os, json
ROOT = r"C:\Users\Gavin\TeKura\FINAL_MODULE_DATA"
PF = os.path.join(ROOT, "pageforge-site", "converter-v2")
def rd(p):
    with io.open(p, encoding="utf-8", newline="") as f: return f.read()
def wr(p, s):
    with io.open(p, "w", encoding="utf-8", newline="") as f: f.write(s)

# ---------------------------------------------------------------- 1. BUILD_CHANGELOG.md
CL = os.path.join(PF, "BUILD_CHANGELOG.md"); s = rd(CL)
head = "# BUILD CHANGELOG — Stage 2 (engine + UI)" + chr(10) + chr(10)
ENTRY = """## 2026-09-17 (round 350, build 260619.21) — THE dragAndDrop BUILD KICKOFF, SHAPE 1: THE WRITER'S IMAGE-PAIR TABLE BUILDS THE KB 03B `dragAndDrop images` FORM, AND EVERY BUILT dragAndDrop GAINS THE 03B BUTTON ROW (Chris's decision D10-3, Option A — widget-BUILD rounds inside the loop, one type per kickoff, largest un-built population first; the autonomous loop's session-14 Round 1; a NEW protected verifier `_verify_dragdrop.cjs`; FULL regeneration of all 416 gated dirs; gate-neutral on the skeleton by design (A1 — a build is inside the collapsed widget marker), RAW +0.066pp; 18 hand-off boxes become the KB widget on 17 pages / 17 modules, 54 pre-existing text builds gain the button row)

### 1. WHAT CHANGED, IN ONE LINE

**A writer's `[drag and drop]` whose table pairs an IMAGE with a WORD / sentence on every row — `image | word` (BLL112 "sit / tap / ants …", BLL122, BLL161, BLL125, BLL220, BLL224, BLL230, BLL210, ENFUN02, MXFUN03 ×2, CHFUN05, BLL244's sentences) or `word | image` (BLL146 "sink / see / trip …", BLL130, BLL233, ENFUN04's `[image] url` cells, ENGS201) — now builds the KB 03B "Standard Layout — With images" widget instead of the hand-off box: `<div class="dragAndDrop images" layout="standard">`, the TEXT always on the fixed question side (`col-7 questionContainer`, one `.question` per row) and the IMAGES as the draggable items (`col-5 ddContainer`: a `.drop` per row, a `.drag` holding the image per row, option = the row index = the answer key) — 03B's placement rule whichever way round the writer typed the columns; the image named `iStock-{id}.jpg` from the URL (any other host → the r278 URL-slug placeholder), Mode P/D through the r240 alt rider (the gold's BLL146 alts ARE the iStock titles), `margB0`, NO `loading="lazy"` (c83 — proven 0 by the verifier); a header / column-label row is dropped (its instruction rides along as the Writers Note — BLL112's "Correct answer - can we jumble them up though please." + "Arrow added to image"); and EVERY built standard dragAndDrop — the r69 text form too — now closes with 03B's `activityButton` row (Reset / Undo hidden / Check answers hidden; the gold ships it on 473 of its 517 standard D&Ds, 0.92).** Never half-built: a red run in the TEXT cell (BLL226's answer word inside a sentence, BLL254's `[correct]`, BLL272's `[kurī]` audio-words, CEDK102's `[Body]`), a repeated label (CEDO105's `under / over / through` = a category sort), a ragged row (ENGJ102's adjective list), prose beside the image (TEFUN08), a second table, an extraType, a harvested media item → the hand-off box as today. Authority: KB 03B (level 1) + D10-3 (A1 — the writer's tag is the target; the gold's substitutions BLL112 / ENFUN04 `noBG column` are recorded, never chased; BLL146 is the exact KB form).

### 2. THE MEASUREMENT (`outputs/_r350_ddcolumn.json` — every dragAndDrop bundle's table over the 297 table-carrying modules, 882 bundles; the session-13 census re-classified by AUTHORING SHAPE)

- The image family (a URL in a cell or a harvested media item, declined) = 321 bundles / 257 pages / 175 modules, and it is NOT one shape: `image | text` 2-column 44 (this round's shape after the fences: 21 sites / 20 pages / 20 modules — 20 clean + BLL112's asset note; Standard 14, Fundamentals 6), `[audio] | image | answer` 3-column 36 / 15 modules (r342's audio-word shape — the gold builds `audioButton` + `wordDrag`, a different widget), the image COLUMN-SORT (`Short vowels | Long vowels` + `word – url` cells → `layout="column"` + `images`) **13 clean** (BLL140 · BLL160 · CEDO102 · ENGC202 · BLL161 · BLL170 · BLL220 · BLL230 · ENGC102 · BLL150 · BLL210 ×2 · BLL221 — under the 20-site floor, recorded for a later round), 66 prose-plus-images with no table, 25 two-table bundles, the rest long-tail.
- Of the 21: **ENGJ102 1.0's `Image | Sentence` table carries a 5th one-cell row of draggable adjectives (a FIB shape — a correct decline), BLL266 has no Claude dir (a forward guarantee) → 18 sites on the corpus + 1 guaranteed.** The gold's form for the 18: `dragAndDrop images` standard (BLL146 exact), `noBG column` with the images as column labels (BLL112 / ENFUN04 — A1 substitutions), `autoCheck noBG` standard.
- The button row: gold standard D&Ds 517, with the `activityButton reset` row **473 (0.92)**; the r69 text form shipped 54 builds without it.

### 3. THE MECHANISM

- `InteractiveBuilder`: the dispatch gains `?? this.#dragAndDropImages(...)` — tried ONLY where the r69 `#dragAndDrop` returned null (it bails on any URL), so the working half is unchanged BY CONSTRUCTION (the r276 order); `#dragAndDropImages` classifies the single 2-column table row by row (exactly one image cell + one text cell, the image column fixed), drops a first no-URL row as the header (its red text → a note when it is an instruction, silent when it is a bare column label "Image | words" or a bracket token `[correct answers]` — `#ddIsNote`), tolerates the writer's own `[image]` / `[photo]` tag (+ a stray bracket, the r174 class — BLL266's `[🔴image]🔴`) and a `[media item N]` reference in the image cell, surfaces any other red there as a note (BLL112), and emits 03B; `#ddImage` renders the drag image in the run's image mode through `MediaBuilder.FinishImg` with the URL (alt = the verified acks title, else the URL-slug title); `#ddClose` emits the button row for both forms.
- Data `Emit_Templates.interactive_builders.dragAndDrop.images` {enabled, env `DDIMAGES_OFF`, open, mid, drag, image_mode_D / P / P_comment, filename_istock, header_row_skip, image_tag_pattern} + `.button_row` {enabled, env `DDBUTTONS_OFF`, close_inner, html, close_outer}. `DDIMAGES_OFF=1 DDBUTTONS_OFF=1` = the r349 corpus byte-for-byte (2110 / 2110, in-memory probe over all 416).

### 4. PROOF + PROTECTED GATES (FULL regeneration of all 416 gated dirs — 36 batches, 4 workers, ALL rc 0 first time; the r348 / r349 race fixes held; `_stalecheck.sh` 0 stale)

- **The in-memory OFF/ON probe (`_r350_probe.cjs`, all 416):** OFF = disk **2110 / 2110**; ON = **60 pages / 54 modules** — 18 image-pair sites built on 17 pages (36 hand-off wrappers gone, 2 Writers Notes added) + 72 button rows (18 new + 54 pre-existing text builds), 0 `loading="lazy"` inside any widget, 0 other change kinds (`_r350_probe_classify.log`). **The regeneration changed EXACTLY those 60 pages / 54 modules (`_content_manifest.py diff`: 60 changed / 0 added / 0 removed), every one byte-identical to the probe's ON page.**
- **Skeleton (PRIMARY): SCAFFOLD mean 50.965% → 50.965% (50.9655 → 50.9655, 0 pages moved) / ≥50% 1072 / ≥75% 159 / ≥90% 14 / skipped 0 @ 1955 — IDENTICAL page-for-page; RAW 35.049% → 35.115% (+0.066pp, the built widgets' insides)** (state `outputs/_r350_sk_final.json`, FRESH; movers `_r350_sk_movers.log`: 0). As D10-3 recorded: a build is invisible to the skeleton by design — the widget subtree (hand-off box or built widget, button row included) collapses to one marker. **The PICK's "small positive move" prediction was wrong for that reason; the round is gate-neutral on the skeleton and counts by the dashboard's *Still a box* test (18 sites, the dashboard regeneration is the next session's first step).**
- compare_structure exact **11464** / EXTRA **175** / missing **607** EXACT · clean **2080/2103 = 98.9%** / leak **26/23** EXACT · body **180** EXACT · tags **9557/9557** · flipCard TOTAL 61 / divergence 0 · speechBubble 4 (at baseline) · math 322/323 (at baseline) · menulabels 91 / 0 · mtkQuiz 17 / 0 · modal 0 · index-sync · entry-parity PASS — **every RESULT line ✓.**
- **NEW protected gate `_verify_dragdrop.cjs`** (in `run_all_gates.sh`, `_selftest_core.cjs` INJECT spec — selftest GREEN: LIVENESS 2 widgets on BLL146 + ENGJ102, DETECTION 0 → 6 with an injected `option="99"` drag + a lazy image): the gate set BLL146 BLL112 ENFUN04 CHFUN05 BLL266 MXFUN03 BLL244 ENGJ102 ARFUN03 ENFUN01 → **13 widgets (images 8) / 76 drags / defect 0**; over the WHOLE changed family (the 54 modules) → see `_r350_verify_dragdrop_family.log` (defect 0 expected — every widget the same two builders).

### 5. NAMED, RECORDED, NOT CHASED

- The gold's widget SUBSTITUTIONS on the built pages (BLL112 / ENFUN04 `noBG column`, `autoCheck` modifiers) — A1. The KB's optional `autoCheck` / `noShuffle` / `noBG` are the developer's editorial choice (no writer signal).
- ARFUN03 0.0's r69 build reads a 2-column CATEGORY table (`Locomotor | Non-locomotor` header + words) as an N:N match — a pre-existing r69 defect the header-row test of the column-sort shape (shape 4) will fix; recorded for that round.
- The next shapes of the kickoff, sized: (2) the `[correct answers]` category sort 40 / 26, (3) the one-row word tiles 39 / 29, (4) the clean category sorts 22 (+ the image column-sort 13 rides with it), then clickDrop.

**Ledger:** FULL ship (round 350; counter reset) · data `Emit_Templates.interactive_builders.dragAndDrop.images` + `.button_row` · env `DDIMAGES_OFF` / `DDBUTTONS_OFF` · engine `InteractiveBuilder.js` (`#dragAndDropImages`, `#ddImage`, `#ddClose`, `#ddIsNote`, the dispatch + the r69 close) · gate tools (outside git, mirrored to `loop/`) `_verify_dragdrop.cjs` (NEW), `_selftest_core.cjs`, `run_all_gates.sh`, `gate_baseline.json` · tools `outputs/_r350_splice.py`, `_r350_patch_residual.py`, `_r350_patch_residual2.py`, `_r350_patch_notes.py`, `_r350_dump.cjs`, `_r350_probe.cjs` (+ `_r350_probe_run.sh`, `_r350_probe_run_on.sh`), `_r350_probe_classify.log`, `_r350_on_changed_{pages,modules}.txt`, `_r350_fullship_par.sh` / `_r350_fullship_run.sh`, `_r350_postship.sh`, `_r350_sk_movers.py`, `_r350_finalise.py` · AppVersion 260619.21.

"""
if "round 350, build 260619.21" not in s:
    assert s.startswith(head), "changelog head"
    s = head + ENTRY + s[len(head):]
    wr(CL, s); print("changelog: r350 entry prepended")

# ---------------------------------------------------------------- 2. Config.js
P = os.path.join(PF, "app", "js", "Config.js"); s = rd(P)
if '"260619.21"' not in s:
    old = '\tstatic AppVersion = "260619.20";'
    assert s.count(old) == 1, "Config anchor"
    s = s.replace(old, '\t// ROUND 350 (260619.21): the dragAndDrop build kickoff, shape 1 — the image-pair table builds the KB 03B images form; the 03B button row on every built dragAndDrop (Chris\'s D10-3).\n' + '\tstatic AppVersion = "260619.21";', 1)
    wr(P, s); print("Config.js: 260619.21")

# ---------------------------------------------------------------- 3. CLAUDE.md
P = os.path.join(PF, "CLAUDE.md"); s = rd(P)
if "ROUND 350 BASELINE" not in s:
    OLD9 = "| **Skeleton (PRIMARY)** | `python3 _skeleton_compare.py` | **ROUND 349 BASELINE (every learning / success label"
    assert s.count(OLD9) == 1, "§9 anchor"
    NEW9 = ("| **Skeleton (PRIMARY)** | `python3 _skeleton_compare.py` | **ROUND 350 BASELINE = r349 page-for-page (the dragAndDrop build kickoff shape 1 — the image-pair table builds the KB 03B `dragAndDrop images` form, and every built dragAndDrop gains the 03B button row; Chris's D10-3; FULL regeneration of all 416 gated dirs, ledger counter 0; a build is INSIDE the collapsed widget marker, so the skeleton is gate-neutral by design): SCAFFOLD mean 50.965% / >=50% 1072 / >=75% 159 / >=90% 14 / skipped 0 @ 1955 — 0 pages moved; RAW 35.049% → 35.115% (+0.066pp)** (state `outputs/_r350_sk_final.json`, FRESH) = **55.5% of achievable** (ceiling 91.9%). cs 11464 / 175 / 607, clean 2080/2103, leak 26/23, body 180 EXACT; the NEW protected `_verify_dragdrop.cjs` 13 widgets / defect 0. Older r349 text: **ROUND 349 BASELINE (every learning / success label")
    s = s.replace(OLD9, NEW9, 1)
    OLDA = "Adjunct verifiers (run when you touch a widget): `_verify_math.cjs`"
    assert s.count(OLDA) == 1, "adjunct anchor"
    s = s.replace(OLDA, "Adjunct verifiers (run when you touch a widget): `_verify_dragdrop.cjs` (round 350 — a PROTECTED gate in `run_all_gates.sh`: every built dragAndDrop is the KB 03B standard form — question / drop / drag counts equal, options paired, the activityButton row, no raw `[tag]`, no `loading=\"lazy\"`, an images widget's drags each one `<img>`), `_verify_math.cjs`", 1)
    OLD11 = "| `MENULABEL_OFF` | 349 |"
    assert s.count(OLD11) == 1, "§11 anchor"
    NEW11 = ("| `DDIMAGES_OFF` / `DDBUTTONS_OFF` | 350 | **THE dragAndDrop BUILD KICKOFF, SHAPE 1 — the writer's IMAGE-PAIR table builds the KB 03B `dragAndDrop images` standard form; every built standard dragAndDrop gains the 03B `activityButton` row** (Chris's D10-3, Option A — widget-BUILD rounds, one type per kickoff; the autonomous loop's session-14 Round 1; **FULL regeneration of all 416 gated dirs**). Data `interactive_builders.dragAndDrop.images` {enabled, env, open, mid, drag, image_mode_D/P/P_comment, filename_istock, header_row_skip, image_tag_pattern} + `.button_row` {enabled, env, close_inner, html, close_outer}; engine `InteractiveBuilder.#dragAndDropImages` (tried only where the r69 `#dragAndDrop` declined — a single 2-column table whose every row pairs ONE image URL with ONE plain-text label, the image column fixed; the TEXT is always the question side, the IMAGES the drags, option = row index; a first no-URL row is the header, its instruction a Writers Note; the image cell's own `[image]` tag / `[media item N]` / a stray bracket tolerated, any other red there a note; null on a red text cell, a repeated label, a ragged row, prose beside the image, a second table, an extraType, harvested media), `#ddImage` (Mode P/D through `FinishImg` with the URL → the slug alt), `#ddClose` (the button row for both forms), `#ddIsNote`. Probe OFF = disk 2110/2110, ON = 60 pages / 54 modules = the regenerated set exactly: 18 image-pair sites built on 17 pages / 17 modules (BLL112 BLL122 BLL125 BLL130 BLL146 BLL161 BLL210 BLL220 BLL224 BLL230 BLL233 BLL244 CHFUN05 ENFUN02 ENFUN04 ENGS201 MXFUN03; BLL266 = a forward guarantee, no Claude dir), 72 button rows (18 new + 54 r69 text builds), 0 lazy. Verifier `_verify_dragdrop.cjs` (NEW, protected; 13 widgets / defect 0; selftest GREEN). Skeleton IDENTICAL page-for-page (a build is inside the collapsed widget marker), RAW +0.066pp; every other gate EXACT. | `DDIMAGES_OFF=1` keeps the image-pair tables as hand-off boxes; `DDBUTTONS_OFF=1` restores the r69 `close` (no button row) — both set = the r349 corpus byte-for-byte. |\n"
             "| `MENULABEL_OFF` | 349 |")
    s = s.replace(OLD11, NEW11, 1)
    OLD14 = "- **Build:** `260619.20` (round 349"
    assert s.count(OLD14) == 1, "§14 anchor"
    NEW14 = ("- **Build:** `260619.21` (round 350 — **the dragAndDrop build kickoff, shape 1: the writer's IMAGE-PAIR table builds the KB 03B `dragAndDrop images` form, and every built standard dragAndDrop gains the 03B button row** (Chris's D10-3, Option A; `InteractiveBuilder.#dragAndDropImages` / `#ddClose` behind `Emit_Templates.interactive_builders.dragAndDrop.images` + `.button_row`, env `DDIMAGES_OFF` / `DDBUTTONS_OFF`; a NEW protected verifier `_verify_dragdrop.cjs` (13 widgets / defect 0, selftest GREEN); the autonomous loop's session-14 Round 1; **FULL regeneration of all 416 gated dirs — the ledger's full-ship backstop, scoped counter 0**; 36 batches all rc 0 first time). **ROUND 350 BASELINE = r349 page-for-page: SCAFFOLD mean 50.965% / ≥50% 1072 / ≥75% 159 / ≥90% 14 / skipped 0 @ 1955 (0 pages moved — a build is inside the collapsed widget marker, gate-neutral by design); RAW 35.049% → 35.115% (+0.066pp)** (state `outputs/_r350_sk_final.json`, FRESH) = **55.5% of achievable** (ceiling 91.9%). cs exact **11464** / EXTRA **175** / missing **607**; clean **2080/2103** / leak **26/23**; body **180**; math 322/323; speechBubble 4; menulabels 91 / 0 — all EXACT; every RESULT line green; 16 selftests GREEN. Corpus 2110 pages / 416 modules, 0 stale, **60 pages / 54 modules changed, 0 added/removed** (18 image-pair sites built on 17 pages, 72 button rows). **Plateau window: a build round — the D10-3 reading counts it by the dashboard's *Still a box* count (18 sites built, the dashboard regeneration = the next session's first step).**\n"
             "- **Build:** `260619.20` (round 349")
    s = s.replace(OLD14, NEW14, 1)
    wr(P, s); print("CLAUDE.md: §9 / adjunct / §11 / §14")

# ---------------------------------------------------------------- 4. gate_baseline.json (textual — keep the file's own formatting)
P = os.path.join(ROOT, "CONVERTER_V2", "reference", "tests", "gate_baseline.json"); s = rd(P)
d = json.loads(s)
if "dragdrop" not in d:
    d["skeleton"]["raw_mean_pct"] = 35.115
    d["skeleton"]["_note_r350"] = "Round 350: the dragAndDrop build kickoff shape 1 + the 03B button row — SCAFFOLD identical page-for-page to r349 (a build is inside the collapsed widget marker); RAW 35.049 → 35.115. State outputs/_r350_sk_final.json."
    d["dragdrop"] = {"widgets": 13, "images": 8, "defect": 0, "per_module": {},
                     "_note": "Round 350 — _verify_dragdrop.cjs over BLL146 BLL112 ENFUN04 CHFUN05 BLL266 MXFUN03 BLL244 ENGJ102 ARFUN03 ENFUN01: 13 widgets (8 images form) / 76 drags / defect 0 — the KB 03B standard form (counts equal, options paired, the activityButton row, no raw [tag], no loading=lazy, one <img> per images drag). per_module is the r348 baseline table (✓ at-or-under, ✗ above); empty = every module at 0."}
    wr(P, json.dumps(d, indent=2, ensure_ascii=False) + "\n"); print("gate_baseline.json: raw + dragdrop block")

# ---------------------------------------------------------------- 5. KB_AMALGAMATION_STATUS.md — the D10-3 row
P = os.path.join(ROOT, "KB_AMALGAMATION_STATUS.md"); s = rd(P)
OLDK = "| **AUTHORISED — Chris D10-3 (2026-09-16), queued item 7 (after the structure rounds)** |"
if OLDK in s and "r350" not in s.split(OLDK)[0][-400:]:
    s = s.replace(OLDK, "| **AUTHORISED — Chris D10-3 (2026-09-16), queued item 7; IN PROGRESS — dragAndDrop kickoff shape 1 SHIPPED r350 (2026-09-17: the image-pair table → 03B `dragAndDrop images`, 18 sites / 17 modules + the 03B button row on every built D&D; new gate `_verify_dragdrop.cjs`); shapes 2–4 next** |", 1)
    wr(P, s); print("KB status: D10-3 row → IN PROGRESS r350")

# ---------------------------------------------------------------- 6. loop/README.md rows
P = os.path.join(PF, "loop", "README.md"); s = rd(P)
if "_r350_splice.py" not in s:
    A = "| `_verify_menulabels.cjs` / `_selftest_core.cjs` / `run_all_gates.sh` / `batch_convert.cjs` / `gate_baseline.json` | `CONVERTER_V2/reference/tests/` | Session 13 Round 2"
    assert s.count(A) == 1, "README anchor"
    ROWS = ("| `_verify_dragdrop.cjs` / `_selftest_core.cjs` / `run_all_gates.sh` / `gate_baseline.json` | `CONVERTER_V2/reference/tests/` | Session 14 Round 1 (engine r350, Chris's D10-3 — the dragAndDrop build kickoff, shape 1) — the NEW protected verifier (every built dragAndDrop is the KB 03B standard form: a questionContainer / ddContainer pair, drop + drag containers, questions = drops = drags, every option paired, the activityButton row, no raw `[tag]`, no `loading=\"lazy\"`, an images widget's drags each one `<img>`; `--selftest` INJECT), the selftest spec + gate runner lines, the baseline's `dragdrop` block |\n"
            "| `_r350_splice.py` / `_r350_patch_residual.py` / `_r350_patch_residual2.py` / `_r350_patch_notes.py` / `_r350_dump.cjs` / `_r350_probe.cjs` / `_r350_probe_run.sh` / `_r350_probe_run_on.sh` / `_r350_probe_{off,on}_0*.log` / `_r350_probe_classify.log` / `_r350_on_changed_{pages,modules}.txt` / `_r350_fullship_par.sh` / `_r350_fullship_run.sh` / `_r350_fullship_regen.log` / `_r350_manifest_diff.log` / `_r350_manifest_changed.txt` / `_r350_postship.sh` / `_r350_gates.log` / `_r350_sk_final.json` / `_r350_sk_full.log` / `_r350_sk_movers.{py,log}` / `_r350_verify_dragdrop_family.log` / `_r350_selftests.log` / `_r350_finalise.py` | `CONVERTER_V2/outputs/` | Session 14 Round 1 (r350) — the idempotent splice (data `images` + `button_row`, engine `#dragAndDropImages` / `#ddImage` / `#ddClose` / `#ddIsNote`) + its three patches (the red-run residual, the stray bracket / bullet + `[photo]`, the note classifier), the bundle-table dump, the 416-module OFF/ON probe and its classification, the full-regeneration runner, the manifest diff, the gates, the skeleton state + movers (0), the family verifier, the finalise |\n")
    s = s.replace(A, ROWS + A, 1)
    wr(P, s); print("README: r350 rows")

# ---------------------------------------------------------------- 7. LOOP_STATE.md
P = os.path.join(ROOT, "LOOP_STATE.md"); s = rd(P)
if "## Session 14 · Round 1 (build round r350 — D10-3 shape 1) — what shipped" not in s:
    A = "## Session 14 · Round 1 PICK (build round r350"
    assert s.count(A) == 1, "LOOP_STATE PICK anchor"
    SHIPPED = """## Session 14 · Round 1 (build round r350 — D10-3 shape 1) — what shipped (the writer's image-pair table builds the KB 03B `dragAndDrop images` form; every built dragAndDrop gains the 03B button row)
- **Shipped 2026-09-17 ≈00:10 NZST (session 14).** AppVersion 260619.21, changelog entry r350, CLAUDE.md §9 / adjunct verifiers / §11 / §14, `gate_baseline.json` (raw 35.115 + a NEW `dragdrop` block), KB status D10-3 row → IN PROGRESS, loop/README rows; FULL regeneration of all 416 gated dirs (36 batches, 4 workers, ALL rc 0 first time — the r348 / r349 race fixes held, 0 re-runs), ledger record-full (counter 0).
- **Built:** the in-memory probe over all 416 — OFF (`DDIMAGES_OFF=1 DDBUTTONS_OFF=1`) = disk 2110/2110; ON = 60 pages / 54 modules = the regenerated set EXACTLY (manifest diff 60 changed / 0 added / 0 removed, every page byte-identical to the probe): **18 image-pair sites built on 17 pages / 17 modules** (BLL112 BLL122 BLL125 BLL130 BLL146 BLL161 BLL210 BLL220 BLL224 BLL230 BLL233 BLL244 CHFUN05 ENFUN02 ENFUN04 ENGS201 MXFUN03 — Standard 9 sites, Fundamentals 5, Inquiry-folder BLL 4; BLL266 builds but has no Claude dir = a forward guarantee; ENGJ102 1.0 declines correctly — its 5th row is a one-cell adjective list, a FIB shape), 36 hand-off wrappers gone, 2 Writers Notes added (BLL112's "Correct answer - can we jumble them up though please." + "Arrow added to image"; BLL122's header instruction), **72 button rows** (18 new + the 54 r69 text builds), 0 `loading="lazy"` inside any widget.
- **Gates:** skeleton IDENTICAL page-for-page (SCAFFOLD 50.9655 → 50.9655, 0 movers, 1072 / 159 / 14 @ 1955; RAW 35.049 → 35.115 = +0.066pp — the built widgets' insides); cs 11464 / 175 / 607, clean 2080/2103, leak 26/23, body 180, tags 9557/9557, flipCard 61 / div 0, speechBubble 4 (at baseline), math 322/323 (at baseline), menulabels 91 / 0, mtkQuiz 17 / 0 — ALL EXACT, every RESULT line ✓; the NEW protected `_verify_dragdrop.cjs` 13 widgets (8 images) / 76 drags / defect 0 on its gate set, selftest GREEN (LIVENESS 2, DETECTION 0 → 6); 16 selftests GREEN. **The PICK's "small positive skeleton move" prediction was WRONG — a build (and the button row) sits INSIDE the collapsed widget marker, exactly as D10-3's §4 reading says; the round is gate-neutral on the skeleton and is judged by the dashboard's *Still a box* count.**
- **The plateau / "moved" test:** 18 sites built < the 20-site "moved" threshold of the D10-3 reading (19 with BLL266's forward guarantee). The dashboard was NOT regenerated (Chris's `/loop-stop` arrived at the gates) — **the next session's first step regenerates `COVERAGE_DASHBOARD.md` (`_r350_dashboard_run.sh` pattern → `_r351_…`) and records dragAndDrop un-built 824 → 806 expected.** Plateau window: build rounds are outside the skeleton window (§4 amendment); provisionally counted as "moved by 18" — reported to Chris as 2 short of the line, not hidden.
- **Lessons for the tools:** (1) the census's clipped cells (80 chars) over-counted the clean shape by 1 (ENGJ102's ragged 5th row) — count shapes on the live bundle dump (`_r350_dump.cjs`), not the clipped census; (2) native Windows node cannot open the `CONVERTER_V2/app` symlink (EACCES) — every engine tool runs under WSL (`wsl.exe -e bash -lc 'cd /mnt/c/… && …'`); the health check's "native toolchain OK" means node/python exist, not that the symlinks resolve; (3) a `node --check` temp file needs a `.js` extension; (4) a heredoc through Git Bash still eats `\\u{…}` / `\\[` — patch scripts are written with the editor (the r349 lesson, re-learned); (5) the `Read` tool on any file under `pageforge-site/` auto-attaches the ~970 KB CLAUDE.md into context — read repo files with bash (`sed -n`), never the Read tool.
- **Recorded, not chased:** the gold's substitutions on the built pages (BLL112 / ENFUN04 `noBG column`, the `autoCheck` modifiers — A1); ARFUN03 0.0's r69 build reads a 2-column CATEGORY table as an N:N match (a pre-existing r69 defect — the column-sort shape's header-row test fixes it); the image column-sort shape 13 clean (under the floor, rides with shape 4); the `[audio] | image | answer` phonics shape 36 / 15 = r342's audio-word widget (a different type).

"""
    s = s.replace(A, SHIPPED + A, 1)
    # position
    B = "- Remaining KB queue (§D): stickyNav (BLOCKED"
    assert s.count(B) == 1, "position anchor"
    s = s.replace(B, "- Session 14 Round 1 (build round r350 — Chris's D10-3, the dragAndDrop kickoff shape 1: the image-pair table → the KB 03B `dragAndDrop images` form + the 03B button row on every built D&D; FULL regeneration of all 416): **SHIPPED 2026-09-17 ≈00:10 (session 14)**. AppVersion 260619.21, CLAUDE.md §9/§11/§14, KB status D10-3 row, `gate_baseline.json` (raw 35.115; new `dragdrop` block). Skeleton identical page-for-page (a build is inside the widget marker), RAW +0.066pp; 18 sites built / 17 modules; new gate `_verify_dragdrop.cjs` (16 selftests). Dashboard regeneration deferred to the next session (Chris's `/loop-stop`).\n" + B, 1)
    # round log
    C = "- s13-r3 (build round r350, D10-3 dragAndDrop kickoff) · MEASURED, not started"
    assert s.count(C) == 1, "round log anchor"
    s = s.replace(C, "- s14-r1 (build round r350, D10-3 dragAndDrop kickoff shape 1) · the writer's IMAGE-PAIR table (`image | word` / `word | image`, one image URL + one label per row) builds the KB 03B `dragAndDrop images` standard form (text = questions col-7, images = drags col-5, option = row index; header row dropped, its instruction a Writers Note; the writer's `[image]` tag / a stray bracket / `[media item N]` tolerated) + the 03B `activityButton` row on EVERY built standard dragAndDrop (the r69 text form included; gold 0.92); NEW protected verifier `_verify_dragdrop.cjs` · SHIPPED 2026-09-17 · FULL regeneration (60 pages / 54 modules changed: 18 image-pair sites built on 17 pages / 17 modules + 72 button rows) · skeleton IDENTICAL page-for-page (a build is inside the collapsed widget marker), RAW 35.049→35.115 (+0.066) · every other gate EXACT · 55.5% of achievable · dashboard test: 18 sites (2 short of the 20-site \"moved\" line; the dashboard regeneration deferred to the next session) · commit (see git log)\n" + C, 1)
    wr(P, s); print("LOOP_STATE.md: what shipped + position + round log")
print("finalise done")
