#!/usr/bin/env python3
"""ROUND 352 (loop session 15 Round 2 — a built CAROUSEL never discards the writer's words: the heading-after-table boundary +
the table-slides path's leading / trailing members) — finalise: changelog, AppVersion (260619.22 → 260619.23), CLAUDE.md §9 /
§11 / §14, gate_baseline.json (skeleton, compare_structure, body_compare, math), loop/README.md rows, LOOP_STATE.md (what shipped
+ position + round log). Idempotent; LF kept (the r351 pattern)."""
import io, os, json
ROOT = r"C:\Users\Gavin\TeKura\FINAL_MODULE_DATA"
PF = os.path.join(ROOT, "pageforge-site", "converter-v2")
def rd(p):
    with io.open(p, encoding="utf-8", newline="") as f: return f.read()
def wr(p, s):
    with io.open(p, "w", encoding="utf-8", newline="") as f: f.write(s)

# ---------------------------------------------------------------- 1. BUILD_CHANGELOG.md
CL = os.path.join(PF, "BUILD_CHANGELOG.md"); s = rd(CL)
head = "# BUILD CHANGELOG — Stage 2 (engine + UI)" + chr(10) + chr(10)
ENTRY = """## 2026-09-17 (round 352, build 260619.23) — A BUILT CAROUSEL NEVER DISCARDS THE WRITER'S WORDS: A SECTION HEADING AFTER THE SLIDE TABLE ENDS THE CAROUSEL (the scanner's heading-after-table rule gets its own exemption list — the slideshow types were swallowing the whole rest of the page), AND THE TABLE-SLIDES CAROUSEL KEEPS ITS LEADING / TRAILING PARAGRAPHS OR DECLINES (the r351 members discipline on the r279 path; the autonomous loop's session-15 Round 2; FULL regeneration of all 416 — 126 pages / 74 modules: 82 pages regain the section the carousel had eaten, 44 pages' carousels revert to the honest hand-off box; compare_structure exact +143, the math verifier's one baseline defect (PES1007) CLEARED, skeleton +0.0005pp with the dips named, body +2 named)

### 1. WHAT CHANGED, IN ONE LINE

**A `[carousel]` whose slides are a TABLE used to own everything the writer typed after it until the next absolute terminator — the section heading, its paragraphs, lists, images, videos, the next table, the rest of the page (AGH1005 2.0 `[H3]` "Parts of a plant" + nine paragraphs; AGH1009 5.0's four h3 sections; XTAS102 3.0's seven titled tables) — because the slideshow types were EXEMPT from `heading_terminates_after_table` through the shared body-exemption list and `slideshow_heading_internal` forced every heading internal; and the r279 table-slides builder built the slides from the tables alone and dropped every other member without a trace.** Measured with the r351 method generalised (`_measure_r352_widgetloss.cjs`: every member text run of ≥ 3 words checked against the assembled page's visible text, confirmed against the disk pages): **206 built carousels on 171 pages / 109 modules were silently dropping writer text the gold keeps as free body on 167 of them.** Now (a) an `[H2]`–`[H5]` after a carousel's captured table ENDS the bundle (`member_rule.heading_terminates_after_table_exempt_types` = `["rotateBanner"]` — the heading rule's own list; the body rule's list is unchanged, a trailing `[body]` is still a caption), so the section renders as ordinary page content exactly where the gold puts it; and (b) `#carouselTableSlides` keeps the members the slides did not consume: a black paragraph or a `[body]` with words before the first table renders through the free-body block emitter BEFORE the carousel (CHFUN06's five "Watch the video…" sentences — the gold's `<p>` before each carousel), one after the last table renders AFTER it (the OSGM501-01 trailing-caption precedent, lists intact); blank lines and instruction-class tags are skipped; a developer-cue paragraph (CS: / Dev: / Note:) declines; **anything else** — a heading when (a) is off, an image / video / other tag, words between the slide tables, a table beyond the slides — cannot be rendered from inside the widget seam, so the build DECLINES and the hand-off box keeps every member (never half-build). Before this round the D10-3 build queue was re-measured and found EXHAUSTED at the 20-site floor for every widget type (§2 below).

### 2. THE MEASUREMENT

- **The D10-3 kickoff queue (measured first, exhausted):** clickDrop 323 un-built (`_r352_clickdrop_declines.log`, `_r352_cdmembers.json` — the largest coherent shapes: the horizontal heading / link / words table 17, the image-button rows 13; 28 XDLS "tag + [image]" boxes carry no content; 50 BLL phonics `[Clickdrop N Image] same image from BLL110` reference a sibling module), carousel (`_r352_carmembers.json` — 65 `[embed book 1]` reading-book requests are external assets; the rest ≤ 10 per shape), accordion / flipCard / modal / tabs (`_r352_wshapes.log` — ≤ 11 per shape; the flipCard 3×3 word grids have no backs), selfCheck (`_r352_scshapes.log` — the BLL typing quiz, image + audio, ≤ 15): **no widget type has a derivable un-built authoring shape ≥ 20 sites.**
- **The widget text-loss census (`_measure_r352_widgetloss.cjs` over all 416 → `_r352_widgetloss_pre.json`; confirmed on disk by 5-word prefix, `_r352_widgetloss_confirm.log`):** 437 of 2553 built widgets drop ≥ 1 member run; confirmed carousel **206 builds / 171 pages / 109 modules (gold keeps the text on 167)**, flipCard 63 / 51 / 42 (45), modal 39 / 32 / 20 (34), accordion 27 / 27 / 19 (10), clickDrop 17 / 15 / 14 (10), dropDown 12 / 12 / 10, speechBubble 5, tabs 4, hintSlider 4; dragAndDrop 0 after r351.
- **The lossy carousels decomposed (`_r352_carousel_trailing.log`):** a trailing heading after the table 23 + mixed, a trailing `[body]` / black paragraph 73 (first trailing member `[body]` 54 / black 19), leading `[body]` / black 8, trailing media 10, the loss INSIDE the table (a dropped title / label row — OSGM301 1.0's "What are the different ways people play games?" = the gold's `<h3>`) 44, no table at all (the video / prose carousels) 80. A heading BETWEEN tables in 11 bundles (XTAS102 3.0 = the gold's seven separate h4 carousels — the cut is right there too).
- **After the round (`_r352_widgetloss_post.log`):** carousel lossy builds **231 → 110** (pages 188 → 93; built 605 → 563), every other type unchanged — the residue is the in-table and the no-table sub-classes, the next rounds.

### 3. THE MECHANISM

- `InteractiveScanner.#swallowMembers` — the table-data section-break block: `hExempt` reads `member_rule.heading_terminates_after_table_exempt_types` when present (else the shared body list — byte-identical when the key is absent or `CARHEADEND_OFF` is set); the body rule keeps its own list. Data `Interactive_Boundary_ChildTag_Bank.json` `_meta.member_rule.heading_terminates_after_table_exempt_types: ["rotateBanner"]`.
- `InteractiveBuilder.#carouselTableSlides` — after the slides render and the leak guard passes: the members before the first table and after the last table are walked in document order (black / `[body]` with words → `renderBlock`, the invocation tag's own words → a paragraph before; instruction-class → skipped; a developer cue → null; anything else → null); words between the slide tables → null. `const html` became `let html` (the first probe declined every candidate on "Assignment to constant variable" — caught by the probe's build notes). Data `Emit_Templates.interactive_builders.carousel.table_slides.members` {enabled, env `CARMEMBERS_OFF`, note_cue_pattern}.
- `CARHEADEND_OFF=1 CARMEMBERS_OFF=1` = the r351 corpus byte-for-byte (2110 / 2110, the in-memory probe over all 416).

### 4. PROOF + PROTECTED GATES (FULL regeneration of all 416 gated dirs — 36 batches, 4 workers, ALL rc 0; `_stalecheck.sh` 0 stale)

- **The in-memory OFF/ON probe (`_r352_probe.cjs`, all 416; `_r352_probe_classify.log`):** OFF = disk **2110 / 2110**; ON = **126 pages / 74 modules** = the regenerated set EXACTLY (`_content_manifest.py diff` 126 changed / 0 added / 0 removed; every page byte-identical to the probe): **82 pages keep their carousel and regain the eaten text (670 text runs restored)**, 44 pages' carousels revert to the hand-off box (a trailing `[video]` / `[image]` 15, words between two slide tables 14, a bracket-less note line 4, a leading heading 7 …), 1 page gains a carousel (XGF9003 0.0), 0 pages lose text except: OSGM301 1.0's title row ("What are the different ways people play games?" — the r63/r266 title-row drop, the in-table sub-class, now visible because the freed bundle builds through the older image path) and a Word comment anchored to a non-first list item in the restored free body (AGH1005 2.0 "Check the numbering here" — the free-body comment emitter's own edge, recorded).
- **Skeleton (PRIMARY): SCAFFOLD mean 50.964% → 50.965% (50.9641 → 50.9646 = +0.0005pp; 88 movers: 35 up, 53 down) / ≥50% 1072 → 1073 / ≥75% 159 → 160 / ≥90% 14 / skipped 0 @ 1955; RAW 35.138% → 35.117% (−0.021pp)** (state `outputs/_r352_sk_final.json`, FRESH; movers `_r352_sk_movers.log`; companions `_r352_dips_companion.log`). **The dips, with their companion numbers:** CHFUN06 0.0 −30.61 is difflib's AUTOJUNK CLIFF — the page's skeleton crossed 200 lines (198 → 203: five restored `<p>` the gold has) and `SequenceMatcher`'s autojunk heuristic switched on (without autojunk 56.1 → 53.7; the gold has the identical h3 / h4 / p / p / carousel run) — a scorer defect, named here for the first time (§3 step 6: the third naming makes it a measurement-tool round: `autojunk=False` + a re-baseline); XTAS102 3.0 −10.26 (overlap 53.4 → 59.7, matched lines 143 → 160 — artefact), AGH1005 7.0 −5.02 (54.3 → 58.0), ENFUN09 −4.22 (62.9 → 64.2), AGH1003 2.0 −3.73 (53.6 → 60.0), CEDW501 2.0 −3.32 (69.2 → 72.3), AGH1009 3.0 −3.24 (68.5 → 74.0), OSBY301 3.0 −3.22 (60.9 → 64.4), AGH1006 5.0 −3.49 (56.4 → 76.6) — every one an alignment artefact by the companion test (the restored sections ADD matched lines); the real dips AGH1005 3.0 −3.46 / 4.0 −0.81 / 6.0 −0.24, XGF9003 0.0 −3.55, XLP01 2.0 −3.43 (companions flat: a restored `<p>` the human placed elsewhere, a carousel that reverted to the box) — NAMED. The gains: OSGM301 1.0 +13.34 (overlap 43 → 57), XLP01 3.0 +10.74, AGH1009 5.0 +10.64 (49.6 → 64.0), AGH1009 7.0 +8.05, CEDO105 2.0 +7.31, XTAS103 0.0 +6.90, AGH1009 8.0 +5.57, AGH1007 4.0 +4.24.
- **compare_structure exact 11464 → 11607 (+143, text-matched 13513 → 13676) / EXTRA 175 EXACT / missing 607 → 617 (+10 — NAMED: the 44 pages whose carousel is now the honest box, the gold's `row carousel` container uncounted there).** clean **2080/2103** / leak **26/23** EXACT · body **180 → 182 (+2 — NAMED: OVER-CAPTURE 42 → 43 and EMPTY container 135 → 136 — ENGI301 2.0 and ENGJ201 5.0, two of the reverted carousels: the gate counts an honest box holding the eaten content as over-capture, while the silent deletion it replaces was invisible to it)** · tags **9557/9557** · flipCard 61 / div 0 · speechBubble 4 (at baseline) · modal 0 · mtkQuiz 17 / 0 · menulabels 91 / 0 · dragdrop 21 / column 5 / defect 0 — EXACT · **math 322/323 → 323/323, defect 1 → 0 — IMPROVED: PES1007 lesson 2's "pre-existing page-tail loss" recorded at r346 as "a capture / boundary class for its own round" WAS this carousel over-capture; the baseline is refreshed to 0.** Every RESULT line ✓; 15 selftests GREEN.
- **The carousel verifiers (adjunct, not protected — OFF vs ON over the 74 changed modules):** `_verify_carousel.cjs` 16 → 16 mismatched video-slide ids (built 266 → 224 = the reverts); `_verify_image_carousel.cjs` defect 17 → 24 — all on CEDO105 (12 → 19: the saturated image-substitution baseline the r149 selftest note records — the human uses different images; a 4th carousel of the same page now classifies as an image carousel), OSGM301 1.0 now builds a 5-slide image carousel with 4 exact + 1 developer image-swap.

### 5. NAMED, RECORDED, NOT CHASED

- The 44 honest reverts: a trailing `[video]` / `[image]` after the slide table (15 — the widget seam has `renderImage` but no video emitter; a follow-up: render trailing media members through the media emitters), words between two slide tables (14 — a multi-table carousel with prose between), a bracket-less note line such as "Answers: 1, 2, 3, 5." (4), a leading heading (7 — the writer's carousel title, the gold's h3/h4 before the widget; no heading emitter at the seam).
- The in-table loss (44 builds: the r63 / r266 title-row drop — OSGM301 1.0's title is the gold's `<h3>`) and the no-table video / prose carousels (80 lossy builds) — the next carousel rounds; then flipCard 63 / modal 39 / accordion 27 / clickDrop 17 / dropDown 12 by the same method.
- The skeleton scorer's autojunk cliff at 200 lines (CHFUN06) — a measurement-tool round when named a third time (§3 step 6), or sooner if Chris asks: `difflib.SequenceMatcher(None, b, a, autojunk=False)` + a full re-baseline.
- A Word comment anchored to a non-first list item in the free body is not emitted (AGH1005 2.0) — the free-body comment emitter's "first item that reaches this point" rule; a small follow-up.

**Ledger:** FULL ship (round 352; counter reset) · data `Interactive_Boundary_ChildTag_Bank._meta.member_rule.heading_terminates_after_table_exempt_types` + `Emit_Templates.interactive_builders.carousel.table_slides.members` · env `CARHEADEND_OFF` / `CARMEMBERS_OFF` · engine `InteractiveScanner.js` (`#swallowMembers` — `hExempt`), `InteractiveBuilder.js` (`#carouselTableSlides` — the members walk, `let html`) · gate tools (outside git, mirrored to `loop/`) `gate_baseline.json` · tools `outputs/_measure_r352_widgetloss.cjs` (+ `_r352_wl_run.sh`, `_r352_widgetloss{,_pre}.json`, `_r352_widgetloss{,_confirm,_post}.log`), `_measure_r352_cdmembers.cjs` / `_measure_r352_carmembers.cjs` / `_measure_r352_wmembers.cjs` / `_measure_r352_scmembers.cjs` (+ their `_run.sh` and `.json`), `_r352_clickdrop_declines.log`, `_r352_alltype_declines.log`, `_r352_wshapes.log`, `_r352_scshapes.log`, `_r352_carousel_trailing.log`, `_r352_debug.cjs`, `_r352_probe.cjs` (+ `_r352_probe_run.sh`), `_r352_probe_classify.log`, `_r352_on_changed_{pages,modules}.txt`, `_r352_fullship_par.sh` / `_r352_fullship_run.sh`, `_r352_dips_companion.py` (+ `.log`), `_r352_verify_carousel{,_OFF}.log`, `_r352_verify_image_carousel{,_OFF}.log`, `_r352_postship.sh`, `_r352_finalise.py` · AppVersion 260619.23.

"""
if "round 352, build 260619.23" not in s:
    assert s.startswith(head), "changelog head"
    s = head + ENTRY + s[len(head):]
    wr(CL, s); print("changelog: r352 entry prepended")

# ---------------------------------------------------------------- 2. Config.js
P = os.path.join(PF, "app", "js", "Config.js"); s = rd(P)
if '"260619.23"' not in s:
    old = '\tstatic AppVersion = "260619.22";'
    assert s.count(old) == 1, "Config anchor"
    s = s.replace(old, '\t// ROUND 352 (260619.23): a built carousel never discards the writer\'s words — a section heading after the slide table ends the carousel; the table-slides path keeps its leading / trailing paragraphs or declines.\n' + '\tstatic AppVersion = "260619.23";', 1)
    wr(P, s); print("Config.js: 260619.23")

# ---------------------------------------------------------------- 3. CLAUDE.md
P = os.path.join(PF, "CLAUDE.md"); s = rd(P)
if "ROUND 352 BASELINE" not in s:
    OLD9 = "| **Skeleton (PRIMARY)** | `python3 _skeleton_compare.py` | **ROUND 351 BASELINE"
    assert s.count(OLD9) == 1, "§9 anchor"
    NEW9 = ("| **Skeleton (PRIMARY)** | `python3 _skeleton_compare.py` | **ROUND 352 BASELINE (a built carousel never discards the writer's words — the heading-after-table boundary + the table-slides members; FULL regeneration of all 416, ledger counter 0): SCAFFOLD mean 50.965% / >=50% 1073 / >=75% 160 / >=90% 14 / skipped 0 @ 1955 — 50.9641 → 50.9646 (+0.0005pp; 88 movers, the dips named with their companion numbers in the r352 changelog — CHFUN06 −30.6 is difflib's autojunk cliff at 200 skeleton lines, a scorer defect); RAW 35.138% → 35.117%** (state `outputs/_r352_sk_final.json`, FRESH) = **55.5% of achievable** (ceiling 91.9%). cs exact 11464 → **11607** / EXTRA 175 / missing 607 → **617** (named: 44 honest reverts); clean 2080/2103, leak 26/23 EXACT; body 180 → **182** (named: two reverted carousels the gate reads as over-capture); math **323/323 defect 0** (PES1007 CLEARED). Older r351 text: **ROUND 351 BASELINE")
    s = s.replace(OLD9, NEW9, 1)
    OLD11 = "| `DDCOLUMN_OFF` / `DDMEMBERS_OFF` | 351 |"
    assert s.count(OLD11) == 1, "§11 anchor"
    NEW11 = ("| `CARHEADEND_OFF` / `CARMEMBERS_OFF` | 352 | **A BUILT CAROUSEL NEVER DISCARDS THE WRITER'S WORDS.** `CARHEADEND_OFF`: the scanner's `heading_terminates_after_table` rule gets its OWN exemption list (`member_rule.heading_terminates_after_table_exempt_types` = `[\"rotateBanner\"]`; before, the slideshow types were exempt through the shared body list and `slideshow_heading_internal` forced every heading internal), so an `[H2]`–`[H5]` after a carousel's captured slide table ENDS the bundle and the writer's next section — heading, paragraphs, lists, images, videos, the next table, the rest of the page (AGH1005 2.0 \"Parts of a plant\", AGH1009 5.0's four h3 sections, XTAS102 3.0's seven h4 carousels) — renders as ordinary page content where the gold puts it (206 built carousels / 171 pages / 109 modules were dropping that text without a trace; the gold keeps it on 167). `CARMEMBERS_OFF`: the r279 table-slides carousel keeps the members its slides did not consume — a black paragraph / `[body]` with words before the first table renders through the free-body block emitter BEFORE the carousel, one after the last table AFTER it (CHFUN06's five \"Watch the video…\" sentences, the gold's `<p>`), blank lines and instruction-class tags skipped, a developer-cue paragraph or ANY other member (a heading, an image / video / other tag, words between the slide tables) DECLINES the build so the hand-off box keeps every member (never half-build). Measured by the widget text-loss census `_measure_r352_widgetloss.cjs` (carousel lossy builds 231 → 110; flipCard 63 / modal 39 / accordion 27 / clickDrop 17 / dropDown 12 remain — the next rounds). FULL regeneration; 126 pages / 74 modules (82 regain the eaten section, 44 revert to the box); cs exact +143, math defect 1 → 0 (PES1007's \"page-tail loss\" WAS this over-capture), skeleton +0.0005pp with every dip named, missing +10 and body +2 named. Data `Interactive_Boundary_ChildTag_Bank._meta.member_rule.heading_terminates_after_table_exempt_types` + `Emit_Templates.interactive_builders.carousel.table_slides.members`. |\n"
             "| `DDCOLUMN_OFF` / `DDMEMBERS_OFF` | 351 |")
    s = s.replace(OLD11, NEW11, 1)
    OLD14 = "- **Build:** `260619.22` (round 351"
    assert s.count(OLD14) == 1, "§14 anchor"
    NEW14 = ("- **Build:** `260619.23` (round 352 — **a built carousel never discards the writer's words: a section heading after the slide table ends the carousel (the scanner's heading-after-table rule's own exemption list), and the table-slides carousel keeps its leading / trailing paragraphs or declines** (`InteractiveScanner.#swallowMembers` `hExempt` behind `member_rule.heading_terminates_after_table_exempt_types`, env `CARHEADEND_OFF`; `InteractiveBuilder.#carouselTableSlides` members walk behind `carousel.table_slides.members`, env `CARMEMBERS_OFF`; the autonomous loop's session-15 Round 2; **FULL regeneration of all 416 gated dirs, ledger counter 0**; 36 batches all rc 0). **ROUND 352 BASELINE: SCAFFOLD mean 50.965% / ≥50% 1073 / ≥75% 160 / ≥90% 14 / skipped 0 @ 1955 (50.9641 → 50.9646 = +0.0005pp; 88 movers, every dip named with its companion numbers — CHFUN06 0.0 −30.6 is the scorer's autojunk cliff at 200 skeleton lines); RAW 35.138% → 35.117%** (state `outputs/_r352_sk_final.json`, FRESH) = **55.5% of achievable** (ceiling 91.9%). cs exact **11607** (+143) / EXTRA **175** / missing **617** (+10 named); clean **2080/2103** / leak **26/23**; body **182** (+2 named); math **323/323 defect 0** (IMPROVED — PES1007 cleared); speechBubble 4; menulabels 91 / 0; dragdrop 21 / 0 — EXACT; every RESULT line green; 15 selftests GREEN. Corpus 2110 pages / 416 modules, 0 stale, **126 pages / 74 modules changed, 0 added/removed** (82 pages regain their eaten section, 44 carousels revert to the honest box, 670 text runs restored). Widget text-loss census: carousel lossy builds 231 → 110.\n"
             "- **Build:** `260619.22` (round 351")
    s = s.replace(OLD14, NEW14, 1)
    wr(P, s); print("CLAUDE.md: §9 / §11 / §14")

# ---------------------------------------------------------------- 4. gate_baseline.json
P = os.path.join(ROOT, "CONVERTER_V2", "reference", "tests", "gate_baseline.json"); s = rd(P)
d = json.loads(s)
if "_note_r352" not in d["skeleton"]:
    d["skeleton"]["mean_scaffold_pct"] = 50.965
    d["skeleton"]["pages_ge_50"] = 1073
    d["skeleton"]["pages_ge_75"] = 160
    d["skeleton"]["raw_mean_pct"] = 35.117
    d["skeleton"]["_note_r352"] = "Round 352: a built carousel never discards the writer's words (the heading-after-table boundary + the table-slides members) — SCAFFOLD 50.9641 → 50.9646 (+0.0005pp; 88 movers, dips named with companions in the changelog; CHFUN06 −30.6 = difflib's autojunk cliff at 200 lines — a scorer defect queued as a tooling round), ≥50 1073, ≥75 160, RAW 35.117. State outputs/_r352_sk_final.json."
    d["compare_structure"]["exact_chain"] = 11607
    d["compare_structure"]["claude_missing_container"] = 617
    d["compare_structure"]["_note_r352"] = "Round 352: exact 11464 → 11607 (+143, the restored sections); missing 607 → 617 NAMED — the 44 pages whose carousel reverts to the honest hand-off box (a trailing [video]/[image], words between slide tables, a leading heading) no longer show the gold's row.carousel container. Hold-or-improve from here."
    d["body_compare"]["any_breakdown"] = 182
    d["body_compare"]["over_capture"] = 43
    d["body_compare"]["_note_r352"] = "Round 352: 180 → 182 NAMED — OVER-CAPTURE 42 → 43 (ENGI301 2.0) and EMPTY container +1 (ENGJ201 5.0): two reverted carousels whose eaten content now sits in an honest box the gate reads as over-capture; the silent deletion it replaces was invisible to the gate. Hold-or-improve from here."
    d["math"]["math"] = 323
    d["math"]["defect"] = 0
    d["math"]["per_module"] = {}
    d["math"]["_note_r352"] = "Round 352: PES1007 lesson 2's 'pre-existing page-tail loss' (the r346 baseline defect 1) WAS the carousel over-capture — cleared by the heading-after-table boundary; 323/323, defect 0, per_module empty."
    d["_meta"]["build"] = "260619.23"; d["_meta"]["round"] = 352; d["_meta"]["date"] = "2026-09-17"
    wr(P, json.dumps(d, indent=2, ensure_ascii=False) + "\n"); print("gate_baseline.json: skeleton / compare_structure / body / math / _meta")

# ---------------------------------------------------------------- 5. loop/README.md rows
P = os.path.join(PF, "loop", "README.md"); s = rd(P)
if "_r352_finalise.py" not in s:
    A = "| `_measure_r351_ddshapes.py` / `_r351_ddshapes.log`"
    assert s.count(A) == 1, "README anchor"
    ROWS = ("| `_measure_r352_widgetloss.cjs` / `_r352_wl_run.sh` / `_r352_widgetloss{,_pre}.json` / `_r352_widgetloss{,_confirm,_post}.log` / `_measure_r352_{cd,car,w,sc}members.cjs` (+ `_r352_{cd,car,w,sc}_run.sh`, `_r352_{cd,car,w,sc}_modules.txt`, `_r352_{cd,car,w,sc}members.json`) / `_r352_clickdrop_declines.log` / `_r352_alltype_declines.log` / `_r352_wshapes.log` / `_r352_scshapes.log` / `_r352_carousel_trailing.log` / `_r352_debug.cjs` / `_r352_probe.cjs` / `_r352_probe_run.sh` / `_r352_probe_{off,on}_0*.log` / `_r352_probe_classify.log` / `_r352_on_changed_{pages,modules}.txt` / `_r352_fullship_par.sh` / `_r352_fullship_run.sh` / `_r352_fullship_regen.log` / `_r352_manifest_diff.log` / `_r352_sk_full.log` / `_r352_sk_final.json` / `_r352_sk_movers.log` / `_r352_dips_companion.py` / `_r352_dips_companion.log` / `_r352_gates.log` / `_r352_verify_carousel{,_OFF}.log` / `_r352_verify_image_carousel{,_OFF}.log` / `_r352_postship.sh` / `_r352_selftests.log` / `_r352_finalise.py` | `CONVERTER_V2/outputs/` | Session 15 Round 2 (engine r352) — the D10-3 build queue re-measured and found exhausted at the floor (every type's un-built shapes < 20 sites), the widget TEXT-LOSS census over every built widget (437 lossy builds; carousel 206 / 171 pages confirmed on disk), the carousel round's probe (OFF = disk 2110/2110; ON = 126 pages), the FULL regeneration, the skeleton / gates / companion numbers for every dip, the two carousel verifiers OFF vs ON, the finalise. |\n")
    s = s.replace(A, ROWS + A, 1)
    wr(P, s); print("README: r352 rows")

# ---------------------------------------------------------------- 6. LOOP_STATE.md
P = os.path.join(ROOT, "LOOP_STATE.md"); s = rd(P)
if "## Session 15 · Round 2 (engine r352" not in s:
    A = "## Session 15 · Round 2 PICK (engine r352"
    assert s.count(A) == 1, "LOOP_STATE PICK anchor"
    SHIPPED = """## Session 15 · Round 2 (engine r352 — a built carousel never discards the writer's words) — what shipped (a section heading after the slide table ends the carousel; the table-slides carousel keeps its leading / trailing paragraphs or declines)
- **Shipped 2026-09-17 ≈11:05 NZST (session 15).** AppVersion 260619.23, changelog entry r352, CLAUDE.md §9 / §11 / §14, `gate_baseline.json` (skeleton 50.965 / 1073 / 160 / raw 35.117; cs exact 11607 / missing 617 named; body 182 named; math 323/323 defect 0 — PES1007 CLEARED), loop/README rows; FULL regeneration of all 416 gated dirs (36 batches, 4 workers, ALL rc 0; `_stalecheck.sh` 0 stale), ledger record-full (counter 0).
- **Built:** the in-memory probe over all 416 — OFF (`CARHEADEND_OFF=1 CARMEMBERS_OFF=1`) = disk 2110/2110; ON = **126 pages / 74 modules** = the regenerated set EXACTLY (manifest diff 126 / 0 / 0; every page byte-identical to the probe; `_r352_probe_classify.log`): **82 pages keep their carousel and regain the section it had eaten (670 text runs restored)**, 44 pages' carousels revert to the honest hand-off box (a trailing `[video]` / `[image]` 15, words between two slide tables 14, a bracket-less note line 4, a leading heading 7), 1 page gains a carousel; 0 pages lose text but OSGM301 1.0's title row (the in-table sub-class) and one Word comment anchored to a non-first list item (AGH1005 2.0 — the free-body comment emitter's edge). The first probe declined every candidate — "Assignment to constant variable" (`const html`), caught by the probe's build notes and fixed (`let html`).
- **Gates:** skeleton SCAFFOLD 50.9641 → 50.9646 (+0.0005pp; 88 movers, 35 up / 53 down; the companions in `_r352_dips_companion.log`: CHFUN06 0.0 −30.61 = difflib's AUTOJUNK CLIFF — the skeleton crossed 200 lines (198 → 203, five restored `<p>` the gold has) and the ratio without autojunk is 56.1 → 53.7 — a scorer defect named for the FIRST time; XTAS102 3.0 −10.26 / AGH1005 7.0 −5.02 / ENFUN09 −4.22 / AGH1003 2.0 −3.73 / CEDW501 2.0 −3.32 / AGH1009 3.0 −3.24 / OSBY301 3.0 −3.22 / AGH1006 5.0 −3.49 all alignment artefacts (the position-free overlap RISES: 53→60, 54→58, 63→64, 54→60, 69→72, 68→74, 61→64, 56→77); real dips AGH1005 3.0 −3.46 / 4.0 −0.81 / 6.0 −0.24, XGF9003 0.0 −3.55, XLP01 2.0 −3.43 (companions flat) NAMED; gains OSGM301 +13.34, XLP01 3.0 +10.74, AGH1009 5.0 +10.64, AGH1009 7.0 +8.05, CEDO105 2.0 +7.31, XTAS103 +6.90 …), ≥50 1072 → 1073, ≥75 159 → 160, ≥90 14; RAW 35.138 → 35.117; **cs exact 11464 → 11607 (+143)**, EXTRA 175, missing 607 → 617 (NAMED — the 44 reverts); clean 2080/2103, leak 26/23; **body 180 → 182 (NAMED — ENGI301 2.0 / ENGJ201 5.0, two reverted carousels the gate reads as over-capture; the silent deletion was invisible to it)**; tags 9557/9557; flipCard / speechBubble / modal / mtkQuiz / menulabels / dragdrop EXACT; **math 322/323 → 323/323 defect 0 — IMPROVED (PES1007's r346 "page-tail loss" WAS this over-capture)**; every RESULT line ✓; 15 selftests GREEN. Adjunct carousel verifiers OFF vs ON over the 74: video ids 16 → 16 mismatched; image carousels defect 17 → 24 — all CEDO105's saturated image-substitution baseline (12 → 19), OSGM301 1.0 now a 5-slide image carousel (4 exact + 1 dev swap).
- **The text-loss census after the round (`_r352_widgetloss_post.log`):** carousel lossy builds 231 → 110 (pages 188 → 93; built 605 → 563); every other type unchanged. Ship ledger: FULL at r352 (counter 0, 8 of headroom). Plateau window (the §4 skeleton window): r352 predicted a skeleton RISE and moved +0.0005pp — but cs exact +143 and math +1 moved other protected gates, so the window is 0 of 3.
- **Recorded, not chased:** the 44 honest reverts (trailing media 15 — the seam has `renderImage` but no video emitter; words between slide tables 14; bracket-less note lines 4; leading headings 7); the in-table title-row loss (44 builds — OSGM301 1.0's `<h3>`) and the no-table video / prose carousels (80 lossy builds) as the next carousel rounds; then flipCard 63 / modal 39 / accordion 27 / clickDrop 17 / dropDown 12 by the same census; the skeleton scorer's autojunk cliff (a tooling round on the third naming, or sooner if Chris asks); the free-body Word comment on a non-first list item.

"""
    s = s.replace(A, SHIPPED + A, 1)
    B = "- Remaining KB queue (§D): stickyNav (BLOCKED"
    assert s.count(B) == 1, "position anchor"
    s = s.replace(B, "- Session 15 Round 2 (engine r352 — a built carousel never discards the writer's words: the scanner's heading-after-table rule gets its own exemption list, the table-slides carousel keeps its leading / trailing paragraphs or declines; FULL regeneration of all 416): **SHIPPED 2026-09-17 ≈11:05 (session 15)**. AppVersion 260619.23, CLAUDE.md §9/§11/§14, `gate_baseline.json` (skeleton 50.965 / 1073 / 160; cs 11607 / 175 / 617; body 182; math 323/323 defect 0). Skeleton +0.0005pp (88 movers, every dip named with its companion; CHFUN06 = the scorer's autojunk cliff), cs exact +143, math IMPROVED, missing +10 and body +2 named; 126 pages / 74 modules (82 regain the eaten section, 44 revert to the box). The D10-3 build queue measured EXHAUSTED at the floor for every type; the widget text-loss census is the new queue (carousel 110 residue, flipCard 63, modal 39, accordion 27, clickDrop 17, dropDown 12).\n" + B, 1)
    C = "- s15-r1 (build round r351, the dragAndDrop MEMBERS rule + D10-3 kickoff shape 2)"
    assert s.count(C) == 1, "round log anchor"
    s = s.replace(C, "- s15-r2 (engine r352, a built carousel never discards the writer's words) · a section heading after a carousel's slide table ENDS the carousel (the scanner's heading-after-table rule's own exemption list — the slideshow types were swallowing the rest of the page) + the r279 table-slides carousel keeps its leading / trailing paragraphs through the free-body emitter or declines on anything it cannot render (206 built carousels / 171 pages were dropping writer text the gold keeps) · SHIPPED · scaffold 50.9641 → 50.9646 (+0.0005pp, dips named with companions; the CHFUN06 −30.6 autojunk cliff named), cs exact +143, math defect 1 → 0, missing +10 / body +2 named · 126 pages / 74 modules (82 regain their section, 44 revert to the box) · FULL regeneration, ledger 0 · commit — see git log\n" + C, 1)
    wr(P, s); print("LOOP_STATE.md: what shipped + position + round log")
print("finalise done")
