#!/usr/bin/env python3
"""ROUND 356 (loop session 16 Round 1 — the EXACT members rule: no built widget discards a member it never READ) — finalise:
changelog, AppVersion (260619.26 → 260619.27), CLAUDE.md §9 / §11 / §14, gate_baseline.json (skeleton + compare_structure +
_meta), loop/README.md rows, LOOP_STATE.md (round record). Idempotent; every file written LF via wr()."""
import io, os, json
ROOT = r"C:\Users\Gavin\TeKura\FINAL_MODULE_DATA"
PF = os.path.join(ROOT, "pageforge-site", "converter-v2")
def rd(p):
    with io.open(p, encoding="utf-8", newline="") as f: return f.read()
def wr(p, s):
    with io.open(p, "w", encoding="utf-8", newline="") as f: f.write(s)

CL = os.path.join(PF, "BUILD_CHANGELOG.md"); s = rd(CL)
head = "# BUILD CHANGELOG — Stage 2 (engine + UI)" + chr(10) + chr(10)
ENTRY = """## 2026-09-17 (round 356, build 260619.27) — NO BUILT WIDGET DISCARDS A MEMBER IT NEVER READ: the r353 members rule made EXACT by READ-TRACKING (`InteractiveBuilder.#trackMembers` + `#withMembersRead`, data `_members_rule.consumption: "read"`, env `WIDGETMEMBERS_OFF`) — 30 built widgets on 26 pages / 26 modules had been silently dropping a writer's paragraph the builder never even looked at (flipCard's table paths read `bundle.tables` alone; a `[body]` after a carousel's slide table; …); FULL regeneration of all 416 — 35 pages / 32 modules change: 31 pages regain their text (88 runs) and 30 dropped `[image]` members render, 4 widgets revert to the honest box; the autonomous loop's session-16 Round 1

### 1. WHAT CHANGED

**The class.** Round 353 built a generic members rule at the one seam every builder passes through (`InteractiveBuilder.Build` → `#withMembers`) and shipped it OFF: it guessed what a builder had CONSUMED from the text of the build, and a text-presence test cannot know that — strict mode reverted 475 widgets on 150 pages for reasons the seam could not verify, prose-only mode duplicated text on 18 pages. The queued exact design was "each builder reports its consumed members" (ten builders, 2–3 rounds). This round found a cheaper exact signal that needs no per-builder edit at all: **a member the builder never READ cannot be in the build.**

**The mechanism (one seam, one flag — `Emit_Templates.interactive_builders._members_rule` {enabled: true, consumption: "read", content_keys, image_member_render, reference_title_pattern}; env `WIDGETMEMBERS_OFF`).** `#trackMembers` runs around the type dispatch in `Build`: for its duration every `memberItem` is a Proxy that records a read of its content (`text` / `blackAfter` / `block` / `nestedBundle`), `bundle.tables` becomes a getter that records its reads, and a bundle property that POINTS AT a member (`sameBlockImage` — the r246 avatar; any array holding members) points at the member's proxy so a builder's identity test still holds (the first probe flipped every TEDC401/402 bubble's side through `memberItems.indexOf(bundle.sameBlockImage)`); `restore()` puts the plain items back in `finally`, before `#withMembers`, `#tagWordsNote`, the caller or the hand-off box see the bundle. `#withMembersRead` then classifies every member: READ (or a table read through `bundle.tables`) → CONSUMED, full stop; unread → a blank line / an instruction-class tag / a bare marker / the invocation tag (r354's note owns its words) / a go-to-journal `[button]` (the caller's `#goJournalTail` emits it AFTER the widget — skipped, never a position inside the build) / a media reference title ("… Stock Illustration - Download Image Now", "… – YouTube": `reference_title_pattern`) → SKIPPED; a media line or tag whose URL / video id / image key IS in the built html → consumed (the builder took it through `bundle.media`); words the built html already carries → consumed (the r353 shingle test, demoted to a guard); an unread `[image]` member → rendered through the page's own image emitter (`renderImage`, the tabs / r352 precedent) before / after the widget; unread PROSE (a black paragraph, a `[body]` / bracket-less line with ≥ 3 words, a SENTENCE carrying a link — "Information sourced from - https://…" — as opposed to a URL-only media line) → rendered through the free-body emitter BEFORE the widget when it precedes the first consumed member and AFTER it when it follows the last; prose BETWEEN consumed members over the short-line allowance, a developer-cue line, a heading, a video / audio / other tag, a table, a nested widget → the build DECLINES and the hand-off box keeps every member (never half-build), with a build note naming why. The widget's own markup is never edited: a build is byte-identical or reverts. `consumption: "text"` keeps the r353 guess for a one-off comparison; it is never the shipped mode.

### 2. THE MEASUREMENT (before coding — `outputs/_measure_r356_consumed.cjs` over all 416, `_r356_consumed.{json,log}`, `_r356_consumed_detail.log`)

- **30 built widgets on 26 pages / 26 modules drop a never-read prose member (53 text runs): flipCard 22 builds / 18 pages (32 runs — the table-form paths `#flipCardDialects` / `#flipCardCards` read `bundle.tables` alone, every black / `[body]` member before or after the card table is dropped: AGH1009 1.0 #1's two paragraphs, TWHK901 0.0's six across three cards, CHFUN05 0.0's "Flip the card to see the sentence in English"), carousel 4 / 4 (BLL117 / 127 / 137 / 157's `[body]` after the slide table), accordion 2 / 2, speechBubble 1, hintSlider 1.** Per template family: Standard 20 pages, Fundamentals 3, Inquiry 3. The gold keeps the lost text as free body on 41 of 53 runs (0.77) and 17 of 26 pages (0.65) — Standard 12/20 = 0.60, Fundamentals 3/3, Inquiry 2/3 — ≥ 0.60 in every family (the "drops": CEDO301 6.0 has no gold pair, AGH1006's "Grafting…" is commented out in the gold, two label lines).
- **The false-consumption check** (an unread member whose words ARE on the page): 11 sites, all TEDC402 / CEDO202 — nine iStock reference-title lines (on the page as the avatar's alt) and one sentence the writer typed twice → the two guards above.
- **The strict forecast:** 17 flipCards with an unread non-prose member — 15 `[image]` / `[video]` whose URL is not in the build, 6 `[button]` (5 = the go-journal button, 1 = AGH1009's "Complete activity 1A in your journal"), 1 stray `[accordion]` tag.
- **Sized as ONE class** (§1b: per template / subject family, one rule at one seam), not per builder — the session-15 stop had sized the residue per builder ("< 20 sites per builder"), the right floor for a widget-BUILD kickoff but not for one engine rule.

### 3. THE PROOF

- **The 416-module in-memory probe** (`_r356_probe.cjs`, the r354 harness; 4 shards): `WIDGETMEMBERS_OFF=1` = disk **2110/2110** (the r354 corpus byte-for-byte); ON = **35 pages / 32 modules** (`_r356_probe_on_0*.log`); the regenerated corpus = the probe's ON pages **2110/2110** (`_r356_manifest_diff.log`: changed 35 / added 0 / removed 0). `_r356_probe_classify.log`: **31 RESTORE pages — 88 text runs gained, 30 `<img>` rendered (TEDC401 / 402's avatar Tina, SSOG103's four postcards, MXFL301's two latitude figures, ANZH205, ENGJ202, TEFUN08, XGF9006), 0 duplicated runs, 0 lost runs; 4 REVERT pages** — AGH1009 1.0 #1 (a `[Button] Complete activity 1A in your journal` the flipCard dropped — not the go-journal form, so the box keeps the cards, the two paragraphs AND the button), BLL246 1.0 #1 (the accordion had dropped 13 word-select story lines that sit between consumed members), XDLS906 1.0 #1 (a 23-word paragraph in an unresolvable bracket between consumed members), XGF9002 1.0 #8 (a flipCard bundle that had swallowed an `[accordion]` section + image — the r352 class). Three rounds of probe refinement, each caught by the classify / the build notes: the bubble-side flip (identity), the go-journal button read as a consumed POSITION (TEDC402 #13 declined on "prose between consumed members" — a button the caller emits after the widget is not a position), a sentence carrying a link read as a media line (MXEX201 4.1's source attribution).
- **The read census after the round** (`_measure_r356b_consumed.cjs` → `_r356b_consumed.log`): **0 lossy-prose bundles, 0 strict declines** over 2507 built bundles. **The widget text-loss census** (`_measure_r356_widgetloss.cjs` → `_r356_widgetloss.json`, the r352 instrument): flipCard lossy builds **57 → 41**, carousel 106 → 102, accordion 35 → 33, speechBubble 10 → 9; modal 44, clickDrop 21, dropDown 16, tabs 5, hintSlider 3 unchanged — no type rises (the residue is READ-but-dropped text: a builder's own rule, the next per-builder classes).
- **Gates** (`_r356_gates.log`, every RESULT line ✓, 0 ✗): **skeleton SCAFFOLD 51.9788 → 51.9819 % (+0.003pp; 32 movers — 10 up / 22 down, pp-sum +0.06, every mover inside the changed set — `_r356_dips_companion.log`: gains AGH1009 1.0 +2.69, ANZH205 3.0 +2.22, SSOG101 1.0 +1.50, XGF9002 1.0 +1.40, BLL117 / 127 / 157 +0.8–0.9; six dips are the scorer's alignment artefact with the position-free overlap or the matched-line count RISING — BLL137 1.1, ENGI405 5.0, MXFL301 1.0, TEFUN08, TWHK901, TWHK903 — and the sixteen others, all ≤ 1.1pp, are NAMED: a restored `<p>` / `<img>` the gold page does not carry at that place — MXEX201 4.1 −1.09 = the "Information sourced from" line the gold drops, AGH1006 2.0 −0.78 = the paragraphs the gold commented out, CEDO202 0.0 −0.65 = lines the gold ships as `<li>`, PES1003 8.0 / ENGJ202 4.0 / SSOG103 2.0 / ENGR202 5.0 / TEDC402 ×3 / TEDC401 4.0 / OSAI101 2.0 / XGF9006 5.0 / ENGR102 4.0 / XMES201 1.0 / CEDW501 3.0 / SSOG103 4.0 −0.02 … −0.41 — the writer's words kept where the human chose otherwise); ≥ 50 % 1093 → 1092 (MXEX201 4.1 50.55 → 49.46, the named source line — the r338 / r289 override), ≥ 75 % 160, ≥ 90 % 14, skipped 0 @ 1955; RAW 36.711 → 36.705 %; cs exact 11607 → 11617 (+10), EXTRA 175, missing 617; clean 2080/2103 = 98.91 %, leak 26/23; body 182; tags 9557/9557; flipCard gate set TOTAL 61 / exact 32 / copy-edit 11 / defect 18 / divergence 0; speechBubble ✓ at baseline; modal / mtkQuiz / math 323/323 / menulabels 91 / dragdrop 21 — all EXACT.** = **56.6 % of achievable** (ceiling 91.9 %).
- **The touched-type verifiers over the changed set, OFF vs ON** (`_r356_family_verifiers.log`): flipCard 605 → 579 card-texts (the 4 reverts), exact 346 → 328, copy-edit 51 → 49, **defect 78 = 78, divergence 80 → 74 (IMPROVED — the reverted cards had no gold counterpart)**; accordion 159 panels every one human-matching; carousel 68 built / 2 mismatched slide ids in BOTH states (pre-existing); speechBubble ENGR202 / TEDC401 / TEDC402 line-for-line identical in both states (23 pre-existing defects outside the gate set); hintSlider OSAI101 6 rows IDENTICAL ✓. (`_verify_speechbubble.cjs` over the whole 32-module changed set ran > 30 minutes at 100 % CPU and was killed — a verifier performance trap on a big module, recorded for the tooling queue; the changed bubble modules were run alone.)

**Ledger:** FULL regeneration of all 416 (36 batches, all rc 0; `_stalecheck.sh` 0 stale), `_ship_ledger.py record-full` (counter 0) · data `_members_rule` {enabled, consumption, content_keys, image_member_render, reference_title_pattern} · env `WIDGETMEMBERS_OFF` · engine `InteractiveBuilder.#trackMembers` / `#withMembersRead` / the `Build` tracker seam · tools `outputs/_measure_r356_consumed.cjs`, `_r356_cm_run.sh`, `_r356_probe.cjs`, `_r356_probe_run.sh`, `_r356_classify.py`, `_r356_notes.cjs`, `_r356_memberdump.cjs`, `_r356_dips_companion.py`, `_measure_r356_widgetloss.cjs`, `_r356_wl_run.sh`, `_measure_r356b_consumed.cjs`, `_r356b_cm_run.sh`, `_r356_fullship_par.sh`, `_r356_postship.sh`, `_r356_finalise.py`.

"""
if "round 356, build 260619.27" not in s:
    assert s.startswith(head), "changelog head"
    s = head + ENTRY + s[len(head):]
    wr(CL, s); print("changelog: r356 entry prepended")

P = os.path.join(PF, "app", "js", "Config.js"); s = rd(P)
if '"260619.27"' not in s:
    old = '\tstatic AppVersion = "260619.26";'
    assert s.count(old) == 1, "Config anchor"
    s = s.replace(old, '\t// ROUND 356 (260619.27): no built widget discards a member it never READ — the r353 members rule made exact by read-tracking (#trackMembers / #withMembersRead; consumption "read"); 30 widgets on 26 pages had been dropping writer paragraphs; FULL regeneration, 35 pages / 32 modules.\n\tstatic AppVersion = "260619.27";')
    wr(P, s); print("Config.js: 260619.27")

P = os.path.join(PF, "CLAUDE.md"); s = rd(P)
if "ROUND 356 BASELINE" not in s:
    OLD9 = "| **Skeleton (PRIMARY)** | `python3 _skeleton_compare.py` | **ROUND 355 BASELINE"
    assert s.count(OLD9) == 1, "§9 anchor"
    NEW9 = ("| **Skeleton (PRIMARY)** | `python3 _skeleton_compare.py` | **ROUND 356 BASELINE (no built widget discards a member it never READ — the exact members rule; FULL regeneration of all 416, ledger counter 0): SCAFFOLD mean 51.982% / >=50% 1092 / >=75% 160 / >=90% 14 / skipped 0 @ 1955 — 51.9788 → 51.9819 (+0.003pp; 32 movers, 10 up / 22 down, every dip named in the r356 changelog with its companion — MXEX201_4_1 −1.09 the ≥50 down-crosser = the restored \"Information sourced from\" line the gold drops); RAW 36.705%** (state `outputs/_r356_sk_final.json`, FRESH) = **56.6% of achievable** (ceiling 91.9%). cs exact **11617** (+10) / EXTRA 175 / missing 617; clean 2080/2103, leak 26/23, body 182, math 323/323, every verifier EXACT. Older r355 text: **ROUND 355 BASELINE")
    s = s.replace(OLD9, NEW9, 1)
    OLD11 = "| `WIDGETMEMBERS_OFF` | 353 | **THE GENERIC MEMBERS RULE (every built widget) — SHIPPED OFF.**"
    assert s.count(OLD11) == 1, "§11 anchor"
    NEW11 = ("| `WIDGETMEMBERS_OFF` | 356 | **NO BUILT WIDGET DISCARDS A MEMBER IT NEVER READ — the exact members rule (the r353 rule made exact by READ-TRACKING).** `InteractiveBuilder.#trackMembers` wraps the type dispatch: every memberItem is a Proxy recording a read of its content (`text` / `blackAfter` / `block` / `nestedBundle`), `bundle.tables` records its reads, a bundle property pointing at a member (`sameBlockImage`) points at its proxy, all restored in `finally`. `#withMembersRead`: a READ member is consumed; an unread one is skipped (blank, instruction, bare marker, the invocation tag, a go-journal `[button]`, a media reference title), consumed (its URL / words are in the build), rendered (prose before / after the widget through the free-body emitter; an `[image]` through the page's image emitter) or declines the build (prose between consumed members, a heading, video / audio / other tag, table, nested widget — the honest box, with a build note). Measured over all 416: 30 widgets / 26 pages dropping never-read prose (flipCard 22 — its table paths read `bundle.tables` alone). FULL regeneration: 35 pages / 32 modules — 31 regain text (88 runs) + 30 images, 4 revert; skeleton +0.003pp (22 dips ≤ 1.1pp named), cs exact +10, every other gate EXACT; read census after 0 lossy; text-loss census flipCard 57 → 41. Data `Emit_Templates.interactive_builders._members_rule` (`consumption: \"read\"`). OFF = the r354 corpus byte-for-byte (2110/2110). |\n"
             "| `WIDGETMEMBERS_OFF` | 353 | **THE GENERIC MEMBERS RULE (every built widget) — SHIPPED OFF (superseded by r356's read mode).**")
    s = s.replace(OLD11, NEW11, 1)
    OLD14 = "- **Build:** `260619.26` (round 355"
    assert s.count(OLD14) == 1, "§14 anchor"
    NEW14 = ("- **Build:** `260619.27` (round 356 — **no built widget discards a member it never READ: the r353 members rule made exact by read-tracking** (`InteractiveBuilder.#trackMembers` / `#withMembersRead`, data `_members_rule.consumption: \"read\"`, env `WIDGETMEMBERS_OFF`; the loop's session-16 Round 1; **FULL regeneration of all 416, ledger counter 0**; 36 batches all rc 0). **ROUND 356 BASELINE: SCAFFOLD mean 51.982% / ≥50% 1092 / ≥75% 160 / ≥90% 14 / skipped 0 @ 1955 (51.9788 → 51.9819 = +0.003pp; 32 movers — 10 up / 22 down, every dip named with its companion; MXEX201_4_1 the ≥50 down-crosser = a restored source line the gold drops); RAW 36.705%** (state `outputs/_r356_sk_final.json`, FRESH) = **56.6% of achievable** (ceiling 91.9%). cs exact **11617** (+10) / EXTRA **175** / missing **617**; clean **2080/2103** / leak **26/23**; body **182**; math 323/323; flipCard 61 / div 0; speechBubble 4; menulabels 91 / 0; dragdrop 21 / 0 — EXACT; every RESULT line ✓; 15 selftests GREEN. Corpus 2110 pages / 416 modules, 0 stale, **35 pages / 32 modules changed, 0 added/removed** (31 pages regain 88 text runs + 30 images, 4 widgets revert to the honest box). Read census after: 0 lossy-prose bundles; text-loss census flipCard 57 → 41, carousel 106 → 102, accordion 35 → 33, no type rises.\n"
             "- **Build:** `260619.26` (round 355")
    s = s.replace(OLD14, NEW14, 1)
    wr(P, s); print("CLAUDE.md: §9 / §11 / §14")

P = os.path.join(ROOT, "CONVERTER_V2", "reference", "tests", "gate_baseline.json"); s = rd(P)
d = json.loads(s)
if "_note_r356" not in d["skeleton"]:
    d["skeleton"]["mean_scaffold_pct"] = 51.982
    d["skeleton"]["pages_ge_50"] = 1092
    d["skeleton"]["raw_mean_pct"] = 36.705
    d["skeleton"]["_note_r356"] = "Round 356: the exact members rule (read-tracking) — SCAFFOLD 51.9788 → 51.9819 (+0.003pp; 32 movers, every dip named), ≥50 1093 → 1092 (MXEX201_4_1, the restored source line the gold drops — NAMED), ≥75 160 / ≥90 14 EXACT; RAW 36.711 → 36.705. State outputs/_r356_sk_final.json."
    d["compare_structure"]["exact_chain"] = 11617
    d["compare_structure"]["_note_r356"] = "Round 356: exact 11607 → 11617 (+10, the restored paragraphs the gold has); EXTRA 175 / missing 617 EXACT."
    d["_meta"]["build"] = "260619.27"; d["_meta"]["round"] = 356
    d["_meta"]["_note_r356"] = "Round 356: the exact members rule — skeleton +0.003pp (named dips), cs exact +10, every other gate EXACT; FULL regeneration, 35 pages / 32 modules."
    wr(P, json.dumps(d, indent=2, ensure_ascii=False) + "\n"); print("gate_baseline.json: r356")

P = os.path.join(PF, "loop", "README.md"); s = rd(P)
if "_r356_finalise.py" not in s:
    A = "| `_r355_skeleton_noautojunk.py` / `_r355_sk_noautojunk.{"
    assert s.count(A) == 1, "README anchor"
    ROWS = ("| `_measure_r356_consumed.cjs` / `_r356_cm_run.sh` / `_r356_consumed.{json,log}` / `_r356_consumed_detail.log` / `_r356_probe.cjs` / `_r356_probe_run.sh` / `_r356_probe_{off,on}_0*.log` / `_r356_probe_classify.log` / `_r356_classify.py` / `_r356_notes.cjs` / `_r356_memberdump.cjs` / `_r356_fullship_par.sh` / `_r356_fullship_run.sh` / `_r356_fullship_regen.log` / `_r356_manifest_diff.log` / `_r356_gates.log` / `_r356_sk_final.json` / `_r356_sk_full.log` / `_r356_dips_companion.{py,log}` / `_r356_family_verifiers.log` / `_measure_r356_widgetloss.cjs` / `_r356_wl_run.sh` / `_r356_widgetloss.json` / `_measure_r356b_consumed.cjs` / `_r356b_cm_run.sh` / `_r356b_consumed.{json,log}` / `_r356_postship.sh` / `_r356_finalise.py` | `CONVERTER_V2/outputs/` | Session 16 Round 1 (engine r356) — the exact members rule: the read-tracking census (30 widgets / 26 pages dropping never-read prose), the 416-module OFF/ON probe + classify, the full regeneration, the gate suite, the skeleton decomposition with companions, the touched-type verifiers OFF vs ON, the after-censuses. |\n")
    s = s.replace(A, ROWS + A, 1)
    wr(P, s); print("README: r356 rows")
print("finalise done")
