#!/usr/bin/env python3
"""Session 12 stop bookkeeping for LOOP_STATE.md (root + the loop/ mirror is copied afterwards). Idempotent; keeps the file's newline."""
import io, os
HERE = os.path.dirname(os.path.abspath(__file__))
LS = os.path.join(HERE, "..", "..", "LOOP_STATE.md")
with io.open(LS, encoding="utf-8", newline="") as f: s = f.read()
nl = "\r\n" if "\r\n" in s[:3000] else "\n"
def L(t): return t.replace("\n", nl)

BANNER = L("""## >>> STOPPED 2026-09-16 ≈20:45 NZST (session 12) on the BUDGET rule (§4 — the 3-hour cap Chris set, hard stop 21:18; the ~45 minutes left after r347 were less than the D10-9 round needs to ship AND prove — it is a FULL-regeneration round with a new verifier — so its pre-measurement was completed and recorded instead of a half-built round): FOUR rounds shipped — r344 (D10-1, c47 in full + the title's stray `*` markers; scoped 21 modules / 48 pages; `ce096f3`), r345 (D10-2, English-first lesson-title pairs; scoped 7 / 7; `d637af9`), r346 (D10-7, Word equations ship as MathML + the new protected `_verify_math.cjs`; scoped 11 / 22; `2caf7b7`), r347 (D10-5, every content table `table table-bordered`, the tableFixed half declined; FULL regeneration of all 416, ledger counter 0; the r346 math-italic-letter fix carried; `acbd5a5`). Chris's session-10 queue is now at **item 6 — D10-9** (its pre-measurement is recorded below: "Session 12 · Round 5 PICK-in-progress (engine r348 — D10-9)"); items 7 (D10-3 widget-build kickoffs) then the ordinary §3 PICKs remain. Nothing BLOCKED this session.
- Scorecard at the stop (the r343 population — 1955 pairs, ceiling 91.9%): SCAFFOLD **51.283% = 55.8% of achievable** (session start 51.265% — r344 +0.016 / r345 0.000 / r346 +0.001 / r347 +0.001 = +0.018pp; still 55.8% at one decimal), RAW 35.409% (from 35.394%), ≥50 **1074** (from 1073) / ≥75 198 / ≥90 15, clean 2080/2103 = 98.91%, leak 26/23, cs exact **11464** (from 11469: r344's −8 = the matched pool shrinking with the dropped duplicate headings, r346's +3), EXTRA 175 / missing 607, body 180, tags 9557/9557, every widget verifier at its standing baseline (speechBubble defect 4; math 322/323 — the 1 = PES1007's pre-existing page-tail loss, named), 14 selftests GREEN (13 + the new math verifier). Ship ledger: FULL at r347 (counter 0, 8 of headroom). Plateau window (both §4 conditions): r344 moved ≥75 / cs → r345 0.000 alone (1 of 3) → r346 moved ≥50 / cs (restart) → **r347 +0.001 with nothing else moved = 1 of 3**.
- Tree: `verify_after_transfer.sh` PASS (the engine manifest refreshed at r344 / r345 / r346 / r347 — backups `CHECKSUMS__engine.pre-r34N.bak`; the gates manifest refreshed at r346 (83 entries, `_verify_math.cjs` added) and r347 (its lost-letter check) — backups `CHECKSUMS__gates.pre-r346.bak` / `.pre-r347.bak`); the corpus on disk is r347's (2110 pages / 416 modules, a full regeneration — every earlier scoped ship's output re-derived and byte-identical but for the 1,225 table pages).
- Lessons this session, for the tools: (1) a Python heredoc through the shell turns `\\b` / `\\uE010` into the literal characters — build such regex text with `chr(92)` or write the tool with the editor and check `repr`; (2) a writer that opens the target BEFORE encoding can truncate an engine file to 0 bytes on an encode error (r347 — `DocxExtractor.js`, rewritten from the HEAD blob with `git show`, no checkout) — encode first, then open (`_r347_splice.py` / `_r347_finalise.py` do); (3) the OFF probe of a NEW round is also the audit of the LAST round (r347's OFF probe found r346's math-italic letters); (4) the batch runner's oembed-cache write race under 4 workers hits ~3 of 36 batches — re-run those singly, rc 0 every time.

""")
KEY = "## >>> STOPPED 2026-09-16 ≈20:45 NZST (session 12)"
ANCH = "## >>> STOPPED 2026-09-16 ≈17:20 NZST (session 11)"
if KEY not in s:
    assert s.count(ANCH) == 1; s = s.replace(ANCH, BANNER + ANCH, 1); print("banner")

PICK = L("""## Session 12 · Round 5 PICK-in-progress (engine r348 — D10-9: c23 / 01B lesson-menu labels everywhere) — PRE-MEASUREMENT ONLY, 2026-09-16 20:29–20:35 NZST; no code, no data edit; the tree is r347's
- **Class:** Chris's D10-9 (Option A, verbatim in "Decisions from Chris (session 10)"): inside `#module-menu-content` on every LESSON page — every learning / success LABEL is `<h5>` by a ROLE classifier (not the r117 phrase list); the wording NORMALISED per 01B 240–244 (learning `We are learning:`; success `I can:` years 7–10 / `You will show your understanding by:` years 1–6; the writer's label kept where the level is unknown); NO section title above the labels (01B 223); the r81 eng-family `<p>` skip retired; the c70 OSSC "Ākonga will …" lead-in SENTENCE stays a `<p>`; the OVERVIEW tab's labels `<h5>` too (its `<h4><span>` titles stay). Verifier `_verify_menulabels`; FULL regeneration; a named override ≈ −0.1pp.
- **Pre-measurement (`outputs/_measure_r348_menulabels.py` → `_r348_menulabels.{json,log}`; 1,056 paired lesson pages with a menu on both sides; the r341 void-aware parser):**
  (a) **The year-level table does not exist in the data.** `Module_Structure_Index.json` `module_meta` carries subject / template_type / prefix / phase / series / dev_order — no year — and the code's level digit is NOT a year (digit 1 = NCEA1 AGH10 / HIS10 / PES10 = years 11+, all `You will show…`; the 1–10 series' digit 1–3 is MIXED at every digit: 1 → YWS 189 / I-can 112, 2 → 88 / 73, 3 → 134 / 71; digit 4 → I-can 91 / 9; 5 → I-can 77; 0 (XLP / XFUN) → I-can). Per MODULE the gold is consistent (only 6 of ~130 modules mix both forms: BLL240, ENGI103, ENGI302, ENGJ402, ENGS302, ENGS401), so a per-module year table would work, a per-series one would not. **Consequence for the round: the wording-normalisation half falls back to the writer's own label on EVERY module (01B's "level unknown" clause, as Chris's answer allows) unless a year table arrives as data (`Module_Structure_Index.module_meta.year` or a KB file — a KB / data session, NOT something to ask Chris again; ship the hook, fill it later).** What CAN be normalised without a year: the label's FORM (trailing colon, sentence case) — measure the gold's exact strings first.
  (b) **The gold keeps a section title on 257 of 1,056 lesson pages** (`h5` "learning intentions" 161, `h5` "how will i know if i've learned it?" 126, `h3` 63 / 40, `h4` 32 / 19 …) — dropping them per 01B 223 is a NAMED override on those 257 pages (Chris's Option A accepts it; record per page).
  (c) **The ROLE classifier's input (Claude's lead-ins in the menu, with the gold's tag for the same label):** success `you will show your …` 367 (gold h5 195 / absent 116 / p 28 / h3 15 / h4 13), learning `we are learning` 290 (h5 195 / p 86), success `i can` 277 (h5 151 / p 98 / absent 18 / h3 10), learning `we are learning to` 236 (h5 151 / p 50 / h4 14 / h3 12), `learning intentions` 130 (h5 76 / h3 27 / absent 19 / h4 8), `we are learning about` 115 (h5 71 / p 29 / h3 13), success `you will be able to` 22 (gold p 22 — the c70-style sentence, NOT a label: exclude), `how will i know` 16 (h3 8 / absent 8), the OSSC `ākonga can / will …` family 13 + 13 + 9 + 7 + 4 + 3 + 2 (gold p / absent — the c70 lead-in sentence, stays `<p>`), `success criteria` 6 (h4 5). The classifier: a menu leaf whose folded text starts with a LEARNING lead-in (`we are learning`, `learning intention(s)`, `what are we learning`, `students will`, `i am learning to`, `walt`) or a SUCCESS lead-in (`i can`, `you will show / demonstrate your understanding`, `success criteria`, `how will i know`, `wilf`) is a label; `ākonga will / can …` and `you will be able to …` are sentences (c70) and stay `<p>`. The "absent" gold column (116 + 19 + 18 …) = pages where the gold has no such label at all (the human dropped or rewrote the menu) — named, not chased.
- **Steps for the next session:** PICK ✔ (this) → MEASURE the gold's exact label strings for the form half (colon / case; 10 min) → IMPLEMENT behind a data flag (`Module_Menu_Scaffold.json` or the menu builder's data: `menu_labels.kb_form` {enabled, env `MENULABEL_OFF`, role_lexicon {learning, success, sentence}, drop_titles, overview_h5, year_table {}}) → the new protected verifier `_verify_menulabels.cjs` (every label `<h5>`, no title above, the c70 sentence `<p>`; selftest INJECT) → PROBE all 416 (OFF = disk 2110/2110 — the tree is r347's full ship) → FULL regeneration (the r347 runner `_r347_fullship_par.sh` pattern; the race batches re-run singly) → gates → skeleton JSON + movers vs `_r347_sk_final.json` (expect ≈ −0.1pp, every dip a named override: the 257 title pages + the gold-`p` label pages) → finalise (`_r348_finalise.py` from the r347 one) → mirror + checksums + verify → commit. Budget: one full session round (~60–75 min).

""")
PK = "## Session 12 · Round 5 PICK-in-progress (engine r348 — D10-9"
PA = "## Session 12 · Round 4 (engine r347 — D10-5) — what shipped"
if PK not in s:
    assert s.count(PA) == 1; s = s.replace(PA, PICK + PA, 1); print("pick")

ROW = L("- s12-pick5 (no engine round) · D10-9 PRE-MEASUREMENT (`_measure_r348_menulabels.py`): the year-level table 01B 240–244 needs does not exist in the data (module_meta has no year; the code digit is not a year; the gold's success wording is mixed at every digit but consistent per module — 6 mixed modules) → the wording half falls back to the writer's label (01B's level-unknown clause) with a data hook; the gold keeps a section title on 257 / 1,056 lesson pages (named override under Option A); the role classifier's lead-in inventory with the gold's tag per lead-in recorded; `you will be able to…` and the OSSC `ākonga will / can…` are c70 sentences, not labels. The round starts at IMPLEMENT next session.\n")
RA = "- s12-r4 (engine r347, D10-5)"
if "- s12-pick5 (no engine round)" not in s:
    i = s.find(RA); assert i > 0; j = s.find(nl, i) + len(nl); s = s[:j] + ROW + s[j:]; print("round log")

NEXT = L("""
**Next session starts with:** the standing §7 kickoff (`/loop-start`); health check (`verify_after_transfer.sh` PASS — engine + gates manifests refreshed at r347); `git status` in pageforge-site: expect a CLEAN tree at the session-12 stop commit (on top of r347 = acbd5a5) — nothing to reconcile; then Chris's session-10 queue from **item 6 — r348, D10-9 (c23 / 01B lesson-menu labels everywhere)**: its PICK + pre-measurement are recorded above ("Session 12 · Round 5 PICK-in-progress (engine r348 — D10-9)") — begin at the gold's exact label-string measurement (the form half), then IMPLEMENT behind the data flag (the year-level table is a hook the data does not yet fill — the writer's wording is kept, never re-ask Chris), the new protected verifier `_verify_menulabels.cjs`, probe all 416 (OFF = disk 2110/2110), FULL regeneration, gates, finalise, commit; then item 7 (D10-3 widget-build kickoffs, one type per round, largest first: dragAndDrop → clickDrop → accordion → …) and the ordinary §3 PICKs. The scorecard baseline is the r347 state (`_r347_sk_final.json`: SCAFFOLD 51.283% = 55.8% of achievable, 1955 pairs, ceiling 91.9%); the ship ledger is at 0 after the r347 full ship (8 scoped ships of headroom); the plateau window stands at 1 of 3. Every recorded decision (D10-1 … D10-9) is settled — never re-ask.
""")
if "expect a CLEAN tree at the session-12 stop commit" not in s:
    s = s.rstrip("\r\n") + nl + NEXT; print("next-session line")
with io.open(LS, "wb") as f: f.write(s.encode("utf-8"))
print("LOOP_STATE.md written")
