#!/usr/bin/env python3
"""Session 13 stop (2026-09-16 ≈22:50 NZST) on the BUDGET rule — writes the r350 PICK-in-progress (the D10-3 dragAndDrop
kickoff measurement), the session-13 stop banner, the session line's result, and the "Next session starts with:" line into
LOOP_STATE.md. Idempotent; LF kept."""
import io, os
HERE = os.path.dirname(os.path.abspath(__file__))
LS = os.path.normpath(os.path.join(HERE, "..", "..", "LOOP_STATE.md"))
s = io.open(LS, encoding="utf-8", newline="").read()

PICK = """## Session 13 · Round 3 PICK-in-progress (build round r350 — D10-3 item 7: the dragAndDrop kickoff, shape family 1) — MEASUREMENT ONLY, 2026-09-16 22:14–22:45 NZST; no code, no data edit; the tree is r349's
- **Class:** Chris's D10-3 (Option A, verbatim in "Decisions from Chris (session 10)"): widget-BUILD rounds, one type per kickoff, largest un-built population first — **dragAndDrop** (the fresh dashboard: 824 un-built sites / 583 pages / 291 modules, 681 shapes); each round takes the type's largest un-built authoring SHAPE family ≥ 20 sites, builds the WRITER's tag to the KB 03B form (A1 — judged on the widget's OWN verifier, never on the human's substitution; never half-build), regenerates the whole type family (§0b — ≈ 309 modules, near-full), the dashboard's *Still a box* count is the plateau "moved" test.
- **Done this session (the §4 amendment's opening step):** `COVERAGE_DASHBOARD.md` REGENERATED at 22:17 (`_r350_dashboard_run.sh`: the r271 variation census 16 shards + merge — 2521 of 4953 writer-tagged widgets build = 50.9%; the r286 all-type decline recorder 16 shards + merge — 10,119 bundles / 3,606 built; `--refresh`). Its three freshness WARNs are the r288 over-broad guard reading the UI-only `Config.js` bump (CLAUDE.md §16 already queues narrowing it) — the census itself is fresh.
- **The r286 decline recorder's dragAndDrop verdicts** (`_r350_dd_declines.log`; 1,089 declined bundles / 292 modules, 84 built / 45): by the builder's deciding guard — `width !== 2` **293** (the 3+-column table), `tables.length !== 1` **287** (prose 200 / multi-table 120), `#hasRedText` **182** (a 2-column table with red writer text), `media` **148** (an image-carrying bundle), `extraTypes` 103, `!label || !answer` 26, a URL in a cell 22. The builder today handles ONE shape: a 2-column `label | answer` table with distinct answers (the KB `layout="standard"`).
- **The finer measurement (`_measure_r350_ddcolumn.cjs` → `_r350_ddcolumn.{json,log}`; every dragAndDrop bundle's table dumped over the 297 modules that carry one — 882 bundles, 58 built / 824 declined):**
  (a) the **3+-column family is NOT one authoring shape** — 323 declined bundles / 270 pages / 171 modules split into: "no clean header, red text" 104, image / media 93, a ONE-row table (word tiles — sentence building: `is | Sant | the | tins. | at`, BLL 12 / XTAS 5 / CEDO 4) 39, a full grid (BLL133 `fluff doll less / fill cuff gloss` — a word-sort whose header IS the first row of items) 32 + 12 red, "no clean header" 21, and the CLEAN category sorts only **22** (header = categories, items under their column 11 + 6 red, a pool with no answer 4 + 1 — ENGR301 1.0's `Agree | Neutral | Disagree` + one ` / `-separated cell = the gold's `layout="column"` with `option="any"`);
  (b) **the gold's column sorts carry NUMBERED answers** (387 `layout="column"` widgets in these modules: 4,691 `option="N"` drops vs 24 `option="any"`), so the writer's answers must sit in the red `[correct answers]` cells — that sub-family is **40 bundles / 35 pages / 26 modules** (BLL 26) and is itself three shapes: category columns with `[correct answers] / knife / know / knee` per column (BLL250 2.1), `item | Correct answer` two-column (BLL167 audio riddles, BLL112 image → word), and the phonics `[Audio] | Image | Correct answer` three-column (BLL250 2.1 / 2.2 — r342's audio-word shape; the gold builds `audioButton` 711 + `wordDrag` 47 in these modules);
  (c) **the IMAGE / media family is the largest coherent one** — 316 declined bundles / 252 pages / 174 modules (BLL 116, ENGI 20, XGF 13, ENFUN 12): prose + images (no table) 66, two tables 18, `image | word` two-column (url in col 0; 5–7 rows) ≈ 40, `audio | image | answer` three-column ≈ 30, image-in-every-cell grids ≈ 20 …; the gold's widgets in those modules: `layout="standard"` 149, `noBG column` 94, `column` 87, FIB 67, scatter 57, `autoCheck standard` 48, `images standard` only 22 — the human substitutes freely (A1: the writer's tag is still the target);
  (d) the 2-column declines: 229, of which repeated-answer categorisation (the builder's own bail) only 5.
- **Consequence for the kickoff (recorded, not re-asked):** the r286 guard names a GUARD, not a shape; sized by AUTHORING shape the candidates ≥ 20 sites are, largest first: **(1) the image D&D `image | word` two-column standard form** (≈ 40 bundles + the r286 `media` guard's 148 — needs the sub-shape count per exact column pattern and the KB 03B `dragAndDrop images` form: text in `questionContainer` col-7, images in `dragContainer` col-5 (constraint 26), NO `loading="lazy"` (c83), the iStock filename from the URL (`#istockFilename`, the speechBubble precedent), 6+ items → the empty-`ddColumn` distribution rule); **(2) the `[correct answers]` category sort** (40 / 26 — `layout="column"`, `option="N"` from the column index, the red run stripped; three sub-shapes to fence); **(3) the one-row word-tile table** (39 / 29 — which KB layout the gold uses for sentence building is unmeasured: FIB 67 / scatter 57 in the family); **(4) the clean category sort** (22 — `option="any"` when one pooled cell, `option="N"` when items sit under their column). Every one needs a NEW `_verify_dragdrop.cjs` (no dragAndDrop verifier exists — A1 needs one: per module, every built widget well-formed to 03B — a `dropContainer` / `dragContainer` pair, drags ⊆ drops by `option`, no raw `[tag]`, no `loading="lazy"`; selftest INJECT) BEFORE the first build ships.
- **Why it stopped here (§4 BUDGET):** at 22:45 the session had 89 minutes to its 00:14 hard stop; a build round = the builder extension + the new verifier + a ≈ 300-module family regeneration + the gates + a fresh dashboard ≈ 2 hours. Rather than leave a half-built widget round (the sessions 11–12 pattern), the measurement is recorded and the round starts at TRIANGULATE next session.
- **Steps for the next session:** TRIANGULATE 3 modules of shape (1) — raw WT table → gold widget → Claude's hand-off box (BLL112 1.0 `image → sit / tap`, an ENGI and an XGF site) → MEASURE the exact column pattern census for shape (1) (`_r350_ddcolumn.json` has every table — a 10-minute classifier) → write `_verify_dragdrop.cjs` (+ the selftest spec + `run_all_gates.sh`) → IMPLEMENT behind `interactive_builders.dragAndDrop.images` {enabled, env `DDIMAGES_OFF`} → PROBE all 416 (OFF = disk 2110/2110) → the §0b family regeneration (every module carrying a dragAndDrop tag ≈ 309 + the working half) → gates + `_verify_dragdrop.cjs` over the whole family → the dashboard regenerated (*Still a box* must fall by ≥ 20) → finalise (`_r349_finalise.py` as the pattern) → commit. Budget: one full session round.

"""
ANCHOR = "## Session 13 · Round 2 (engine r349 — D10-9) — what shipped"
if "## Session 13 · Round 3 PICK-in-progress (build round r350" not in s:
    assert s.count(ANCHOR) == 1; s = s.replace(ANCHOR, PICK + ANCHOR, 1); print("r350 PICK written")

BANNER = """## >>> STOPPED 2026-09-16 ≈22:55 NZST (session 13) on the BUDGET rule (§4 — the 3-hour cap Chris set, hard stop 00:14; the ~89 minutes left after the r350 measurement were less than a widget-BUILD round needs to ship AND prove — a builder extension, a NEW dragAndDrop verifier, a ≈ 300-module family regeneration, the gates and a fresh dashboard ≈ 2 hours — so the D10-3 kickoff's measurement was completed and recorded instead of a half-built round): TWO rounds shipped — r348 (the tooling round the 16 Sept review queued: `_verify_speechbubble.cjs` / `_verify_math.cjs` read their per-module baseline from `gate_baseline.json` and print ✓ at baseline / ✗ only above it; the batch runner's oembed-cache race closed; `09156f8`) and r349 (Chris's D10-9 — every learning / success label in the module menu is the KB's `<h5>` colon form, the "We are learning to:" family normalised with "to …" items, lesson-page titles above a label dropped, the overview tab's labels `<h5>`, the c70 sentence kept; a NEW protected verifier `_verify_menulabels.cjs`; the SECOND batch-runner race (`batch_results.json`) closed; FULL regeneration of all 416 — 715 pages / 319 modules; `88f595c`). Chris's session-10 queue is now at **item 7 — D10-3, the dragAndDrop build kickoff** (its measurement is recorded below: "Session 13 · Round 3 PICK-in-progress (build round r350)"); the ordinary §3 PICKs follow the kickoffs. Nothing BLOCKED this session. <<<
- Scorecard at the stop (the r343 population — 1955 pairs, ceiling 91.9%): SCAFFOLD **50.965% = 55.5% of achievable** (session start 51.283% = 55.8%; r348 0.000 (tooling) / r349 **−0.318pp = a NAMED KB-over-gold override** — the LESSON half of D10-9 +0.063pp, the OVERVIEW half Chris chose in D10-9 (f) −0.375pp (164 overview pages, BLL 87 — its two-column overview menu keeps `<p>` labels in the gold on 154 of 179); every one of the 322 movers inside the 715 changed pages), RAW 35.049% (from 35.409%), ≥50 **1072** (from 1074; 9 down / 7 up, named) / ≥75 **159** (from 198 — 39 named overview pages: BLL 32, ENG 6, ANZH105, SCPH301_5) / ≥90 **14** (from 15 — ENGI401_0_0), clean 2080/2103 = 98.91%, leak 26/23, cs exact 11464 / EXTRA 175 / missing 607, body 180, tags 9557/9557, every widget verifier ✓ at its recorded baseline (speechBubble 4, math 322/323 — now printed as ✓, r348) and the new menulabels 91 / 0 — **the first fully green gate suite**; 15 selftests GREEN. Ship ledger: FULL at r349 (counter 0, 8 of headroom). Plateau window: r349's PICK predicted a move and it moved 0.318pp → **0 of 3** (r348 was gate-configuration, outside the window). **The D10-9 estimate was ≈ −0.1pp; the overview half alone measured −0.375pp — reported to Chris in the §5 report with the one-flag reversal (`menu.lesson_label_form.overview_labels: false` keeps the lesson half and reverts the overview half); it is a decided item and was not re-asked (§5b).**
- Tree: `verify_after_transfer.sh` PASS (the engine manifest refreshed at r348 / r349 — backups `CHECKSUMS__engine.pre-r348.bak` / `.pre-r349.bak`; the gates manifest refreshed at r348 (the two verifiers + `batch_convert.cjs`) and r349 (84 entries, `_verify_menulabels.cjs` added) — backups `.pre-r348.bak` / `.pre-r349.bak`); the corpus on disk is r349's (2110 pages / 416 modules, a full regeneration); `COVERAGE_DASHBOARD.md` regenerated 22:17 on the r349 corpus (interactive coverage 50.9%, un-built dragAndDrop 824 / 291 modules); git CLEAN at the session-13 stop commit (r349 = 88f595c beneath it).
- Lessons this session, for the tools: (1) the "≈ 3 of 36 batches" race was TWO files — the oembed cache (r348) and `batch_results.json` (r349); both saves are now atomic + merged + torn-tolerant on read, and the four r349 race batches re-ran IN PARALLEL rc 0 — the next full regeneration is the test of 0; (2) a `<h5 eng>` attribute is invisible to a whole-corpus diff until the §0b whole-family probe runs — the r349 attrs patch came from PNR101 in the OFF/ON probe, not from any gate; (3) a heredoc through the shell still eats `\\b` / `\\u{…}` — write patch scripts with the editor (r349's `_r349_patch_attrs.py`); (4) a module list written by Windows Python is CRLF — every probe that takes `$(cat list)` needs the r349 `.replace(/\\r/g, "")` guard; (5) a WAITING-on-Chris item in a decided class is reported, never re-asked — the overview half's cost went into the report with its one-flag reversal, and the round shipped as decided.

"""
B_ANCHOR = "## >>> STOPPED 2026-09-16 ≈20:45 NZST (session 12)"
if "## >>> STOPPED 2026-09-16 ≈22:55 NZST (session 13)" not in s:
    assert s.count(B_ANCHOR) == 1; s = s.replace(B_ANCHOR, BANNER + B_ANCHOR, 1); print("stop banner written")

OLD_NEXT_HEAD = "**Next session starts with:** the standing §7 kickoff (`/loop-start`); health check (`verify_after_transfer.sh` PASS — engine + gates manifests refreshed at r347);"
NEW_NEXT = ("**Next session starts with:** the standing §7 kickoff (`/loop-start`); health check (`verify_after_transfer.sh` PASS — engine + gates manifests refreshed at r349); `git status` in pageforge-site: expect a CLEAN tree at the session-13 stop commit (on top of r349 = 88f595c) — nothing to reconcile; note the KB HEAD (§0) against `KB_AMALGAMATION_STATUS.md` (469f496 at this stop); then Chris's session-10 queue from **item 7 — the D10-3 dragAndDrop build kickoff, round r350**: its measurement is recorded above (\"Session 13 · Round 3 PICK-in-progress (build round r350)\") — begin at the TRIANGULATION of shape (1), the image D&D `image | word` two-column standard form (BLL112 1.0, an ENGI and an XGF site), then the exact column-pattern census from `_r350_ddcolumn.json`, then the NEW `_verify_dragdrop.cjs` BEFORE any build ships, the builder extension behind a data flag + env toggle, probe all 416 (OFF = disk 2110/2110), the §0b family regeneration (≈ 309 modules), gates + the verifier over the whole family, the dashboard regenerated (*Still a box* must fall by ≥ 20), finalise, commit; the kickoff continues shape by shape ((2) the `[correct answers]` category sort 40 / 26, (3) the one-row word tiles 39 / 29, (4) the clean category sorts 22) until no shape family ≥ 20 sites remains, then clickDrop. The scorecard baseline for every later round is the r349 state (`_r349_sk_final.json`: SCAFFOLD 50.965% = 55.5% of achievable, 1955 pairs, ceiling 91.9%); the ship ledger is at 0 after the r349 full ship (8 scoped ships of headroom); the plateau window stands at 0 of 3. Every recorded decision (D10-1 … D10-9) is settled — never re-ask; the overview half of D10-9 is reported (its measured cost and the one-flag reversal), not re-asked. Queued tooling (no round needed unless Chris asks): narrow `_coverage_dashboard.py`'s freshness guard to the engine's `data_map` + non-UI engine files (the r288 `_stalecheck.sh` pattern — CLAUDE.md §16) so a `Config.js` bump stops printing three false WARNs.\n\n"
            "*(The session-12 line that follows is kept for the record.)* **Session 12's next-session line was:** the standing §7 kickoff (`/loop-start`); health check (`verify_after_transfer.sh` PASS — engine + gates manifests refreshed at r347);")
if "the session-13 stop commit (on top of r349 = 88f595c)" not in s:
    assert s.count(OLD_NEXT_HEAD) == 1, "next-session anchor"; s = s.replace(OLD_NEXT_HEAD, NEW_NEXT, 1); print("next-session line written")

# the session-13 line's result
OLD_S13 = "Plateau window carried: 1 of 3 (r347). Ship ledger: FULL at r347 (counter 0, 8 of headroom).\n"
NEW_S13 = ("Plateau window carried: 1 of 3 (r347). Ship ledger: FULL at r347 (counter 0, 8 of headroom). **Session 13 result: r348 (the two red-at-baseline verifiers read ✓ at their per-module baseline; the oembed-cache race closed; tooling, gate-neutral; commit 09156f8) · r349 (D10-9 — every menu label the KB's `<h5>` colon form, FULL regeneration 715 pages / 319 modules, −0.318pp = a named override: lesson half +0.063 / overview half −0.375; the second batch-runner race closed; commit 88f595c) · r350 (D10-3 dragAndDrop kickoff) MEASURED, not started — STOPPED ≈22:55 on the BUDGET rule (89 minutes left, less than a build round needs).** No automatic compaction occurred this session (§6 — recorded as none).\n")
if "**Session 13 result:" not in s:
    assert s.count(OLD_S13) == 1, "session line anchor"; s = s.replace(OLD_S13, NEW_S13, 1); print("session line written")

# round log: the r350 measurement line
OLD_R = "- s13-r2 (engine r349, D10-9)"
i = s.find(OLD_R); assert i > 0
NEW_R = "- s13-r3 (build round r350, D10-3 dragAndDrop kickoff) · MEASURED, not started · the dashboard regenerated (coverage 50.9%, un-built D&D 824 / 291 modules); the r286 decline recorder + a table dump over every D&D bundle: the 3+-column family is not one shape (clean category sorts 22, `[correct answers]` sorts 40 / 26 modules, one-row word tiles 39 / 29, image / media 316 bundles / 174 modules = the largest coherent shape); a NEW `_verify_dragdrop.cjs` is needed before any build ships · pages moved 0 · no commit of its own (recorded in the session-13 stop commit) · STOPPED on the BUDGET rule ≈22:55\n"
if "- s13-r3 (build round r350" not in s:
    s = s[:i] + NEW_R + s[i:]; print("round log written")
io.open(LS, "w", encoding="utf-8", newline="").write(s); print("LOOP_STATE.md written")
