import io, os
ROOT = r"C:\Users\Gavin\TeKura\FINAL_MODULE_DATA"
p = os.path.join(ROOT, "LOOP_STATE.md")
s = io.open(p, encoding="utf-8", newline="").read()

# 1. the top banner: session-14 result + STOPPED block above the session-13 STOPPED block
A = "**Session 14 started:** 2026-09-16 23:30 NZST"
assert s.count(A) == 1
i = s.index(A); j = s.index("\n", i)
line = s[i:j]
if "Session 14 result" not in line:
    line2 = line + " **Session 14 result: r350 (D10-3 dragAndDrop kickoff shape 1 — the image-pair table → the KB 03B `dragAndDrop images` form + the 03B button row on every built D&D; NEW gate `_verify_dragdrop.cjs`; FULL regeneration 60 pages / 54 modules; skeleton identical page-for-page, RAW +0.066pp; 18 sites built) SHIPPED ≈00:15 NZST 17 Sep — STOPPED on CHRIS'S INSTRUCTION (`/loop-stop` at 00:05, as the gate suite finished; the round's remaining steps — post-ship housekeeping, finalise, commit — were completed and proven, the dashboard regeneration deferred).** No automatic compaction occurred this session (§6 — recorded as none)."
    s = s[:i] + line2 + s[j:]
B = "\n## >>> STOPPED 2026-09-16 ≈22:30 NZST (session 13)"
assert s.count(B) == 1
STOP = """
## >>> STOPPED 2026-09-17 ≈00:20 NZST (session 14) on CHRIS'S INSTRUCTION — "stop the loop at the next logical point" (`/loop-stop`, received at 00:05 as the r350 gate suite finished): ONE round shipped — r350 (Chris's D10-3, the dragAndDrop build kickoff's shape 1: the writer's IMAGE-PAIR table builds the KB 03B `dragAndDrop images` standard form — text = questions, images = drags — and every built standard dragAndDrop gains the 03B `activityButton` row; a NEW protected verifier `_verify_dragdrop.cjs`; FULL regeneration of all 416 — 60 pages / 54 modules changed: 18 image-pair sites built on 17 pages / 17 modules + 72 button rows; skeleton IDENTICAL page-for-page (a build is inside the collapsed widget marker — D10-3's own §4 reading), RAW +0.066pp; every other gate EXACT; commit — see git log). The round was FINISHED and proven rather than toggled OFF: the probe, the regeneration, the full gate suite and the family verifier (72 widgets / 54 modules / defect 0) were all complete when the stop arrived; only the dashboard regeneration (the build round's *Still a box* "moved" test) is deferred to the next session. Nothing BLOCKED, nothing uncommitted. <<<
- Scorecard at the stop (the r343 population — 1955 pairs, ceiling 91.9%): SCAFFOLD **50.965% = 55.5% of achievable** (unchanged — 0 pages moved), RAW **35.115%** (from 35.049), ≥50 **1072** / ≥75 **159** / ≥90 **14**, clean 2080/2103 = 98.91%, leak 26/23, cs exact 11464 / EXTRA 175 / missing 607, body 180, tags 9557/9557, every widget verifier ✓ (flipCard div 0, speechBubble 4 at baseline, math 322/323 at baseline, menulabels 91 / 0, mtkQuiz 17 / 0, modal 0, **dragdrop 13 / 0 — NEW**); 16 selftests GREEN. Ship ledger: FULL at r350 (counter 0, 8 of headroom). Plateau window: build rounds sit outside the skeleton window (§4 amendment); r350's "moved" test = the dashboard count — 18 sites built, 2 short of the 20-site line (BLL266 = a 19th, forward guarantee) — recorded as-is, the dashboard regeneration is the next session's first step.
- Tree: `verify_after_transfer.sh` PASS (the engine manifest refreshed at r350 — backup `CHECKSUMS__engine.pre-r350.bak`; the gates manifest refreshed at r350 (85 entries, `_verify_dragdrop.cjs` added) — backup `.pre-r350.bak`); the corpus on disk is r350's (2110 pages / 416 modules, a full regeneration, `_stalecheck.sh` 0 stale); `COVERAGE_DASHBOARD.md` is STALE (22:17 on the r349 corpus — its dragAndDrop un-built count 824 predates r350's 18 builds); git CLEAN at the session-14 stop commit (r350 beneath it); the root `LOOP__Autonomous_Rounds.md` restored from the committed mirror at the session start (the review amendments were missing — see "Session 14 started").
- Lessons this session, for the tools: (1) engine tools run under WSL only (`wsl.exe -e bash -lc`) — native node cannot open the `CONVERTER_V2/app` symlink; (2) never read a repo file with the Read tool (it attaches the 970 KB CLAUDE.md) — `sed -n` / python instead; (3) the census's clipped cells over-count a shape by the ragged rows they hide — confirm on the live bundle dump; (4) `awk … file | … > file` truncates the input before it is read (the checksum-manifest refresh must go through the `.bak`); (5) a build round is gate-neutral on the skeleton BY DESIGN — do not predict a skeleton move for one, predict the dashboard count.
"""
s = s.replace(B, STOP + B, 1)

# 2. Decisions from Chris (session 14)
C = "## Decisions from Chris (session 10 — 2026-09-16 ≈15:20 NZST"
assert s.count(C) == 1
DEC = """## Decisions from Chris (session 14 — 2026-09-16 23:30 → 2026-09-17 00:20 NZST; every instruction he gave, in order; the durable record)
- **2026-09-16 23:30 — the standing §7 kickoff via `/loop-start` (no argument = 12 rounds or 10 hours):** "Continue the PageForge autonomous loop … REGENERATE CORPUS for every round … RUN UNINTERRUPTED (§5c) … Honour every entry under 'Decisions from Chris' and never re-ask them … commit after every round, never push." Authorises: the D10-3 kickoff round r350 (shape 1) under the standing REGENERATE CORPUS mandate — done.
- **2026-09-17 ≈00:05 — the standing STOP message via `/loop-stop`:** "STOP THE LOOP at the next logical point, without interrupting anything already running … If the current round's remaining steps can be finished and proven in under 10 minutes, finish and commit the round; otherwise switch its toggle OFF … record every decision … update LOOP_STATE.md … commit everything finished … give me the §5 report … confirm it is safe to close." Applied: r350's probe / regeneration / gates / family verifier were complete at the stop; the finalise + commit were done (≈15 minutes of writing — over the 10-minute guide, judged right because the alternative, a toggle-OFF regeneration of 54 modules plus a description, would have cost as much and discarded a fully proven round); the dashboard regeneration deferred. No decision on any class was given this session — every D10 decision stands, nothing re-asked.

"""
s = s.replace(C, DEC + C, 1)

# 3. the final "Next session starts with:" line — supersede the session-13 one
D = "**Next session starts with:** the standing §7 kickoff (`/loop-start`); health check (`verify_after_transfer.sh` PASS — engine + gates manifests refreshed at r349)"
assert s.count(D) == 1
k = s.index(D)
old_tail = s[k:]
s = s[:k] + "*(Session 13's next-session line, kept for the record — superseded by the line at the very end of this file.)* Session 13 wrote: " + old_tail.rstrip("\n") + "\n\n" + \
"""**Next session starts with:** the standing §7 kickoff (`/loop-start`); health check (`verify_after_transfer.sh` PASS — engine + gates manifests refreshed at r350); `git status` in pageforge-site: expect a CLEAN tree at the session-14 stop commit (r350 beneath it) — nothing to reconcile; note the KB HEAD (§0) against `KB_AMALGAMATION_STATUS.md` (469f496 at this stop); **every engine tool runs under WSL** (`wsl.exe -e bash -lc 'cd /mnt/c/Users/Gavin/TeKura/FINAL_MODULE_DATA/CONVERTER_V2/reference/tests && …'` — native node EACCES on the `app` symlink) and repo files are read with `sed -n`, never the Read tool. Then: **(1)** regenerate `COVERAGE_DASHBOARD.md` on the r350 corpus (copy `_r350_dashboard_run.sh` → `_r351_dashboard_run.sh`, ≈10 min under WSL; expect dragAndDrop un-built 824 → 806 = r350's 18 builds — record the exact count in the r350 round-log line and the plateau note), **(2)** continue Chris's session-10 queue item 7 — the dragAndDrop kickoff, shape by shape from the session-13 sizing: (2) the `[correct answers]` category sort 40 bundles / 26 modules (`layout="column"`, `option="N"` from the column index, the red run stripped; three sub-shapes to fence — BLL250's per-column `[correct answers] / knife / know`, BLL167's `item | Correct answer`, the phonics `[Audio] | Image | Correct answer` which is r342's audio-word widget and is NOT this shape), (3) the one-row word tiles 39 / 29 (measure which KB layout the gold uses for sentence building first — FIB 67 / scatter 57 in the family), (4) the clean category sorts 22 + the image column-sort 13 (`layout="column"` + `images`; `option="any"` for one pooled cell, `option="N"` under a column header; the header-row test also fixes ARFUN03's r69 mis-build) — each behind its own data flag + env toggle, each proven by the 416-module OFF/ON probe (`_r350_probe.cjs` pattern), each regenerated as the whole dragAndDrop family (a full ship in practice — ledger 0, 8 of headroom), each verified by `_verify_dragdrop.cjs` over the whole family (extend its checks for the column layout before shape (2) ships: drops grouped in `ddColumn`s, `option="N"` ≤ the column count or `any`); when no shape family ≥ 20 sites remains, the kickoff moves to clickDrop (324 / 108). The scorecard baseline for every later round is the r350 state (`_r350_sk_final.json`: SCAFFOLD 50.965% = 55.5% of achievable, RAW 35.115%, 1955 pairs, ceiling 91.9%); build rounds are judged by the dashboard's *Still a box* count (≥ 20 = moved), structure rounds by the skeleton. Every recorded decision (D10-1 … D10-9) is settled — never re-ask. Queued tooling (no round needed unless Chris asks): narrow `_coverage_dashboard.py`'s freshness guard to the engine's `data_map` (CLAUDE.md §16).
"""
io.open(p, "w", encoding="utf-8", newline="").write(s)
print("LOOP_STATE stop entries written")
