#!/usr/bin/env python3
"""SESSION 28 / TASK 1 — CONVERTER_V2_GUIDE.md: the plain-English note on the registry rebuild + the new Subject_Prefix_Map.json.
Idempotent; LF preserved. Run under WSL."""
import io, os
P = "/mnt/c/Users/Gavin/TeKura/FINAL_MODULE_DATA/pageforge-site/CONVERTER_V2_GUIDE.md"
s = io.open(P, encoding="utf-8", newline="").read()
if "Subject_Prefix_Map.json" in s:
    print("guide already updated"); raise SystemExit
OLD = ("- **Granular_Scaffold_Registry.json**, **Scaffold_Consensus.json**, **Module_Menu_Scaffold.json** — measurement outputs read only by the Python test tooling in the development harness, **not by the engine**. Safe to ignore in day-to-day work; regenerated by their build scripts.\n")
assert s.count(OLD) == 1, "A17 anchor"
NEW = OLD + (
    "- **Subject_Prefix_Map.json** (round 408, 20 Sept 2026) — the one hand-written input to the rebuild: which subject label a module-code prefix belongs to, for the prefixes the "
    "old report folders never filed (the September 2026 intake's CBI / CHI / WJFUN / PWY … and a few older ones such as BLLR and TEDC). The registry builder reads the report "
    "folders first and only fills gaps from this file. The label is what the HTML Generator's Reference-module **Subject** filter shows; a prefix with no label anywhere shows "
    "under \"All subjects\" but is never offered as a filter entry. The labels in it are marked PROPOSED until Chris approves them (the decision points are written in its `_meta`).\n"
    "\n"
    "**When the library grows (an intake), rebuild ALL of these together — never just one.** Round 263 (August 2026) shipped a module with no menus precisely because the index was "
    "rebuilt while the Style-Anchor and Menu registries were not; round 408 (September 2026) did the whole set in one pass and the recipe is in `converter-v2/CLAUDE.md` §13 "
    "(`build_granular_registry.py`, the per-family Style-Anchor mining, `derive_menu_type.cjs`, `build_convention_registry.py`, the heading lexicon, the feature index, the legacy "
    "consensus, then a probe over every module to size the regeneration). Plain-English result of round 408: the picker went from 454 to 552 library modules, every new family got "
    "its own measured page shell (which is what turned the 21 WJFUN modules from 2–5 invented pages into the one page their developers built), and the skeleton score rose "
    "53.1 % → 53.7 % with no other gate moving the wrong way.\n")
s = s.replace(OLD, NEW, 1)
io.open(P, "w", encoding="utf-8", newline="").write(s)
print("guide updated")
