#!/usr/bin/env python3
"""Round 5 PICK → LOOP_STATE.md (inserted before '## Round log'). Run under WSL."""
import io, os
R = "/mnt/c/Users/Gavin/TeKura/FINAL_MODULE_DATA/"
STATE = R + "LOOP_STATE.md"
lines = io.open(STATE, encoding="utf-8").read().split("\n")
b = next(i for i, l in enumerate(lines) if l.startswith("## Round log"))
pick = [
"## Session 29 — Round 5 PICK (engine r414) — THE NESTED ACTIVITY BOX: a synthetic widget box never opens inside an open activity box (20 Sept ≈17:40 → in progress)",
"- **Class.** Claude ships an `activity` box INSIDE another `activity` box on **108 sites / 94 pages / 65 modules**; the gold on 3 pages (11, all Mathematics — MXDI101 / MXFL101 / MXFL301, editorial). The inner box is ALWAYS `activity interactive` = the r217 SYNTHETIC standalone-widget box (`saOwner`) or the r266 level-pages box (`lvOwner`) opened while a writer's activity frame is still on the stack — the `isNewActivity` guard at the bundle site closes an open activity only for a bundle with a REAL owner / id, and the synthetic owners are decided AFTER it. The outer is a bundle-owned `activity interactive` whose frame stayed open after its own widget (77), a plain writer box (22) or a super-content box (9). Found through the empty-shell census (`_s29_r5_emptyrows.py` → `_s29_r5_emptyrows.out`: 818 empty `row › col` shells, 725 of them the MODULE MENU's `moduleMenu › row › col-md-8` shell on pages whose gold menu has TEXT (445, class C content) or no menu element at all (56, FRFUN 25 — the family's `menu_type`, a registry question); the 154 body shells decompose to the r378 / r314 held-frame `breakRow()` running with the outer box still open (76), 38 writer-owned EMPTY boxes, 14 HPFUN omitted-prompt rows (r203) — the nested box is the mechanism behind the 76: the inner box's close pops the outer's inner `row › col-12`, and the outer's own close then lands in a fresh `row › col-md-8` shell).",
"- **Measured** (`_s29_r5_nestbox.py` → `_s29_r5_nestbox.out`, every nested pair on a paired page, the inner box's text found in the gold): 97 pairs / 84 pages / 63 modules; decided 43 — the gold keeps the widget INSIDE the outer's box 19 (BLL 10 / 10 — the phonics multi-widget box, the r229 CL-0030 record), starts a SEPARATE box 18 (Mathematics 5 / 6, English 3 / 3, FRFUN 4 / 4, NCEA1 3), no box 6; 54 ABSENT (the gold's built widget carries different words). By group: BLL 26 pages / 23 modules, NCEA1 18 / 9, Mathematics 12 / 8, LtL 10 / 4, English 9 / 8, FRFUN 4 / 1. The nesting itself is 0.97 wrong in every group; the un-nesting FORM splits by family. NEW-FAMILY CHECK: WJFUN 1 page, FRFUN 4 — the class holds without the intake families.",
"- **Authority:** §1b (2) — the gold never nests an activity box (KB 01F: one box per numbered task); the engine's own `isNewActivity` convention (a new activity bundle closes any still-open activity) extended to the synthetic owners.",
"- **Fix (planned):** `activity_wrapper.standalone_widget_box.inside_open_activity {enabled, env NESTBOX_OFF, keep_inside_subjects: [\"1-10 Blended Literacy\"]}` — at the bundle site, when the synthetic owner (`saOwner` / `lvOwner`) is about to open and the stack top is an `activity`: CLOSE the outer first (the inner becomes the writer's next sibling box with the next positional letter — Mathematics / English / FRFUN), or in a `keep_inside_subjects` module SUPPRESS the synthetic box so the widget renders inside the open box (BLL). Score both forms per subject with `_skeleton_compare.match()` on the probe's ON pages before regenerating.",
"- **Not taken, recorded:** the module-menu empty shell (725 — right where the gold's menu has content; where the gold ships NO menu element the fix is a family `menu_type` row: FRFUN 25 / 26 lesson pages, ConnectED 13); the 38 writer-owned empty boxes (the gold's box count exceeds Claude's — the r379 `[Activity: Embedded – Brainstorm]` class); the 14 HPFUN omitted-prompt rows.",
"",
]
lines[b:b] = pick
io.open(STATE, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
print("LOOP_STATE.md", os.path.getsize(STATE), "bytes")
