#!/usr/bin/env python3
"""Round 9 PICK → LOOP_STATE.md (inserted before '## Round log'). Run under WSL."""
import io, os
R = "/mnt/c/Users/Gavin/TeKura/FINAL_MODULE_DATA/"
STATE = R + "LOOP_STATE.md"
lines = io.open(STATE, encoding="utf-8").read().split("\n")
b = next(i for i, l in enumerate(lines) if l.startswith("## Round log"))
pick = [
"## Session 29 — Round 9 PICK (engine r418) — THE FIRST TILE PANEL TAKES THE `row.clickDropContent.noBorder` FORM + the r417 title-pin repair (20 Sept ≈21:50 → in progress; scoped ship #2 since the r416 FULL)",
"- **Class (two parts, one family, the same 30 pages).** (a) The r417 bare panel LOST the r334 title pin: `activityTitleLevelPostpass`'s `titleRe` reads `<div class=\"row\"><div class=\"col-12\"><h…` after the box open, so the bare panel's first heading stayed at the relevel level — 114 of 179 panels ship `<h5>` where the gold (and the r416 disk) has `<h3>` (XDLS903 14 / 36, 904 36 / 36, 905 35 / 35, 906 29 / 29; XDLS902's writer typed `[H3]`). A defect r417 introduced under the gates' noses (the row / col removal outweighed it: 30 up / 0 down) — repaired, not reverted (the r293b rule). (b) The gold's FIRST panel on every tile-grid page is the ROW form: `<div class=\"row clickDropContent noBorder\"><div class=\"col-12 col-md-8\"><div class=\"activity dropbox\" number=\"2A\">` — the `clickDropContent` token on the section ROW, not the box (the JS's first `.clickDropContent` shows open, `noBorder`); the later panels keep `clickDropContent activity dropbox` on the box.",
"- **Measured** (`_s29_r9_panelforms.py` → `_s29_r9_panelforms.out`, every paired page of XDLS902–906 + 909): the first panel is the row form on **35 / 35** pages of 902–906 (XDLS902 lessons 2–7 carry ALL six panels in the row form — the module's own extension; lesson 1 first-only; 903–906 7 / 7 each first-only); the row's class string `row clickDropContent noBorder` 65 / 65, the col `col-12 col-md-8` 64 / 65 (one `col-md-10`), the box `activity dropbox` (no `clickDropContent` token) 65 / 65. Claude wraps every panel in the plain section row `row > col-md-8 col-12` with the token on the box. XDLS909 (Claude has no tile grid there) = all direct. Floor: 35 pages ≥ 20 ✓; intake-free family.",
"- **Also measured, DECLINED (record):** DIFF_QUEUE #1035 — the per-panel `Upload to dropbox` button (Claude 157 buttons on 39 pages, one per writer `[3 buttons – film, camera and microphone] Upload to dropbox` marker at the end of EVERY panel) vs the gold's ONE per page on 35 / 35 pages of 902–906 — the gold's developer consolidated them into an INVENTED extra box (`activity dropbox` number 2G `Share your learning!` + prose in NO WT) after the panels; XDLS909's gold keeps the per-panel form (6 / 6 per page). An A1 substitution with invented text — class C; the writer's per-panel button stands.",
"- **Authority:** §1b (2) — the gold's own first-panel form (35 / 35); the r334 rule's own contract (the box's title heading is h3).",
"- **Fix (planned):** (a) `activityTitleLevelPostpass` accepts the bare box (`titleRe`'s inner `row > col-12` group optional — the OFF form still matches only through the group, byte-identical everywhere else); (b) `tile_grid.first_panel_row {enabled, env CDFIRSTROW_OFF, row_class}`: in `ContentConverter.#cdTilePair`, for `state.panelIds[0]` the section row directly wrapping the box (`<div class=\"row\">` + `<div class=\"col-md-8 col-12\">`, nothing else between) takes the class `row clickDropContent noBorder` and the box keeps `activity dropbox` (no prefix); any other shape falls back to the prefix form. Probe: `CDFIRSTROW_OFF=1` = the disk except the 30 pages' `<h5>` → `<h3>` title lines (the pin repair, untoggled — it is r417's own defect); ON = the first-panel row on the same 30 pages; scored with `match()` before regenerating; SCOPED regeneration of the 5 + a 12-module spot-check.",
"",
]
lines[b:b] = pick
io.open(STATE, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
print("LOOP_STATE.md", os.path.getsize(STATE), "bytes")
