#!/usr/bin/env python3
"""Round 7 PICK → LOOP_STATE.md (inserted before '## Round log'). Run under WSL."""
import io, os
R = "/mnt/c/Users/Gavin/TeKura/FINAL_MODULE_DATA/"
STATE = R + "LOOP_STATE.md"
lines = io.open(STATE, encoding="utf-8").read().split("\n")
b = next(i for i, l in enumerate(lines) if l.startswith("## Round log"))
pick = [
"## Session 29 — Round 7 PICK (engine r416) — THE ACTIVITY TITLE TYPED INSIDE THE RED SPAN: `[Activity 2A] Concrete poems` all red → the box's `<h3>` (20 Sept ≈19:20 → in progress; THE NEXT SHIP IS THE FULL `ship.sh` BACKSTOP — scoped #7 of 8)",
"- **Class.** An `[Activity …]` opener whose TITLE the writer typed INSIDE the red span — `🔴[RED TEXT] [Activity 2A] Concrete poems [/RED TEXT]🔴`, `[Activity] Calculating soil type.`, `[Activity box:] Ka pai!` — the words after the bracket still red, so they are the span's FREE text (`parse.free`), not `blackAfter`. The r66 standalone title rule (`activity_wrapper.standalone_title_heading`) and the owner-lead `addLead` both read `blackAfter` only: the title is DROPPED SILENTLY (Claude's box opens with the first content paragraph; the words appear nowhere on the page — CEDW201 2A, AGH1002 2A, CEDK101 3A, XLP01 4A–4D, TWHA903 / 904 / 905's eleven `Ka pai!` boxes) — a §6 silent strip the gold contradicts: its box opens `<h3>Concrete poems</h3>`. Found through DIFF_QUEUE #585 (`activity MISSING h3`, 384 pages / 190 modules) decomposed by `_s29_r7_boxtitle.py` → `_s29_r7_boxtitle.out` (7582 gold box titles: MATCH 3275; the non-match = the r369 numbering class (631 title-paired boxes with a different number = 0.18, `_s29_r7_boxnum.py`), the gold's INVENTED titles (WT source absent 1486 — class C, the r217 note), the Bilingual table dialect, and the `opener red-embedded` rows 132) and measured by `_s29_r7_redtitle.py` → `_s29_r7_redtitle.out` / `.json` (216 red-embedded opener spans / 86 modules).",
"- **Measured** (`_s29_r7_titlerule.cjs` — the candidate rule applied with the LIVE TagNormaliser to every span): the rule — an `activity` CONTAINER_OPEN opener with an EMPTY bracket remainder (or a mode word), free text that is not an instruction fragment / cue, not parenthesised, not digit-led, not colon-ended, ≤ 8 words, and does NOT itself resolve to a lexicon tag (`Parse('[' + free + ']')` → `radio quiz` / `drag and drop` / `word find` / `mcq` / `dropdown` / `engagement quiz button` = a widget NAME, never a title) — selects **48 sites / 30 modules: the gold's box opens with that `<h3>` on 40 = 0.83** (absent 4: MXDI101 / MXFL104 / ENGC204 / OSAH; 'elsewhere' 4 = the MXFL202 split-run dump artefact `Grams and` + `k` + `ilograms`). By group: Te ara Whakapuawa 11 / 11, ConnectED 3 / 3, Leaving to Learn 5 / 5, Blended Literacy 4 / 4, English 4 / 5, Mathematics 10 / 15, NCEA1 3 / 4. Every exclusion measured: `[Activity: Embedded] <widget>` (remainder `embedded`, 59 sites — gold absent 52), widget names 37 (gold absent 27 / h3 8 — `Word art` → `data marker`, `Sequence the story` → `story heading`: the lexicon's cost, recorded), digit-led 10 (`[Activity] 4A Perspectives` — gold absent), parenthesised / colon-ended / cues 8. NEW-FAMILY CHECK: no intake family in the class (WJFUN 0) — it holds across the Inquiry / Standard families.",
"- **Authority:** §1b (2) — the gold's own box form (KB 01F: the box opens with its `<h3>` title); the r66 / r362 / r365 title rules completed for the red-embedded dialect.",
"- **Fix (planned):** `activity_wrapper.standalone_title_heading.embedded_free_text {enabled, env EMBTITLE_OFF, max_words 8, remainder_allow [individual, independent, group]}` — ONE helper `ContentConverter.#embeddedOpenerTitle(it)` (the live rule above, `RenderText(it.text)` for the original-case words) consulted at BOTH opener sites: the plain path sets `it._embeddedTitle` and `ActivitiesBuilder.activityOpen` emits it as the `<h{level}>` (the whole `blackAfter` then renders as content, its first line no longer promoted); the bundle-owned path pushes it FIRST into `leadStream` as an `_ownerTitle` black item (so `addLead` makes it the `<h3>` and the owner's black tail joins the lead prose). OFF = the r415 output byte-for-byte.",
"- **Not taken, recorded (measured this PICK):** the empty writer-owned box residue after r415 (`_s29_r7_emptybox.out`: 64 boxes / 52 pages / 32 modules — the gold has NO box with that number on 34; the `[Go to your Learners Journal and complete activity 1A and 1B]` journal-instruction openers 12 / 3 AGH modules (under the floor; gold mixed), the HPFUN numberless boxes 6 (the [New tab] path has no phase numbering — 6 pages), CEDT207's 2D–2F); the activity-number mismatch (`_s29_r7_boxnum.out`: 631 / 3540 title-paired boxes = 0.18 on 331 pages / 173 modules — letter drift 386 from Claude's own extra / missing boxes (the r369 declined class: fix the boxes, never renumber), phase drift 150 (WJFUN108 / 105 = the gold's REORDERED tiles, editorial; the TRR `1C` vs `1.2` letter-vs-decimal = the r330 KB-preference override), HPFUN numberless 23); DIFF_QUEUE #585's `inside a longer line` rows (1361: 1129 the Bilingual PNR / TRR `[H2] English ║ [H2] Māori` table cells — the TMoA family's rendering, recorded).",
"",
]
lines[b:b] = pick
io.open(STATE, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
print("LOOP_STATE.md", os.path.getsize(STATE), "bytes")
