#!/usr/bin/env python3
"""Round 6 PICK → LOOP_STATE.md (inserted before '## Round log'). Run under WSL."""
import io, os
R = "/mnt/c/Users/Gavin/TeKura/FINAL_MODULE_DATA/"
STATE = R + "LOOP_STATE.md"
lines = io.open(STATE, encoding="utf-8").read().split("\n")
b = next(i for i, l in enumerate(lines) if l.startswith("## Round log"))
pick = [
"## Session 29 — Round 6 PICK (engine r415) — THE OWNED HEADING-LED BUNDLE WITH NO TABLE: the empty writer-owned box takes its section (20 Sept ≈18:45 → in progress)",
"- **Class.** The r412 / r413 shape without the table: a writer-owned (or r92 embedded-id) typed-widget invocation whose member walk ended at once on the writer's `[H3]`, with the quiz written as PARAGRAPHS after it (`[Activity 1A] [Dropdown Quiz – Auto Check]` + `[H3] Synonym strength` + `[body]` + the questions and options as lines — WJFUN307 / 210 / 211, ENGJ403, ENFUN03, ENGS404, TEFUN05, SCES201) — the box shipped EMPTY (the `no content captured` flag) and the whole section free after it. r413 took the heading + prose only when a TABLE followed. Found through the empty-box census (`_s29_r6_emptybox.py` → `_s29_r6_emptybox.out`: Claude 96 EMPTY writer-owned boxes on 73 pages / 47 modules; the gold's same-numbered box holds text 39 / media 21 = **60 / 96 = 0.63**, no box with that number 36) and the owned-walk census's no-table rows (`_s29_r6_notable_rows.tsv`: 47 owned bundles / 40 pages / 28 modules).",
"- **Measured** (`_s29_r6_goldcheck.py` over the 125 heading-led no-table bundles → `_s29_r6_notablecheck.out`): the heading inside the gold's box 46 / 99 found = 0.46 overall — a TIE, split by family (MiW 7 / 9, Technology 4 / 4, Science 3 / 4, dragAndDrop 5 / 7 IN; English 0 / 7, NCEA1 1 / 7, dropDown 6 / 13 out); the OWNED half alone (the box already exists) 0.55–0.67 by type. Scored with the skeleton gate's own `match()` on the probe's ON pages (`_s29_r415_pagescore.py`): **34 paired pages, 24 up / 2 down / 8 same, +57.7pp-sum** — MiW 8 / 0, NCEA1 4 / 0, Science 3 / 0, Mathematics 1 / 0, Technology 6 / 0 (7 same), ENFUN 1 / 2 (−1.5). NEW-FAMILY CHECK: without WJFUN 26 pages, 16 up / 2 down, +36.6 — holds. Unowned bundles (0.41 boxed) stay free.",
"- **Authority:** §1b (2) — the gold's own box form (KB 01F: the box holds the task's title, instruction and widget); the r412 / r413 rule completed for the no-table dialect.",
"- **Fix (planned):** `opener_rule.heading_table_owner.owned_bundles.no_table {enabled, env NOTABLEOWNED_OFF}` — in `#headingTableOwner`, when the table scan finds none, an owned bundle (a real owner, or the r92 embedded id) takes the heading as its FIRST lead item and the member walk RESUMES right after it (the standard capture with its own terminators; the r366 lead_free rule frees the first paragraph).",
"- **Not taken, recorded (measured this PICK):** DIFF_QUEUE #3677 (gold `col-12` section column vs Claude `col-md-8 col-12`, 315 pages) — the gold's single-column body row is `col-12 col-md-8` ≥ 0.78 for every content kind (`_s29_r6_colwidth.py` → `_s29_r6_colwidth.out`; tables 0.46 / 0.42 col-md-12 a tie, overview headings 0.61 / 0.37) — an alignment artefact, declined; #587 / #606 (the box's `interactive` class, 247 + 114 pages) — number-paired (`_s29_r6_intflag.py` → `_s29_r6_intflag.out`) the flag tracks the widget Claude's box holds (dragAndDrop 0.88, mcq 0.65 int; clickDrop / carousel / TKmodal plain) and the 446 gold-interactive / Claude-plain boxes hold NO widget at all (a capture class) — declined; the after-widget row break (`_s26_rowpair.py` re-run → `_s29_r6_rowpair.out`: WIDGET 0.63 on 129 pages; the raw-HTML instrument `_s29_r6_widgetflow.py` → `_s29_r6_widgetflow.out`: 0.57 on 61 pages, speechBubble 0.60, hand-off 0.58) — a tie, declined; the footer rows #441–#443 (MISSING next-lesson / home-nav 97–100 pages) — page-COUNT artefacts (Claude's last page pairs with a gold page that is not the gold's last: AGH1004 7 pages vs the gold's 10), declined; the 133 'gold menu / Claude no menu' lesson pages — the gold's menu is COMMENTED OUT (ART1002) — not a class; CHI1003 / 1004 / 1005's ≤ 20 % pages — `Merge item N` lessons (the r300 zero class, the ceiling's population).",
"",
]
lines[b:b] = pick
io.open(STATE, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
print("LOOP_STATE.md", os.path.getsize(STATE), "bytes")
