#!/usr/bin/env python3
"""r425 FINISH finalise (OPERATING_GUIDE §12): the changelog entry, Config.js bump 260619.96 -> .97, OPERATING_GUIDE §9 / §11 / §14,
gate_baseline.json re-based to 2377 pairs, the loop file's §0 census table, verify_after_transfer.sh's census, the
Input_Doc_Rules note. Run under WSL: python3 _s33_r425_finalise.py"""
import re, json, shutil
R = "/mnt/c/Users/Gavin/TeKura/FINAL_MODULE_DATA/"
PF = R + "pageforge-site/converter-v2/"
def rd(p): return open(p, encoding="utf-8").read()
def wr(p, s): open(p, "w", encoding="utf-8", newline="\n").write(s)

entry = """## 2026-09-22 (round 425 FINISHED, build 260619.97) — THE XOTP ACTIVITY-TABLE ADAPTER ENABLED: the twelve reader modules join the corpus (2559 → 2583 pages, 2353 → 2377 pairs) + the "I can" success-criteria list (the autonomous loop's session 33 Round 1; THE FULL-REGENERATION BACKSTOP — scoped #8 since r416, counter → 0)

### 1. WHAT CHANGED

**The flag.** `Input_Doc_Rules.input_shapes.activity_table.adapter.enabled` false → **true** (env `ACTTABLEADAPT_OFF` still reverts the whole family to the r424 refusal). Everything the r425 entry below describes as BUILT is now LIVE: `DocxExtractor.AdaptActivityTable`, the bare activity box, the repeated lesson `<h1>`, the alert variant, the two-column item menu (`ITEMMENU_OFF`), the keep-digit prefixes. The 12 modules (XOTPB08–13, XOTPG01, G03–06, XOTPO01) rebuilt **byte-identical to the parked build 5** (`outputs/_s31_r425_build5_output/`, 36 / 36 files) before the one residue below was added.

**The residue shipped with it — the "I can" success-criteria list (`adapter.overview_list_after_label`).** The Overview cell's five "I can" items are typed as PLAIN paragraphs in the docx (no `numPr`, no style — verified in XOTPG04 / G01 / O01, `outputs/_s33_r425_ican_numpr` probe), so they reached the item menu as five `<p>`; the gold ships them as `<ul><li>` on every page that has them (6 modules × 2 pages, 12 / 12 = 1.00) and the KB fixes the form (01B_MODULE_MENUS_FOOTER: `<h5>I can:</h5>` + `<ul><li>`; constraint 23). A family-dialect rule inside the adapter (LOOP §1d exception 1, riding with the round it belongs to): the lines after a label matching `^i can\\s*:?$` (folded), up to the next bold label / parenthetical / `CS:` line / the first line of ≥ 16 words, take the corpus bullet prefix, and `ListsAndRuns.renderBlackText` groups them into one `<ul>`. The B-series Overview cells hold only the external Google-Doc link and never match. Not built (recorded): the trailing bold sentence `**Remember to do the assessment quiz!**` that the human splits into its own `<p><b>` (a bold run inside the same paragraph, no line break — 9 / 12 golds, 18 pages, no KB rule, under the floor); the gold's page-2 "Word Challenge" tables, which exist only as a pasted picture (`[IMAGE: image1.png]`, the needs-Chris #11 class); the `<h5>I can:</h5>` (D10-9); the acks on page 1 (KB c33).

### 2. PROOF

- Build 7 vs the parked build 5, page for page with the gate's own scorer (`_s33_r425_b5vs7.py`): **12 up / 0 down / 12 identical, +36.50pp-sum**; the 12-module mean 58.76 → **60.28 %** (G01 / G03 / G04 / G05 69.2 → 72.6 on page 1, 56.9 → 60.5 on page 2; G06 68.8 → 70.8 / 52.6 → 54.8; O01 65.3 → 67.6 / 52.9 → 55.1); the B-series 12 pages byte-identical. Page 2's shape checked once (XOTPG04_2_0, 60.5 %): the residual diff is the `<h5>` vs `<p>` label (D10-9), the Remember split and the picture-only tables — nothing derivable left.
- `_s33_r425_probe_run.sh` (the r410 harness, `_s33_r425_probe.cjs` = `_s28_t3_probe.cjs` verbatim, over all 507 Claude-dir modules in 4 shards): **OFF (`ACTTABLEADAPT_OFF=1`) = the disk on every page, 2559 / 2559, the 12 "prep refused (unsupported)" — the r424 state exactly**; **ON = 2583 / 2583 identical, changed 0** — the adapter fires on the 12 alone and changes nothing else (`ITEMMENU_OFF` and the alert variant are XOTP-scoped by the item family / code prefix).
- SCOPED regeneration first (`_s33_r425_regen.sh`: the 12 + a fresh 12-module spot-check sample, seed 425): `_content_manifest.py fresh` **0 truly stale**; `changed` = exactly the 12; `_scoped_spotcheck.py verify` **12 / 12 byte-identical**; `scoped_ship.sh` (`_s33_r425_scoped_ship.log`) toggle-exists ✓, containment **12 ⊆ 12** ✓, spot-check ✓; the exact decomposition (`_s33_r425_fastloop_named.log`, `--allow-stale-baseline` because the sample's PMT101 / CEDR302 were re-generated byte-identical after the snapshot — proven by the content manifest; CEDR302 dropped from the re-score list because it is a `compare_exclusions.txt` module the full gate never scores and an explicit code list would have added its page to the baseline — a spot-check sampler nit, recorded): skeleton 54.17 → 54.23 IMPROVED, ≥50 +21, cs exact +63, body ANY +3 NAMED (below), clean +0.01; **the ledger reached scoped #8 → the FULL backstop was due, so this round IS the full regeneration** (`_s33_r425_fullship_par.sh`, 39 batches, 4 workers, 6 min, all rc 0; `_stalecheck.sh` 0 stale; `_content_manifest.py changed` = NOTHING — the full regeneration reproduced the scoped state byte for byte on all 504 page-bearing modules; `_ship_ledger.py record-full --round 425`, counter 0).
- `run_all_gates.sh` (`_s33_r425_gates.log`, the full corpus): skeleton state `_s33_r425_sk_final.json` **54.1703 → 54.2320 % @ 2353 → 2377 pairs** (+0.0617pp = (54.1703 × 2353 + 60.281 × 24) / 2377 — the 24 new pages entering ABOVE the corpus mean, pure population arithmetic — LOOP §1e), ≥50 **1442 → 1463** (+21 = the 21 XOTP pages ≥ 50), ≥75 238, ≥90 20, RAW 38.193 → 38.239, median 55.3; `_s29_skdelta.py` r423 → r425: **movers 0 (up 0 / down 0), new-only 24, gone 0** — not one pre-existing page moved; compare_structure 14318 / 186 / 689 / 23 (the 12 add 63 / 0 / 0 / 0 to the matched pool 16557 → 16620); body_compare 55 / 5 / **193** / **251**; clean 2532 / 2576 = 98.29 %; leak 73 / 44 EXACT; tags 9557 / 9557; every verifier ✓ (the XOTP pages carry only hand-off boxes — carousel 12 / dragAndDrop 22 / flipCard 6 / multiChoiceQuiz 5 — and the acks accordion, so no verifier module set needs extending); `_gatecheck.py cs bc` then `skeleton defect` (`_s33_r425_gatecheck.log`): every row IMPROVED or HELD except body_compare ANY 248 → 251.
- **The body_compare +3, NAMED (`_s33_r425_bcdelta.py` — every pre-existing page's flag unchanged):** XOTPB08_1_0 (2 EMPTY widgets), XOTPB11_1_0 (1), XOTPB12_1_0 (1) — the B-series reader-book carousel and the picture / sentence matching dragAndDrop whose payload exists only as a pasted picture + an external Google-Doc link (`[IMAGE: image3.png]`, the needs-Chris #11 / #14 items); the box is honest and empty by design, exactly as the r425 record predicted. Population growth, not a mover.
- Post-ship (`_s33_r425_postship.sh`): the fast-loop baseline re-snapshot (2377 pages), the content manifest snapshot (2583 pages / 504 page-bearing modules), 17 selftests GREEN (49 / 0), the feature index `--rehtml` / `--merge` / `--selftest` GREEN (552 modules), the DIFF MINER re-run on the r425 corpus (2377 pairs / 496 modules, 8969 classes, **184 CANDIDATE** — unchanged in count, every row re-counted on the new population), **the ceiling re-measured on the new population** (`_ceiling_r425.{json,md,log}`): scaffold **90.9 %** (loose 93.5 %) — unchanged — so **54.232 % = 59.7 % of achievable** (band 58.0–59.7).

### 3. PROTECTED GATES (all HELD on the 2,353-pair pre-existing population, EXACT page for page — 0 movers; the whole-population absolutes RE-BASED to 2,377 pairs — `_s33_r425_gates.log`, `_s33_r425_gatecheck.log`, `_s33_r425_skdelta.log`, `_s33_r425_bcdelta.py`)

- **Skeleton (PRIMARY)**: SCAFFOLD **54.2320 % @ 2377 pairs** (the 2353 pre-existing pairs 54.1703 % EXACT; the 24 new pairs enter at 60.28 %); ≥50 **1463** (+21), ≥75 **238**, ≥90 **20**, RAW **38.239 %**; skipped 0.
- **compare_structure** 14318 / 186 / 689 / 23 (pre-existing 14255 / 186 / 689 / 23 EXACT; the 12 add 63 / 0 / 0 / 0); **body_compare** 55 / 5 / 193 / 251 (pre-existing 55 / 5 / 190 / 248 EXACT; +3 EMPTY = the three B-series page-1 hand-off boxes, named); **defect** clean 2532 / 2576 = 98.29 % (pre-existing 2508 / 2552 EXACT + 24 clean), leak 73 / 44 EXACT; tags 9557 / 9557; every verifier EXACT.
- Plateau (§4): a recognition-family round whose PICK predicted the population change, not a pre-existing-page move — the window stays at 0 of 3. Ledger: FULL at r425, scoped counter 0 (8 of headroom).

### 4. RECORDS

`OPERATING_GUIDE.md` §9 / §11 / §14 and the loop file's §0 census (507 dirs / 2,583 pages / 2,377 pairs; the no-build list is now the 7 with no Writers Template + the 3 TRR dirs with no output — the 12 XOTP are IN); `gate_baseline.json` re-based (`_note_r425`); `_MIGRATION/verify_after_transfer.sh` census 495 → 507 dirs, 2559 → 2583 pages (`.pre-s33.bak` kept); the checksum manifests; the loop mirror. Open needs-Chris items unchanged (#11 the XOTPB08 picture, #14 the reader book, #15 the XOTPB Overview text).

"""
p = PF + "BUILD_CHANGELOG.md"; s = rd(p)
head, rest = s.split("\n", 1)
assert head.startswith("# BUILD CHANGELOG") and rest.lstrip("\n").startswith("## 2026-09-21 (round 425, build 260619.96)")
wr(p, head + "\n\n" + entry + rest.lstrip("\n"))

p = PF + "app/js/Config.js"; s = rd(p)
old = '\tstatic AppVersion = "260619.96";'; assert s.count(old) == 1
note = ("\t// ROUND 425 FINISHED (260619.97): THE XOTP ACTIVITY-TABLE ADAPTER ENABLED (Input_Doc_Rules.input_shapes.activity_table.adapter.enabled true; "
        "env ACTTABLEADAPT_OFF reverts) + the 'I can' success-criteria list (adapter.overview_list_after_label: the plain-paragraph items after the label "
        "take the corpus bullet prefix and render as the KB 01B <ul><li>; 12 pages up / 0 down). The loop's session 33 Round 1: the 12 rebuilt byte-identical "
        "to the parked build 5, then the list; probe OFF = disk 2559 / 2559 with the 12 refused, ON = 2583 / 2583; scoped ship #8 -> the FULL regeneration "
        "backstop (39 batches, 0 stale, the manifest byte-identical); the 2353 pre-existing pairs EXACT (0 movers), the whole-population mean 54.1703 -> "
        "54.2320 % @ 2377 pairs (the 24 new pages at 60.28 %), >=50 1442 -> 1463; body_compare +3 EMPTY named (the B-series picture-only widgets).\n")
wr(p, s.replace(old, note + '\tstatic AppVersion = "260619.97";'))

p = PF + "OPERATING_GUIDE.md"; s = rd(p)
old9 = "| **Skeleton (PRIMARY)** | `python3 _skeleton_compare.py` | **ROUND 423 BASELINE ("; assert s.count(old9) == 1
new9 = ("| **Skeleton (PRIMARY)** | `python3 _skeleton_compare.py` | **ROUND 425 BASELINE (the XOTP activity-table adapter ENABLED — the 12 reader modules "
        "join the corpus, 2559 → 2583 pages; `adapter.enabled: true`, env `ACTTABLEADAPT_OFF`; + the \"I can\" list `adapter.overview_list_after_label`; "
        "THE FULL REGENERATION backstop, scoped #8 → counter 0): SCAFFOLD mean 54.2320% / >=50% 1463 / >=75% 238 / >=90% 20 / RAW 38.239% @ 2377 pairs, "
        "pairs skipped 0 — the 2353 pre-existing pairs hold r423 EXACTLY (54.1703 %, 0 movers); the mean moved by population arithmetic alone "
        "((54.1703 × 2353 + 60.281 × 24) / 2377), NAMED; every other gate EXACT on the pre-existing population and RE-BASED to 2377 pairs "
        "(cs 14318 / 186 / 689 / 23, body 55 / 5 / 193 / 251 — the +3 EMPTY = the B-series picture-only hand-off boxes, named; clean 2532 / 2576 = 98.29 %, "
        "leak 73 / 44). Ceiling re-measured 90.9 % → 59.7 % of achievable.** "
        "Previous — ROUND 423 BASELINE (")
s = s.replace(old9, new9)
old11 = "| `ACTTABLEADAPT_OFF` / `ITEMMENU_OFF` | 425 | **THE XOTP ACTIVITY-TABLE ADAPTER — BUILT, PROVEN ON THE TWELVE, SHIPPED INERT"; assert s.count(old11) == 1
row11 = ("| `ACTTABLEADAPT_OFF` / `ITEMMENU_OFF` | 425 (finished 2026-09-22) | **THE XOTP ACTIVITY-TABLE ADAPTER ENABLED + the \"I can\" success-criteria list** "
         "(the autonomous loop's session 33 Round 1 — the round below finished: `input_shapes.activity_table.adapter.enabled: true`; the 12 XOTP modules "
         "(24 pages) join the corpus; `adapter.overview_list_after_label {enabled, label_match ^i can\\\\s*:?$, stop_min_words 16}` — the Overview cell's "
         "plain-paragraph success-criteria items after the \"I can:\" label take the corpus bullet prefix and render as the KB 01B / c23 `<ul><li>` "
         "(gold 12 / 12 pages; 6 modules up +36.5pp-sum; the B-series cells never match). OFF (`ACTTABLEADAPT_OFF=1`) = the r424 state: the 12 refused BY NAME, "
         "every other page byte-identical (2559 / 2559 proven over all 507 modules). Not built: the trailing bold `Remember to do the assessment quiz!` "
         "sentence the human splits into its own `<p><b>` (18 pages, no KB rule), the picture-only Word-Challenge tables, the `<h5>` label (D10-9). "
         "THE FULL-REGENERATION BACKSTOP (scoped #8 → 0); baselines re-based to 2377 pairs. |\n")
s = s.replace(old11, row11 + old11)
old14 = "- **Build:** `260619.96` (round 425 — **THE XOTP ACTIVITY-TABLE ADAPTER: BUILT"; assert s.count(old14) == 1
b14 = ("- **Build:** `260619.97` (round 425 FINISHED — **THE XOTP ACTIVITY-TABLE ADAPTER ENABLED: the twelve reader modules join the corpus + the "
       "\"I can\" success-criteria list** — `adapter.enabled: true` (env `ACTTABLEADAPT_OFF`), `adapter.overview_list_after_label`; the autonomous loop's "
       "session 33 Round 1; the 12 rebuilt byte-identical to the parked build 5, then 12 pages up / 0 down for the list (means 35.6–66.6 %, ≥50 21 / 24); "
       "the probe OFF = disk 2559 / 2559 with the 12 refused, ON = 2583 / 2583; **THE FULL REGENERATION (the ledger's backstop at scoped #8 — 39 batches, "
       "0 stale, the manifest byte-identical; counter 0)**; **ROUND 425 BASELINE: SCAFFOLD mean 54.2320% / >=50% 1463 / >=75% 238 / >=90% 20 / RAW 38.239% "
       "@ 2377 pairs** — the 2353 pre-existing pairs EXACT (0 movers), the 24 new pages enter at 60.28 %; cs 14318 / 186 / 689 / 23, body 55 / 5 / 193 / 251 "
       "(+3 EMPTY named: the B-series picture-only boxes), clean 2532 / 2576 = 98.29 %, leak 73 / 44; every verifier EXACT; 17 selftests GREEN; the feature "
       "index GREEN; the miner 184 CANDIDATE on 2377 pairs; the ceiling re-measured 90.9 % (54.232 = 59.7 % of achievable); the corpus is now "
       "**2583 pages / 507 dirs**). Previous: ")
s = s.replace(old14, b14 + old14)
wr(p, s)

p = R + "CONVERTER_V2/reference/tests/gate_baseline.json"; s = rd(p)
def setv(key, old, new):
    global s
    pat = r'("%s":\s*)%s(?=[,\s}])' % (re.escape(key), re.escape(str(old)))
    s, n = re.subn(pat, lambda m: m.group(1) + str(new), s, count=1); assert n == 1, key
setv("build", '"260619.95"', '"260619.97"'); setv("round", 424, 425); setv("date", '"2026-09-21"', '"2026-09-22"')
setv("claude_pages", 2610, 2634); setv("paired_pages", 2353, 2377); setv("gated_dirs", 485, 497)
setv("mean_scaffold_pct", 54.17, 54.23); setv("pages_ge_50", 1442, 1463); setv("raw_mean_pct", 38.2, 38.24)
setv("pairs", 2353, 2377)
setv("exact_chain", 14255, 14318)
setv("any_breakdown", 248, 251); setv("empty_container", 190, 193)
setv("clean_pages", 2508, 2532); setv("total_pages", 2552, 2576); setv("clean_pct", 98.28, 98.29)
a = '    "_note_r424": "Round 424 (session 31 Round 2)'; assert s.count(a) == 1
s = s.replace(a, '    "_note_r425": "Round 425 FINISHED (session 33 Round 1, 2026-09-22): the XOTP activity-table adapter ENABLED (Input_Doc_Rules.input_shapes.activity_table.adapter.enabled true, env ACTTABLEADAPT_OFF) + the I-can success-criteria list (adapter.overview_list_after_label) — the 12 reader modules join the population: 24 pages / 24 pairs (means 35.6-66.6 %, 21 of 24 >= 50), pairs 2353 -> 2377, gated dirs 485 -> 497, Claude pages 2610 -> 2634. THE FULL-REGENERATION BACKSTOP (scoped #8 -> counter 0): 39 batches rc 0, 0 stale, the content manifest byte-identical to the scoped state. SPLIT BY POPULATION (LOOP 1e): the 2353 pre-existing pairs reproduce r423 EXACTLY on every decomposable gate (skeleton 54.1703 / 1442 / 238 / 20, 0 movers; cs 14255 / 186 / 689 / 23; body 55 / 5 / 190 / 248; clean 2508 / 2552; leak 73 / 44); every absolute below is the whole 2377-pair population. body_compare ANY +3 = XOTPB08_1_0 (2) / XOTPB11_1_0 / XOTPB12_1_0 EMPTY hand-off boxes whose payload is a pasted picture + a Google-Doc link (needs Chris #11 / #14), named.",\n' + a)
a2 = '    "_note_r421b": "Round 423: SCAFFOLD 54.2065'; assert s.count(a2) == 1
s = s.replace(a2, '    "_note_r425b": "Round 425 FINISHED: SCAFFOLD 54.1703 -> 54.2320 @ 2353 -> 2377 pairs (+0.0617pp = (54.1703 x 2353 + 60.281 x 24) / 2377 — the 24 XOTP pages entering above the mean, 0 movers on the pre-existing pairs, NAMED); >=50 1442 -> 1463 (+21 = the XOTP pages >= 50); >=75 238 / >=90 20 EXACT; RAW 38.193 -> 38.239; median 55.3. State outputs/_s33_r425_sk_final.json.",\n' + a2)
a3 = '    "_note_r423": "Round 423: exact 14170 -> 14255'; assert s.count(a3) == 1
s = s.replace(a3, '    "_note_r425": "Round 425 FINISHED: exact 14255 -> 14318 (+63) = the text-matched pool 16557 -> 16620 (+63) — all the 12 XOTP modules\' own pages (63 / 0 / 0 / 0); EXTRA 186 / missing 689 / row-wrap 23 EXACT.",\n' + a3)
a4 = '    "_note_r423": "Round 423: over-capture 54 -> 55'; assert s.count(a4) == 1
s = s.replace(a4, '    "_note_r425": "Round 425 FINISHED: EMPTY 190 -> 193 / ANY 248 -> 251 = XOTPB08_1_0 (2 EMPTY widgets), XOTPB11_1_0, XOTPB12_1_0 — the B-series reader-book carousel / picture-matching dragAndDrop boxes whose payload exists only as a pasted picture + an external Google-Doc link (needs Chris #11 / #14; honest empty boxes, named); over-capture 55 / runaway 5 EXACT; the pre-existing 2552 pages\' flags unchanged (_s33_r425_bcdelta.py).",\n' + a4)
a5 = '    "_note_r423": "Round 423: clean 2504 / 2548'; assert s.count(a5) == 1
s = s.replace(a5, '    "_note_r425": "Round 425 FINISHED: clean 2508 / 2552 -> 2532 / 2576 = 98.29 (the 24 XOTP pages all clean), leak 73 occ / 44 pages EXACT.",\n' + a5)
json.loads(s)
wr(p, s)

# the Input_Doc_Rules note (the Edit tool could not match the line earlier in the session)
p = PF + "data/Input_Doc_Rules.json"; s = rd(p)
a6 = 'The next loop flips this to true and finishes r425 from the LOOP_STATE.md handover."'; assert s.count(a6) == 1
s = s.replace(a6, 'ENABLED 2026-09-22 (session 33 Round 1): r425 finished from the LOOP_STATE.md handover — the 12 rebuilt byte-identical to build 5, the I-can list (overview_list_after_label) added, the A/B probe over all 507 modules (OFF = disk 2559 / 2559 with the 12 refused; ON = 2583 / 2583), the FULL regeneration backstop, the 2353 -> 2377 re-base."')
json.loads(s)
wr(p, s)

# the loop file's §0 census table (mirror copied by the mirror step)
p = R + "LOOP__Autonomous_Rounds.md"; s = rd(p)
old = ("| Claude module dirs | 416 | **495** |\n| Claude pages | 2,109 | **2,559** |\n| gold dirs | 454 | **552** |\n"
       "| Writers Template / Media List docx | 619 | **762** |\n| skeleton paired pages | 1,956 | **2,353** |")
assert s.count(old) == 1
s = s.replace(old, ("| Claude module dirs | 416 | **507** |\n| Claude pages | 2,109 | **2,583** |\n| gold dirs | 454 | **552** |\n"
                    "| Writers Template / Media List docx | 619 | **762** |\n| skeleton paired pages | 1,956 | **2,377** |"))
old2 = ("**552 gold dirs against 495 Claude dirs is CORRECT, not a fault.** 19 modules have no Claude\n"
        "build (§2): the 12 XOTP modules until the r425 adapter is enabled, and 7 with no Writers\n"
        "Template at all. A gold-only dir is the expected state for them. After r425 ships the figures\n"
        "become 507 dirs / 2,583 pages / 2,377 pairs — update this table at that finalise.")
assert s.count(old2) == 1
s = s.replace(old2, ("**552 gold dirs against 507 Claude dirs is CORRECT, not a fault** (r425 finished 22 Sept 2026: the 12\n"
                     "XOTP modules are IN). 7 modules have no Claude build because they have no Writers Template at all\n"
                     "(§2), and 38 older gold dirs — the \"r285 ghost-directory class\" (BLL243 …, CEDK401 …, TRR110 — see\n"
                     "`LOOP_STATE.md`'s session-33 start note) — have never had a Claude dir; they are a recorded lane for\n"
                     "the PICK step, not an intake. A gold-only dir is the expected state for all of them."))
s = s.replace("Current (22 September 2026, build 260619.96):", "Current (22 September 2026, build 260619.97 — r425 finished):")
wr(p, s)

# verify_after_transfer.sh census
p = R + "_MIGRATION/verify_after_transfer.sh"; s = rd(p)
shutil.copyfile(p, p + ".pre-s33.bak")
o1 = '"495"   # r423 (2026-09-21): 494 -> 495'; o2 = '"2559"   # r423 (2026-09-21): 2555 -> 2559'
assert s.count(o1) == 1 and s.count(o2) == 1
s = s.replace(o1, '"507"   # r425 finished (2026-09-22): 495 -> 507, the 12 XOTP reader modules (the activity-table adapter enabled); r423 (2026-09-21): 494 -> 495')
s = s.replace(o2, '"2583"   # r425 finished (2026-09-22): 2559 -> 2583, the 12 XOTP modules x 2 pages; r423 (2026-09-21): 2555 -> 2559')
wr(p, s)
print("FINALISE_DONE")
