#!/usr/bin/env python3
"""Session 33 Round 1 — LOOP_STATE.md finalise for the r425 FINISH: the s31-r3 record + this round's record move to the
archive, the Round-log line, Position, standing facts, the miner line, the next-session line. Run under WSL."""
import re
R = "/mnt/c/Users/Gavin/TeKura/FINAL_MODULE_DATA/"
def rd(p): return open(p, encoding="utf-8").read()
def wr(p, s): open(p, "w", encoding="utf-8", newline="\n").write(s)
st = rd(R + "LOOP_STATE.md"); ar = rd(R + "LOOP_STATE_ARCHIVE.md")

# 1. the s31 Round 3 (r425 BUILT + SHIPPED INERT) section → the archive (verbatim), replaced by a pointer line
m = re.search(r"^## Session 31 — Round 3 \(engine r425.*?(?=^## Round log)", st, re.S | re.M)
assert m, "s31-r3 section"
sec = m.group(0)
record = """## Session 33 — Round 1 (engine r425 FINISHED, build 260619.97, 22 Sept 09:56 → ≈11:05) — THE XOTP ACTIVITY-TABLE ADAPTER ENABLED + the "I can" success-criteria list; THE FULL-REGENERATION BACKSTOP (scoped #8 → 0)

**PICK (the handover's Round 1).** Finish r425 from the 'Session 31 — Round 3' record: flip `input_shapes.activity_table.adapter.enabled` to true, rebuild the 12, decide the two derivable menu residues, the A/B probe, the scoped ship, the postship suite, the 2353 → 2377 re-base. Authority: the r425 record (LOOP §2's no-build bullet; the intake's §7 item 4); the residue under KB 01B / constraint 23 (level 1) and §1d exception 1 (a family dialect inside the adapter).

**WHAT SHIPPED.** (1) The flag (`sed` on line 381 — the Edit tool could not match the JSON's line; `_shipped_inert` note updated by the finalise). (2) The 12 rebuilt (`_s33_r425_build6.log`, rc 0) **byte-identical to the parked build 5 — 36 / 36 files**. (3) The residue measured: the five "I can" items are PLAIN paragraphs in the docx (no numPr, no style — `ican_numpr.py` on XOTPG04 / G01 / O01; the s31 "empty numFormats map" theory was wrong — there is no numbering to lose), the gold lists them `<ul><li>` on 12 / 12 pages of the 6 modules that have them (the B-series Overview cells hold only the external Google-Doc link), KB 01B fixes the form → `adapter.overview_list_after_label {label_match ^i can\\s*:?$, stop_min_words 16}` in `DocxExtractor.AdaptActivityTable` (the lines after the label take the corpus `• ` prefix until a bold label / parenthetical / CS: line / ≥ 16-word prose line; `renderBlackText` groups them). Rebuilt (`build7.log`): exactly the 12 G/O pages changed; `_s33_r425_b5vs7.py` (the gate's scorer, build 5 vs 7) **12 up / 0 down, +36.50pp-sum, the 12-module mean 58.76 → 60.28 %**. The "right column `<b>`" residue re-read against the gold: the gold's two paragraphs are plain like Claude's; the difference is the trailing bold sentence `**Remember to do the assessment quiz!**` (a bold run inside the same paragraph, no `<w:br>` — `remember.py`) that the human splits into its own `<p><b>` on 9 / 12 golds — 18 pages, no KB rule, RECORDED not built. Page 2 checked once (XOTPG04_2_0, 60.5 %): the residual diff = the `<h5>` label (D10-9), the Remember split, and the gold's two "Word Challenge" tables that exist only as `[IMAGE: image1.png]` in the WT (the needs-Chris #11 picture class). (4) `_s33_r425_probe_run.sh` over all 507 modules (4 shards): **OFF = 2559 / 2559 identical, the 12 "prep refused (unsupported)"; ON = 2583 / 2583 identical** — the adapter changes the 12 alone. (5) `_s33_r425_regen.sh` (the 12 + a 12-module spot-check sample, seed 425): fresh 0 truly stale, changed = the 12, spot-check 12 / 12; `scoped_ship.sh` toggle ✓ containment 12 ⊆ 12 ✓ spot-check ✓; `_fastloop_diff.py … --allow-stale-baseline --accept-named "body_compare ANY breakdown" --commit` (PMT101 / CEDR302 in the sample were re-generated byte-identical after the snapshot — the mtime guard's false alarm, the content manifest the proof; CEDR302 dropped from the re-score list: a `compare_exclusions.txt` module the full gate never scores, which an explicit code list would have added to the baseline — a spot-check sampler nit, follow-up) → skeleton +0.06, ≥50 +21, cs +63, body ANY +3 named, clean +0.01; the ledger hit **scoped #8 = the FULL backstop due → `_s33_r425_fullship_par.sh` (39 batches, 4 workers, 6 min, all rc 0; `_stalecheck.sh` 0; `_content_manifest.py changed` = NOTHING — the full regeneration reproduced the scoped state byte for byte)**; `_ship_ledger.py record-full --round 425 --build 260619.97` (counter 0). (6) `run_all_gates.sh` (`_s33_r425_gates.log`): **skeleton 54.1703 → 54.2320 % @ 2353 → 2377 pairs** (+0.0617pp = (54.1703 × 2353 + 60.281 × 24) / 2377, population arithmetic — LOOP §1e), **≥50 1442 → 1463**, ≥75 238, ≥90 20, RAW 38.239; `_s29_skdelta.py` **movers 0, new-only 24, gone 0**; cs 14318 / 186 / 689 / 23 (+63 / 0 / 0 / 0); body 55 / 5 / 193 / 251 (**+3 EMPTY NAMED, `_s33_r425_bcdelta.py`: XOTPB08_1_0 ×2, XOTPB11_1_0, XOTPB12_1_0 — the B-series reader-book carousel / picture-matching boxes whose payload is a pasted picture + a Google-Doc link, needs-Chris #11 / #14; every pre-existing page's flag unchanged**); clean 2532 / 2576 = 98.29 %; leak 73 / 44; tags 9557 / 9557; every verifier ✓ (the XOTP pages carry only hand-off boxes — carousel 12 / dragAndDrop 22 / flipCard 6 / MCQ 5 — no verifier set to extend); `_gatecheck.py cs bc` + `skeleton defect` every row IMPROVED / HELD but the named body row; 17 selftests GREEN (49 / 0); feature index GREEN; the miner re-run (2377 pairs / 496 modules, 8969 classes, **184 CANDIDATE**); **the ceiling re-measured on the new population (`_ceiling_r425`): 90.9 % unchanged → 54.232 = 59.7 % of achievable**. (7) Finalise (`_s33_r425_finalise.py` / `_finalise2.py` / `_checksums.sh`): the changelog entry, Config.js 260619.97, OPERATING_GUIDE §9 / §11 / §14, `gate_baseline.json` re-based (`_note_r425`), the loop file's §0 table (507 / 2,583 / 2,377) + item 7, `verify_after_transfer.sh` lines 77–78 (`.pre-s33.bak`), the checksum manifests (`.pre-r425fin.bak`), the mirror.

**Concurrency note.** While this round ran, Chris's `/loop-review` follow-up session ("reviewer fixes", commit c942de2 at 10:05, Fable) rewrote the loop file (§0 census exceptions, the 38 pre-intake never-converted modules as the first Round 0d, §1f phase order, §3 mirror list, §7) and 27 lines of this file; it touched no engine / data file and committed only `loop/` files, so nothing of this round was lost or double-written — but the finalise script's §0 edit asserted on the old text and part 2 re-targeted the new one. That session is finished (not running).
"""
st = st.replace(sec, "## Session 31 — Round 3 (engine r425, BUILT + SHIPPED INERT) and Session 33 — Round 1 (r425 FINISHED) → LOOP_STATE_ARCHIVE.md 'Session 31 — Round 3 … / Session 33 — Round 1 (archived from LOOP_STATE.md 2026-09-22 ≈11:05 NZST, session 33 §5d)' — grep the engine number there.\n\n")
ar = ar.rstrip("\n") + "\n\n" + sec.rstrip("\n") + "\n\n" + record + "\n"

# 2. the Round-log line
o = "- s31-r3 (engine r425, build 260619.96, BUILT + SHIPPED INERT"
assert st.count(o) == 1
line = ("- s33-r1 (engine r425 FINISHED, build 260619.97, 22 Sept 09:56 → ≈11:05) · THE XOTP ACTIVITY-TABLE ADAPTER ENABLED (`adapter.enabled: true`, "
        "`ACTTABLEADAPT_OFF`) + the \"I can\" success-criteria list (`adapter.overview_list_after_label`, KB 01B / c23, 12 pages up +36.5pp-sum) · the 12 rebuilt "
        "= build 5 byte-identical, then the list · probe OFF 2559 / 2559 with the 12 refused, ON 2583 / 2583 · SHIPPED as THE FULL-REGENERATION BACKSTOP "
        "(scoped #8 → 0; 39 batches, 0 stale, manifest byte-identical) · skeleton 54.1703 → 54.2320 % @ 2353 → 2377 pairs (population arithmetic, 0 movers), "
        "≥50 1442 → 1463, ≥75 238, ≥90 20 · cs 14318 / 186 / 689 / 23 · body 55 / 5 / 193 / 251 (+3 EMPTY named: the B-series picture-only boxes) · "
        "clean 2532 / 2576 · every verifier ✓ · miner 184 · ceiling 90.9 % → 59.7 % of achievable · the corpus 2583 / 507 · plateau 0 of 3\n")
st = st.replace(o, line + o)

# 3. Position
o = "- LAST BUILT, SHIPPED INERT: **r425** (build 260619.96, 21 Sept ≈22:00, session 31 Round 3 — THE XOTP ACTIVITY-TABLE ADAPTER; the flag `input_shapes.activity_table.adapter.enabled` is FALSE in the committed tree; the 12 modules stay refused as at r424 until the next session flips it and finishes the ship — the record is the 'Session 31 — Round 3' section below)."
assert st.count(o) == 1
st = st.replace(o, "- LAST BUILT, SHIPPED INERT: none — r425 was FINISHED by session 33 Round 1 (22 Sept 2026). No round in flight.")
o = "- LAST SHIPPED: **r424** (build 260619.95, output-inert — no page changed; the s31-r2 Round-log line); LAST PAGE-CHANGING SHIP: **r423**"
assert st.count(o) == 1
st = st.replace(o, ("- LAST SHIPPED = LAST FULL: **r425 FINISHED** (build 260619.97, 22 Sept ≈11:05, session 33 Round 1 — THE XOTP ACTIVITY-TABLE ADAPTER ENABLED + the \"I can\" "
                    "list; the 12 reader modules join the corpus; THE FULL-REGENERATION BACKSTOP, scoped counter 0; **skeleton 54.1703 → 54.2320 % @ 2353 → 2377 pairs "
                    "(population arithmetic, 0 movers), ≥50 1463, ≥75 238, ≥90 20, RAW 38.239 %**; cs 14318 / 186 / 689 / 23; body 55 / 5 / 193 / 251 (+3 named); "
                    "clean 2532 / 2576; leak 73 / 44; `gate_baseline.json` at r425 (2377 pairs, `_note_r425`); `outputs/_s33_r425_sk_final.json` the skeleton state; "
                    "ceiling 90.9 % re-measured on 2377 pairs (`_ceiling_r425`) → 54.232 = **59.7 % of achievable**; **corpus = 2583 pages / 507 dirs / 2377 pairs**; "
                    "the miner re-run 22 Sept 10:42 on the r425 corpus, 184 CANDIDATE). Before it **r424** (build 260619.95, output-inert — no page changed; the s31-r2 "
                    "Round-log line); before that **r423**"))
o = "- Plateau window (§4): **0 of 3** — r423 a recognition round"
assert st.count(o) == 1
st = st.replace(o, "- Plateau window (§4): **0 of 3** — r425 a recognition-family round (12 modules entered the population; 0 movers), r423 a recognition round")
o = "- **THE LOOP STOPPED 2026-09-21 ≈22:00 (session 31) on Chris's `/loop-stop`** — r425 in the tree SHIPPED INERT; the next session's Round 1 is FINISHING r425"
assert st.count(o) == 1
st = st.replace(o, "- (RESOLVED 22 Sept by session 33 Round 1 — r425 finished.) **THE LOOP STOPPED 2026-09-21 ≈22:00 (session 31) on Chris's `/loop-stop`** — r425 in the tree SHIPPED INERT; the next session's Round 1 was FINISHING r425")
o = "- Standing facts: AppVersion 260619.96 (r425 the XOTP activity-table adapter, BUILT + SHIPPED INERT, session 31 Round 3, 21 Sept); before it 260619.95"
assert st.count(o) == 1
st = st.replace(o, "- Standing facts: AppVersion 260619.97 (r425 FINISHED — the XOTP adapter enabled + the I-can list, session 33 Round 1, 22 Sept; the FULL backstop); before it 260619.96 (r425 BUILT + SHIPPED INERT, session 31 Round 3, 21 Sept) / 260619.95")
o = "`DIFF_QUEUE.md` 21 Sept 19:50 on the r424 corpus (HEAD 4472204; 2,353 pairs), 184 CANDIDATE rows, all dispositioned — re-mined after every ship)."
assert st.count(o) == 1
st = st.replace(o, "`DIFF_QUEUE.md` 22 Sept 10:42 on the r425 corpus (2,377 pairs / 496 modules), 184 CANDIDATE rows — re-mined after every ship).")

# 4. the next-session line (kept ≤ 800 chars now that the r425 handover is spent)
m = re.search(r"^\*\*Next session starts with:\*\* .*$", st, re.M)
assert m
nxt = ("**Next session starts with:** the standing `/loop-start` (health check; the \"Amended:\" line; the §7 diff check; `git status` CLEAN at the session-33 "
       "commits). No round in flight. The order the 22 Sept review set, minus the finished Round 1: **Round 2 = ENABLE r422** (FRFUN06's side-tab dialect, "
       "`side_tab_nav.enabled: true`, §1d exception 1 / D12-1 — OFF byte-identical elsewhere, ON = FRFUN06's 10 pages, every gate holds, scoped regen of the 1); "
       "**Round 3 = Round 0d for the 38 pre-intake never-converted modules** (LOOP §0's list; §1f Phases 2 + 5–7: pre-create the nested dirs, convert by explicit "
       "code list in batches ≤ 11, refusals by cause, no ghost dirs, re-base by population, re-mine, the §0 table + the verify script's expect values); then the "
       "miner's queue on the current corpus under §3 / §4. NEEDS CHRIS: the open lines of the \"Needs Chris\" section (a new item = one new line there).")
st = st[:m.start()] + nxt + st[m.end():]
wr(R + "LOOP_STATE.md", st); wr(R + "LOOP_STATE_ARCHIVE.md", ar)
print("STATE_DONE", len(st), len(nxt))
